### PR TITLE
Fix #3240 - file push broken on windows with 2.13

### LINKED ISSUE #3240: file push broken on windows with 2.13
# Required information

   * LXC version: 2.13

# Issue description

Pushing file from Windows results in file with backslashes written to root.

# Steps to reproduce

```
> lxc file push 01install.sh node:remote/01install.sh
> lxc exec remote:cpm -- ls
> lxc exec remote:cpm -- ls /
'C:\01install.sh'  boot  etc ...
```

```
> lxc file push 01install.sh node:remote/root/01install.sh
> lxc exec remote:cpm -- ls /
'C:\root\01install.sh' ...
```

# Information to attach

 - [ ] container log (lxc info NAME --show-log)
 - [ ] main daemon log (/var/log/lxd.log)
 - [ ] output of the client with --debug
 - [ ] output of the daemon with --debug

### PR DESCRIPTION
**Pull request by techtonik**
Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner please review

**Comment by brauner** [comment]
lgtm

**Comment by techtonik** [comment]
Thanks for review. =)

**Comment by brauner** [comment]
Thanks for fixing! :)

**Pull request merged**
