### PR TITLE
container/lxc: Fixes ipvlan support check

### PR DESCRIPTION
**Pull request by tomponline**
Also alerts user if they try to add ipvlan nic to running container.

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@brauner @stgraber I wanted to flag this one up, this could potentially cause issues hot-plugging any nic type on a LXD instance where LXC doesn't support IPVLAN. Have also alerted user if they try to add an ipvlan nic to a running container.

**Comment by brauner** [comment]
Makes sense to me. This is a technical restriction we currently have?

**Comment by tomponline** [comment]
@brauner correct, we check that LXC supports ipvlan before the container starts in `initLXCIPVLAN` however this check was erroneously left in and will likely have the undesirable affect of preventing you hot-plugging non-ipvlan interfaces on when using LXD with a non-ivplan-compatible LXC. My understanding is that upstreams who build LXD against older LXC versions will run into trouble without this patch.

**Comment by tomponline** [comment]
@brauner the other check to prevent ipvlan from being added to running containers is just a user experience improvement, as currently it would add it but silently do nothing until the container is restarted. As currently IPVLAN setup is only done via LXC.

**Comment by tomponline** [comment]
jenkins please test this

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
