### PR TITLE
Redo logging and keep original logging API

### PR DESCRIPTION
**Pull request by jsimonetti**
This pullrequest changes logging in the shared library to use empty anonymous functions
The main package (lxd and lxc) have been reworked to use a new logging package which adds back the original functionality of the logging and also keeps the original API.

The effect of this is that the shared package no longer has the following dependencies:
github.com/mattn/go-colorable
gopkg.in/inconshreveable/log15.v2/term
gopkg.in/inconshreveable/log15.v2/stack
gopkg.in/inconshreveable/log15.v2

References #1375
Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by stgraber** [comment]
jenkins: ok to test

**Comment by jsimonetti** [comment]
Hmm, dunno why it added the commits from tycho0. I hope this doesn't screw up things... :(

**Comment by jsimonetti** [comment]
This has become a mess. I apologize and will redo the whole thing as it looks like other changes I didn't make it into my branch.

**Pull request closed without merging**
