### PR TITLE
test: Add a basic concurency test

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Note that this test currently fails completely due to remaining locking issues with the DB.

**Comment by stgraber** [comment]
I really think we should do 2), it's true we can deal with most of those problems in the lxc client, but the fact is, not everyone does that, some will have their own client code, and so having to deal with those errors everywhere seems problematic.

**Comment by stgraber** [comment]
I'm also not sure whether that's the case for you, but here, I do hit the locking errors extremely quickly which would suggest that in some cases, it's not actually waiting the right amount of time (or waiting at all).

**Comment by tych0** [comment]
#525 had a cherry picked version of this, so I'm closing this one.

**Pull request closed without merging**
