### PR TITLE
Split autoUpdateImage function

### PR DESCRIPTION
**Pull request by albertodonato**
Extract the code to update a single image from autoUpdateImages, so that the logic can be reused.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Shouldn't autoUpdateImage be made to return an error, making it up to the caller whether to discard it or not?

**Comment by albertodonato** [comment]
Yeah, I can do that. I didn't change it since in many case the error was only logged, but I can keep the logging in autoUpdateImage and return the error in all cases.

**Comment by albertodonato** [comment]
jenkins: test this please

**Pull request merged**
