### PR TITLE
lxd import: rewrite

### LINKED ISSUE #3682: Problem with LXD Import
Refering to Issue #3005 

----------

lxd import doesn't work porperly on my system...
OS: Debian Stretch, LXD 2.16 (Snap)

Created a new container from scratch (ubuntu 17.04)
made some changes, created 3 Snapshots of the container (with lxc snapshot ....)
here is zft list -t all:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                           
...
...
zpool1/lxd/snapshots/test                                                                    25.4K  1.24T  25.4K  none         
```

then I made a zfs-backup:
```
zfs send -R zpool1/lxd/containers/test@snapshot-dritter > /tmp/test
```

important: i didn't save the snapshots-dataset for this container (maybe this was my failure?)

then destroyed the container:

```
lxc stop test
lxc delete test
```

zfs shows no further datasets of the container, ans no snapshots any more

then restored zfs:

```
zfs receive zpool1/lxd/containers/test < /tmp/test
``` 

worked fine, zfs list -t a shows:
```
zpool1/lxd/containers/test                                                                   5.68M  1.24T   314M  /var/snap/lxd/common/lxd/storage-pools/pwhost/containers/test        
zpool1/lxd/containers/test@snapshot-erster                                                   51.6K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-zweiter                                                  52.4K      -   314M  -                                                                    
zpool1/lxd/containers/test@snapshot-dritter                                                      0      -   314M  -                                                                    
```
but it doesn't show the snapshot dataset -> thats right, I didn't backup it...

then import the container
```
lxd import test
```
seems to be successful:
```
lxc list
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
|    NAME    |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
| test       | STOPPED |                     |      | PERSISTENT | 0         |                                                                                                         
+------------+---------+---------------------+------+------------+-----------+                                                                                                         
```
but the snapshots are missing - so lxd didn't find the really existing zfs snapshots...
and now the container cannot be startet:
```
> lxc start test
error: Failed to run: /snap/lxd/3346/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/test/lxc.conf:                                           
Try `lxc info --show-log test` for more info                                                                                                                                           

> lxc info --show-log test
Name: test                                                                                                                                                                             
Remote: unix://                                                                                                                                                                        
Architecture: x86_64                                                                                                                                                                   
Created: 2017/08/14 12:03 UTC                                                                                                                                                          
Status: Stopped                                                                                                                                                                        
Type: persistent                                                                                                                                                                       
Profiles: default                                                                                                                                                                      
                                                                                                                                                                                       
Log:                                                                                                                                                                                   
                                                                                                                                                                                       
            lxc 20170814120333.534 ERROR    lxc_conf - conf.c:run_buffer:416 - Script exited with status 1.                                                                            
            lxc 20170814120333.534 ERROR    lxc_start - start.c:lxc_init:450 - Failed to run lxc.hook.pre-start for container "test".                                                  
            lxc 20170814120333.534 ERROR    lxc_start - start.c:__lxc_start:1314 - Failed to initialize container "test".                                                              
            lxc 20170814120333.534 WARN     lxc_commands - commands.c:lxc_cmd_rsp_recv:177 - Command get_cgroup failed to receive response: Connection reset by peer.                  
```

to ensure that this is not only because of the missing snapshot-dataset, I retried it again:
with also saving zpool1/lxd/snapshots/test and restoring it...
same result: lxc list doesn't show any snapshots, and container doesn't run.

### PR DESCRIPTION
**Pull request by brauner**
Closes #3682.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
TODO: Remove any snapshots that exist in the pool but not in the backup.yaml file when "force" is passed. This requires some more thinking for the specific backends. I have the implementation for the obvious candidates dir and btrfs. The other ones are a little trickier.

**Comment by brauner** [comment]
The failure is expected right now. This depends on https://github.com/lxc/lxd/pull/3820 being merged.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@stgraber, ready to go/review.

**Pull request merged**
