### PR TITLE
Basic CPU load balancing and a ton of cleanup

### PR DESCRIPTION
**Pull request by stgraber**
This is the first pass on CPU load balancing and a fair amount of cleanup that happened as a result of it.

I'm marking this blocked for now because there are a couple of FIXMEs I'd like to get rid of, but it's now good enough to throw at Jenkins for some stress testing (testsuite passes locally).

### CODE REVIEW

**Comment by stgraber** [comment]
- Looks like I forgot about the go tests... will have to fix those.

 - Still need to add DB migration code for limits.cpus to limits.cpu.

 - Add a flag to PUT /1.0/containers/NAME to allow modifying volatile so we can have it set when copying a container or snapshots around, but not have it set for the rest as volatile is really meant to be internal and not user writable.

 - Add an argument to validateConfig to define whether we're checking a profile or a container config, in the former case, disallow volatile keys entirely.

 - Add DB migration code which wipes any volatile key set on any profile (to prevent them from failing to load).

**Comment by stgraber** [comment]
All of @tych0's comments to this point have been addressed.

**Comment by tych0** [comment]
Hmm. it seems you can't get github to show you a "big" diff, so it won't let me comment on it. I'll just post stuff here:

https://github.com/stgraber/lxd/blob/1304c3d44c09715700f399ebda701fd7f44224be/lxd/container_lxc.go#L927 should be "stopping"

**Comment by stgraber** [comment]
Added debugging to Jenkins now, retrying so I can see what's actually failing.

jenkins: test this please

**Comment by stgraber** [comment]
And of course it all passed now. Let's try again...

jenkins: test this please

**Comment by stgraber** [comment]
Test passed again, going to go with a total of 5 tries, here comes the 3rd one.

jenkins: test this please

**Comment by stgraber** [comment]
Let's try run number 4.

jenkins: test this please

**Comment by stgraber** [comment]
And try 5 out of 5, maybe I'll get lucky.

jenkins: test this please

**Comment by stgraber** [comment]
Got it! Looks like a reboot on old LXC kind of problem, will look into it.

**Comment by stgraber** [comment]
Alright, so that was a pass, let's try to get 4 more success in a row then I'll consider it good :)

jenkins: test this please

**Comment by stgraber** [comment]
2/3

jenkins: test this please

**Comment by stgraber** [comment]
3/5

jenkins: test this please

**Comment by stgraber** [comment]
4/5

jenkins: test this please

**Comment by stgraber** [comment]
5/5

jenkins: test this please

**Comment by stgraber** [comment]
Looks like things are solid.

**Pull request merged**
