### PR TITLE
Stream lifecycle and log events to Loki

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

**Comment by monstermunchkin** [comment]
jenkins: Test this please

**Comment by stgraber** [comment]
@monstermunchkin what's the behavior when clustered? Are we correctly only sending the local lifecycle and logging events?
We don't want to end up with every system in the cluster sending the same information to loki.

**Comment by monstermunchkin** [comment]
> what's the behavior when clustered? Are we correctly only sending the local lifecycle and logging events?

We're sending everything that's also is shown in `lxc monitor`. That includes events from all members of the cluster.

> We don't want to end up with every system in the cluster sending the same information to loki.

OK. Should we then make the config per-node, i.e. move the loki config to `lxd/node/config.go`?

**Comment by monstermunchkin** [comment]
@stgraber I've added `EventSourcePull` to the excluded sources in the listener which removes duplicate events.

**Comment by stgraber** [comment]
@monstermunchkin we're missing doc and API extension on this one.

**Pull request merged**
