### PR TITLE
cleanup: remove subtest

### LINKED ISSUE #9450: Remove use of legacy github.com/mpvl/subtest
# Issue description

As Golang 1.13 is the minimum supported version for building LXD, the use of github.com/mpvl/subtest to run subtests is no longer needed and has become an unnecessary dependency. Please consider updating code to use Golang's testing module directly.

This was noticed while reviewing dependencies needed to cleanly package LXD for Debian.

### PR DESCRIPTION
**Pull request by hypnoglow**
Fixes #9450

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
jenkins: test this please

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can you sign off your commit.

**Comment by hypnoglow** [comment]
> Please can you sign off your commit.

Done

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
