### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Wow, port conflict, that's some bad luck :)

jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

For real this time...

**Comment by stgraber** [comment]
Pushed updated commits doing s/exportToTar/export/g, two lines changed, string only.

**Comment by hallyn** [comment]
looks good to me

**Comment by stgraber** [comment]
Random failure on a previously successful arch+compiler combo, trying again...

Jenkins: test this please

**Pull request merged**
