### PR TITLE
Fully implement the LVM storage driver.

### PR DESCRIPTION
**Pull request by pcdummy**
This is untested - not ready to merge.

Here to show it Mike.

Signed-off-by: René Jochum <rene@jochums.at>

### CODE REVIEW

**Comment by pcdummy** [comment]
@mikemccracken can you test this a bit and give feedback? Currently i don't have a Machine to test (will have one this evening.)

**Comment by stgraber** [comment]
Marking as blocked since this isn't meant to be merged at this point.

**Comment by mikemccracken** [comment]
Hi @pcdummy, thanks for getting this started, it was helpful.
I had actually already started some of these things earlier, and our branches overlap a little. I am about to push a PR that implements snapshot and copy, and although I wasn't able to easily base my branch on your work, I did use some code from this branch - the part for handling copying from a non-lvm container - and I made a note of it in the relevant commit.

I didn't use this branch directly because the branch I already had did a couple of extra things we realized were necessary a few weeks back: first, renaming the LVs so that container names could not conflict with snapshot names (you can't name an LV with a '/' so you need to do some mapping there)
and second, we need to freeze and call syncfs to ensure that the snapshot is as consistent as possible.

**Comment by stgraber** [comment]
Closing this in favor of #1033

**Comment by mikemccracken** [comment]
Just a note so this doesn't get lost, this does still have some code that isn't in #1033 , e.g. rename and snapshot rename.

**Pull request closed without merging**
