### PR TITLE
Makefile tweaks for gomod

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline good to go and seems to fix our problem

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tomponline tip has now been fixed so this should look quite good once Jenkins is done with it

**Comment by tomponline** [comment]
@stgraber looks good, what changed with go mod to require the addition of an offline mode, is this because it uses its own cache rather than an existing download cache?

**Comment by stgraber** [comment]
@tomponline it uses the cache but will still try to refresh...

**Pull request merged**
