### PR TITLE
Instance: Ensure raw.lxc values are applied last when writing lxc.conf file

### LINKED ISSUE #9093: raw.lxc key does't appened but inserted into container's lxc.conf
# Required information

* LXC version: 4.0.10 ( >= 4.0.7)
* LXD version: 4.17

# Issue description

According to instances.md, configuration key `raw.lxc`  contains "Raw LXC configuration to be appended to the generated one". For LXD 4.17 the strings from `raw.lxc` key does not **appended to** the generated lxc.conf but **inserted somewhere in** that file.
Due to the changes in LXC >= 4.0.7 ([1](https://github.com/lxc/lxc/commit/942b2d318642cc6b596b8d9778daa506a5578a56), [2](https://github.com/lxc/lxc/commit/320061b34fea7d7f280b0a421dddeac7dac7f1bf)) that makes impossible to configure container's network interfaces via LXC keys like `lxc.net.[N].ip[46].*` .

# Steps to reproduce

 1. Create minimal CT:
```
# lxc init images:busybox/1.33.1 raw-lxc-test --storage  default
Creating raw-lxc-test
                                            
The instance you are starting doesn't have any network attached to it.
  To create a new network, use: lxc network create
  To attach a network to an instance, use: lxc network attach
```
 2. Add a physical network interface into CT, and lets LXC set IPv4 address on it via 'raw.lxc':
```
# lxc config device add raw-lxc-test eth0 nic name=eth0 nictype=physical parent=raw-lxc
Device eth0 added to raw-lxc-test
# lxc config set raw-lxc-test raw.lxc="lxc.net.0.ipv4.address=10.0.0.1/24"
```

Resulting CT configuration:
```
# lxc config show raw-lxc-test
architecture: x86_64
config:
  image.architecture: amd64
  image.description: Busybox 1.33.1 amd64 (20210806_06:00)
  image.os: Busybox
  image.release: 1.33.1
  image.serial: "20210806_06:00"
  image.type: squashfs
  image.variant: default
  raw.lxc: lxc.net.0.ipv4.address=10.0.0.1/24
  volatile.apply_template: create
  volatile.base_image: 982fe78bba9b756ea0e53b145ea1180577b1fa15108afc205d3fcf8f04114dcf
  volatile.idmap.base: "0"
  volatile.idmap.next: '[{"Isuid":true,"Isgid":false,"Hostid":1000000,"Nsid":0,"Maprange":65536},{"Isuid":false,"Isgid":true,"Hostid":1000000,"Nsid":0,"Maprange":65536}]'
  volatile.last_state.idmap: '[]'
  volatile.uuid: de680a53-e263-4a37-9126-f5b15a6b82e2
devices:
  eth0:
    name: eth0
    nictype: physical
    parent: raw-lxc
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
```
 3. Create dummy network interface 'raw-lxc', start a CT. LXC should rename interface to 'eth0' and set IPv4 address on it - but the later one is not happen, there is no IPv4 on eth0 inside CT:
```
# ip link add raw-lxc type dummy
# lxc start raw-lxc-test
# lxc exec raw-lxc-test ip addr show dev eth0
13: eth0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether 52:05:22:cc:80:a0 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::5005:22ff:fecc:80a0/64 scope link 
       valid_lft forever preferred_lft forever
```
In the generated CT lxc.conf content of the `raw.lxc` key was inserted inside configuration file, not _appended_ to it:
```
# tail /var/log/lxd/raw-lxc-test/lxc.conf
lxc.seccomp.profile = /var/lib/lxd/security/seccomp/raw-lxc-test
lxc.idmap = u 0 1000000 65536
lxc.idmap = g 0 1000000 65536
lxc.mount.auto = shmounts:/var/lib/lxd/shmounts/raw-lxc-test:/dev/.lxd-mounts
lxc.net.0.ipv4.address=10.0.0.1/24
lxc.net.0.type = phys
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.link = raw-lxc
lxc.rootfs.path = dir:/var/lib/lxd/containers/raw-lxc-test/rootfs
```
And in the LXC >= 4.0.7 `lxc.net.0.type` wipes all previous interface configuration - so `lxc.net.0.ipv4.address` is dropped.

 4. Let's imitate the `raw.lxc` value **appending** to the end of generated by LXD lxc.conf file - right according to the documentation.

Stop CT via LXD and delete LXD-specific lines from the generated lxc.conf:
```
# lxc stop raw-lxc-test
# sed -e '/lxc\.hook/ d' -e '/lxc\.seccomp\.profile/ d' -e '/idmap/ d' -i  /var/log/lxd/raw-lxc-test/lxc.conf
```
Move 'raw.lxc' content (`lxc.net.0.ipv4.address=10.0.0.1/24`) to the end of the lxc.conf:
```
# sed -e '/ipv4\.address/ d' -i /var/log/lxd/raw-lxc-test/lxc.conf
# echo "lxc.net.0.ipv4.address=10.0.0.1/24" >> /var/log/lxd/raw-lxc-test/lxc.conf
```
Now the end of the lxc.conf file is following:
```
# tail  /var/log/lxd/raw-lxc-test/lxc.conf
lxc.tty.max = 0
lxc.uts.name = raw-lxc-test
lxc.mount.entry = /var/lib/lxd/devlxd dev/lxd none bind,create=dir 0 0
lxc.mount.auto = shmounts:/var/lib/lxd/shmounts/raw-lxc-test:/dev/.lxd-mounts
lxc.net.0.type = phys
lxc.net.0.name = eth0
lxc.net.0.flags = up
lxc.net.0.link = raw-lxc
lxc.rootfs.path = dir:/var/lib/lxd/containers/raw-lxc-test/rootfs
lxc.net.0.ipv4.address=10.0.0.1/24
```
Start CT via raw LXC and check eth0 configuration:
```
# lxc-start -f /var/log/lxd/raw-lxc-test/lxc.conf raw-lxc-test
# lxc-attach raw-lxc-test ip addr show eth0
14: eth0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue qlen 1000
    link/ether 52:05:22:cc:80:a0 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.1/24 brd 10.0.0.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5005:22ff:fecc:80a0/64 scope link 
       valid_lft forever preferred_lft forever
```

### PR DESCRIPTION
**Pull request by tomponline**
Fixes #9093

Initially I thought this PR would be easy, just find the place where raw.lxc entries were added to the lxc.conf file and rearrange it. 
Alas it was not as simple as that, as lxc.conf generation is split between `initLXC()` and `startCommon()` (maybe more?) and although this PR fixes the reported issue, I am concerned it may introduce other problems because the raw.lxc entries will no longer be added to the config used in all of the instances that `initLXC()` is called outside of `startCommon()`.

To make matters more complicated, I don't really understand the role of the `config` arg on this function (or the mysterious `d.cConfig` variable) and what purpose the interplay between those two serve, and so I am struggling to reason about when `initLXC()` actually uses the `raw.lxc` values anyway.

https://github.com/lxc/lxd/blob/ec61dea1c40f0935c16890e22f95620bda5fce67/lxd/instance/drivers/driver_lxc.go#L671-L676

So I put this PR up with hesitancy.

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
Also in digging into this more in now transpires that the `inst.SaveConfigFile()` function isn't really doing what it should, because it is only take the config generated from `initLXC()` and not all the device config added by `startCommon()`. 

Luckily this function only seems to be being used `patchContainerConfigRegen` which was added here https://github.com/lxc/lxd/commit/622a9e908572ca61db5696bcc9290ed1c7023c7e as to support upgrading from LXD 2.0 to 3.0. 

> This is to catch anyone who's upgraded to 3.0 but still has some 2.0 configs around.

However this may well not be doing what is expected of it now.

I would suggest we try and banish the `inst.SaveConfigFile()` function (as it does nothing for VMs anyway) as it is already not truly doing what it suggests it does.

**Comment by stgraber** [comment]
And indeed, I saw the SaveConfigFile function and pretty much ignored it as it's just used in that one patch.
As far as I know, that patch needs very little actual LXC config, it just needs enough to allow for exec/console to behave, so lacking devices isn't an issue.

**Comment by tomponline** [comment]
> And indeed, I saw the SaveConfigFile function and pretty much ignored it as it's just used in that one patch.
> As far as I know, that patch needs very little actual LXC config, it just needs enough to allow for exec/console to behave, so lacking devices isn't an issue.

Cool, I think we could move `SaveConfigFile` to the `Container` Interface rather than the `Instance` interface and then add a big warning in the comment explaining it basically shouldn't be used. Then the patch can try and cast each instance to a Container and skip the ones that aren't.

**Comment by stgraber** [comment]
@tomponline since this was really just for LXC, we could also cast directly to an LXC container.

**Comment by tomponline** [comment]
> @tomponline since this was really just for LXC, we could also cast directly to an LXC container.

IIRC I think we kept the specific driver types unexported.

**Pull request closed without merging**
