### PR TITLE
storage/lvm: Adds spaced used reporting for LVM thinpools

### LINKED ISSUE #5868: LVM Storage info always shows zero space used
# Required information

 * Distribution: Ubuntu
 * Distribution version: 16.04.5 LTS
 * The output of "lxc info" or if that fails: 
[lxc_info.txt](https://github.com/lxc/lxd/files/3315068/lxc_info.txt)
   * Kernel version: 4.4.0-151-generic
   * LXC version: 3.0.3
   * LXD version: 3.0.3
   * Storage backend in use: LVM

# Issue description

LVM Storage info always shows zero space used

# Steps to reproduce

 1. Create an LVM thinpool storage
 2. Launch a container on LVM storage
 3. Check storage usage using "lxc storage info <POOLNAME>"
 4. Reported "space used" is 0B, as per attached
[lxc_storage_info.txt](https://github.com/lxc/lxd/files/3315067/lxc_storage_info.txt)

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 - [X] Container log (`lxc info NAME --show-log`)
[lxc_info_show-log.txt](https://github.com/lxc/lxd/files/3315065/lxc_info_show-log.txt)
 - [X] Container configuration (`lxc config show NAME --expanded`)
[lxc_config_show_expanded.txt](https://github.com/lxc/lxd/files/3315097/lxc_config_show_expanded.txt)
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 - [ ] Output of the client with --debug
 - [X] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)
[lxc_monitor.txt](https://github.com/lxc/lxd/files/3315066/lxc_monitor.txt)
Actual LVM Storage Usage: [lvs.txt](https://github.com/lxc/lxd/files/3315100/lvs.txt)

### PR DESCRIPTION
**Pull request by tomponline**
Also optimises volume group reporting to avoid running vgs twice by retrieving both fields needed in one go.

Fixes #5868

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber tested on thin and non-thin pools.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Once https://github.com/lxc/lxc/pull/3074 is merged I can retest this.

**Comment by stgraber** [comment]
It's merged but will take a little while before we get new debs for it, I'll retry then

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
