### PR TITLE
Optimize automatic custom volume snapshots

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Ok, that's about as much as I can do to optimize things without getting into much larger changes.

@masnax upcoming change to eliminate UsedBy in most cases should improve things a fair bit further.

Ideally what we'd like for many of those cases is a way to load a set of instances enough to have an expanded config but not have a full driver struct. This way we can do a config key check from within a DB transaction, then filter things so we only keep the few instances we care about to fully load and act upon.

**Comment by tomponline** [comment]
@stgraber I think InstancesList() which I added for the acl iirc would help here and we could work to optimize and standardize on that. I specifically wrote it for that scenario of not returning it as a driver but with the option of expanding the config.

**Comment by tomponline** [comment]
@stgraber needs a rebase please

**Comment by tomponline** [comment]
> @stgraber I think InstancesList() which I added for the acl iirc would help here and we could work to optimize and standardize on that. I specifically wrote it for that scenario of not returning it as a driver but with the option of expanding the config.

@stgraber e.g https://github.com/lxc/lxd/blob/6fd49811c4792f26b9faa1c84a5cfb7de986c76c/lxd/network/acl/acl_load.go#L200

**Comment by stgraber** [comment]
> @stgraber I think InstancesList() which I added for the acl iirc would help here and we could work to optimize and standardize on that. I specifically wrote it for that scenario of not returning it as a driver but with the option of expanding the config.

Ah yeah, that looks pretty good. We'd want to convert that to a ClusterTx function and ideally would want a way to turn its output into a functional instance.Instance without needing to hit the database again.

**Comment by stgraber** [comment]
@tomponline rebase done. Github looks a bit broken but Jenkins is running at https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/7089/

**Comment by stgraber** [comment]
@tomponline good to go

**Comment by stgraber** [comment]
Self-merging this as we need to get LXD 5.2 out the door :)

**Review by tomponline — COMMENTED** [review]
No worries looks good.

**Pull request merged**
