### PR TITLE
lxc/config: no name shown when editing the instance's config

### PR DESCRIPTION
**Pull request by simondeziel**
```
$ EDITOR=cat lxc config edit lxd-test | grep name
### name: instance1
### Note that the name is shown but cannot be changed
```

### CODE REVIEW

**Comment by tomponline** [comment]
Hrm I'm not sure we should have merged this change. But rather investigate why `lxc config show <instance>` isn't returning `name` (as the comment indicates) as it is inconsistent with how `lxc network edit <network>` and `lxc storage edit <pool>` work (which is they return `name` but changes to it our ignored).

**Comment by stgraber** [comment]
@tomponline it's because we moved from Instance to InstancePut some time ago to avoid getting a MASSIVE chunk of text due to expandedConfig and expandedDevices being in Instance

**Comment by tomponline** [comment]
@stgraber got you, shouldn't we also do this for other entity types also then?

**Comment by tomponline** [comment]
Or modify it to not include expanded config/devices?

**Comment by tomponline** [comment]
For instance `lxc network edit lxdbr0` also includes:

```
used_by:
- /1.0/profiles/default
- /1.0/profiles/vsmall
- /1.0/instances/v1
- /1.0/instances/v2
- /1.0/instances/vbuild
managed: true
status: Created
locations:
- none
```

Which are not editable.
So if we are only including editable fields in the `lxc <object> edit` command output (which does make sense), then I feel we should do it consistently.

**Comment by stgraber** [comment]
I definitely prefer seeing the read-only fields, it's easier to be sure what you're working against, so I don't want to move them all to Put.

But at the same time, we can't split Instance into a InstanceNoExpanded or something like that without breaking some users of the instance struct, so I'm not super keen on doing that.

We could mark the expanded fields as `omitempty` and then manually empty them prior to spawning the editor, that likely wouldn't cause downstream breakage, though it would still be a bit of a lie as those fields don't normally qualify for omitempty.

**Comment by tomponline** [comment]
Yep agreed we don't want to change the values returned from the API.

Can we create a `InstanceNonExpanded` struct type though and add a `NonExpanded() InstanceNoExpanded` function to the `Instance` type (like we do for `Writable() InstancePut`), rather than altering the structure of `Instance`, that could be used in `lxc config edit` to remove the expanded fields from the editor?

**Comment by stgraber** [comment]
Yeah, that should be okay, we'll need a .Writable() or whatever on that one too so we can get back our InstancePut.

**Comment by tomponline** [comment]
Yep makes sense

**Pull request merged**
