### PR TITLE
jsimonetti's logging branch + bugfix

### PR DESCRIPTION
**Pull request by stgraber**
Closes #1388

### CODE REVIEW

**Comment by tych0** [comment]
Sorry, still playing with this one myself. I find all the Logger, log.Logger, LxdLog, etc. very confusing. I've gotten rid of the LxdLog proxy so far, trying to get rid of some redundant types elsewhere.

**Comment by stgraber** [comment]
Ah yeah, I just made it work properly, I agree that we can probably get something simpler that works just as well, not that the current proposal is that bad since the actual logging calls remain mostly identical, it's just the plumbing that's probably a bit more complex than it could be.

**Comment by tych0** [comment]
Yep, no worries. Trying to fix the plumbing now to be a little less convoluted. Then I'll send you a patch to look over and we can merge.

**Comment by tych0** [comment]
Ok, I think if you cherry-picked https://github.com/tych0/lxd/commit/57c913e10caf8ff46619c5a37cf05693aa4d4544 I'd be happy with it. The AddContext thing is a little bit annoying because golang doesn't do real type polymorphism, but I couldn't figure out another way around it.

**Comment by stgraber** [comment]
Looks fine to me, waiting for jenkins to agree.

**Comment by jsimonetti** [comment]
You guys are so much better at this :p
Though I'm learning a lot by this example!

**Pull request merged**
