### PR TITLE
s/config profile/profile

### LINKED ISSUE #615: lxc config profile is unweildly
Can we switch this to `lxc profile` instead? I'm not sure that there's really any reason to have `config` in there.

### PR DESCRIPTION
**Pull request by tych0**
Closes #615

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like Travis found a regression.

**Comment by tych0** [comment]
Hmm. I must have confused something, it worked locally, but apparently it broke somewhere in my rebasing. Anyway, fixed now, sorry about that.

**Comment by stgraber** [comment]
Kinda hard to see in the diff, did you keep one "lxc config profile" in one of the tests to ensure we don't regress the compatibility code?

**Comment by tych0** [comment]
Yep, hopefully this links to it:

https://github.com/lxc/lxd/pull/633/files#diff-1c7169c60b8d0ff103be4f4e8a1b1cd0R12

**Comment by stgraber** [comment]
Perfect!

**Comment by stgraber** [comment]
Perfect!

**Pull request merged**
