### PR TITLE
Fix location of daily repo

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by stgraber** [comment]
Should actually be lxd-git-master as you don't need the very latest git snapshot of all the dependencies.

**Comment by stgraber** [comment]
Oh and as Travis says, please include the required Signed-off-by line in your commit message :)

Thanks!

**Comment by stefanv** [comment]
OK, Travis should be happier now.

**Comment by stgraber** [comment]
Perfect, thanks!

**Pull request merged**
