### PR TITLE
lxd/db/networks: Fix NULL description

### LINKED ISSUE #8051: Issue with last snap refresh for latest/beta
# Required information

 * Distribution: Ubuntu
 * Distribution version: 20.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.4.0-51-generic 
   * LXC version: 
   * LXD version: 4.7, latest/beta
   * Storage backend in use: BTRFS

# Issue description

Starting LXD unix socket failing

# Steps to reproduce

 1. Try to start lxd socket

# Information to attach

Issue is here when running with debug

```
INFO[10-19|00:47:07] Applying patch "network_ovn_enable_nat" 
DBUG[10-19|00:47:07] Database error: &errors.errorString{s:"sql: Scan error on column index 3, name \"description\": converting NULL to string is unsupported"} 
EROR[10-19|00:47:07] Failed to start the daemon: Failed applying patch "network_ovn_enable_nat": sql: Scan error on column index 3, name "description": converting NULL to string is unsupported 
INFO[10-19|00:47:07] Starting shutdown sequence 
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #8051

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline @brauner good to go. We'll want that in before we release 4.7 to stable.

**Comment by tomponline** [comment]
@stgraber thanks for this. Is there a particular reason that the `description` field isn't marked `NOT NULL` like the other fields in that table? New networks are created with an empty string for network (which is why the patch didn't trigger that issue in our tests). Could we make `description` NOT NULL like the other columns to avoid this class of error in the future?

```sql
CREATE TABLE "networks" (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    project_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    state INTEGER NOT NULL DEFAULT 0,
    type INTEGER NOT NULL DEFAULT 0,
    UNIQUE (project_id, name)
);
```

**Comment by stgraber** [comment]
The reason is that it's a field we've added after the fact I believe. So we didn't set not null to deal with the initial schema update without having to potentially copy the entire table due to sqlite limitations.

Looks like the generated database code handles such cases properly but the hand written one didn't.

**Comment by tomponline** [comment]
@stgraber I can put a patch in that will re-create the table with NOT NULL if it cannot be altered, have done something similar when adding project ID column for networks.

**Pull request merged**
