### PR TITLE
Document list format options

### PR DESCRIPTION
**Pull request by techtonik**
Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by brauner** [comment]
Not necessary to run jenkins but I need to take a look at the jenkins test suite runs anyway so I'm abusing your branch. :) Thanks!

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by techtonik** [comment]
Doesn't seem to react. =)

**Comment by techtonik** [comment]
Ok. I see the result now.

**Pull request merged**
