### PR TITLE
doc: add video links

### PR DESCRIPTION
**Pull request by ru-fu**
Plus clarifications for disk devices.

### CODE REVIEW

**Comment by ru-fu** [comment]
Gnaah, the spelling issue is in the title of the YouTube video. So this needs an update to the Sphinx extension ...

**Comment by ru-fu** [comment]
https://github.com/canonical/lxd-sphinx-extensions/pull/7 (in case anyone wants to review ;) )

**Comment by stgraber** [comment]
Approved the PR

**Comment by ru-fu** [comment]
Passing now. :)

**Pull request merged**
