### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by stgraber**
Fixed a number of issues that were reported over the Christmas break on my flight back home.

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@stgraber, I haven't forgotten the branch but I can't really merge since Jenkins doesn't seem to want to test it...

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Looks like `lvm` - surprise, surprise - is unhappy:

```
EROR[01-03|17:26:25] Failed to create new "btrfs" UUID for container "uuid2" on storage pool "lxdtest-4N9-pool-btrfs": /dev/lxdtest-4N9-pool-btrfs/containers_uuid2 is mounted
 


error: Failed to run: btrfstune -f -u /dev/lxdtest-4N9-pool-btrfs/containers_uuid2: /dev/lxdtest-4N9-pool-btrfs/containers_uuid2 is mounted
```

**Comment by stgraber** [comment]
ain't that fun... I'll take a look at what LVM's doing...

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner so turns out Jenkins was just drunk, all green now.

**Pull request merged**
