### PR TITLE
shared/util/linux: only complain on xattr size increase

### PR DESCRIPTION
**Pull request by adilger**
If the xattr (list) size reported for a file is larger than the
actual size, this should not be considered an error, since the
allocated buffer will be large enough to hold the actual xattrs
returned, and is only a temporary allocation in any case.

Signed-off-by: Andreas Dilger <adilger@dilger.ca>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
This seems fine, though I'm now wondering how you managed to get a system where two calls within just a few milliseconds returned a different size. Is it a very busy filesystem that actually had an xattr change occur or is it a case of some kind of filesystem incorrectly reporting the size initially, then reporting a different size when asked to actually pull it?

**Comment by adilger** [comment]
> ... or is it a case of some kind of filesystem incorrectly reporting the size
> initially, then reporting a different size when asked to actually pull it?

it is the latter. The filesystem is Lustre, a high-performance distributed parallel filesystem. In some cases, the client doesn't know in advance what the exact size and count of xattrs will be, so it may provide a "safe" upper estimate of the xattr size/count, and then when the actual xattrs are read they will fit within the provided buffer size.  The patch avoids incorrectly returning an error for the case where the actual xattrs returned can fit within the buffer. 

That said, with a parallel filesystem, other client nodes may potentially be adding or removing xattrs, and this could even happen with local filesystems (eg. background process to add a checksum xattr on the file, or whatever), so there is always going to be a small TOCTOU race. It is more robust to be accepting of minor changes rather than refuse to access the file.

**Comment by stgraber** [comment]
Good to know about Lustre!

**Pull request merged**
