### PR TITLE
default routes for lxd

### PR DESCRIPTION
**Pull request by kunalkushwaha**
default routes are added as per discussion on mailing list.

file modified are 
client.go
config.go

two helper functions are added in client.go  for parsing getURITokens() and getRemoteURL()

Signed-off-by: Kunal Kushwaha <kunal.kushwaha@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Hi.

Any plans on fixing that Travis failure?

**Comment by kunalkushwaha** [comment]
Hi,

I need help for fixing this. 

This patch has two main changes. 
1. config.go : here default routes are added in LoadConfig() at  https://github.com/kunalkushwaha/lxd/blob/83ec08983915fd67a3c213ea1cd8e3d248897a0c/config.go#L54

If LXD is installed and running at local machine "/var/lib/lxd/unix.socket" will be created so added local route there as per specs "unix+lxd://var/lib/lxd/socket".

While assigning to unix socket it is assigned as "unix://var/lib/lxd/unix.socket" "https://github.com/kunalkushwaha/lxd/blob/83ec08983915fd67a3c213ea1cd8e3d248897a0c/client.go#L215

On Travis : it gives error error:
Get 127.0.0.1:8443/1.0/finger: unsupported protocol scheme ""

I am not able to run these https://github.com/lxc/lxd/blob/master/test/remote.sh tests at my local dev machine.

Please help me, if what could be error.

**Comment by tych0** [comment]
I think this error probably has to do with how golang is parsing the protocol on the front (i.e., you probably don't want to pass "unix+lxd" to golang, since golang doesn't know what lxd is). I haven't played with it enough to tell you how to fix it, though.

**Comment by kunalkushwaha** [comment]
I feel, we need to review the test cases in test/remote.sh

I ran each test separately, and understood the failure condition.
Its failing for "lxc remote add local 127.0.0.1:8443"

Below is the log for commands I executed

```bash
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote list | grep 'local'
local <http://unix.socket>
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote set-default local
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote set-default local --debug
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./ lxc remote rename local foo
bash: ./: Is a directory
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote rename local foo
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote list | grep 'foo'
foo <http://unix.socket>
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote list | grep -v 'local'
foo <http://unix.socket>
images <https://registry.linuxcontainers.org>
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote remove foo
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote list | grep -v 'local'
images <https://registry.linuxcontainers.org>
kunal@kunal-VirtualBox:~/go/src/github.com/lxc/lxd/lxc$ ./lxc remote add local 127.0.0.1:8443 --debug
2015/01/16 12:20:27 connecting to local
2015/01/16 12:20:27 trying to local:x
2015/01/16 12:20:33 fingering the daemon
error: Get 127.0.0.1:8443/1.0/finger: unsupported protocol scheme ""
```

I intentionally not executed first test case as it was failing with same condition as last remote add.

 PS : Now I understood how to execute these tests at my local machine too :)

**Comment by tych0** [comment]
Looks to me like that test failing for the same reason as above. What do you mean by "review" the tests?

**Pull request closed without merging**
