### PR TITLE
doc/server: update Loki config

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
@ru-fu I don't know if adding "lifecycle" to the wordlist is the way to go, please let me know if there's a better way, thanks!

**Comment by simondeziel** [comment]
@ru-fu when looking at the preview doc (cool feature!) I noticed I forgot to single quote the values. Is the spellchecker skipping quoted strings? If so, I should remove the "lifecycle" word from the wordlist.

**Comment by stgraber** [comment]
@simondeziel yeah, the spellchecker ignores quoted strings, so you should be able to remove lifecycle from the list

**Comment by ru-fu** [comment]
> @ru-fu when looking at the preview doc (cool feature!) I noticed I forgot to single quote the values. Is the spellchecker skipping quoted strings? If so, I should remove the "lifecycle" word from the wordlist.

Yes, please remove it from the list. In normal text, it should be spelled as two words (or hyphenated in combinations like "life-cycle events"). For variables and the like it's of course fine as one word, but then it needs to be marked as code. 
And yes, all quoted strings are ignored in the spell check. :)

**Review by ru-fu — APPROVED** [review]
:+1:

**Pull request merged**
