### PR TITLE
Bugfix: allow inconsistent copy for pool and project migrations

### PR DESCRIPTION
**Pull request by markylaing**
While investigating #10091 I found that local copies using rsync (e.g. between pools or projects) did not allow for inconsistent copies. This change checks for the exit status of rsync on a local copy and returns nil if allowInconsistent is set. This required passing the allowInconsistent argument through the driver and pool interfaces.

### CODE REVIEW

**Comment by markylaing** [comment]
@tomponline as I mentioned [here](https://github.com/lxc/lxd/pull/10442#issuecomment-1133090571) this PR is a potential fix for some other issues with `--allow-inconsistent`. 

Thus far this has gone unreported, so potentially errcode 24 is never returned for local copy, or there is no use case for --allow-inconsistent when copying between pools or projects.

**Review by tomponline — COMMENTED** [review]
Does this still freeze the instance if not specified?

**Comment by tomponline** [comment]
> Does this still freeze the instance if not specified?

To better clarify what I'm asking: is this just a fix to ensure rsync doesn't cause an inconsistent copy to fail? Thanks

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Also what about RefreshVolume()?

**Comment by markylaing** [comment]
> > Does this still freeze the instance if not specified?
> 
> To better clarify what I'm asking: is this just a fix to ensure rsync doesn't cause an inconsistent copy to fail? Thanks

So the bug which caused instances to freeze should have been fixed by #10442. What motivated this PR was noticing that `(*lxdBackend).CreateInstanceFromCopy` was not using the `allowInconsistent` argument here: https://github.com/lxc/lxd/pull/10443/files#diff-029fdd0e1afdacb0e66630c0d7e813772122db9a7d036060902838db315d9c4dR1018. Following that I found that the rsync error code 24 wasn't being ignored in the generic VFS copy volume function.

> Also what about RefreshVolume()?

On initial inspection, it appeared that `RefreshVolume` was only called through the storage volume API and since `--allow-inconsistent` is only defined for instances I figured defaulting to `false` would be fine. Looking at it again today I've just found [this call](https://github.com/lxc/lxd/blob/ae0601a1b59783a7c818247200ca64de26df8278/lxd/storage/backend_lxd.go#L1489) which will cause `lxc copy c1 c2 --allow-inconsistent --refresh` to fail on an rsync error if c1 and c2 are on the same pool, effectively ignoring the `--allow-inconsistent` flag.

I'll submit another PR for that.

**Pull request merged**
