### PR TITLE
Restricted snapshots and backups

### LINKED ISSUE #8703: Add new project restrictions for snapshots and backups
Snapshots and backups can be expensive both to produce and store them, so it would make sense to make them a restricted feature.

We should add:
 - restricted.backups (allow/deny)
 - restricted.snapshots (allow/deny)

Which will restrict the creation of any instance backups/snapshots or volume backups/snapshots.

### PR DESCRIPTION
**Pull request by presztak**
Resolves #8703

### CODE REVIEW

**Comment by stgraber** [comment]
@presztak Looking good though we also need to prevent scheduled snapshots of instances and custom volumes when the project has the feature restricted.

I suspect the easiest for that is to hook into `autoCreateCustomVolumeSnapshots` and `autoCreateContainerSnapshots`, adding a check for whether the instance or volume's project can be snapshotted and if not, skipping over it.

**Comment by presztak** [comment]
@stgraber PR updated.

**Comment by stgraber** [comment]
Thanks, looks good to me!

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
