### PR TITLE
lxd/instance/lxc: Fix swappiness calculation

### PR DESCRIPTION
**Pull request by stgraber**
Closes #9017

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
@stgraber please could you add some comments explaining the reasoning behind those specific numbers being used though?

**Comment by stgraber** [comment]
I've posted the details in the other PR but basically the logic was meant to add some weight when the priority is lowered (increase swapiness) but keeping the max value at the system default of 60 to avoid getting the container above all other processes.

At some point (possibly the cgroup rework?) the logic got tweaked and we ended up with the current behavior. This both fixes the calculation to work the expected way AND also properly handles unsetting the key.

**Comment by stgraber** [comment]
@tomponline updated

**Comment by tomponline** [comment]
@stgraber thanks.

Why do we only allow setting the swap priority between 0 and 10 (mapping to swappiness 70 and 60) rather than a higher range (0 .. 100)?

**Comment by stgraber** [comment]
@tomponline no real reason, we could expose more of the swapiness range, though in practice the real use cases we've seen are:
 - Don't have the instance swap (limits.memory.swap=false)
 - I don't care about those containers (lower limits.memory.swap.priority)
 - Normal containers (standard system swapiness)

The lack of that knob in cgroup2 also means that whatever we add at this point may be lost until an alternative is implemented over there. I'm also not the biggest fan of that particular option these days as unfortunately reducing the swappiness can backfire, basically putting more memory pressure on the container which then causes the kernel to evacuate the VFS cache.

In the worst example of that, we've had a few containers doing NorthSec that ended up trading around 5MB of additional memory (or swap) usage for 1.5GB/s of constant I/O re-fetching the same 5MB chunk over and over again...

**Pull request merged**
