### PR TITLE
Support context.Context in client

### PR DESCRIPTION
**Pull request by whywaita**
Hi maintainers! :)

This PR adds `XXXWithContext` function.
This function's argument has [context.Context](https://pkg.go.dev/context#Context).

This context will use `http.Request`.
Users of a library can cancel using `context.Context`.

Signed-off-by: whywaita <whywaita@whywrite.it>

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm, so I can't say that I'm thrilled about the idea of doubling the number of exported functions :)

The ones for connection I think make sense to add, that's fine. For the rest, I wonder if we could get away with a `.WithContext(ctx).XYZ` trick, the same way we do for `UseTarget` or `UseProject` currently.

This would let us just add one more function and should reduce the size of this change significantly.

Also worth noting, we shouldn't make any changes to `lxd_containers.go` as all those functions are effectively deprecated in favor of the `lxd_instances.go` ones. We've been keeping those around to avoid breaking downstream users but we don't add any new functions in there.

**Comment by tomponline** [comment]
Yes that should make sense as one can use the same context for multiple requests. We should make it so that calling WithContext multiple times chains the contexts though rather than replace.

**Comment by tomponline** [comment]
Also aside from canceling the http request would it be possible to tie operation cancelation into context cancelation where appropriate?

**Comment by stgraber** [comment]
Yeah, probably, we'd need some changes to the operation logic in the client but that should be doable.

**Comment by whywaita** [comment]
@stgraber @tomponline Thank you for your comments!

> The ones for connection I think make sense to add, that's fine. For the rest, I wonder if we could get away with a .WithContext(ctx).XYZ trick, the same way we do for UseTarget or UseProject currently.

`UseTarget` or `UseProject` only change variable in `ProtocolLXD`. This situation can use your suggested method. But, I think this method can't apply to `WithContext`.
`target` and `project` is the value of struct, But `context.Context` should not be stored inside a struct type. ref: [Contexts and structs](https://go.dev/blog/context-and-structs)

This is a sample code that implements the chaining method.
https://go.dev/play/p/vpt8QzOAPpP

```
$ go run main.go
{Value:}
&{Value:temporary value} // Call WithValue
{Value:temporary value} // Remain temporary value, It occurred bug
```

`context.Context` is request-scoped value, So this situation can't apply `.WithContext(ctx)` and function needs `context.Context` in first arguments.
`XXXWithContext` is main function and `XXX` call `XXXWithContext` with `context.Background()` for backward compatibility.

`XXXWithContext` method use offen many case in Go. ref: [net/http](https://pkg.go.dev/net/http#NewRequestWithContext)

> Also worth noting, we shouldn't make any changes to lxd_containers.go as all those functions are effectively deprecated in favor of the lxd_instances.go ones. We've been keeping those around to avoid breaking downstream users but we don't add any new functions in there.

Oh, really? ok, I will delete new functions in `lxd_containers.go`.

**Comment by stgraber** [comment]
Yeah, so I'd definitely like for `UseProject`, `UseTarget` and `WithContext` to all return a proper distinct struct, so we'll likely need some copy logic to do this properly. We definitely don't want those functions to alter the source struct.

And yeah, storing a context as part of the struct isn't ideal and doesn't really follow the current Go guidelines and when we do write a new Go client, we will definitely have all functions take in contexts, but for now, I'd like to stay away from the symbol pollution and duplicated functions/wrappers.

**Comment by whywaita** [comment]
hmm, many codes need to remove `context.Context` after function if `context.Context` is embedded in a struct.

Maybe, implementation is it. What do you think?

```Go
type ProtocolLXD struct {
	ctx context.Context
(snip)
}

func (r *ProtocolLXD) GetImages() ([]api.Image, error) {
	ctx := r.ctx
	if ctx == nil {
		ctx = context.Background()
	}
	defer func() {
		r.ctx = nil
	}()

	images := []api.Image{}

	_, err := r.queryStruct(ctx, "GET", "/images?recursion=1", nil, "", &images)
	if err != nil {
		return nil, err
	}

	return images, nil
}
```

**Comment by stgraber** [comment]
Well, based on what you showed above, this would have issues if someone does a bunch of things in parallel in Go routines.
I also agree with an earlier comment from @tomponline that this approach would allow for:
```
    client = client.UseTarget("foo").WithContext(ctx)
    client.CreateSomething
    client.UpdateSomethingElse
```

And effectively run a batch of actions using a shared context, so having it clear automatically doesn't feel ideal.

I think I'd expect `WithContext` to give me a proper standalone copy of the client with that context applied and with no way for the caller to change/remove the context without getting another client through another `WithContext` call.

**Comment by whywaita** [comment]
I see. I will try to implement `WithContext` after.

```
func (r *ProtocolLXD) WithContext(ctx context.Context) InstanceServer {
	rr := r
	rr.ctx = ctx
	return rr
}
```

And I have a  question.
Do you have a plan to add context to the first argument with breaking backward compatibility?

If there is,
About when will that be?
Why not now?

I think it can with versioning.

**Comment by stgraber** [comment]
We're not going to do it with LXD 5.0 LTS as we're too close to that release, so maybe LXD 6.0 LTS which would be in a bit over two years.

**Comment by whywaita** [comment]
@stgraber I implemented,  https://github.com/lxc/lxd/pull/9785/commits/f5e352f2d001fc0cc338fe8be22f542eebbc6daf.
Please review it again.

**Comment by stgraber** [comment]
Nice! That's so much shorter.

Can you maybe turn this into two commits:
 - client: Add WithContext
 - client: Add context-aware connection functions

**Comment by whywaita** [comment]
ok, I fixed 💪

**Comment by whywaita** [comment]
Sorry, I found a revert commit. I will delete it.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Tests are failing I'm afraid

**Comment by tomponline** [comment]
32msocket[0m=10.1.1.101:8443
Error: Failed to create network "lxd856090" in project "default": net/http: nil Context

**Comment by whywaita** [comment]
I will check it after 👀

**Comment by whywaita** [comment]
I fixed it, Please retry to test. https://github.com/lxc/lxd/pull/9785/commits/27f54b3e1e6b82a7fc095d74f5f029c3eda141d4

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks good, can you rebase that last commit into the first?

**Comment by whywaita** [comment]
rebased :)

**Comment by stgraber** [comment]
jenkins: test this please

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by whywaita** [comment]
Thank you!

**Pull request merged**
