### PR TITLE
lxd/db/cluster: Fix incorrect storage volume node IDs

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

**Comment by monstermunchkin** [comment]
See https://discuss.linuxcontainers.org/t/error-sql-scan-error-on-column-index-0-name-node-id-converting-null-to-int-is-unsupported/8826

**Comment by monstermunchkin** [comment]
This bug doesn't seem to affect clusters, and only occurs on setups which have two or more storage pools where one of them is ceph or cephfs.

**Comment by stgraber** [comment]
@monstermunchkin should you fix the original DB patch too to avoid this issue happening in the first place?

Having an extra patch fix the damage is obviously good but we could probably avoid creating the damage too :)

**Comment by monstermunchkin** [comment]
@stgraber OK, I'll do that. Wasn't sure whether or not we change existing patches.

**Pull request merged**
