### PR TITLE
Do not try to use syslog on Windows

### PR DESCRIPTION
**Pull request by techtonik**
Another incremental fix for #825. Is there a better way to do this?

Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

To have this branch tested by Jenkins, comment "jenkins: ok to test"
To have a one time test done, comment "jenkins: test this please"

**Comment by techtonik** [comment]
@stgraber strange. I see Jenking results here https://jenkins.linuxcontainers.org/job/lxd-trigger-github-pr/155/arch=i386,compiler=golang-1.3,restrict=lxd-priv/console

**Comment by stgraber** [comment]
You forgot to run "go fmt ./..."

**Comment by stgraber** [comment]
And yeah, it's strange that jenkins triggered. I wonder if the automatic comment is enough to trigger it, which would be pretty special :)

**Comment by stgraber** [comment]
I'll change the comment to not include the magic strings, hopefully that'll do the trick :)

**Comment by techtonik** [comment]
`go fmt ./...` is cool. There should be a GitHub plugin for that. =)

**Comment by techtonik** [comment]
But note that I am currently on Windows machine and didn't test on Linux if syslog handler is initialized properly.

**Comment by stgraber** [comment]
Looks like Linux is fine but you broke MacOS :)

**Comment by techtonik** [comment]
@stgraber Done.

**Pull request merged**
