### PR TITLE
Move ZFS helper functions

### PR DESCRIPTION
**Pull request by dnegreira**
Moved all the helper functions from lxd/storage_zfs.go to lxd/storage_zfs_utils.go

Closes: #3471

Signed-off-by: David Negreira <David@otherreality.net>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
buildd03 is being really annoying today

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
