### PR TITLE
Small doc fixes

### PR DESCRIPTION
**Pull request by ru-fu**
Several small fixes to the docs - see the commits.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by stgraber** [comment]
What are the text changes to doc/instances.md?

Github doesn't show a useful diff here.

**Comment by ru-fu** [comment]
> What are the text changes to doc/instances.md?
> 
> Github doesn't show a useful diff here.

Only removing spaces at the end of the line (default configuration in my editor). So Git actually displays it correctly. ;)

**Comment by stgraber** [comment]
Ah, Github Mobile didn't show them, Github Web does, fun...

Can you move those whitespace fixes into a separate commit?

**Comment by stgraber** [comment]
(They likely weren't there as an accident, they were there because we needed actual line breaks at some point with some markdown parsers but that shouldn't be needed with Sphinx)

**Comment by ru-fu** [comment]
Updated.

**Pull request merged**
