### PR TITLE
lxd/storage: Cleanup volume API endpoints

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This is in preparation for adding new API endpoints for #7708

**Comment by tomponline** [comment]
@stgraber looks like an issue on tests with this change, perhaps to do with capturing `{name:.*}` in the URL?

**Comment by stgraber** [comment]
Yeah, it's a CLI issue I believe, snapshots should be accessed through /snapshots/name instead.

**Comment by stgraber** [comment]
@tomponline should be good to go as a first step

**Review by tomponline — APPROVED** [review]

**Pull request merged**
