### PR TITLE
Split util_linux.go cgo specific code to seperate file

### PR DESCRIPTION
**Pull request by mjrider**
util_linux.go for all linux util functions, without cgo specific code
util_linux_cgo.go for all linux util functions depending on cgo

Reason:

github.com/sl1pm4t/terraform-provider-lxd uses the shared lxd code for
interactions with the lxd daemon. Compiling this for other
architectures, results in a build where archive_linux.go isn't
compilable because of missing functions defined in util_linux.go

This would fix compile errors where no cgo specific code is used but the code needed is not compiled because it is in a cgo only source file

with this, gox could build the terraform plugin for the following platforms

```
gox
Number of parallel builds: 7

-->     windows/386: github.com/sl1pm4t/terraform-provider-lxd
-->       linux/arm: github.com/sl1pm4t/terraform-provider-lxd
-->   freebsd/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->   windows/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->      darwin/386: github.com/sl1pm4t/terraform-provider-lxd
-->     openbsd/386: github.com/sl1pm4t/terraform-provider-lxd
-->     freebsd/386: github.com/sl1pm4t/terraform-provider-lxd
-->       linux/386: github.com/sl1pm4t/terraform-provider-lxd
-->    darwin/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->     linux/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->      netbsd/arm: github.com/sl1pm4t/terraform-provider-lxd
-->     freebsd/arm: github.com/sl1pm4t/terraform-provider-lxd
-->      netbsd/386: github.com/sl1pm4t/terraform-provider-lxd
-->    netbsd/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->   openbsd/amd64: github.com/sl1pm4t/terraform-provider-lxd
-->     linux/s390x: github.com/sl1pm4t/terraform-provider-lxd
```

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by mjrider** [comment]
i tried it on a locally installed trusty box, and it  isn't enough for other architectures
it then fails on:
```
Stderr: # github.com/lxc/lxd/shared
../../lxc/lxd/shared/archive_linux.go:83:15: undefined: DeviceTotalMemory
```

that error was the reason why i started to split to cgo code in a separate file

**Comment by brauner** [comment]
@mjrider, I'm going to close my patch. Can you please copy the code I wrote in there for the ifdefines into this branch and then we can go on and merge it.

**Comment by mjrider** [comment]
i pulled your change into my branch

**Comment by brauner** [comment]
Can you please remove the merge commit? Also, please do a `make static-analysis` as Jenkins looks unhappy with formatting in your branch.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Jenkins went offline on two builder. Don't worry.

**Pull request merged**
