### PR TITLE
Instance: Stop source instance from freezing when using --allow-inconsistent

### LINKED ISSUE #10091: Stateless lxc copy freeze container despite allow-inconsistent is set
# Required information

   * Kernel version: 5.4.0-91-generic
   * LXC version: 4.0.12
   * LXD version: 4.24
   * Storage backend in use: dir

# Issue description

lxc copy freeze source container despite `--allow-inconsistent` and `--stateless` is set. 

# Steps to reproduce
```
lxc copy remote:a b --stateless --allow-inconsistent
```

### PR DESCRIPTION
**Pull request by markylaing**
Running `lxc copy c1 remote:c1 --stateless --allow-inconsistent` is currently causing the source container c1 to freeze. This change ensures that the container is not frozen for either `lxc copy c1 remote:c1 --allow-inconsistent` or `lxc copy remote:c1 c1 --allow-inconsistent`. 

Closes #10091

### CODE REVIEW

**Comment by markylaing** [comment]
@tomponline This should fix the issue, though I think I may have found a couple more problems that I'll put in a separate PR for us to discuss.

**Review by tomponline — CHANGES_REQUESTED** [review]
Other request specific properties (like refresh) are added to the migrationSourceWs struct rather than as args to Do() so would be good to keep things consistent.

**Comment by markylaing** [comment]
> Other request specific properties (like refresh) are added to the migrationSourceWs struct rather than as args to Do() so would be good to keep things consistent.

@tomponline fixed.

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
jenkins: test this please

**Pull request merged**
