### PR TITLE
correctly set liblxc loglevel to debug when in --debug mode

### PR DESCRIPTION
**Pull request by tych0**
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Oops, not sure how that was even considered valid Go code :)

So your change is still wrong, we certainly don't want to set loglevel to trace if no debug or verbose arguments were passed.

I think we want:
 - --debug -> trace
 - --verbose -> info
 - No debug or verbose arg -> warn

**Comment by tych0** [comment]
Oh, yeah, I didn't even read the surrounding code. I'll push a fix for that too in a sec.

**Comment by tych0** [comment]
Wait. Do we really want debug == trace? Why not debug == debug? The others sound fine.

**Comment by tych0** [comment]
Oh, I see. Trace is what it was before. Never mind, that sounds good then. I was thinking it was just debug.

**Pull request merged**
