### PR TITLE
lxd/operations: Support nil state

### PR DESCRIPTION
**Pull request by monstermunchkin**
This adds support for a nil state which may occur when using the
lxd-agent.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@monstermunchin for my own understanding, does this reduce the functionality of an operation when used without state? If so what is lost and what is the remaining purpose of an operation? Thanks

**Comment by stgraber** [comment]
@tomponline without state, the operation will not be recorded in the database (agent has no database and this is only relevant for clustering) and you won't be getting updates on operation through events (which similarly isn't very relevant to the agent).

**Comment by tomponline** [comment]
@stgraber thanks, what purpose does the operation serve without state?

**Comment by stgraber** [comment]
@tomponline None of the endpoints at `/1.0/operations` requires the state, we only need the state when clustering or when the client is using `/1.0/events` rather than using the operations API directly.

**Pull request merged**
