### PR TITLE
Typo: now -> know

### PR DESCRIPTION
**Pull request by ajthemacboy**

### CODE REVIEW

**Comment by stgraber** [comment]
Good catch. Can you sign-off your commit (Signed-off-by line) as mentioned in CONTRIBUTING.md?

Thanks

**Comment by ajthemacboy** [comment]
Sorry, I doubt I did that right, I've never made a pull request before. Where do I add my sign-off?

**Comment by stgraber** [comment]
In the commit message itself.
If using the command line, the "-s" flag to "git commit" will do it for you.

**Comment by ajthemacboy** [comment]
I think you better do it yourself. I have no idea what I'm doing.

**Pull request closed without merging**
