### PR TITLE
Use a helper function for creating working directories.

### PR DESCRIPTION
**Pull request by jameinel**
Rather than creating a cleanup function for each type, just create
the directories with a function that safely cleans them up when the
process exits.

### CODE REVIEW

**Comment by jameinel** [comment]
This is an alternative fix vs https://github.com/lxc/lxd/pull/1523
It both creates the directories with an interesting name, so that if they *are* left around, we know who created them. And then it always cleans them up at exit.

**Comment by stgraber** [comment]
Please sign-off your commits (see CONTRIBUTING.md)

**Comment by stgraber** [comment]
@jameinel any chance you can get this signed-off?

Thanks!

**Comment by stgraber** [comment]
Closing due to lack of activity (and us not being able to legally merge this without the Signed-off-by line).

**Pull request closed without merging**
