### PR TITLE
Cgroup: Update GetIOStats to be more flexible

### LINKED ISSUE #10953: Failed parsing io.stat
# Required information

 * Distribution: Alpine
 * Distribution version: edge
 * The output of "lxc info":
```yaml
config: {}
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- snapshot_schedule_aliases
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
- tpm_device_type
- storage_zfs_clone_copy_rebase
- gpu_mdev
- resources_pci_iommu
- resources_network_usb
- resources_disk_address
- network_physical_ovn_ingress_mode
- network_ovn_dhcp
- network_physical_routes_anycast
- projects_limits_instances
- network_state_vlan
- instance_nic_bridged_port_isolation
- instance_bulk_state_change
- network_gvrp
- instance_pool_move
- gpu_sriov
- pci_device_type
- storage_volume_state
- network_acl
- migration_stateful
- disk_state_quota
- storage_ceph_features
- projects_compression
- projects_images_remote_cache_expiry
- certificate_project
- network_ovn_acl
- projects_images_auto_update
- projects_restricted_cluster_target
- images_default_architecture
- network_ovn_acl_defaults
- gpu_mig
- project_usage
- network_bridge_acl
- warnings
- projects_restricted_backups_and_snapshots
- clustering_join_token
- clustering_description
- server_trusted_proxy
- clustering_update_cert
- storage_api_project
- server_instance_driver_operational
- server_supported_storage_drivers
- event_lifecycle_requestor_address
- resources_gpu_usb
- clustering_evacuation
- network_ovn_nat_address
- network_bgp
- network_forward
- custom_volume_refresh
- network_counters_errors_dropped
- metrics
- image_source_project
- clustering_config
- network_peer
- linux_sysctl
- network_dns
- ovn_nic_acceleration
- certificate_self_renewal
- instance_project_move
- storage_volume_project_move
- cloud_init
- network_dns_nat
- database_leader
- instance_all_projects
- clustering_groups
- ceph_rbd_du
- instance_get_full
- qemu_metrics
- gpu_mig_uuid
- event_project
- clustering_evacuation_live
- instance_allow_inconsistent_copy
- network_state_ovn
- storage_volume_api_filtering
- image_restrictions
- storage_zfs_export
- network_dns_records
- storage_zfs_reserve_space
- network_acl_log
- storage_zfs_blocksize
- metrics_cpu_seconds
- instance_snapshot_never
- certificate_token
- instance_nic_routed_neighbor_probe
- event_hub
- agent_nic_config
- projects_restricted_intercept
- metrics_authentication
- images_target_project
- cluster_migration_inconsistent_copy
- cluster_ovn_chassis
- container_syscall_intercept_sched_setscheduler
- storage_lvm_thinpool_metadata_size
- storage_volume_state_total
- instance_file_head
- instances_nic_host_name
- image_copy_profile
- container_syscall_intercept_sysinfo
- clustering_evacuation_mode
- resources_pci_vpd
- qemu_raw_conf
- storage_cephfs_fscache
- network_load_balancer
- vsock_api
- instance_ready_state
- network_bgp_holdtime
- storage_volumes_all_projects
- metrics_memory_oom_total
- storage_buckets
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses: []
  architectures:
  - aarch64
  - armv7l
  certificate: RECATED
  certificate_fingerprint: REDACTED
  driver: lxc | qemu
  driver_version: 5.0.1 | 7.1.0
  firewall: nftables
  kernel: Linux
  kernel_architecture: aarch64
  kernel_features:
    idmapped_mounts: "true"
    netnsid_getifaddrs: "true"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.15.70-0-lts
  lxc_features:
    cgroup2: "true"
    core_scheduling: "true"
    devpts_fd: "true"
    idmapped_mounts_v2: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Alpine Linux
  os_version: 3.17_alpha20220809
  project: default
  server: lxd
  server_clustered: false
  server_event_mode: full-mesh
  server_name: lxd
  server_pid: 2938
  server_version: "5.5"
  storage: zfs | btrfs
  storage_version: 2.1.5-1 | 5.19.1
  storage_supported_drivers:
  - name: zfs
    version: 2.1.5-1
    remote: false
  - name: btrfs
    version: 5.19.1
    remote: false
  - name: dir
    version: "1"
    remote: false
```

# Issue description

I don't know when this started happening since I haven't checked the logs for quite some while but I can see this warning once per minute in the LXD log:
```
time="2022-09-27T05:46:24Z" level=warning msg="Failed to get disk stats" err="Failed parsing io.stat (\"8:0 179:0 rbytes=151552 wbytes=0 rios=22 wios=0 dbytes=0 dios=0\"): input does not match format" instance=openwrt-snapshot instanceType=container project=default
```

# Steps to reproduce
Unfortunately, I don't know how.
The weird part is that it only happens to one of many containers though.

# Information to attach
My current assumption is that the debug message is enough for you to understand what's wrong since it contains the line that can't be parsed. If not, I'll provide more information.

### PR DESCRIPTION
**Pull request by tomponline**
Allows additional metrics to be added to io.stat file without it failing.

Fixes #10953

Also includes shiftfs fix for test suite.

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber something I noticed whilst testing this is that when using cgroupv2 on my ubuntu jammy system I did not have a blkio cgroup (shown in `lxc warning list`) but the `io.stat` file was still available.

So two questions I had was:

1. How do I enable the blkio controller in cgroupv2 (as this code path is only for cgroupv2)?
2. Should we even be relying on the blkio controller being present in order to generate these stats from the `io.stat` file?

**Review by monstermunchkin — APPROVED** [review]

**Comment by monstermunchkin** [comment]
> 1. How do I enable the blkio controller in cgroupv2 (as this code path is only for cgroupv2)?

AFAIK `blkio` doesn't exist in cgroupv2. It has `io` instead.

**Comment by tomponline** [comment]
> > 1. How do I enable the blkio controller in cgroupv2 (as this code path is only for cgroupv2)?
> 
> AFAIK `blkio` doesn't exist in cgroupv2. It has `io` instead.

thanks, in that case there is a bug here https://github.com/lxc/lxd/blob/255a79ff40234e1fa1ebb0e07eac88c73705b60a/lxd/cgroup/abstraction.go#L955-L958 because it tries to detect the blkio cgroup and returns unavailable for cgroupv2 systems, making reaching https://github.com/lxc/lxd/blob/255a79ff40234e1fa1ebb0e07eac88c73705b60a/lxd/cgroup/abstraction.go#L1021-L1022 impossible.

Although I don't know how the OP got that error.

**Comment by tomponline** [comment]
Oh except:

https://github.com/lxc/lxd/blob/master/lxd/cgroup/init.go#L488-L492

Thats confusing :(

**Comment by tomponline** [comment]
OK figured it out. There seems to be a problem (at least on my system) with LXD detecting the io cgroup controller is available.

From what I can see, LXD detects the cgroup controllers it has available by doing:

1. Read `/proc/self/cgroup` and extracting the cgroup path, in my case `/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-04801f11-afad-4a8f-b04d-d309c69a831b.scope`
2. Then reading `/sys/fs/cgroup/<path from above>/cgroup.controllers`. So in my case `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/app-org.gnome.Terminal.slice/vte-spawn-04801f11-afad-4a8f-b04d-d309c69a831b.scope/cgroup.controllers`

On my system this gives:
 
```
memory pids
```

So no `io` controller hence the error: `Couldn't find the CGroup blkio` (which is confusing but anyway).

But... if I look at the cgroups for the actual containers:

```
cat /sys/fs/cgroup/lxc.monitor.c1/cgroup.controllers 
cpuset cpu io memory hugetlb pids rdma misc
```

We can see that there is the io controller available but just not to the LXD process.
I suspect something is wrong with the way I'm starting up LXD...

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Anyway this pr should be fine now.

**Pull request merged**
