### PR TITLE
lxd/project: Always allow cloud-init:config drives

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
Could 'cloud-init:config' be made a constant so where it's now used in multiple places are linked in code? Thanks

**Comment by stgraber** [comment]
Not without causing an import loop...

**Comment by stgraber** [comment]
Well, I could probably move the const into the project package but that'd be a bit weird.

**Comment by stgraber** [comment]
@tomponline we're dealing with both lxd/device and lxd/project here. I think it makes sense to have the const inside of lxd/device as it is today, unfortunately we can't export this as lxd/project importing lxd/device causes the import loop.

**Comment by tomponline** [comment]
> @tomponline we're dealing with both lxd/device and lxd/project here. I think it makes sense to have the const inside of lxd/device as it is today, unfortunately we can't export this as lxd/project importing lxd/device causes the import loop.

Ok fair enough 🙂

**Comment by stgraber** [comment]
@tomponline good to go

**Pull request merged**
