### PR TITLE
Remove pre LXD 4.0.0 schema patches

### PR DESCRIPTION
**Pull request by tomponline**

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline let me know if you'd like me to take some of this over and see what we can get into 5.0.
Currently I'm working my way through #10156 and looking at fixing #10041, #10101 and #10122 before releasing 5.0, the rest I'll push to 5.1.

**Comment by tomponline** [comment]
> @tomponline let me know if you'd like me to take some of this over and see what we can get into 5.0. Currently I'm working my way through #10156 and looking at fixing #10041, #10101 and #10122 before releasing 5.0, the rest I'll push to 5.1.

Yes that would be great if you have time. Thanks

**Comment by stgraber** [comment]
@tomponline did you have more you wanted to put in there or are we good now that I got the tests to behave?

**Comment by tomponline** [comment]
> @tomponline did you have more you wanted to put in there or are we good now that I got the tests to behave?

I think that's it for now. We have to keep all of the old post clustering schema patches to allow the current schema to build right?

**Comment by stgraber** [comment]
Yeah, I'd stay away from messing with the DB patches themselves as it may get weird for the schema versioning.

**Pull request merged**
