### PR TITLE
container/lxc: Moves volatile host_name enrichment to fillNetworkDevice

### PR DESCRIPTION
**Pull request by tomponline**
Also clears volatile host_name keys when container stops.

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Appears to be breaking migration somehow?

**Comment by tomponline** [comment]
@stgraber this was do to with adding back in host_name enrichment from volatile data into `fillNetworkDevice()`. It seems that migration doesnt stop the container on source before starting again on dest and this causes the same host name to be used during the tests that are running on the same host and so conflict and prevent container start.

I ended up reverting my change, and adding a function called `getVolatileHostName()` instead as I think the safest common scenario is for host_name to not be populated from volatile during `fillNetworkDevice()` as that is almost always not what you want. And in the couple of scenarios where you need to look up the volatile data, its clearer to do it explicitly.

I've also removed the sriov host_name enrichment from volatile in `fillNetworkDevice` too, as it is overriden in `fillSriovNetworkDevice` anyway.

**Comment by tomponline** [comment]
jenkins: test this please

**Pull request merged**
