### PR TITLE
list: Re-add dropped sort.Sort call

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by techtonik** [comment]
@stgraber but why? The list is already sorted.

**Comment by stgraber** [comment]
@techtonik The LXD API doesn't specify any sorting of the lists it returns, the fact that it happens to be sorted alphabetically in this case is an accident and not something the client should rely on.

**Comment by stgraber** [comment]
For example, if we were to start using goroutines to prepare the response on the server side, then the returned dataset would be sorted by whichever goroutine is done first rather than by the DB ordering and that'd then cause clients that don't sort based on what they want to render to show things in a seemingly random ordering.

**Comment by techtonik** [comment]
@stgraber I see. Then maybe remove `ORDER BY name` from server side query, so that clients are not built relying on that current behavior?

**Pull request merged**
