### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by pcdummy**
Please pull in the storage branch (#858) first.

Currently this adds 2 Commits:
- Define the snapshot delimiter in shared.
- Code consistency for the DB code.

Both are a split out of my upcoming "containers" branch where i define an Interface for lxdContainer and make lxdContainer the base for all Container operations.

### CODE REVIEW

**Comment by pcdummy** [comment]
Please review this comit for commit, instead of all changes at once.

**Comment by pcdummy** [comment]
It was just that variable.

**Comment by stgraber** [comment]
Branch needs rebasing :(

**Comment by stgraber** [comment]
Left a couple of comments. Will recheck post-rebase.

**Comment by pcdummy** [comment]
Rebase is done, about the log15 change. This way we make sure the logger is never empty. Yeah, its another function call and another if per logline. Not sure we want this.

**Comment by pcdummy** [comment]
Did another manual rebase and removed the log15 "optimization".

**Comment by stgraber** [comment]
Thanks, looking at this now.

**Pull request merged**
