### PR TITLE
Send snapshots

### PR DESCRIPTION
**Pull request by tych0**

### CODE REVIEW

**Comment by stgraber** [comment]
Please fix the two path comments and fix whatever is causing Jenkins regressions then it should be fine to merge.

**Comment by tych0** [comment]
jenkins: test this please

**Comment by tych0** [comment]
Jenkins: test this please

**Comment by stgraber** [comment]
Let's call it good :)

**Comment by tych0** [comment]
/me prays to the CI gods for forgiveness :)

**Pull request merged**
