### PR TITLE
driver_qemu: transition to OVMF with 4M

### PR DESCRIPTION
**Pull request by monkz**
LXD will use and initialize VMs with OVMF fd size 4MB if a VM was not initialized with 2MB. Detection is based on the existence of "qemu.nvram" file, thus 2MB taking precedence if present. New initialized VMs will use "qemu.4MB.nvram" as nvram filename instead.

### CODE REVIEW

**Comment by monkz** [comment]
For this PR is  https://github.com/lxc/lxd-pkg-snap/pull/119 required.

Cherry picking this commit onto 5.12 candidate was successful in my tests.

**Comment by stgraber** [comment]
We need the code to be backward compatible, that is, work on a system without a .4MB file present.
Not all LXD users use the snap so we have no way to guarantee that those files will exist.

**Comment by tomponline** [comment]
@monkz hey, how are you getting on with this?

**Comment by monkz** [comment]
Not forgotten, I've just a temporary misalignment of tasks due to personal matters. 😅
But tests work well so far.

I might need help on how to react if LXD detects (detecting is possible via size) 4M was used, but is not available on a new host after transfer.

**Comment by tomponline** [comment]
@monkz shall I close this for now?

**Comment by stgraber** [comment]
My upcoming PR will be closing this one.

**Comment by monkz** [comment]
Thank you both.

**Pull request closed without merging**
