### PR TITLE
lxc/utils/table: add compact table

### PR DESCRIPTION
**Pull request by 745150400**
Feature #9162 Introducing a different --format makes the table more compact.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by stgraber** [comment]
This needs:
 - make i18n
 - git commit -a -s -m "i18n: Update translation templates"
 - git push

As it's modifying some translated strings.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by 745150400** [comment]
> This needs:
> 
> * make i18n
> * git commit -a -s -m "i18n: Update translation templates"
> * git push
> 
> As it's modifying some translated strings.

ok, give me a moment, i'm learning how to make il8n

**Review by simondeziel — APPROVED** [review]

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
