### PR TITLE
shared/logging: Add freebsd build conditional to log_posix.go

### PR DESCRIPTION
**Pull request by vifino**
Allows building of the LXD client on FreeBSD.
Rudimentary testing shows that the client is functional, too.

Minuscule change, great profit for FreeBSD users. :)

Signed-off-by: Adrian Pistol <vifino@tty.sh>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
There's not much point in waiting for Jenkins on all slaves. If it builds it's fine. :)

**Comment by vifino** [comment]
Yay! :tada:

**Comment by brauner** [comment]
@vifino, are you really using the client from `FreeBSD` to run containers on Linux? I'd like to read about that actually. It sounds fun. Given that the underlying driver `liblxc` is mainly focused on system containers I'd like to hear some thoughts/insights from `'FreeBSD` people.

**Comment by vifino** [comment]
@brauner Not sure I count as "FreeBSD People", but I can give you some words.
But yes, I am using the client on FreeBSD to manage LXD servers on Linux.

I'm using LXD on a few machines, let me speak about the machine that I run 24/7 at home. 
It runs Alpine on the host, a virtualized OPNSense VM for the basic router-buisness things.
Few things run on the host, a NTP server and nginx for proxying purposes are the only things I can think of.

I use LXD containers much like I'd use jails on a FreeBSD machine. I have a `xmpp` container running `prosody`, a `vcs` container running `gitea`, compartmentalized things in very, very minimal containers. All based on Alpine. Really like how easy it is to manage.

Basic stuff which I assume most LXD users are doing.
My network setup is a bit convoluted, but that's beneath the point.

Anyhow, I connect to the machine via the LXD client from machines which I control.
Just quite casual things. Not much magic here apart from LXD. :)

I do plan to make a small `bhyve` VM which runs LXD and some essential services and then use lxd to manage it. Mostly for testing reasons. With `criu`, I can build some container to run *something* and just
push it to some boxen.

But yeah, not much to tell. Just managing LXD servers like I would on any Linux machine.

Unrelated: The only issue with using Alpine as a host is that systemd-based images don't really work, which unfortunately make up the majority of modern distributions, I'm afraid.
I think with some kernel changes, it might work. Currently, everything fails to connect to the bus and
no actual start of processes happens. systemd just sits there, idly...

**Comment by brauner** [comment]
Thanks for the writeup. About your systemd-container-on-Alpine-host problem. The issue is usually just that systemd expects the named cgroup `systemd` to exist.So on the host if you do:

```
sudo mkdir /sys/fs/cgroup/systemd
sudo mount -t cgroup -o rw,nosuid,nodev,noexec,relatime,none,name=systemd cgroup /sys/fs/cgroup/systemd
```
and then try to create `systemd` containers does that work?

**Comment by vifino** [comment]
I am trying. I got LXD to throw a lot of errors. :)

Between
```
λ vifino [~] → lxc launch images:ubuntu/artful systemdtest
Creating systemdtest
error: Failed container creation:
 - https://images.linuxcontainers.org: UNIQUE constraint failed: storage_volumes.storage_pool_id, storage_volumes.name, storage_volumes.type
```
and
```
λ vifino [~] → lxc launch images:debian/jessie testmachine
Creating testmachine
error: Failed container creation:
 - https://images.linuxcontainers.org: Unpack failed, Failed to run: tar -C /var/lib/lxd/storage-pools/storage/images/792012706 --numeric-owner -Jxf /var/lib/lxd/images/0d6ae4bcccfdb72fdcb88ab5db770a1e37a147c6bdb3b24164ba95d984bba0f6: tar: templates/hosts.tpl: Cannot open: File exists
tar: metadata.yaml: Cannot open: File exists
tar: templates/hostname.tpl: Cannot open: File exists
tar: Exiting with failure status due to previous errors.  tar: templates/hosts.tpl: Cannot open: File exists
```

I have "ghost containers" which don't show in list but in storage pool editing.
I can "fix" those issues by deleting the downloaded images or stale ZFS paths.

Guess that's what I get for having this machine be my long running testbed. :)

---

It seems to work better. `dhclient` no longer has bus errors. systemctl still `Failed to connect to bus: No such file or directory`.
Not sure if the debian stretch image is supposed to start anything by default, though... It doesn't seem to.

**Comment by brauner** [comment]
Which LXD version are you on?

**Comment by brauner** [comment]
lxc info should tell you

**Comment by vifino** [comment]
Oops, sorry. Got distracted.
LXD 2.19.

**Comment by brauner** [comment]
It seems that your db got messed up so I suspect that's one of the main issues. It seems that there are a bunch of entries from old but deleted containers. What LXD version did you start with actually, if you remember?

**Comment by vifino** [comment]
Sorry, I can not. But it was more than a year ago for sure. Maybe one and a half?

**Comment by vifino** [comment]
It was before the 18th february for sure. This install/config setup probably came initially from 2.9.1, but I am not sure.

**Pull request merged**
