### PR TITLE
Storage: Enable BTRFS nodatacow on raw block files to avoid quota issues

### LINKED ISSUE #9124: BTRFS quota is reached when filling up VM disk image file
Even though LXD sets the BTRFS quota 100MB (by default) larger than the VM disk file max size, if the VM uses all of its disk space the underlying BTRFS filesystem sees that the referenced disk quota has been reached and prevents LXD from starting the VM because it cannot write the backup file. Even though there should be some space free.

It seems like BTRFS quota isn't working the way we think it does.

See https://discuss.linuxcontainers.org/t/btrfs-issues-storage-pools-btrfs-empty-and-btrfs-quota-100-while-inside-the-vm-only-48-utilized/11897

Steps to reproduce:

```
lxc storage create btrfs btrfs
lxc init images:ubuntu/focal/cloud v1 --vm -s btrfs

# This should do 2 things; increase disk image file size to 11GB, and enable BTRFS disk quotas to a size of 11GB+100MiB (which is the default `volume.state` size) to account for the entirety of the disk size, and allow 100MiB for volume state usage.
lxc config device set v1 root size=11GB # Accounting for VM image file size sizeBytes=11104862208 blockSize=11000004608
```
Check BTRFS quota set (expect it to be blockSize 11000004608 + 100MiB (104857600 bytes) = 11104862208 bytes):
```
sudo btrfs subvolume show --raw /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1
virtual-machines/v1
	Name: 			v1
	UUID: 			5816cce0-0dba-3348-bd29-14b80dfdbc85
	Parent UUID: 		06d1312f-5158-f44e-89a0-999e132ee7bc
	Received UUID: 		-
	Creation time: 		2021-12-01 12:27:57 +0000
	Subvolume ID: 		272
	Generation: 		2516
	Gen at creation: 	2515
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			-
	Snapshot(s):
	Quota group:		0/272
	  Limit referenced:	11104862208 # Matches requested sizeBytes of 11104862208
	  Limit exclusive:	-
	  Usage referenced:	2361466880
	  Usage exclusive:	57344
```

Check size of root disk file (expect it to be 11000004608 bytes):

```
sudo du -b /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
11000004608	/var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
```

Start the VM:
```
lxc start v1
lxc shell v1
```

Now inside v1 run until the disk fills up (should fill up the disk image but not reach BTRFS quota as it has another 100MiB allowed):
```
cat /dev/urandom > /root/foo.bin
cat: write error: Read-only file system
```

You can now see that the BTRFS referenced quota has been reached, which it shouldn't have been.

```
sudo btrfs subvolume show --raw /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1
virtual-machines/v1
	Name: 			v1
	UUID: 			5816cce0-0dba-3348-bd29-14b80dfdbc85
	Parent UUID: 		06d1312f-5158-f44e-89a0-999e132ee7bc
	Received UUID: 		-
	Creation time: 		2021-12-01 12:27:57 +0000
	Subvolume ID: 		272
	Generation: 		3246
	Gen at creation: 	2515
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			-
	Snapshot(s):
	Quota group:		0/272
	  Limit referenced:	11104862208
	  Limit exclusive:	-
	  Usage referenced:	11104841728 # Limit reached, so how to explain if disk size is still 11000004608.
	  Usage exclusive:	9011888128
```

Disk image is still at set size of 11000004608.
```
sudo du -b /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
11000004608	/var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
```

And the actual used blocks of the image are:

```
du  -B1 root.img 
10758160384	root.img
```

Indeed the total size of the volume is less than the quota:

```
du  -B1 
20480	./templates
8192	./config/systemd
4096	./config/udev
4096	./config/files
14815232	./config
10773151744	.
```

### PR DESCRIPTION
**Pull request by tomponline**
Enable `nodatacow` so that random writes don't cause fragmentation and old extents to be kept.
BTRFS extents are immutable so when blocks are written they end up in new extents and the old ones remains until all of its data is dereferenced or rewritten. 

These old extents are counted in the quota, and so leaving CoW enabled can cause the BTRFS subvolume quota to be reached even if the block volume file isn't full.

Fixes #9124

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber this seems to fix the issue in https://github.com/lxc/lxd/issues/9124, and speed wise is equivalent to without it on my NVME drive:

```
dd if=/dev/urandom of=/root/foo.img bs=4M conv=fdatasync
dd: error writing '/root/foo.img': No space left on device
2474+0 records in
2473+0 records out
10375110656 bytes (10 GB, 9.7 GiB) copied, 125.724 s, 82.5 MB/s
```

Whereas the best I got before was `82.9 MB/s` (and sometimes it was lower than `82.5 MB/s`).

**Comment by tomponline** [comment]
@stgraber I will rework this based on comment https://github.com/lxc/lxd/issues/9124#issuecomment-985569642

> The compress stuff has been absolutely horrible at causing filesystem corruption in the past and as it's indeed a global option for the entire filesystem, I'd be quite worried to turn it on.

**Comment by stgraber** [comment]
@tomponline does this approach work properly?

**Comment by tomponline** [comment]
@stgraber just testing this now...

**Comment by tomponline** [comment]
@stgraber yep seems to work:

```
dd if=/dev/urandom of=/root/foo.img bs=4M conv=fdatasync
dd: error writing '/root/foo.img': No space left on device
2474+0 records in
2473+0 records out
10375118848 bytes (10 GB, 9.7 GiB) copied, 125.374 s, 82.8 MB/s
```

Quota not reached:

```
sudo btrfs subvolume show --raw /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1
virtual-machines/v1
	Name: 			v1
	UUID: 			7a356a4c-3372-e041-b39c-393a8fab7e9a
	Parent UUID: 		99549cb4-c2b0-5a4f-810c-15901948c93d
	Received UUID: 		-
	Creation time: 		2021-12-03 16:19:08 +0000
	Subvolume ID: 		268
	Generation: 		384
	Gen at creation: 	263
	Parent ID: 		5
	Top level ID: 		5
	Flags: 			-
	Snapshot(s):
	Quota group:		0/268
	  Limit referenced:	11916017664
	  Limit exclusive:	-
	  Usage referenced:	11354607616
	  Usage exclusive:	10848555008
```

**Comment by tomponline** [comment]
Hrm, so ith a fresh BTRFS storage pool (no existing image volumes):

```
lxc init images:ubuntu/focal/cloud v1 -s btrfs --vm
lxc config device set v1 root size=11Gi
sudo lsattr /var/lib/lxd/storage-pools/btrfs/images/15685435d292987420498cfc4e9529ec9d794c977715d7a7514a84bbb27a9b80/root.img
---------------C---- /var/lib/lxd/storage-pools/btrfs/images/15685435d292987420498cfc4e9529ec9d794c977715d7a7514a84bbb27a9b80/root.img
sudo lsattr /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
---------------C---- /var/lib/lxd/storage-pools/btrfs/virtual-machines/v1/root.img
```

It breaks:
```
dd if=/dev/urandom of=/root/foo.img bs=4M conv=fdatasync
dd: error writing '/root/foo.img': Read-only file system
2256+0 records in
2255+0 records out
9458155520 bytes (9.5 GB, 8.8 GiB) copied, 116.296 s, 81.3 MB/s
```

**Pull request closed without merging**
