### PR TITLE
Add the ability to send unix signal to a non-interactive exec session.

### PR DESCRIPTION
**Pull request by gleize**
From what I've tested and understand, the `ExecInstance` function can be called with a boolean `Interactive` flag.

* When the flag is on :
  * `stderr` and `stdout` are both merged to a `stdout` reader (so there is no way to know the source)
  * unix signals can be sent to the process
* When the flag is off :
  * `stderr` and `stdout` are kept separated using two distinct readers
  * unix signals are received, but not executed

So since, I would like to keep `stderr` and `stdout` separated AND the ability to send signals to the running process, I've added some code to handle the signals in the non-interactive case.

### CODE REVIEW

**Comment by stgraber** [comment]
Hi,

Can you rebase this on master and make sure that your commit is signed-off (git commit --amend -s)?

We can't really look at submitted code until the DCO check passes.

Thanks!

**Comment by gleize** [comment]
Hi,

It's done.

Thanks.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by elv-pierre** [comment]
The tests got stuck ?

**Comment by gleize** [comment]
The tests got stuck ?

**Comment by stgraber** [comment]
Yep, I'll have to go clean things up by hand later, looks like your change is causing a regression that causes an indefinite hang.

**Comment by gleize** [comment]
Sorry about that. I wasn't able to run all the tests (using `make check`) because some of the files didn't compile (even before I made the change), so I didn't catch that issue beforehand.

That last commit should fix the hang. At least I was able to reproduce it on my own tests.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
This looks fine to me.

**Pull request merged**
