### PR TITLE
netutils: improve file descriptor retrieval and increase robustness

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@brauner @stgraber there seems to be some static analysis failures on golang-tip, still happy to merge this?

**Comment by tomponline** [comment]
@brauner @stgraber ah Ive just seen @stgraber has handled this in https://github.com/lxc/lxd/pull/8496/commits/2a9aa8f5bcd48517345476e730cc007baca92049

**Comment by tomponline** [comment]
Also have just noticed its draft too :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@tomponline should be good to go!

**Comment by brauner** [comment]
Thanks, @stgraber!

**Pull request merged**
