### PR TITLE
Support .schema in lxd sql dump and update database docs

### LINKED ISSUE #4390: Improve database handling
Now that we are effectively dealing with two databases (lxd.db and raft), we need to make sure we have some pretty consistent tooling available to deal with those databases.

Off the top of my head, I'd like to at least see:
 - Move all database files under /var/lib/lxd/database/ renaming lxd.db to local.db in the process and `raft` to `global` so that we have consistent naming for the two databases.
 - Add support for `patch.local.sql` and `patch.global.sql` files in /var/lib/lxd/database. If present, they should be read and executed immediately after loading the database driver. On success, the file should be removed from disk to prevent accidental double execution.
 - Fix `lxd sql` causing LXD to panic when fed an empty query
 - Make `lxd sql` support reading from stdin as an alternative to passing the query as an argument
 - Have `lxd sql` support running multiple queries (if not already the case)
 - Make `lxd sql` interact with both databases, offering a consistent way to poke at LXD's databases. I'm happy to just require the first argument be one of `local` or `global` to achieve this.
 - Add support for `.dump` to `lxd sql` as a way to dump the database in SQL format.
 - Update our pre-upgrade logic to backup both local and global databases prior to doing a schema upgrade. Test that we have a clear way to perform a revert in a non-clustered environment (equivalent to `mv lxd.db.bak lxd.db` prior to 3.0)
 - Update doc/database.md to reflect the current database schema, explain the split between the two databases and make it clear what is where.

I expect to cherry-pick all of this to the stable-3.0 branch for LXD 3.0.1.

### PR DESCRIPTION
**Pull request by freeekanayaka**
Fixes #4390.

### CODE REVIEW

**Comment by stgraber** [comment]
@freeekanayaka any reason for not just implementing those two as the ".schema" and ".dump" SQL queries?

So I can do `lxd sql local .dump` or `lxd sql global .schema` just as I would with sqlite3?

**Comment by freeekanayaka** [comment]
@stgraber I wished it would be that easy, but .dump and .schema are implemented in the sqlite3 command line too using the normal C sqlite3 API, which by itself does not understand .dump and .schema.

**Comment by stgraber** [comment]
@freeekanayaka why can't we do the exact same thing? special case .dump and .schema as query string in the `lxd sql` client instead of making it --schema?

**Comment by freeekanayaka** [comment]
Ah I see what you mean now. Sure.

**Comment by freeekanayaka** [comment]
@stgraber done

**Pull request merged**
