### PR TITLE
Sort listing by container name. Fixes #734

### LINKED ISSUE #734: Order the devices list
Currently devices are applied in the order in which ranging over the keys happens.  Currently that is the same as the order in which they were added to the lxdcontainer.devices map.  And that is profiles first, then container.  This means we are depending on a golang implementation detail, which is not good.  Add ordering to the devices list.

This is a low priority item compared to many others, but will become higher priority as people begin to use more complicated setups.

### PR DESCRIPTION
**Pull request by basvanbeek**

### CODE REVIEW

**Comment by tych0** [comment]
Hi, can you sign off your commit (`git commit --amend -s`)? LGTM otherwise, thanks!

**Comment by basvanbeek** [comment]
signed off...

**Comment by stgraber** [comment]
All the commits in the branch must be signed-off. Looks like your branch history contains multiple merges and multiple commits. I'd recommend you rebase it down to a single commit.

**Comment by basvanbeek** [comment]
Should be a single signed off commit now.

**Comment by stgraber** [comment]
Hi,

Thanks for that.

Travis is still complaining about some formatting issue. Can you run "go fmt ./..." and update your commit with the result?
(Or look for the diff on the Travis failure page)

Thanks!

**Comment by basvanbeek** [comment]
Properly formatted... sorry for the amount of wasted energy.

**Pull request merged**
