### PR TITLE
init: Enable compression on new zfs pools

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by tomposmiko** [comment]
Why? Why by default? Is it really a good idea?

If you do it, I would (I do in the real world) choose compression=lz4.
But I think configuring it at time of container launch would be more suitable.

**Comment by stgraber** [comment]
compression=on is lz4 by default if ZFS was built with lz4 support.

We had a bunch of folks ask for this in production environments, noticed that just about everyone is turning compression on for their pools anyway when they look at the ZFS configuration and for the storage people we talked to, the CPU usage of lz4 is negligible on any system which is suitable for ZFS.

**Comment by stgraber** [comment]
So it's a sane thing to do when the user just goes through the simple "give me a storage pool" interactive configuration process. People who want something fancier are likely to know about ZFS and just have LXD use a subset of an existing pool, in which case we don't set any flag at all.

As for having this be per container, we have more storage API work coming soon which may make this easier to do but right now, we don't want to expose filesystem configuration knobs as primitive of a generic API to manage system containers.

**Comment by tomposmiko** [comment]
You're right, it defaults to lz4. I was in the impression it's gzip.

**Pull request merged**
