### PR TITLE
Ip package

### LINKED ISSUE #7871: Move all iproute (`ip` command) calls to a separate package
Our long term plan is to switch from calling `ip` as a subprocess and instead hit netlink directly from Go.

But as a first step, we need to refactor our calls to `ip` and move everything into a new package, providing a first abstraction layer that we can then use as the basis for the switch to netlink.

So for this issue, we'll want to locate all calls to `ip`, figure out what they do, from that determine what level of abstraction can be done by the new package, then implement the new functions and port over all existing `ip` calls.

### PR DESCRIPTION
**Pull request by presztak**
Resolves #7871

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
```
/lxc-ci/build/tmp.6GmnHQLDpH/go/src/github.com/lxc/lxd/lxd/device/nic_sriov.go:356:3: ineffectual assignment to err
```

**Comment by presztak** [comment]
@stgraber fixed. Not yet sure why on my local machine `static_analysis` test pass.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@presztak can you make this package be `golint` clean? (and add it to the relevant part of our static_analysis test)

**Comment by presztak** [comment]
@stgraber done.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
