### PR TITLE
lxd/storage/zfs: Fix dataset handling on copy

### LINKED ISSUE #5359: Failed to initialize storage volume, after copy over zfs
# Issue description

I'm trying to have a container + data volume, where I snapshot both of them, execute a shell command then snapshot both of them again .. so that I have an audit trail along the way. The below set of commands fail consistently

# Steps to reproduce

 1. Run the below shell commands on a fresh lxd/pool
 2. Watch the error?

```

lxc launch ubuntu:18.04 container-6d8a1e8771ad200e1d616b238125830db412fc86
lxc storage volume create s data-6d8a1e8771ad200e1d616b238125830db412fc86
lxc storage volume attach s data-6d8a1e8771ad200e1d616b238125830db412fc86 container-6d8a1e8771ad200e1d616b238125830db412fc86 /data

lxc storage volume copy s/data-6d8a1e8771ad200e1d616b238125830db412fc86 s/data-ea258f44566afa4feb9480843af24075b9662d9a
lxc cp container-6d8a1e8771ad200e1d616b238125830db412fc86 container-ea258f44566afa4feb9480843af24075b9662d9a
lxc config device remove container-ea258f44566afa4feb9480843af24075b9662d9a data-6d8a1e8771ad200e1d616b238125830db412fc86
lxc config device add container-ea258f44566afa4feb9480843af24075b9662d9a data-ea258f44566afa4feb9480843af24075b9662d9a disk source=data-ea258f44566afa4feb9480843af24075b9662d9a path=/data pool=s
lxc start container-ea258f44566afa4feb9480843af24075b9662d9a
```
The last line to start the new container, fails with the below error!
```

Error: Common start logic: Failed to initialize storage volume "data-ea258f44566afa4feb9480843af24075b9662d9a" of type "custom" on storage pool "s": No such file or director
y: "/var/snap/lxd/common/lxd/storage-pools/s/custom/data-ea258f44566afa4feb9480843af24075b9662d9a"
Try `lxc info --show-log container-ea258f44566afa4feb9480843af24075b9662d9a` for more info
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #5359

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by kim0** [comment]
BTW it seems the test suite needs a fix .. Thanks

**Comment by stgraber** [comment]
Yeah, the testsuite failures are related to LXC 3.1 breaking all our tests for some reason.

**Comment by kim0** [comment]
Alright .. should I expect a snap edge build to appear for me in a little while ?

**Comment by stgraber** [comment]
Yeah, edge will update once this is merged, which is currently blocked on us fixing CI.

In the mean time, you can just `mkdir -p` the path that's shown as `No such file or directory`, that should fix it.

**Comment by stgraber** [comment]
Oh, right because that bug would cause it to get mounted in the wrong spot...

Try deleting the copied volume and copy it again, from what I remember from the code, the second copy may work fine due to it using a slightly different codepath.

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
