### PR TITLE
enable IPV6 name resolution

### PR DESCRIPTION
**Pull request by tmclane**
Enable IPV6 name resolution inside containers.

### CODE REVIEW

**Comment by tych0** [comment]
Can you sign off your commit? (`git commit --amend -s`)

**Comment by tmclane** [comment]
Done!

**Comment by stgraber** [comment]
So looking at the manpage, shouldn't we be using "ra-stateless,ra-names" instead?

That way a stateless DHCPv6 server would also run to provide things like DNS information to clients (and SLAAC would still work fine for those that don't know about the other-config flag).

**Comment by tmclane** [comment]
Added ra-stateless and ra-names.

**Pull request merged**
