### PR TITLE
lvm: implement lv resizing

### LINKED ISSUE #1205: lvm: allow lv resizing
When using lvm as storage backend, upon creating a container lxd creates a new fixed sized lv, the size is hardcoded and equals to 100Gb. It would be very nice to have an option to change it through lxd config, at least globally. Though, I guess, it would be just awesome if we could specify the size per container as well.

### PR DESCRIPTION
**Pull request by brauner**
- ext4: grow and shrink
- xfs: grow only (shrink requires dump, mkfs, and restore)

Closes #1205.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
I named the key `volatile.apply_quota` mainly because it has a more generic use. So far when a container was created and the storage for it wasn't yet ready we skipped applying quota (e.g. for btrfs and zfs) by using the new volatile key we can set `volatile.apply_quota: 10GB` and then on next container start make sure that the quota (or resize in the case of lvm) is applied.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner please rebase

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Rebase messed-up. Will update in a second.

**Comment by brauner** [comment]
@stgraber, regular zfs EBUSY. Everything else looks good. Should be good for review.

**Comment by brauner** [comment]
```
lxc-start xen1 20170509224159.533 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1562 - created directory for console and tty devices at /usr/lib/x86_64-linux-gnu/lxc/dev/bla"
lxc-start xen1 20170509224159.533 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1622 - moved mount "/usr/lib/x86_64-linux-gnu/lxc/dev/console" to "/usr/lib/x86_64-linux-gnu/lxc/dev/bla/console"
lxc-start xen1 20170509224200.214 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1631 - cleared all (31) mounts from "/usr/lib/x86_64-linux-gnu/lxc/dev/console"
lxc-start xen1 20170509224200.214 DEBUG    lxc_conf - conf.c:lxc_setup_ttydir_console:1668 - console has been setup under "bla/console" and symlinked to "/usr/lib/x86_64-linux-gnu/lxc/dev/console"
```

**Pull request merged**
