### PR TITLE
Convert syscall.Stdin to int explicitly for Windows

### LINKED ISSUE #825: Make it possible to build the client on Windows
Currently the client can be built on Linux and MacOS, possibly on some other unix systems too.

However it won't build on Windows due to a bunch of remaining unix-isms which would have to be re-implemented using the Windows equivalent.

Specifically, there are a bunch of file related functions in shared/ which use Unix system calls to retrieve their information, those should be moved to a util_unix.go file and an equivalent be implemented for Windows.

Same goes with a few client features like signal handling for SIGWINCH and stdin/stdout/stderr mode handling in exec. Those would have to be changed to use a generic interface which can then be backed by a unix and a windows backend.

### PR DESCRIPTION
**Pull request by techtonik**
This is the last commit necessary to properly close #825.

### CODE REVIEW

**Comment by techtonik** [comment]
I now have `lxc.exe` binary after:

    set GOPATH=E:\go\
    go get -v github.com/lxc/lxd

    cd %GOPATH%\src\github.com\lxc\lxd

    go get -t -v -d ./...
    go install -v ./lxc

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

To have this branch tested by Jenkins, use the "ok to test" command.
To have a one time test done, use the "test this please" command.

Commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by techtonik** [comment]
Chromium uses AUTHORS at the root of repository for such list.

**Comment by stgraber** [comment]
Jenkins uses the list of organization members in Github which is fine.

It just didn't trigger automatically in this case due to a network issue on the LXC CI network, so had to manually poke it once connectivity got restored.

**Pull request merged**
