### PR TITLE
firewalld & lxd : allow containers to access the internet

### PR DESCRIPTION
**Pull request by kerphi**
Few documentation is better than nothing.
There is maybe a better way to fix it.

Similar issue for docker containers:
https://success.docker.com/article/why-am-i-having-network-problems-after-firewalld-is-restarted

### CODE REVIEW

**Comment by tomponline** [comment]
@kerphi can you confirm that the steps documented here do not fix your issue? https://github.com/lxc/lxd/blob/master/doc/networks.md#allow-dhcp-dns-with-firewalld

**Comment by tomponline** [comment]
@kerphi do you know which firewalld rule is actually causing the problem?

**Comment by stgraber** [comment]
The commit would also need to be signed-off before we could include this PR.

**Comment by kerphi** [comment]
> @kerphi can you confirm that the steps documented here do not fix your issue? https://github.com/lxc/lxd/blob/master/doc/networks.md#allow-dhcp-dns-with-firewalld

I confirm it does not fixes the internet outgoing access from the container.

However, this tip (`firewall-cmd --zone=trusted --change-interface=lxdbr0`) is mandatory to start the containers or it will not be able to acquire an IP.

**Comment by kerphi** [comment]
> The commit would also need to be signed-off before we could include this PR.



> @kerphi do you know which firewalld rule is actually causing the problem?

I don't know how to do that.

For now, I understand firewalld is very aggressive when starting: it looks like all the existing iptables rules are just destroyed by firewalld startup. 
I'm searching other way to fix the problem: for example i'd like to be able to replicate the lxd specific iptables rules in the firewalld configuration and to memory thanks to "--permanent" firewalld feature (if i'm able to fine this way, i could update the doc too)

**Comment by kerphi** [comment]
> The commit would also need to be signed-off before we could include this PR.

I don't understand your request?

**Comment by tomponline** [comment]
> > The commit would also need to be signed-off before we could include this PR.
> 
> > @kerphi do you know which firewalld rule is actually causing the problem?
> 
> I don't know how to do that.
> 
> For now, I understand firewalld is very aggressive when starting: it looks like all the existing iptables rules are just destroyed by firewalld startup.
> I'm searching other way to fix the problem: for example i'd like to be able to replicate the lxd specific iptables rules in the firewalld configuration and to memory thanks to "--permanent" firewalld feature (if i'm able to fine this way, i could update the doc too)

Ah OK so if firewalld is wiping out all existing lxd iptables rules then that would be an issue. I was testing something similar with firewalld the other day, but this was on a host that used nftables rather than iptables so the situation was different. Thanks

**Comment by stgraber** [comment]
Ok, so I don't think we should put stuff about systemd units in our documentation.

We don't write or ship those units ourselves, those are handled by distributions.
The right solution here is to file a bug against the distribution so the packager can add the relevant After= line to sort out the ordering.

**Comment by stgraber** [comment]
The logic is also incorrect, it should be a `After=` line in `lxd.service` so the service is started after firewalld. The `Before` in this doc won't work as it actually tells LXD to start before firewalld. It's also not going to work because `.socket` units are in a different target than regular units, so there is no `firewalld` unit to consider.

Anyway, short answer is that this needs to be done in distro packaging and that the right way is most likely `After=firewalld.service` in the `lxd.service` unit.

**Comment by kerphi** [comment]
@stgraber ok i agree, modifying lxd/firewalld systemd integration is not related directly to LXD but to the distro packaging. I will check to this if i do not find a better way to integrate lxc and firewalld.

Do you think this ["Allow DHCP, DNS with Firewalld"](https://github.com/lxc/lxd/blob/master/doc/networks.md#allow-dhcp-dns-with-firewalld) section is at the good place in the documentation? maybe a FAQ section would be better for such tips?
I ask because if I found the way to well configure firewalld to allow containers to access internet outbound, maybe it could be included somewhere in the LXD doc of faq?

**Comment by stgraber** [comment]
We've only had two people ask about firewalld so far, so given the size of our community, I wouldn't call that frequent yet, so not FAQ territory :)

It's fine to add to the existing section on firewalld if there are more commands that folks ought to be running though.

**Comment by kerphi** [comment]
I'm trying to understand how an application can configure specific iptables itself without being erased by firewalld.

I think the docker way is working, it seams they are using iptable chains to isolate the docker rulez from other iptables rules:
https://docs.docker.com/network/iptables/#add-iptables-policies-before-dockers-rules

Thanks to that (or I miss something else?), when I start firewalld, docker iptables rulez (included in these chains) are kept:

```
root@lxd-ubuntu:~# iptables -L | grep -i docker
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
Chain DOCKER (1 references)
Chain DOCKER-ISOLATION-STAGE-1 (1 references)
Chain DOCKER-ISOLATION-STAGE-2 (0 references)
Chain DOCKER-USER (1 references)

root@lxd-ubuntu:~# systemctl restart firewalld
root@lxd-ubuntu:~# iptables -L | grep -i docker
DOCKER-USER  all  --  anywhere             anywhere            
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere            
DOCKER     all  --  anywhere             anywhere            
Chain DOCKER (1 references)
Chain DOCKER-ISOLATION-STAGE-1 (1 references)
Chain DOCKER-ISOLATION-STAGE-2 (0 references)
Chain DOCKER-USER (1 references)
```

When I compare to LXD:
```
root@lxd-ubuntu:~# lxd --version
4.0.0
root@lxd-ubuntu:~# systemctl restart snap.lxd.daemon.service 
root@lxd-ubuntu:~# iptables -L | grep -i lxd
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp dpt:bootps /* generated for LXD network lxdbr0 */
ACCEPT     all  --  anywhere             anywhere             /* generated for LXD network lxdbr0 */
ACCEPT     all  --  anywhere             anywhere             /* generated for LXD network lxdbr0 */
ACCEPT     tcp  --  anywhere             anywhere             tcp spt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp spt:domain /* generated for LXD network lxdbr0 */
ACCEPT     udp  --  anywhere             anywhere             udp spt:bootps /* generated for LXD network lxdbr0 */
root@lxd-ubuntu:~# systemctl restart firewalld
root@lxd-ubuntu:~# iptables -L | grep -i lxd
```

**Comment by stgraber** [comment]
but those chains are only useful if something jumps into them, so if firewalld clears the default chains it will clear the jumping rules too.

**Comment by tomponline** [comment]
What os and version are you running out of interest?

**Comment by kerphi** [comment]
> What os and version are you running out of interest?

```
root@lxd-ubuntu:~# uname -a
Linux lxd-ubuntu 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
root@lxd-ubuntu:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
root@lxd-ubuntu:~# lxd --version
3.0.3
root@lxd-ubuntu:~# apt policy firewalld
firewalld:
  Installé : 0.4.4.6-1
  Candidat : 0.4.4.6-1
 Table de version :
 *** 0.4.4.6-1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe i386 Packages
        100 /var/lib/dpkg/status
```

I also tried with lxd 4.0.0 (using snap to install it)

**Comment by tomponline** [comment]
I confirmed that a `systemctl restart firewalld` on ubuntu 18.04 does indeed wipe all existing iptables rules, including LXDs. This breaks things like outbound NAT.

**Pull request closed without merging**
