### PR TITLE
Add icons for Diataxis categories

### PR DESCRIPTION
**Pull request by ru-fu**
A draft PR for now since we don't have official icons yet, and because we should move the extension to the lxd-sphinx-extensions package when we're happy with how it works.

The PR updates the navigation with icons depending on the Diataxis category of each doc file. The category can be specified in the file metadata. Otherwise, it is extracted from the location of the file.

### CODE REVIEW

**Comment by tomponline** [comment]
@ru-fu shall we close this for now?

**Comment by ru-fu** [comment]
> @ru-fu shall we close this for now?

Not sure what our policy is for this.
I'm currently waiting for the official icons and will pick this up again once we have them (probably within the next month or two).

**Comment by tomponline** [comment]
> > @ru-fu shall we close this for now?
> 
> Not sure what our policy is for this. I'm currently waiting for the official icons and will pick this up again once we have them (probably within the next month or two).

My preference would be for closing for now so it keeps the list of pending PRs down, that way its clearer to see what is waiting to be merged vs still being worked on.

**Comment by ru-fu** [comment]
ok :)

**Pull request closed without merging**
