### PR TITLE
Plug new dqlite backend

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
The only meaning test failure seems to a crash due to a failed assertion in dqlite. I'd say things look stable enough to merge this branch, and investigate the crash separately (whose fix will need to happen in dqlite and doesn't require a lxd change).

**Comment by stgraber** [comment]
I think we need an update to Makefile for 'make deps'

**Comment by freeekanayaka** [comment]
> I think we need an update to Makefile for 'make deps'

Fixed.

**Comment by stgraber** [comment]
@freeekanayaka DCO...

**Pull request merged**
