### PR TITLE
Fix target filenames for recursive push with './' as source

### LINKED ISSUE #3446: lxc file push -r of CWD results in incorrect file names
# Required information

 * Distribution: Ubuntu 16.04
 * Kernel version: 4.4.0-79-generic
 * LXC version: 2.14
 * LXD version: 2.14
 * Storage backend in use: dir

# Issue description
When you attempt to run `lxc file push -rp ./ CONTAINER/dest` all of the filenames at `/dest` within the container are missing characters at the front of all files and dirs. For instance, a ls of the current working dir on the host:
```bash
~/github/my-project$ ls -a
.  ..  bin  build.sh  .git  .gitignore  include  init  lib  LICENSE  Makefile  points.dat  README.md  src
```
I am instead seeing `/dest` within the container with partial file/dir names:
```bash
/point # ls -a
.         ..        ADME.md   CENSE     b         c         clude     ild.sh    ints.dat  it        itignore  kefile    n
```
If it helps at all, the container image I'm using is `images:alpine/3.5`.

To reproduce:
1. `cd projectdir`, where `projectdir` is a dir with files you'd like to copy into the container
1. `lxc launch images:alpine/3.5 test`
1. `lxc exec test mkdir /dest`
1. `lxc file push -rp ./ test/dest` (adding a trailing `/` after `test/dest` doesn't seem to make a difference)
1. `lxc exec test ls -a /dest` should result in the output described above

**Something to note:** if you replace the push step with `lxc file push -rp ../projectdir test/dest` works great! The issue seems to only occur when `./` is explicitly referenced.

There doesn't seem to be anything useful in the kernel, container, lxd logs nor the client debug output (though, shout out if you think you need these).

### PR DESCRIPTION
**Pull request by albertodonato**
Closes #3446

### CODE REVIEW

**Comment by brauner** [comment]
@techtonik, can you verify that this doesn't break on Windows?

**Comment by stgraber** [comment]
@albertodonato can you add a test for the "./" case please?

**Comment by techtonik** [comment]
What command should I run for a test?

**Comment by stgraber** [comment]
@techtonik just making sure we didn't regress any of the obvious "lxc file push" and "lxc file push -r" commands would be nice. So try sending a file and a directory, if that works, then things should be fine.

**Pull request closed without merging**
