### PR TITLE
VM: forklimits

### PR DESCRIPTION
**Pull request by tomponline**
- Adds `forklimits` command for launching a process with locally changed rlimits.
- Switches qemu process to use `forklimits` with unlimited `memlock` rlimit for PCI passthrough.

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline any chance we can effectively exec the command rather than running a subcommand?
That would avoid keeping another full copy of the lxd binary + Go runtime in memory for every VM instance. (but that may be a tricky subject because of how Go works)

**Comment by tomponline** [comment]
@stgraber I'll take a look, but in the specific case of qemu, because we have it fork anyway, this process goes away quickly.

**Comment by tomponline** [comment]
@stgraber I'm looking to use `syscall.Exec`

**Comment by stgraber** [comment]
Ah, good point, then we may not care about this at all.

**Comment by stgraber** [comment]
At least for now :)

**Comment by tomponline** [comment]
> @tomponline any chance we can effectively exec the command rather than running a subcommand?
> That would avoid keeping another full copy of the lxd binary + Go runtime in memory for every VM instance. (but that may be a tricky subject because of how Go works)

Implemented in https://github.com/lxc/lxd/pull/6809

**Pull request merged**
