### PR TITLE
Fill missing csv docs

### PR DESCRIPTION
**Pull request by techtonik**
Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
You should probably also do a `make i18n`.

**Comment by brauner** [comment]
Yep, you need a `make i18n` commit.

**Comment by techtonik** [comment]
I am on Windows. =/

**Comment by techtonik** [comment]
```
> xgettext-go -o po/lxd.pot --add-comments-tag=TRANSLATORS: --sort-output --package-name=lxd --msgid-bugs-address=lxc-devel@lists.linuxcontainers.org --keyword=i18n.G --keyword-plural=i18n.NG *.go shared/*.go lxc/*.go lxd/*.go
panic: open *.go: The filename, directory name, or volume label syntax is incorrect.

goroutine 1 [running]:
main.processSingleGoSource(0x11abc1b0, 0x11aa80c5, 0x4, 0x11aa5b60, 0x0)
        E:/p/lxd/go/src/github.com/snapcore/snapd/i18n/xgettext-go/main.go:175 +0x56
main.processFiles(0x11abe2a8, 0x4, 0xc, 0xd, 0xd)
        E:/p/lxd/go/src/github.com/snapcore/snapd/i18n/xgettext-go/main.go:164 +0xa7
main.main()
        E:/p/lxd/go/src/github.com/snapcore/snapd/i18n/xgettext-go/main.go:293 +0xf5
```
Unfortunately https://github.com/snapcore/snapd/tree/master/i18n/xgettext-go docs are empty.

**Comment by brauner** [comment]
Ah, ok. I'll put it in my branch.

**Comment by techtonik** [comment]
Thanks.

**Pull request merged**
