### PR TITLE
fixed image info formatting for size

### PR DESCRIPTION
**Pull request by jensg-st**
Signed-off-by: Jens Gerke <jens.gerke@sisa-tech.com>

### CODE REVIEW

**Comment by jensg-st** [comment]
A typo I'm assuming?

**Comment by tych0** [comment]
Not sure, the output matches that in /specs/command-line-user-experience.md. I think it's just a question of do we want to print the decimal points for MB. I don't think it makes a lot of sense, since fractional measurements are usually just given in KB or whatever. Does that mean we should get rid of the .2 in the format string instead?

**Comment by jensg-st** [comment]
In the specs I could not find how it it is supposed to be. I' m getting something like '1.1e+02MB' which is scientific, but not what I would expect. I agree with you comment about decimal points. '%.0f' is maybe what people think should be there?

**Comment by stgraber** [comment]
So I've been thinking about this a bit and looked at our current images.

Looking at what we have out there, ranging from a tiny busybox image all the way to a rather fat container image, the table below shows a few different ways of rendering the image size and the result for each class of image.

 | Rendering | Tiny | Slightly less tiny | Normal | Big
:-- | :-- | :--- | :--- | :--- | :---
1 | %.2f MB | 0.40MB | 1.25MB | 65.43MB | 543.21MB
2 | %d MB | 0MB | 1MB | 65MB | 543MB
3 | %d MB or KB | 400KB | 1MB | 65MB | 543MB
4 | %.2f MB or %d KB | 400KB | 1.25MB | 65.43MB | 543.21MB

Personally, my preference is:
 - 4
 - 1
 - 3
 - 2

**Comment by jensg-st** [comment]
My preference would be more 1 and then 4. But that might be pure laziness, because handling KB, MB and GB just does not add enough value to do it. :)

Should we ditch the pull request and add an issue for it? You make the call for either solution 1 or 4 anyway. Assuming that 2 & 3 seem to pretty useless looking at your demo numbers in the table.

**Comment by stgraber** [comment]
I'm fine with 1) and indeed it's the easiest approach so we should make sure it's what we're using across the board.

**Comment by jensg-st** [comment]
Do you want me to rebase this tiny fix and change it to "%.2f"?

**Comment by stgraber** [comment]
yep, that'd be great.

**Comment by stgraber** [comment]
Marking incomplete so I stop looking at it

**Comment by jensg-st** [comment]
Sorry, other project takes longer than expected. What a surprise in an IT project...Will do it as soon as possible.

**Comment by stgraber** [comment]
No worries. It was just bothering me because the current pull request passed Travis so looks ready for merging but isn't because it doesn't contain what we discussed :)

The incomplete tag makes it a lot more visually obvious that I should ignore it for now.

**Comment by stgraber** [comment]
Closing this pull request for now. Feel free to ask me to re-open or just send a new one when you have time to look into this again.

Thanks!

**Pull request closed without merging**
