### PR TITLE
API: Storage volumes permission check

### PR DESCRIPTION
**Pull request by tomponline**

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber I have corrected the perms for the manage storage volumes routes (non-GET verbs).

Does this depend on https://github.com/lxc/lxd/pull/6987 or can it be merged before, as this is just adding permission checks?

**Comment by stgraber** [comment]
Looking at what we did elsewhere, I think we need to use `AllowProjectPermission("storage-volumes", "view")` for the read-only endpoints (GET).

**Comment by stgraber** [comment]
For the record, I've just gone through all of our existing endpoints and the rest does look correct AFAICT.

So indeed we need to line up storage with what we're doing for profiles/images, which means requiring `manage-storage-volumes` for any write operation and `view` for any read operation.

**Comment by stgraber** [comment]
You can test this behavior with your VM by assigning the `auditor` role on a given project, that role only has the `read` permission.

**Comment by tomponline** [comment]
> You can test this behavior with your VM by assigning the `auditor` role on a given project, that role only has the `read` permission.

I've updated the view permissions on GET routes and tested access using Auditor role, confirmed working as expected.

**Pull request merged**
