### PR TITLE
alphabetize device processing

### LINKED ISSUE #2233: Process devices in alphabetical order when generating lxc.conf
Hello,

We are currently working with LXC 1.x tools and we want to use LXD to manage our containers. But after a few tests, it seems some features have been willingly removed. I open this new issue to see if it's still possible to change a few things and use LXD in production. :)

We use a custom (debootstrap-based) container template (converted to image a few days ago).

Our rootfs is minimal (even debootstrap was too "bloated" for us), our goal was to:
 - Start only *mandatory* services
 - Remove as much capabilities as we can (bye bye sys_admin, net_admin and so on)

Our network configuration:

    +--------+------------------------------+
             |           External bridge
             |
     +----------------+
     |       +        |
     | veth0: X.X.X.X |
     |                |
     |     LXC-01     |
     |                |
     | veth1: Y.Y.Y.Y |
     |       +        |
     +----------------+
             |
             |           Internal bridge
    +---------------------------------------+

So here is our problem... We can't set two static IP addresses properly in our containers. This is what happens:
 - If we use the recommended/default method (DHCP), it violates our policy (run only mandatory services)
 - If we configure interfaces inside our container, this won't work because net_admin is dropped. To be honest, DHCP will also fail for the very same reason.
 - If we configure raw.lxc, well... Sometimes our internal veth obtains the external IP address (as explained by Stéphane in one of his commits). Sadly, this is not reliable.

I understand we want to run a custom (and maybe very specific or unusual) distribution. I also understand a "classic" distribution might throw away "pre-init" network configuration (or just go nuts) but our distribution will not do such things.

This worked very well for years with the old LXC versions. **Is it possible to allow setting ipv4/6 and gateway through LXD? I don't really mind if you mark this as a "touch this only if you know what you are doing"-feature.** The auto-generated configuration file will then have `lxc.network.ipv4` not at the end of file (where raw.lxc belongs) but right after each veth declaration.

I guess [this is the right file](https://github.com/lxc/lxd/blob/3ce6bd71afd41f3fb66cc3a48b0662473542fced/lxd/container_lxc.go#L802) for such a patch. I really hope not to have to maintain a fork just for this, I think this could be useful for other sysadmins.

Thanks a lot for your time!

Regards

### PR DESCRIPTION
**Pull request by tych0**
Unfortunately, there's not a way to range over a custom type, and there's
no way to sort a map, so we end up with this verbosity :(

Closes #2233

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Indeed unfortunate that there isn't an easier way to do this.

Looking around, I see a bunch more places where we iterate through a list of devices, though I think we should only do the named-based sorting for those places where the order may actually matter.

Off the top of my head, I'd say this is during lxc.conf generation (so initLXC) and when updating a container (Update) as those are the only times that I can think of where we may run into ordering problems when processing multiple devices.

Can you think of other cases?

Note that we will need to expand that ordering logic a bit further when dealing with #2249 as for disk entries, we'll instead want them sorted by target path.

**Comment by tych0** [comment]
Isn't it only the places where we iterate over expandedDevices that actually matter? That's what I searched for.

As for sorting by path, that shouldn't be too hard, I can add that. (Well, it'd be nicer if the sorting interface was nicer, but I digress...)

**Comment by stgraber** [comment]
Ah yeah, I grepped for any case where we sort through devices, including localDevices so that must be why I got a bunch more hits, I may also have got hits for cases where we stored the device list in a variable before iterating through it.

Anyway, doing it for all uses of expandedDevices is fine. There's going to be a bunch of cases where it's un-needed since we only ever really need this thing sorted when we generate the LXC configuration or when we inject new mounts into the container, but it's not like that sorting is going to be particularly long.

**Comment by tych0** [comment]
Well, maybe. You don't know how ugly the sorting is turning out to be :)

**Comment by tych0** [comment]
jenkins: test this please

some weirdness going on in the tests :(

**Pull request merged**
