### PR TITLE
clustering: Force configuration when bootstrapping first node of cluster

### PR DESCRIPTION
**Pull request by MathieuBordere**
Just running clustering CI tests to debug test failures.

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by MathieuBordere** [comment]
jenkins: test this please

**Pull request merged**
