### PR TITLE
don't set the log path twice

### PR DESCRIPTION
**Pull request by tych0**
Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
I'm only seeing one lxc.logfile in the code, where is the other?

**Comment by stgraber** [comment]
Also, if you rebase your branch, it should then be able to pass travis.

**Comment by tych0** [comment]
On Thu, Apr 30, 2015 at 02:51:20AM -0700, Stéphane Graber wrote:
> Also, if you rebase your branch, it should then be able to pass travis.

Hmm, it is rebased on master.

**Comment by tych0** [comment]
On Thu, Apr 30, 2015 at 02:51:09AM -0700, Stéphane Graber wrote:
> I'm only seeing one lxc.logfile in the code, where is the other?

we set it via go-lxc:

$ grep -ri SetLogFile *
containers.go:  if err = d.c.SetLogFile(filepath.Join(dir, "lxc.log")); err != nil {

**Comment by hallyn** [comment]
Yeah it's weird, I swear I had removed that block before, but i see it in master.

**Pull request merged**
