### PR TITLE
client: convert EventListener to use api.Event

### PR DESCRIPTION
**Pull request by smibarber**
Improve EventListener's AddHandler function to use an api.Event
struct rather than an interface{}.

Fix an asymmetry between the AddHandler functions for
Operation and EventListener, as the former provides an
api.Operation struct to its handler function, but the latter
gives just an interface{} that must be either be teased apart
with type assertions or marshaled back into JSON and
unmarshaled into the appropriate type.

Signed-off-by: Stephen Barber <smbarber@chromium.org>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
That unfortunately breaks currently:
```
+ LXD_DIR=/lxc-ci/build/tmp.7aUcHmgEFh/go/src/github.com/lxc/lxd/test/tmp.cYz/TYu lxc config set cluster.offline_threshold 30
+ LXC_LOCAL=1 lxc_remote config set cluster.offline_threshold 30
+ set +x
+ eval /lxc-ci/build/tmp.7aUcHmgEFh/go/bin/lxc "config" "set" "cluster.offline_threshold" "30" --verbose
+ /lxc-ci/build/tmp.7aUcHmgEFh/go/bin/lxc config set cluster.offline_threshold 30 --verbose
panic: interface conversion: interface {} is api.Event, not map[string]interface {}

goroutine 759 [running]:
main.eventForward(0x2, 0x10b0660, 0xc420030e80)
	/lxc-ci/build/tmp.7aUcHmgEFh/go/src/github.com/lxc/lxd/lxd/events.go:200 +0x1c6
github.com/lxc/lxd/lxd/cluster.eventsUpdateListeners.func2(0xc4205ec156, 0x7, 0x3b4f2b1e, 0xed39f0124, 0x0, 0xc4207a8700, 0x62, 0x70)
	/lxc-ci/build/tmp.7aUcHmgEFh/go/src/github.com/lxc/lxd/lxd/cluster/events.go:103 +0x97
created by github.com/lxc/lxd/client.(*ProtocolLXD).GetEvents.func2
	/lxc-ci/build/tmp.7aUcHmgEFh/go/src/github.com/lxc/lxd/client/lxd_events.go:114 +0x1aa
WARN[12-09|12:27:17] Could not notify node 10.1.1.101:8443 
+ LXD_DIR=/lxc-ci/build/tmp.7aUcHmgEFh/go/src/github.com/lxc/lxd/test/tmp.cYz/rQ2 lxc info
+ LXC_LOCAL=1 lxc_remote info
+ + setgrep +x -q cluster.offline_threshold: "30"
```
:)

**Comment by smibarber** [comment]
D'oh. I worried that one of those runtime type assertions would get me. I think I got all of the lxd-side event code this time.

Sorry for the noise there :) one day I'll manage to get the integration tests to fully run on my workstation.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks good to me.

This is technically an API break for our client package which we usually strive to avoid, but I'm not aware of anyone directly using the EventListener AddHandler outside of our own code and this change makes things much more usable in general.

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
