### PR TITLE
Add a 10 second dial timeout to RFC3493Dialer

### LINKED ISSUE #1469: lower timeout for calls from lxc client
If you try to do commands on a remote server that is down or otherwise unreachable, it now takes forever to return with the ' Unable to connect' message.
I believe a 10s timeout would be more reasonable and still adequate for the purpose.

### PR DESCRIPTION
**Pull request by jsimonetti**
Closes #1469

Signed-off-by: Jeroen Simonetti <jeroen@simonetti.nl>

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by tych0** [comment]
Can we make this configurable somehow? I can just imagine some slow DNS server somewhere causing problems, but the underlying connection being fast, and this patch making lxc unusuable in that situation.

**Comment by tych0** [comment]
jenkins: ok to test

**Comment by jsimonetti** [comment]
Absolutely. I will add patches.
Would 10 seconds be an OK default which can be overriden with a commandline argument on the side of lxc and a config key on the side of lxd?

**Comment by jsimonetti** [comment]
Actually, the DNS lookup is done before the net.DialTimeout, so the dial always happens to an ip adress and thus slow DNS servers are not included in the timeout.

**Comment by tych0** [comment]
On Wed, Jan 06, 2016 at 06:45:31AM -0800, Jeroen Simonetti wrote:
> Absolutely. I will add patches.
> Would 10 seconds be an OK default which can be overriden with a commandline argument on the side of lxc and a config key on the side of lxd?

Yep, seems like a reasonable default to me, and the configuration
you've suggested seems good as well. People with shitty DNS servers
are hopefully a corner case, but I've seen it happen :)

**Pull request merged**
