### PR TITLE
doc: test adding a feedback form

### PR DESCRIPTION
**Pull request by ru-fu**
Signed-off-by: Ruth Fuchss <ruth.fuchss@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
So a few questions :)

 - What's that thing about?
 - What data does it get?
 - Where does the data go?
 - Who gets access to it?
 - Does this use any cookie or anything (which would require us to start doing GDPR compliance stuff in the docs...)?

**Comment by turtle0x1** [comment]
This is gross, for so many reasons.

Better options might include

  - Provide a link to the survey
  - Pin a thread in the discussion forum with a link
  - Email your paying customers a link

No need to send your doc readers data to the US or include google analytics (the parent company uses google analytic cookies and ships data across continents).

**Comment by evildmp** [comment]
> Documentation preview available at: https://linuxcontainers.org/lxd/docs/pr.9867/

I'm getting a 404 there @ru-fu.

**Comment by stgraber** [comment]
Oops, our auto-expiration logic was a bit overly keen.
I've now tweaked it to not be so aggressive and it has now published this preview again.

**Comment by stgraber** [comment]
In general, I share many of @turtle0x1's concerns.

I'm not at all against there being an easy way to submit feedback, we've done that before for example in our online demo website. But the form used to do (and its source) that needs to be part of the published documentation, I don't want us to source random obfuscated external javascript which can change at any point.

The feedback form would also need to be very clear about who will have access to that feedback, what exactly is recorded and have a clear privacy policy which complies with GDPR and similar data privacy requirements.

Another concern that kinda falls from that is that if there's a free form way for users to provide doc feedback, this may cause a split between documentation issues being reported through that and being reported through Github.
There is a slight barrier to entry for Github (need to create an account) so I understand that it may be a good idea to have an easy mean to provide feedback, but we should still encourage folks to file issues when possible and would need to make sure that we don't end up with two distinct piles of documentation issues (so those coming from feedback should get filed as bugs if not immediately corrected).

**Comment by stgraber** [comment]
I think a good goal for the documentation would be that when consumed locally (release tarball), it shouldn't pull anything from the internet. This will ensure a good experience for those in an airgaped environment.

@ru-fu can correct me there but I believe that currently the only thing missing there is the logo which we include from linuxcontainers.org. We likely could sort that one out by having the `make doc` target download it in much the same way we do themes and the Swagger parser.

**Comment by stgraber** [comment]
@ru-fu could you send a PR which:
 - Downloads the logo & favicon from linuxcontainers.org at doc build time
 - Add a `make doc` or Makefile dependency so `make dist` gets us a `doc/html` tree included in the tarball
 - Check that the doc in that tarball is generally functional and doesn't pull stuff from the internet

**Comment by ru-fu** [comment]
I understand the concern about GDPR and embedding external JavaScripts - we'll need to see how to deal with that.

But just to clarify: The idea here is to gather feedback per page, not do a survey over the full documentation. Such a survey would of course be done differently, but to get spontaneous feedback on each page, we can't send people to the forum or email out a survey.

Also, there is a difference between doc feedback and documentation issues. The expected feedback would be something like "I was looking for XYZ but didn't find it", "this answered the question that I had" or "I don't understand this". None of these would usually be raised as documentation issue.
Of course, there will be some feedback that will result in doc issues, and we'll need to create them then.

**Comment by evildmp** [comment]
Looks good to me @ru-fu, thanks.

**Comment by evildmp** [comment]
@turtle0x1 "This is gross" is not an appropriate form of comment in software review or an acceptable way to respond to someone else's work.

If you have legitimate concerns about this, please express them within the spirit of [the code of conduct for this project](https://github.com/lxc/lxd/blob/master/CODE_OF_CONDUCT.md), so that they can be considered and addressed appropriately.

I politely request that you delete that comment. Thank you.

**Comment by turtle0x1** [comment]
@evildmp  I've amended it but I wont delete it.

**Comment by evildmp** [comment]
@turtle0x1 Thanks a lot for doing that.

**Comment by evildmp** [comment]
**Information captured**

With this mechanism we would capture a minimum of information. Obviously, there's the information that the user can submit (all optional):

* a rating
* a comment
* and email address

In addition, some technical information is captured - the user's browser/OS versions. I don't think those can be turned off.

We don't capture IP address or location.

I can't say with certainty what the tool does with cookies - _as far as I can tell_, it creates a cookie for caching, but doesn't do anything else. https://support.usabilla.com/hc/en-us/search?utf8=%E2%9C%93&query=cookies has more information; again as far as I can tell, the feedback button we are using doesn't involve any GDPR-relevant cookies.

**Documentation feedback vs documentation issues**

The value of this approach is that it provides an in-page feedback mechanism with a very low bar for users. They don't need a GitHub account, and they can leave minimal feedback - without comment - anonymously. That's a useful thing to have. All feedback is directly associated with a documentation page, without any extra effort required.

This system does provide a way to turn feedback into issues, which I think is important. 

Another approach could be a "leave feedback" button that creates a GitHub issue and includes the location of the page in question; however this wouldn't provide a rating mechanism, or the possibility of anonymous or comment-free feedback.

More generally, as @ru-fu points out, documentation _feedback_ is different from a documentation _issue_; they reveal and express different things.

**Comment by turtle0x1** [comment]
The whole script is blocked by `uBlock` so I assume other adblockers will block it to.

The script it downloads includes google analytics.

**Comment by wgx** [comment]
My 2 cents, in case this is useful. When we have previously collected survey information as a User Experience team, we've included a mandatory checkbox / agreement with this wording:

> **Privacy**
> I agree that my participation is subject to acceptance of the Privacy Notice and Privacy Policy, located at: [https://ubuntu.com/legal/data-privacy/survey](https://ubuntu.com/legal/data-privacy/survey) & [https://ubuntu.com/legal/data-privacy](https://ubuntu.com/legal/data-privacy)


This was written for us by in-house legal, about 18 months ago.

**Comment by cassiocassio** [comment]
Do come and talk in with us in #user research about the tooling and approach. Lots of teams use GetFeedback in various places and to various ends.

A long time ago we proposed building a simple version of this kind of feedback tool, and we did some initial work - but were given a strong - and I think in retrospect - correct steer to not build everything ourselves – which all the benefits and tradeoffs that implies.

During procurement this went through legal. We always provide the correct links to the legal / privacy docs in the surveys.

>Another concern that kinda falls from that is that if there's a free form way for users to provide doc feedback

There's a whole range You can ask for feedback passively or actively - you can wait for bug reports, solicit opinions on topics in a Discourse, email existing paying customers, offer drop-in clinics, or run formal usability studies. You can run a survey on a single bullet-point feature or leave an open suggestion-box - and of course, accept PRs.  

#user research

**Comment by stgraber** [comment]
You are asking non-Canonical staff to come talk to you in a company internal channel, that's not going to work too well :)

**Comment by stgraber** [comment]
So just to be clear, I don't think any of us have a problem with there being a way for user to send back feedback on a documentation page but there are a few problematic aspects of the current approach that would need to be addressed.

 - It's loading everything through an external script. This can lead to additional page loading delays or errors in offline/airgaped environments which are common with our larger deployments.
 - This is also a potential security issue should that 3rd party script ever be taken over.
 - Making that last point more problematic, we will be shipping a compiled version of the doc within the LXD tarball, so should something bad happen with that external provider, we won't be able to go change it.
 - It has been reported that the script loads tracking code (Google analytics) which would require a cookie warning.


Using a third party platform for this isn't really a problem here but I'd like us to have a local chunk of javascript which will provide the user with links to the required privacy policies and a short explanation that this will be using a 3rd party online service prior to that external script being loaded.

This should address all the concerns above and just require one extra click from the user to both consent to using the external service (and applicable policies) and triggering the first external access from the documentation. We'll need to make sure that this tiny piece of code will fail nicely should the remote script not be downloadable as that may indicate:
 - Airgaped environment
 - Ad/script blocker
 - 3rd party service is broken, gone or we stopped using it for some reason


Separately from that, from my earlier question, we still need to address the who has access to the data. This is an open source project with maintainers and active contributors from a variety of companies.

It feels wrong to have this feedback available solely to a subset of Canonical staff members. I wouldn't want it to necessarily be open to everyone but I believe it be reasonable to expect all LXD maintainers to have access to it as they do all other bit of infrastructure we use.

**Comment by stgraber** [comment]
> The whole script is blocked by uBlock so I assume other adblockers will block it to.

Oh, that would explain why I couldn't see anything on the preview, I just assumed that something was wrong with the draft PR :)


So yeah, I think we'd really need something that doesn't get blocked by the most common, usually reasonable ad blocker!

**Comment by tomponline** [comment]
> > The whole script is blocked by uBlock so I assume other adblockers will block it to.
> 
> Oh, that would explain why I couldn't see anything on the preview, I just assumed that something was wrong with the draft PR :)
> 
> So yeah, I think we'd really need something that doesn't get blocked by the most common, usually reasonable ad blocker!

I thought the same thing too.

**Comment by ru-fu** [comment]
We should probably restrict it to only run on linuxcontainers.org, not on local copies of the docs.

**Comment by stgraber** [comment]
> We should probably restrict it to only run on linuxcontainers.org, not on local copies of the docs.

I think it'd make sense to exclude it from the build that goes into the release tarballs at least since the doc there is likely to be outdated so the feedback may be less useful.

Doing that would still leave us with:
 - We shouldn't use something that the most common adblockers will reject, we want the feedback from more technically inclined users too and those are likely to have some kind of adblocking in place
 - We shouldn't use something that will load tracking code without prior user consent
 - We need the data to be accessible to project maintainers outside of Canonical

Having the logic only be on current online versions of the doc would however eliminate most concerns about the service being broken, discontinued or taken over as it's something we could realistically easily fix then.

**Comment by stgraber** [comment]
For those of us running adblockers, I took some screenshot of what this is supposed to look like in an incognito session with ublock disabled for the domain.
Screenshot from 2022-02-07 10-56-45
Screenshot from 2022-02-07 10-56-39
Screenshot from 2022-02-07 10-56-30

**Comment by stgraber** [comment]
As discussed, closing this PR as the proposed platform is at least currently unsuitable for us.

**Pull request closed without merging**
