### PR TITLE
Add --format and json output for image list command

### PR DESCRIPTION
**Pull request by ctrlrsf**
Adds the --format option to the `lxc image list` command. Possible options are table and json.

Image list filters still work regardless of output format.

--format table example:
```
$ lxc image list images: 'description=.*yakkety.*s390x.*' --format table
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|             ALIAS             | FINGERPRINT  | PUBLIC | DESCRIPTION               | ARCH  |  SIZE   |         UPLOAD DATE |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
| ubuntu/yakkety/s390x (1 more) | 03a93a03d6bb | yes    | Ubuntu yakkety (s390x) (20160517_03:49) | s390x | 73.19MB | May 17, 2016 at 4:26am (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|                               | 42f6c2bb9348 | yes    | Ubuntu yakkety (s390x) (20160515_03:49) | s390x | 73.09MB | May 15, 2016 at 5:20am (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|                               | a6539f9ece07 | yes    | Ubuntu yakkety (s390x) (20160515_09:20) | s390x | 73.19MB | May 16, 2016 at 6:22pm (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
```

--format json example:
```
$ lxc image list images: 'description=.*yakkety.*s390x.*' --format json
[{"aliases":[],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160515_03:49.tar.xz","fingerprint":"42f6c2bb9348e27a8a048ce9657574cc524473bfa801902f4461da1ca1a456ba","properties":{"architecture":"s390x","build":"20160515_03:49","description":"Ubuntu
yakkety (s390x)
(20160515_03:49)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76642122,"auto_update":false,"created_at":"2016-05-15T05:20:21Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-15T05:20:21Z"},{},{}]
[{"aliases":[],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160515_03:49.tar.xz","fingerprint":"42f6c2bb9348e27a8a048ce9657574cc524473bfa801902f4461da1ca1a456ba","properties":{"architecture":"s390x","build":"20160515_03:49","description":"Ubuntu
yakkety (s390x)
(20160515_03:49)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76642122,"auto_update":false,"created_at":"2016-05-15T05:20:21Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-15T05:20:21Z"},{"aliases":[],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160515_09:20.tar.xz","fingerprint":"a6539f9ece0734574e6ffdaf81e421975fbeb32ac2637b16fe2cbc5648c909fd","properties":{"architecture":"s390x","build":"20160515_09:20","description":"Ubuntu
yakkety (s390x)
(20160515_09:20)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76743878,"auto_update":false,"created_at":"2016-05-16T18:22:41Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-16T18:22:41Z"},{}]
[{"aliases":[],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160515_03:49.tar.xz","fingerprint":"42f6c2bb9348e27a8a048ce9657574cc524473bfa801902f4461da1ca1a456ba","properties":{"architecture":"s390x","build":"20160515_03:49","description":"Ubuntu
yakkety (s390x)
(20160515_03:49)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76642122,"auto_update":false,"created_at":"2016-05-15T05:20:21Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-15T05:20:21Z"},{"aliases":[],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160515_09:20.tar.xz","fingerprint":"a6539f9ece0734574e6ffdaf81e421975fbeb32ac2637b16fe2cbc5648c909fd","properties":{"architecture":"s390x","build":"20160515_09:20","description":"Ubuntu
yakkety (s390x)
(20160515_09:20)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76743878,"auto_update":false,"created_at":"2016-05-16T18:22:41Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-16T18:22:41Z"},{"aliases":[{"name":"ubuntu/yakkety/s390x/default","description":"Ubuntu
yakkety (s390x)
(default)"},{"name":"ubuntu/yakkety/s390x","description":"Ubuntu yakkety
(s390x)"}],"architecture":"s390x","cached":false,"filename":"ubuntu-yakkety-s390x-default-20160517_03:49.tar.xz","fingerprint":"03a93a03d6bb370a129518c0fd53aa6b199342d8ef40c643c43710972334c4df","properties":{"architecture":"s390x","build":"20160517_03:49","description":"Ubuntu
yakkety (s390x)
(20160517_03:49)","distribution":"ubuntu","release":"yakkety"},"public":true,"size":76740678,"auto_update":false,"created_at":"2016-05-17T04:26:27Z","expires_at":"1970-01-01T00:00:00Z","last_used_at":"0001-01-01T00:00:00Z","uploaded_at":"2016-05-17T04:26:27Z"}]
```

Closes https://github.com/lxc/lxd/issues/1951

Signed-off-by: Rene Fragoso <ctrlrsf@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
There's something wrong with the output. See:
```
[
  {
    "aliases": [],
    "architecture": "x86_64",
    "cached": false,
    "filename": "trusty-server-cloudimg-amd64-lxd.tar.xz",
    "fingerprint": "5088e275e4cf31b1229f8ca9b857ff428c5eae8643cf3c10d097964dbd4b8e61",
    "properties": {
      "aliases": "14.04,default,lts,t,trusty",
      "architecture": "amd64",
      "description": "ubuntu 14.04 LTS amd64 (daily) (20160516)",
      "label": "daily",
      "os": "ubuntu",
      "release": "trusty",
      "serial": "20160516",
      "version": "14.04"
    },
    "public": false,
    "size": 123627804,
    "auto_update": true,
    "update_source": {
      "server": "https://cloud-images.ubuntu.com/daily",
      "protocol": "simplestreams",
      "certificate": "",
      "alias": "t"
    },
    "created_at": "2016-05-16T00:00:00Z",
    "expires_at": "2019-04-17T00:00:00Z",
    "last_used_at": "0001-01-01T00:00:00Z",
    "uploaded_at": "2016-05-17T19:07:08Z"
  },
  null
]
[
  {
    "aliases": [],
    "architecture": "x86_64",
    "cached": false,
    "filename": "trusty-server-cloudimg-amd64-lxd.tar.xz",
    "fingerprint": "5088e275e4cf31b1229f8ca9b857ff428c5eae8643cf3c10d097964dbd4b8e61",
    "properties": {
      "aliases": "14.04,default,lts,t,trusty",
      "architecture": "amd64",
      "description": "ubuntu 14.04 LTS amd64 (daily) (20160516)",
      "label": "daily",
      "os": "ubuntu",
      "release": "trusty",
      "serial": "20160516",
      "version": "14.04"
    },
    "public": false,
    "size": 123627804,
    "auto_update": true,
    "update_source": {
      "server": "https://cloud-images.ubuntu.com/daily",
      "protocol": "simplestreams",
      "certificate": "",
      "alias": "t"
    },
    "created_at": "2016-05-16T00:00:00Z",
    "expires_at": "2019-04-17T00:00:00Z",
    "last_used_at": "0001-01-01T00:00:00Z",
    "uploaded_at": "2016-05-17T19:07:08Z"
  },
  {
    "aliases": [],
    "architecture": "x86_64",
    "cached": true,
    "filename": "ubuntu-16.04-server-cloudimg-amd64-lxd.tar.xz",
    "fingerprint": "f4c4c60a6b752a381288ae72a1689a9da00f8e03b732c8d1b8a8fcd1a8890800",
    "properties": {
      "aliases": "16.04,x,xenial",
      "architecture": "amd64",
      "description": "ubuntu 16.04 LTS amd64 (release) (20160420.3)",
      "label": "release",
      "os": "ubuntu",
      "release": "xenial",
      "serial": "20160420.3",
      "version": "16.04"
    },
    "public": false,
    "size": 144224660,
    "auto_update": true,
    "update_source": {
      "server": "https://cloud-images.ubuntu.com/releases",
      "protocol": "simplestreams",
      "certificate": "",
      "alias": "16.04"
    },
    "created_at": "2016-04-20T00:00:00Z",
    "expires_at": "2021-04-21T00:00:00Z",
    "last_used_at": "2016-05-10T22:41:34.841211828Z",
    "uploaded_at": "2016-05-10T22:31:53Z"
  }
]
```

Notice how you're getting two separate lists, one with one entry and then the rest in a second one.

**Comment by stgraber** [comment]
Since you changed the help, you'll also need to run "make i18n" and commit the resulting change to po/lxd.pot.

**Comment by ctrlrsf** [comment]
Good catch! Had moved JSON encoder into for loop by mistake. Output looks much better now. Also updated lxd.pot.

Thanks for your comments. Let me know if you have any other feedback.

```
$ lxc image list images: 'description=.*yakkety.*s390x.*' --format table
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|             ALIAS             | FINGERPRINT  | PUBLIC |               DESCRIPTION               | ARCH  |  SIZE   |         UPLOAD DATE          |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
| ubuntu/yakkety/s390x (1 more) | 03a93a03d6bb | yes    | Ubuntu yakkety (s390x) (20160517_03:49) | s390x | 73.19MB | May 17, 2016 at 4:26am (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|                               | 42f6c2bb9348 | yes    | Ubuntu yakkety (s390x) (20160515_03:49) | s390x | 73.09MB | May 15, 2016 at 5:20am (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+
|                               | a6539f9ece07 | yes    | Ubuntu yakkety (s390x) (20160515_09:20) | s390x | 73.19MB | May 16, 2016 at 6:22pm (UTC) |
+-------------------------------+--------------+--------+-----------------------------------------+-------+---------+------------------------------+


$ lxc image list images: 'description=.*yakkety.*s390x.*' --format json | jq '.'
[
  {
    "uploaded_at": "2016-05-15T05:20:21Z",
    "last_used_at": "0001-01-01T00:00:00Z",
    "expires_at": "1970-01-01T00:00:00Z",
    "created_at": "2016-05-15T05:20:21Z",
    "auto_update": false,
    "aliases": [],
    "architecture": "s390x",
    "cached": false,
    "filename": "ubuntu-yakkety-s390x-default-20160515_03:49.tar.xz",
    "fingerprint": "42f6c2bb9348e27a8a048ce9657574cc524473bfa801902f4461da1ca1a456ba",
    "properties": {
      "release": "yakkety",
      "distribution": "ubuntu",
      "description": "Ubuntu yakkety (s390x) (20160515_03:49)",
      "build": "20160515_03:49",
      "architecture": "s390x"
    },
    "public": true,
    "size": 76642122
  },
  {
    "uploaded_at": "2016-05-16T18:22:41Z",
    "last_used_at": "0001-01-01T00:00:00Z",
    "expires_at": "1970-01-01T00:00:00Z",
    "created_at": "2016-05-16T18:22:41Z",
    "auto_update": false,
    "aliases": [],
    "architecture": "s390x",
    "cached": false,
    "filename": "ubuntu-yakkety-s390x-default-20160515_09:20.tar.xz",
    "fingerprint": "a6539f9ece0734574e6ffdaf81e421975fbeb32ac2637b16fe2cbc5648c909fd",
    "properties": {
      "release": "yakkety",
      "distribution": "ubuntu",
      "description": "Ubuntu yakkety (s390x) (20160515_09:20)",
      "build": "20160515_09:20",
      "architecture": "s390x"
    },
    "public": true,
    "size": 76743878
  },
  {
    "uploaded_at": "2016-05-17T04:26:27Z",
    "last_used_at": "0001-01-01T00:00:00Z",
    "expires_at": "1970-01-01T00:00:00Z",
    "created_at": "2016-05-17T04:26:27Z",
    "auto_update": false,
    "aliases": [
      {
        "description": "Ubuntu yakkety (s390x) (default)",
        "name": "ubuntu/yakkety/s390x/default"
      },
      {
        "description": "Ubuntu yakkety (s390x)",
        "name": "ubuntu/yakkety/s390x"
      }
    ],
    "architecture": "s390x",
    "cached": false,
    "filename": "ubuntu-yakkety-s390x-default-20160517_03:49.tar.xz",
    "fingerprint": "03a93a03d6bb370a129518c0fd53aa6b199342d8ef40c643c43710972334c4df",
    "properties": {
      "release": "yakkety",
      "distribution": "ubuntu",
      "description": "Ubuntu yakkety (s390x) (20160517_03:49)",
      "build": "20160517_03:49",
      "architecture": "s390x"
    },
    "public": true,
    "size": 76740678
  }
]

$ lxc image list --format table
+--------+--------------+--------+----------------------------------------+--------+---------+------------------------------+
| ALIAS  | FINGERPRINT  | PUBLIC |              DESCRIPTION               |  ARCH  |  SIZE   |         UPLOAD DATE          |
+--------+--------------+--------+----------------------------------------+--------+---------+------------------------------+
| alias1 | d1751d04873b | no     | Ubuntu xenial (amd64) (20160517_03:49) | x86_64 | 77.19MB | May 17, 2016 at 5:25pm (UTC) |
+--------+--------------+--------+----------------------------------------+--------+---------+------------------------------+

$ lxc image list --format json | jq '.'
[
  {
    "uploaded_at": "2016-05-17T17:25:14Z",
    "last_used_at": "2016-05-17T17:47:29.028534862Z",
    "expires_at": "1970-01-01T00:00:00Z",
    "created_at": "2016-05-17T04:21:08Z",
    "update_source": {
      "alias": "ubuntu/xenial/amd64",
      "certificate": "",
      "protocol": "lxd",
      "server": "https://images.linuxcontainers.org"
    },
    "auto_update": true,
    "aliases": [
      {
        "description": "alias1",
        "name": "alias1"
      }
    ],
    "architecture": "x86_64",
    "cached": true,
    "filename": "ubuntu-xenial-amd64-default-20160517_03:49.tar.xz",
    "fingerprint": "d1751d04873bf1701854101a16a8805bd0d65e04e945ea16f19c916fe13d5953",
    "properties": {
      "release": "xenial",
      "distribution": "ubuntu",
      "description": "Ubuntu xenial (amd64) (20160517_03:49)",
      "build": "20160517_03:49",
      "architecture": "amd64"
    },
    "public": false,
    "size": 80935558
  }
]

```

**Comment by stgraber** [comment]
That does look much nicer!

jenkins: test this please

**Pull request merged**
