### PR TITLE
Export function DownloadFileHash

### PR DESCRIPTION
**Pull request by monstermunchkin**
Remove DownloadFileSha{256,512}, and export DownloadFileHash. This
removes the restriction of only using sha256 and sha512.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
I think we should rename `downloadFileSha` to `DownloadFileHash` and remove the hash specific functions from shared, porting all our code to just calling `DownloadFileHash` with the expected hash as argument.

@monstermunchkin what do you think?

**Comment by monstermunchkin** [comment]
I also added the option to omit a hash function in which case the checksum is ignored. This is useful for distrobuilder.

**Comment by stgraber** [comment]
Failures are unrelated, I sent a branch to fix that, once confirmed we can retry and land this one.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
