### PR TITLE
zfs: import loop-backed storage pools + bugfixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
Addresses https://github.com/lxc/lxd/issues/2990.

**Comment by brauner** [comment]
Includes test if import works correctly after an export.

**Comment by brauner** [comment]
Closes https://github.com/lxc/lxd/issues/2997.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
