### PR TITLE
lxd/firewall: Don't create zombies

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber presumably this is only occurring if the command fails to run?

**Comment by stgraber** [comment]
Not only that, for iptables we were also always causing it I believe.

**Comment by stgraber** [comment]
`ebtablesInUse` doesn't call Wait()

**Comment by tomponline** [comment]
@stgraber ah yes good spot.

**Pull request merged**
