### PR TITLE
Instance: Unify profile validation and loading for instance create endpoint

### PR DESCRIPTION
**Pull request by tomponline**
Part of the requirements in order to provide an expanded request to the instance placement scriptlet (https://github.com/lxc/lxd/pull/11180).

Also reduces transactions and queries used.

Merge https://github.com/lxc/lxd/pull/11222 first.

### CODE REVIEW

**Review by monstermunchkin — APPROVED** [review]

**Comment by tomponline** [comment]
Looks like I just broke it.

**Comment by stgraber** [comment]
jenkins looking a bit mad at this one :)

**Comment by tomponline** [comment]
> @tomponline did you mean to push a fix for this one?

All fixed now thanks

**Comment by tomponline** [comment]
@stgraber if you take a look at https://github.com/lxc/lxd/pull/11222 first, then I can rebase this one once its merged to make review easier.

**Comment by stgraber** [comment]
@tomponline ready for rebase

**Comment by tomponline** [comment]
Thanks. I've got an issue that isn't detected by the tests to fix on this branch, that I just noticed now as part of my testing of the instance placement scriptlet.

**Comment by tomponline** [comment]
@stgraber ok this is ready for review now.

**Pull request merged**
