### PR TITLE
Storage: Generic VFS functions

### PR DESCRIPTION
**Pull request by tomponline**
Moves generic VFS functions out of common driver, as not relevant to all driver types, and instead into own standalone file. Changes signatures to accept driver interface as argument so that it can

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tomponline that zfs failure appears to be persisting

**Comment by tomponline** [comment]
Indeed will take a look

**Comment by tomponline** [comment]
@stgraber fixed it, was using `genericVFSRenameVolume` in ZFS driver rather than `genericVFSRenameVolumeSnapshot`

**Pull request merged**
