### PR TITLE
lxd/vsock: Better handle errors

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
@stgraber is it worth handling the special types of errors where you `break` in the first connection attempt too?

**Comment by stgraber** [comment]
@tomponline what do you mean?

**Comment by tomponline** [comment]
@stgraber oh ignore me, I'd misread the PR and thought you hadn't remove the initial connect attempt, are you happy for me to merge this now?

**Comment by stgraber** [comment]
@tomponline yep. I still ran into the issue once, so it's not 100% perfect but the remaining issue is deep in Go's net package and not AFAICT anything we're doing. I've also had the upstream vsock package merge a few EINTR handling fixes for me to improve things further.

I've been spamming a test server for over an hour and it's not gone crazy yet, usually it did within 5min, so definitely more solid.

**Pull request merged**
