### PR TITLE
Update gomod

### PR DESCRIPTION
**Pull request by monstermunchkin**
This updates gomod and removes the `replace` directive.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

Fixes https://github.com/lxc/lxd/issues/10927

### CODE REVIEW

**Comment by tomponline** [comment]
Glad to see this is building without the replace line now. Please can you separate the commits to show the removal of replace and general updates as there are some new imports there.

**Comment by monstermunchkin** [comment]
@tomponline I've split this into two parts, the first one allowing the removal of the `replace` directory, and the other just doing an update.

**Comment by stgraber** [comment]
Ah, finally! That will have taken long enough for everyone to move away from that mess :)

**Review by tomponline — APPROVED** [review]
Thanks!

**Pull request merged**
