### PR TITLE
Add base image column to 'lxc info'

### PR DESCRIPTION
**Pull request by sean-jc**
Signed-off-by: Sean Christopherson <sean.j.christopherson@intel.com>

I couldn't find any way to get the base image of a container via `lxc`, i.e. without directly using the REST API.  Adding a column to `lxc info` seems like a good fit as the necessary data is already available.  I waffled on `b` versus `i` for the column key, basically flipped a coin in the end.

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm, so I'm not sure this is used often enough to really warrant its own column.
What's your use case for having this as a column?

Would #2032 be a workable alternative to this for you?

**Comment by sean-jc** [comment]
There's no real use case, I simply like having the extra contextual information when experimenting and testing.  #2032 would work, closing this PR.

**Comment by stgraber** [comment]
Note that "lxc config show" will also show you the value if you only need it for a given container.

**Comment by sean-jc** [comment]
Argh, I knew it had to be available somewhere, I keep forgetting `config` is relevant for containers.  Thanks!

**Pull request closed without merging**
