### PR TITLE
api extension: btrfs.mount_options

### LINKED ISSUE #3264: api extension: btrfs.mount_options
For details see https://discuss.linuxcontainers.org/t/storage-pool-default-mount-options/80 .

### PR DESCRIPTION
**Pull request by brauner**
Closes #3264.

References: https://discuss.linuxcontainers.org/t/storage-pool-default-mount-options/80
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@stgraber, I'll push another patch onto that branch soon that will remount the storage pool on mount option change. The we have the `StoragePoolUpdate()` sorted as well all in one patch. :)

**Comment by brauner** [comment]
@stgraber, added the update code. Would need another review. :)

**Pull request merged**
