### PR TITLE
Promote database node upon delete

### PR DESCRIPTION
**Pull request by freeekanayaka**
This commits make the cluster automatically promote a spare node as database node (if available) when another node gets deleted.

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
I disabled a couple of unit tests which seem to be flaky on jenkins. The integration tests seem fine tho, and they cover this code. I'll try to re-enable the flaky unit-tests as follow-up changes.

**Comment by stgraber** [comment]
I don't like seeing no success for unit tests on i386. Lets try again.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
