### PR TITLE
Add ability to add VIF name (veth.pair) using host_name #1444

### PR DESCRIPTION
**Pull request by bkuschel**
Wlll set veth.pair name, if set.

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by srkunze** [comment]
@bkuschel Not sure about all go styling rules and as it seems LXD uses tabs for indentation. As you see, the signed-off-by check failed. Just use `-s` option when committing. :)

**Comment by stgraber** [comment]
You're missing the code for nic hotplug (createNetworkDevice in container_lxc.go).

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
You have one commit that's missing the signed-off-by line.

**Comment by stgraber** [comment]
looks like this needs rebasing, you should never have a "Merge branch..." commit in your pull requests.

**Comment by bkuschel** [comment]
I did do a rebase, i don't know why it did a merge when I pushed Redoing it.

**Comment by bkuschel** [comment]
It's easier for me to create a new pull then clean this one up. Here is the new Pull...
https://github.com/lxc/lxd/pull/1450

**Pull request closed without merging**
