### PR TITLE
Fixed small typo. (issue #10409)

### LINKED ISSUE #10409: Typo in reference to a path
There are a few typos in the help text (referenace to a path that isn't right)

For example:

https://github.com/lxc/lxd/blob/b1d4ef79d1a914b4ba5faaf430d30b2cfa6e3ce9/lxc/config_device.go#L94

### PR DESCRIPTION
**Pull request by erik78se**
Fixed typo in path.

Fixes #10409

### CODE REVIEW

**Comment by tomponline** [comment]
Please can you sign off your commit using `-s` on your commit command.

**Comment by erik78se** [comment]
> 

Oh, how do I do revert this then?

**Comment by simondeziel** [comment]
`git commit -s --amend` should let you edit the last commit. After that, you'll need to `git push --force`.

**Comment by simondeziel** [comment]
Also, since the change touches localized text, you'll need to:

* `make i18n`
* `git commit -sm "i18n: Update translation templates" po/`
* `git push`

**Comment by erik78se** [comment]
I have to pull down go aswell?

**Comment by erik78se** [comment]
make i18n
(cd / ; go install -v -x github.com/snapcore/snapd/i18n/xgettext-go@latest)
# get https://proxy.golang.org/github.com/@v/list
# get https://proxy.golang.org/github.com/snapcore/snapd/i18n/@v/list
# get https://proxy.golang.org/github.com/snapcore/snapd/@v/list
# get https://proxy.golang.org/github.com/snapcore/@v/list
# get https://proxy.golang.org/github.com/snapcore/snapd/i18n/xgettext-go/@v/list
# get https://proxy.golang.org/github.com/snapcore/snapd/i18n/xgettext-go/@v/list: 410 Gone (0.064s)
# get https://proxy.golang.org/github.com/snapcore/snapd/i18n/@v/list: 410 Gone (0.065s)
# get https://proxy.golang.org/github.com/snapcore/@v/list: 410 Gone (0.065s)
# get https://proxy.golang.org/github.com/snapcore/snapd/@v/list: 200 OK (0.065s)
# get https://proxy.golang.org/github.com/@v/list: 410 Gone (0.065s)
# get https://proxy.golang.org/github.com/snapcore/snapd/@latest
# get https://proxy.golang.org/github.com/snapcore/snapd/@latest: 200 OK (0.006s)
WORK=/tmp/go-build2381068003
xgettext-go -o po/lxd.pot --add-comments-tag=TRANSLATORS: --sort-output --package-name=lxd --msgid-bugs-address=lxc-devel@lists.linuxcontainers.org --keyword=i18n.G --keyword-plural=i18n.NG lxc/*.go lxc/*/*.go
/bin/sh: 1: xgettext-go: not found
Makefile:230: recipe for target 'update-pot' failed
make: *** [update-pot] Error 127

**Comment by simondeziel** [comment]
It looks like the freshly installed `xgettext-go` is no in your `$PATH`.

**Comment by stgraber** [comment]
Did the `make i18n` call for you.

**Pull request merged**
