### PR TITLE
Add a warning in case the range in uid/gid mapping too small

### PR DESCRIPTION
**Pull request by azat**
Otherwise it is hard to understand the culprit of the following error:

    "No available uid/gid map could be found"

### CODE REVIEW

**Comment by tomponline** [comment]
Feels like the problem message should be added to the returned error rather than logged though.

**Comment by azat** [comment]
>Feels like the problem message should be added to the returned error rather than logged though.

I thought about this, but decided to make it a warning, like `No available uid/gid map could be found`.
I guess the original reason can be because w/o uid/gid map privileged containers works.
Do you still think that it should be fatal error?

**Comment by tomponline** [comment]
I'm just worried this is going to add noise in the logs that is not particularly useful.
When do you encounter the "No available uid/gid map could be found" error?

**Comment by azat** [comment]
>When do you encounter the "No available uid/gid map could be found" error?

When I've added too small range in subuid/subgid (65535 actually, not that small)

**Comment by tomponline** [comment]
Which lxc command triggers this warning?

**Comment by azat** [comment]
Not lxc, but simply starting lxd

**Comment by tomponline** [comment]
> Not lxc, but simply starting lxd

OK thanks, but what I'm getting at is how does the warning actually manifest as a problem? (That is where we should try and improve the error)

**Comment by azat** [comment]
>but what I'm getting at is how does the warning actually manifest as a problem? (That is where we should try and improve the error)

Not sure that I got this. Can you elaborate?

My case was that I've created a range that is lower then 65536, and I did not know that there is some limitations in LXD, and so when I tried to use LXD unprivileged container it does not started (because it does not accepted by range). After looking into sources I saw this limitation, but it is impossible to understand the root cause without looking into source code right now.

**Comment by tomponline** [comment]
> when I tried to use LXD unprivileged container it does not started (because it does not accepted by range)

Did you get a helpful error when the container failed to start? It feels like if not it would be better to improve that rather than add background logginh so people don't have to know tolook in the logs.

**Comment by azat** [comment]
>Did you get a helpful error when the container failed to start?

No, and even after this patch the helpful message will be only in lxd log, which not be provided to user, since those checks is done when the daemon starts and did not propagated to user wen it tries to create nonprivileged container.

> It feels like if not it would be better to improve that rather than add background logginh so people don't have to know tolook in the logs.

Ok, closing.

**Comment by tomponline** [comment]
Yeah that was my point. It would be useful to know what error you did get do we can identify and improve it. Thanks.

**Comment by azat** [comment]
>It would be useful to know what error you did get do we can identify and improve it

`lxd.log`

```
t=2022-01-03T22:46:35+0300 lvl=info msg="LXD is starting" mode=normal path=/var/lib/lxd version=4.21
t=2022-01-03T22:46:35+0300 lvl=info msg="Kernel uid/gid map:" 
t=2022-01-03T22:46:35+0300 lvl=info msg=" - u 0 0 4294967295" 
t=2022-01-03T22:46:35+0300 lvl=info msg=" - g 0 0 4294967295" 
t=2022-01-03T22:46:35+0300 lvl=warn msg="No available uid/gid map could be found" 
t=2022-01-03T22:46:35+0300 lvl=warn msg="Only privileged containers will be able
```

```
# lxc launch ubuntu:20.04
Creating the instance
Error: Failed instance creation: Failed creating instance record: Failed initialising instance: Invalid config: LXD doesn't have a uid/gid allocation. In this mode, only privileged containers are supported
```

**Comment by azat** [comment]
BTW if you talking about more sane checks, that it worth also checking that mapping for lxd/root are the same then (AFAIU it is required only for uninstall or smth like this)

**Pull request closed without merging**
