### PR TITLE
lxd-agent: Support for `systemd-notify`

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber out of interest, did this fix an ordering issue/race or did it just speed up boot?

**Comment by brauner** [comment]
It either eliminates races which, or - which is what the notify type is usually used for - it speeds up boot since the service can indicate when it is ready for systemd to continue but can still go on initializing.

**Comment by stgraber** [comment]
It actually slows down boot in our case but this then allows a service that needs a file that's generated by the agent to be able to declare After=lxd-agent and know the file will have been created by the time the service is started.

Right now, it's racy as systemd starts services depending on lxd-agent as soon as the agent is executed.

**Comment by tomponline** [comment]
@stgraber I see, thanks. Do we have any services like that which need lxd agent yet or do you have something in mind?

**Comment by brauner** [comment]
> It actually slows down boot in our case but this then allows a service that needs a file that's generated by the agent to be able to declare After=lxd-agent and know the file will have been created by the time the service is started.

How does this slow down boot?

**Comment by tomponline** [comment]
I've added a PR to capture this knowledge for future reference. https://github.com/lxc/lxd/pull/7245

Is there a specific service that we have in mind for using `After=lxd-agent`?

Thanks

**Comment by stgraber** [comment]
We currently don't but with the other issue requesting the agent starts renaming nics on boot, users may start depending on it.

**Comment by stgraber** [comment]
It's slowing down boot because before this change anything that's scheduled to start after lxd-agent would be allowed to start as soon as lxd-agent was spawned, now they're allowed to start after the agent has done it's initialization steps, so a tiny bit later.

**Pull request merged**
