### PR TITLE
New snapshot tables

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by stgraber** [comment]
@freeekanayaka just a reminder that you can mark a PR as a draft when submitting to Github (but sadly not afterwards).

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@freeekanayaka the ceph and random backend failures look legitimate on:
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/6727/

Going to trigger another run to be 100% sure.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
Jenkins seems happy now, also the ceph backend went green.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
The last failure in the ceph backend (```Error: Migration API failure: Target node is offline```) seems unrelated, perhaps a timing issue that makes the system consider that node offline even if it isn't?

Triggered another Jenkins build.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@freeekanayaka are you happy with this now?

**Comment by freeekanayaka** [comment]
@stgraber "happy" is a bit strong :) But yes, I consider this the final version: the goal of changing the schema to the desired one has been achieved, and the tests pass. So I'd call it a good enough first pass.

I think the next step would be to change the higher-level code accordingly, e.g. stop using the container interface for snapshot-related functionality. But that can come later, perhaps as part of the work needed for VMs.

**Pull request merged**
