### PR TITLE
gomod tweaks

### LINKED ISSUE #9477: SQL scan error during syncing images
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5117/arch=amd64,backend=zfs,compiler=golang-1.16/console#console-section-4

```
/lxc-ci/build/tmp.bsFTtbNZzP/go/bin/lxc image import /lxc-ci/build/cache/testimage.tar.xz --alias testimage --verbose
INFO[11-04|17:06:18] Syncing image to members started         fingerprint=f0ccd75d90d88ff2c95b4c8934e7430c38207aba78370568c592ea9a6d1bdf37 project=default
INFO[11-04|17:06:18] Syncing image to members finished        fingerprint=f0ccd75d90d88ff2c95b4c8934e7430c38207aba78370568c592ea9a6d1bdf37 project=default
Error: Failed syncing image between nodes: Failed to get image: Failed to fetch images: Failed to fetch images: sql: Scan error on column index 12, name "last_use_date": unsupported Scan, storing driver.Value type <nil> into type *time.Time
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #9477

### CODE REVIEW

**Comment by MathieuBordere** [comment]
Is this the only place a potentially NULL time is scanned?

**Comment by tomponline** [comment]
> Is this the only place a potentially NULL time is scanned?

No, sadly. https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5121/arch=arm64,backend=dir,compiler=golang-1.13/console#console-section-3

**Review by monstermunchkin — APPROVED** [review]
Looks good. But why's the btrfs change in this PR?

**Comment by tomponline** [comment]
> Looks good. But why's the btrfs change in this PR?

https://github.com/lxc/lxd/issues/9418

**Pull request merged**
