### PR TITLE
lxc/profile: Add cross-project copy

### LINKED ISSUE #10340: Support copying profiles across projects
# Required information

 * Distribution: Ubuntu
 * Distribution version: 22.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 5.15.0
   * LXC version: 5.0.0
   * LXD version: 5.0.0
   * Storage backend in use:

# Issue description

`lxc profile copy` doesn't work the way its help-text's wording would imply, ie. the wording says `--project        Override the source project`, but that actually overrides both the source and the target project instead of just the source.

# Steps to reproduce

 1. Switch to e.g. "_project2_"
 2. Do `lxc profile copy default default2 --project project1`
 3. "_project2_" won't have the newly-copied profile, but instead it'll be in "_project1_" and it'll be a copy of the "_default_"-profile from "_project1_", not from "_project2_".

* Suggested fix

Either the word "source" should be removed, or it should specifically only apply to the project to copy from, not the project to copy to, in which case it should copy to the currently-active project. A `--target-project` option would also make sense.

### PR DESCRIPTION
**Pull request by stgraber**
Closes #10340

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by tomponline — CHANGES_REQUESTED** [review]
Please can we have a test added for this. Thanks.

**Review by tomponline — APPROVED** [review]
Thanks!

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tomponline good to go

**Pull request merged**
