### PR TITLE
RFC: initial cluster database plumbing

### PR DESCRIPTION
**Pull request by freeekanayaka**
This branch adds the initial plumbing for adding and managing a dqlite database to LXD.

It does NOT introduce a dependency on dqlite yet, but prepares the ground for doing so.

It does however introduce new dependencies on the go-grpc-sql package and all its indirect dependencies, most noticeably the grpc Go package which requires Go 1.8 or higher.

The idea is to first figure out how to have CI happy with this change (for instance we'll  have to exclude Go <1.8 from the build) and then gradually move on to include more complicated dependencies like dqlite, which require a custom sqlite build.

### CODE REVIEW

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
We won't be able to land this until we have Go 1.9 backported to Ubuntu 16.04 as until then we must keep building with Go 1.6.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@freeekanayaka do you still benefit from having this one open?

**Comment by freeekanayaka** [comment]
Yes, since we don't have green CI builds/tests for the clustering branch, this PR helps me ensuring that the part of the changeset that does not require dqlite works fine. I guess we can close this as soon as we make CI progress with the clustering branch.

**Comment by freeekanayaka** [comment]
Closing this PR since #4094 is basically green (albeit with clustering tests temporarily disabled).

**Pull request closed without merging**
