### PR TITLE
lxd/instance/qemu: Support running inside a LXD container

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
With this change in place, we can then run LXD VMs inside of a LXD container with:
```
lxc launch images:ubuntu/22.04 u22 -c security.nesting=true
lxc config device add u22 kvm unix-char source=/dev/kvm
lxc config device add u22 vhost-net unix-char source=/dev/vhost-net
lxc config device add u22 vhost-vsock unix-char source=/dev/vhost-vsock
```

**Comment by stgraber** [comment]
@tomponline good to go

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Lgtm! Worth adding a section to the docs with those commmands above showing how lxd can run VMS inside containers?

**Comment by stgraber** [comment]
I'm not sure it's something I'd really want to encourage. Passing those character devices may significantly reduce or in some cases entirely nullify the normal security benefit of LXD containers.

It's fine for testing purposes but those devices generally expose you to system wide objects with no built-in namespacing support.

**Comment by juippis** [comment]
Hey, 

Will this be backported into LTS-5.0?

**Pull request merged**
