### PR TITLE
Fix issues with network API

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Jenkins looks pretty happy with this.

**Comment by freeekanayaka** [comment]
Fixes #4813.

**Comment by freeekanayaka** [comment]
Since the user has already provided detailed info to reproduce the issue, and we already have tests in this area, it shouldn't be to hard to add a test that proofs that the change work and that we won't break again in the future. YMMV.

Other than that, it looks good to me.

**Comment by brauner** [comment]
Merging this now so that edge users have that fix available soon.

**Pull request merged**
