### PR TITLE
Add a simple list formatting example for #3055

### PR DESCRIPTION
**Pull request by techtonik**
Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Actually looks like you've allowed maintainer changes to your branch so I should be able to fix that myself now :)

Translations also need to be updated, will do that too.

**Comment by stgraber** [comment]
Branch updated

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by techtonik** [comment]
Thanks. It is hard to update translations from GitHub web interface. =)

**Pull request merged**
