### PR TITLE
Backups export explanation

### PR DESCRIPTION
**Pull request by jamielsharief**
Expanded explanation on how backups can be used and when they can fail.

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm, the API docs usually do not refer to commands from a particular client tool.
I'll see what we can do here to make it clearer but keep it in line with the rest of the API doc.

**Comment by jamielsharief** [comment]
> Hmm, the API docs usually do not refer to commands from a particular client tool.
> I'll see what we can do here to make it clearer but keep it in line with the rest of the API doc.

My concern was more about the `optimized_storage` , the API docs do not mention that if you export a backup using this that you will not be able to restore it on a host with a different storage pool.

**Comment by stgraber** [comment]
@jamielsharief isn't that covered in `doc/backup.md`?

**Comment by stgraber** [comment]
Added an extra bit to the `POST` method creating the backup to make it clear that you need to restore on the same driver.

**Pull request closed without merging**
