### PR TITLE
lxd/cluster: Guarantee single hearbeat loop

### LINKED ISSUE #8422: Cluster heartbeat is sometimes nested
When looking at the monitor logging we see that the heartbeats of our cluster is not behaving as it should. There could be multiple problems. This issue is about one of them.

# Required information

```
  os_name: Ubuntu
  os_version: "20.04"
  project: default
  server: lxd
  server_clustered: true
  server_version: "4.10"
  storage: lvm
  storage_version: 2.02.176(2) (2017-11-03) / 1.02.145 (2017-11-03) / 4.41.0
```

# Issue description

Besides the normal heartbeats at 10 second interval, there are also two extra heartbeats. This can be shown by looking at monitor logging, using `lxc monitor --type=logging`, see below.

This report is mainly to request to prevent nested heartbeat calls. It should not harm normal operation of cluster heartbeats, and it may help further investigation other problems. Besides avoid the extra calls it could be helpful if we can find out where these extra calls come from.

I've created a small Python script to reformat the logging output, and to sort the entries with their timestamp because in the normal logging output the entries can be swapped. Anyway, what I want to show looks like this:
```
2021-02-04 11:09:43.360817+01:00  Starting heartbeat round
2021-02-04 11:09:53.360933+01:00  Starting heartbeat round
2021-02-04 11:09:56.371733+01:00  Starting heartbeat round    <===== huh?
2021-02-04 11:09:56.461215+01:00  Starting heartbeat round    <===== huh?
2021-02-04 11:10:03.361091+01:00  Starting heartbeat round
2021-02-04 11:10:13.361212+01:00  Starting heartbeat round
2021-02-04 11:10:23.361347+01:00  Starting heartbeat round
2021-02-04 11:10:33.361442+01:00  Starting heartbeat round
2021-02-04 11:10:43.361503+01:00  Starting heartbeat round
2021-02-04 11:10:53.361628+01:00  Starting heartbeat round
2021-02-04 11:10:56.376217+01:00  Starting heartbeat round    <===== huh?
2021-02-04 11:10:56.445026+01:00  Starting heartbeat round    <===== huh?
2021-02-04 11:11:03.361865+01:00  Starting heartbeat round
2021-02-04 11:11:13.362012+01:00  Starting heartbeat round
2021-02-04 11:11:23.362032+01:00  Starting heartbeat round
2021-02-04 11:11:33.362045+01:00  Starting heartbeat round
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #8422

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by keestux** [comment]
Thanks.
Nevertheless, I'm still a bit worried how that will affect my situation. To be honest, I have no knowledge of the Go world. I'm guessing that the next call will wait until the lock is free. If that's true then I will see the three extra calls "pile up". Every minute, I see 9(!) heartbeat rounds, each take roughly 8 seconds. That's 72 seconds. Can you please tell me that I'm wrong. I'm scared that my system will blow up when 4.12 is deployed.
(( This concern also posted on the [forum](https://discuss.linuxcontainers.org/t/excluding-offline-node-from-refresh-but-everything-seems-ok), sorry for the duplicate. ))

**Comment by stgraber** [comment]
https://github.com/lxc/lxd/pull/8453 should improve that part

**Comment by stgraber** [comment]
Even with the previous logic, all you'd have is heartbeats piling up for a bit, as it's all done async, at worst you'd end up with a bunch of goroutines waiting for the lock and your system performing heartbeats one after the other.

The problematic part would be to have multiple versions of the state in flight, the lock eliminated that.

**Comment by keestux** [comment]
Wow, great.  #8453 takes away my worry.
Now eagerly looking forward to 4.12 :-)

**Pull request merged**
