### PR TITLE
fix typo in fuidshift cli text

### PR DESCRIPTION
**Pull request by ranjib**

### CODE REVIEW

**Comment by tych0** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tych0** [comment]
Can you sign off on your commit?

```
git commit --amend -s
git push -f $remote typo
```

should do the trick.

**Comment by ranjib** [comment]
@tych0 done.
btw `man fuidshift` print the option description twice. I could not figure out why though,
```
USAGE:(1)                                                                                                                       User Commands                                                                                                                       USAGE:(1)

NAME
       Usage: - uid/gid shifter

SYNOPSIS
       fuidshift directory [-t] [-r] <range1> [<range2> ...]

DESCRIPTION
       -t implies test mode.
              No file ownerships will be changed.

       -r means reverse, that is shift the uids out of hte container.

              A range is [u|b|g]:<first_container_id:first_host_id:range>.  where u means shift uids, g means shift gids, b means shift both.  For example: debian/tmp/usr/bin/fuidshift directory b:0:100000:65536 u:10000:1000:1

       -t implies test mode.
              No file ownerships will be changed.

       -r means reverse, that is shift the uids out of hte container.

              A range is [u|b|g]:<first_container_id:first_host_id:range>.  where u means shift uids, g means shift gids, b means shift both.  For example: debian/tmp/usr/bin/fuidshift directory b:0:100000:65536 u:10000:1000:1

```

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
