### PR TITLE
Properly handle xattrs

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by brauner** [comment]
How often are we going to fix this? :)
Do all versions of tar support this?

**Comment by stgraber** [comment]
Looking around, most versions of tar going back to 2008 or so should have it, if we get reports of distros that don't support it, we'll see about adding some detection logic (or telling them to please update their version of tar to something vaguely modern).

**Comment by stgraber** [comment]
But it's not quite the end of the fun with xattrs, I'm filing another issue now about it...

(Though this branch still makes sense regardless)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner should be good to go

**Pull request merged**
