### PR TITLE
Reverts root disk device non-empty pool check

### PR DESCRIPTION
**Pull request by tomponline**
The recent modification to `IsRootDiskDevice` to correctly verify for a non-empty `pool` property has caused issues with the migration process from older server versions that don't have storage pool support, and will also cause problems when using the client against older version versions.

As such this change has been reverted and the non-empty `pool` property check moved into the disk device validation itself.

A comment has been added to avoid confusion in the future.

Part of #5819

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline you revert commit isn't signed-off

**Comment by stgraber** [comment]
Otherwise looks good, will merge once that's fixed

**Comment by tomponline** [comment]
@stgraber ah ok wasnt sure if I needed to do that will do it now.

**Comment by tomponline** [comment]
@stgraber thats done now.

**Pull request merged**
