### PR TITLE
Make the test suite use lxc.apparmor.profile instead of lxc.aa_profile

### PR DESCRIPTION
**Pull request by freeekanayaka**
Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This will break on LXC 2.0.x... We need a version check for this like we do in kernel_limits and use the new syntax only on 2.1 or higher.

**Comment by brauner** [comment]
On Mon, Feb 12, 2018 at 12:21:15PM -0800, Stéphane Graber wrote:
> This will break on LXC 2.0.x... We need a version check for this like we do in kernel_limits and use the new syntax only on 2.1 or higher.

@free is this a small patch you can send today? It should just be
something like

  lxc_version=$(lxc info | grep "driver_version: " | cut -d' ' -f4)
  lxc_major=$(echo "${lxc_version}" | cut -d. -f1)
  lxc_minor=$(echo "${lxc_version}" | cut -d. -f2)

  if [ "${lxc_major}" -lt 2 ] || ([ "${lxc_major}" = "2" ] && [ "${lxc_minor}" -lt "1" ]); then
    # use lxc.apparmor.profile
  elif
    # use lxc.aa_profile
  fi

Christian

**Comment by freeekanayaka** [comment]
@brauner pushed #4252, thanks

**Comment by stgraber** [comment]
We probably should move the version/major/minor logic to an include and only do it once for the entire testsuite run but that's a small optimization we can do later :)

**Pull request merged**
