### PR TITLE
lxd/instance/qemu: Avoid conflicting vsock IDs

### LINKED ISSUE #9426: Nested VMs conflict with vsock IDs of host VMs
When working on the VM stateful migration work I have discovered that the vsock `guest-cid` ID seems to be able to conflict with VMs running on the host.

Host OS: Ubuntu 21.10
Kernel: 5.13.0-20-generic

Guest OS: Ubuntu 20.04
Kernel: 5.11.0-38-generic
With LXD agent running inside.

If a VM running on host ends up having the same DB ID as a VM running inside the guest VM, then the guest VM cannot start because the vsock IDs are conflicting, e.g.

```
qemu-system-x86_64:/var/snap/lxd/common/lxd/logs/v1/qemu.conf:128: vhost-vsock: unable to set guest cid: Address already in use
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #9426

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline I think that ends up being the simplest approach to handle the nesting case.
We could do something more complex which would decouple the context ID from the database ID, but that would need locking, scanning for existing ID, ... which is all annoying and slow.

This approach is pretty simple, instead of the hardcoded base of `3`, we move to a hardcoded base of whatever the VsockID is (2 on a real host, some uint32 in a VM), we add 1 for backward compat with older IDs and then add the instance ID.

This turns the logic into a no-op for non-nested cases and for nested cases, it fixes the issue by shifting everything to be after the guest's own ID.

The part I mention in the comment about potential clashes on upgrade if we didn't have the "+ 1" part will still affect some amount of users which run LXD nested as we're effectively changing all IDs there. Existing guests are perfectly fine, where things can get messy is when one of those is restarted as it may then conflict with another running VM.

But the nested use case is a small enough one and the likelihood of hitting a collision in such a case is low enough that I don't think we really need to bother about it. If someone hits it, restarting their instances will fix it anyway.

**Comment by tomponline** [comment]
@stgraber this is certainly simpler than what I started doing for this:

https://github.com/tomponline/lxd/commit/dcc30d164a9fb6dbc80f099ce4d5615ffebefecc

Which was to optimistically try random vsock IDs to find a free one.
Although this approach won't necessarily play well with other vsock users on the system.

Certainly its an improvement on what we have now.

**Comment by stgraber** [comment]
Right, it still would hit issues if you have libvirt or something else also creating vsock contexts, but so far we've not seen much (or any) evidence of this hitting our users. The only case where I've seen issues is when we're nesting LXD itself.

**Comment by stgraber** [comment]
@tomponline good to go

**Pull request merged**
