### PR TITLE
Log errors returned by reverter hooks

### PR DESCRIPTION
**Pull request by markylaing**
In relation to #10392 and https://github.com/lxc/lxd/issues/10392#issuecomment-1125842768 in order for the `errcheck` linter to pass, we need to inspect or explicitly ignore all errors. This change changes the type signature of `revert.Hook` to return an error which is logged during `revert.Fail` if non-nil.

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
There's a distinct lack of logging going on in the `lxd/revert: Log errors returned by revert hooks.` commit :)

**Comment by markylaing** [comment]
> There's a distinct lack of logging going on in the `lxd/revert: Log errors returned by revert hooks.` commit :)

:man_facepalming: fixed.

**Comment by tomponline** [comment]
From IRC:
Just looking at your lint PR now, can you explain why the linter was complaining about the revert again?
I understand the defer part, the reverter isn't clear.

**Comment by tomponline** [comment]
Hrm OK I see. Perhaps it would be easier to not change the reverter, but just add `_` where we are not wanting to handle the error or log the warning/react to errors if the function is a multi-part revert. I thought that now after looking at your PR, as in some cases you've logged the warning inside the reverter (if its a multi-step revert) and now other places are logging the error in the revert package itself. Feels cleaner to let the function passed to the reverter to handle logging and/or specifying the error isn't handled using `_`.

**Comment by markylaing** [comment]
@tomponline ok no worries.

**Pull request closed without merging**
