### PR TITLE
Make lxd-images work nicer-ly with proxies

### PR DESCRIPTION
**Pull request by tych0**
Thanks to Scott Moser for the patch.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by raharper** [comment]
Nice, this works on my machine behind proxy.

**Comment by stgraber** [comment]
Hmm, wait, why is that needed?

That patch is identical to what I first gave smoser but we then figured that using p80 every time would work too and would let us drop the if statement.

**Comment by stgraber** [comment]
So before we merge that, I'd like to see proof of a case where our current code (which uses proxy-friendly gpg over port 80) fails in some cases and understand exactly what those cases are.

**Comment by tych0** [comment]
I don't know, I just added it because rharper told me too :)

**Comment by stgraber** [comment]
So we agreed with @raharper that this patch does nothing, closing the pull request.

**Pull request closed without merging**
