### PR TITLE
lxd-user: use atomic operations

### PR DESCRIPTION
**Pull request by brauner**
Rather than relying on heavy-handed locks, rely on atomic operations.

Signed-off-by: Christian Brauner <brauner@kernel.org>

### CODE REVIEW

**Comment by brauner** [comment]
I couldn't test this locally right now, @stgraber. Maybe you can.

**Comment by brauner** [comment]
> Rather than relying on heavy-handed locks, rely on atomic operations.
> 
> Signed-off-by: Christian Brauner [brauner@kernel.org](mailto:brauner@kernel.org)

Hmpf, my sign-off got messed up it seems.

**Comment by stgraber** [comment]
Logic looks correct, testing now.

**Comment by stgraber** [comment]
```
Jan 11 13:42:33 dakara systemd[1]: Started Service for snap application lxd.daemon.
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg="Connecting to LXD"
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg="Starting up the server"
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg=Connected gid=200512 pid=582316 uid=201105
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg=Disconnected gid=200512 pid=582316 uid=201105
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg=Connected gid=200512 pid=582316 uid=201105
Jan 11 13:42:33 dakara lxd-user[582354]: time="2022-01-11T13:42:33-05:00" level=info msg=Disconnected gid=200512 pid=582316 uid=201105
Jan 11 13:43:03 dakara lxd-user[582354]: time="2022-01-11T13:43:03-05:00" level=info msg="Shutting down for inactivity"
Jan 11 13:43:03 dakara systemd[1]: snap.lxd-user.daemon.service: Deactivated successfully.
```

**Comment by stgraber** [comment]
Cleared RFC tag as this looks good to me.

**Pull request merged**
