### PR TITLE
lxc/config_trust: Support stdin and allow name override 

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
@albertodonato

**Comment by tomponline** [comment]
Should we make the name flag required when reading from stdin to avoid using /dev/stdin  as basis of the name.

**Comment by stgraber** [comment]
@tomponline nah, I think it's okay, it records as `stdin` which is about as good as the behavior it does with a normal filename :)

**Comment by stgraber** [comment]
@tomponline looking green enough to get merged

**Pull request merged**
