### PR TITLE
driver_lxc: pass flags to shiftfs mount

### PR DESCRIPTION
**Pull request by brauner**
Link: https://discuss.linuxcontainers.org/t/mount-home-directory-read-only-permission-denied
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
thanks @brauner

**Comment by tomponline** [comment]
@brauner looks like the tests are failing...

**Comment by brauner** [comment]
> @brauner looks like the tests are failing...

oO weird

**Comment by brauner** [comment]
Wow, there's a slew of bugs.

**Comment by brauner** [comment]
Thanks, @tomponline!

**Comment by tomponline** [comment]
Thanks for fixing it :)

**Pull request merged**
