### PR TITLE
Remove IPv6 leases on container delete

### PR DESCRIPTION
**Pull request by georghopp**
Signed-off-by: Georg Hopp <georg@steffers.org>

This is an addition to the fix of #2781 which also removes IPv6 leases on container delete.

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Hmm, so using just the name won't work either. The recorded name in the lease is whatever the DHCP client sent us and may not at all align with the container name.

**Comment by stgraber** [comment]
I commented in https://github.com/lxc/lxd/commit/f4c1079ac1284652d62ef43d3b7e97ae5d5264b1 with what should be a more reliable way to deal with this (based on reading the dnsmasq lease generation code).

**Comment by stgraber** [comment]
@georghopp let me know if you run out of time to do this on your side and I'll work on a branch to fix this myself.

**Comment by georghopp** [comment]
I updated this according to your suggestions but please review carefully. This is the first time I do anything with go and most of the stuff is an adaption of VonC's solution to (this stackoverflow)[https://stackoverflow.com/questions/25686109/split-string-by-length-in-golang] question.

**Comment by georghopp** [comment]
Finished work on this until further feedback.

**Comment by stgraber** [comment]
Thanks for your work! I've updated your branch to squash this change into a single commit, keeping your original commit message and expanding a bit in it.

I also had to run "go fmt ./..." to fix some formatting issues with your change, but have otherwise not modified the code in any way.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
