### PR TITLE
firewalld & lxd : how to let Firewalld control the LXD's iptables rules

### PR DESCRIPTION
**Pull request by kerphi**
this is related to https://github.com/lxc/lxd/pull/7195 but this a bit more generic

### CODE REVIEW

**Comment by tomponline** [comment]
Whilst this no doubt works for the basic case, my concern would be that these instructions get out of date when/if the rules that LXD would add change in the future. It would also be worth highlighting here that `bridged` NIC features like `security.*_filtering` (https://linuxcontainers.org/lxd/docs/master/instances#nictype-bridged) would also be affected by firewallld starting after LXD and/or being restarted and removing the security firewall rules LXD had added on a per-instance basis (different rules for each instance).

I would suggest at least that a warning be added to this section stating that this is not a fool-proof approach and may end up inadvertently introducing a security risk.

**Comment by kerphi** [comment]
Ok thank you @tomponline, I just added a warning.

**Comment by stgraber** [comment]
Hi,

We still need those commits signed off before they can go in, see: https://github.com/lxc/lxd/blob/master/doc/contributing.md#developer-certificate-of-origin

**Comment by kerphi** [comment]
> Hi,
> 
> We still need those commits signed off before they can go in, see: https://github.com/lxc/lxd/blob/master/doc/contributing.md#developer-certificate-of-origin

I'm not sure i did the right thing to "signed off" but is it better now?

**Pull request merged**
