### PR TITLE
Make sure lxc file edit doesn't change target file's permissions

### PR DESCRIPTION
**Pull request by ctrlrsf**
This change prevents `lxc file edit` from changing the target file's permissions when a container's file is edited. To fix this, a new PushFileEdit() method was added that does not send any permission information to lxd server. When no permission information is passed on, permissions for the target file are not changed.

Reason for adding PushFileEdit instead of reusing existing PushFile() method is that there was no way of specifying -1 for its mode argument(os.FileMode type, which is uint32). The zero value of os.FileMode is actually a valid mode, so couldn't use that to indicate "no mode" either.

Closes https://github.com/lxc/lxd/issues/2047

### CODE REVIEW

**Comment by stgraber** [comment]
Waiting for Jenkins to be functional again (broken github integration), will kick a test then and merge if all looks good. Thanks for the branch!

**Comment by stgraber** [comment]
Hmm, looking at this closely, it looks like it could be made much simpler and much shorter if you did:
 - Add a parameter to the push() function to tell it to send the uid, gid and mode (so no separate function for edit, just pass false instead)
 - Change PushFile to not set X-LXD-uid if -1
 - Change PushFile to not set X-LXD-gid if -1
 - Change PushFile to take mode as a string rather than os.FileMode and not set it if empty
 - Change PushFile call in file.go to send the mode in octal format (fmt.Sprintf("%04o", mode.Perm()))

With this, the delta should shrink to something much more manageable for inclusion in a bugfix release.

**Comment by ctrlrsf** [comment]
Thanks for the insight. Original implementation used a flag, but wasn't sure if PushFile APIs could be changed so went with new functions instead. Updated PR with your recommendations. Let me know if you have any further suggestions.

**Comment by stgraber** [comment]
Yeah, I usually try not to change the client.go API in stable releases (and this will be going to one), but that particular function was changed in 2.0.1 so I don't feel too bad changing it a bit again in 2.0.2 :)

**Pull request merged**
