### PR TITLE
typo fix

### PR DESCRIPTION
**Pull request by setharnold**
typo fix `defaul` -> `default`.

### CODE REVIEW

**Comment by tomponline** [comment]
Please can you sign off your commit

**Comment by tomponline** [comment]
Closing for https://github.com/lxc/lxd/pull/10439

**Comment by setharnold** [comment]
Cool, thanks, sorry for the trouble, but I've never tried to amend commits before, and didn't get around to figuring out how that's done before you beat me :)

**Comment by tomponline** [comment]
No worries, thanks for spotting the mistake!

**Pull request closed without merging**
