### PR TITLE
Fix spelling: permisson -> permission

### PR DESCRIPTION
**Pull request by dolph**
This change will also impact the *.po files, but I assume I don't need to re-generate those manually in this PR?

### CODE REVIEW

**Comment by stgraber** [comment]
You don't need to update the individual .po files but you do need to update the template (lxd.pot).

This can be done with "make i18n"

**Comment by stgraber** [comment]
@dolph any chance you can run "make i18n" and commit the result?

If not, I'll copy your commit to my branch and do it for you tomorrow.

**Comment by stgraber** [comment]
Cherry-picked into my branch and ran i18n on top, closing this pull request.

**Comment by dolph** [comment]
Thank you, @stgraber!

**Pull request closed without merging**
