### PR TITLE
shared/util: Fix unit parsing (metric vs iec)

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
Breaks the test-suite.

**Comment by stgraber** [comment]
Added LVM handling, hopefully that'll do the trick.

**Comment by stgraber** [comment]
@brauner going to bed now, can you take a look at what's making LVM unhappy with this change?
I'm running out of places that need the 512 trick...

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Looks good now, doesn't it?

**Comment by stgraber** [comment]
Well, LVM does, CEPH, not so much

**Comment by brauner** [comment]
May I - at this point - ask whether we really really need this and who requested anything else than `1024`? :)

**Comment by stgraber** [comment]
Ok, that should do the trick now :)

**Comment by stgraber** [comment]
@brauner should be good to go now, at last :)

**Pull request merged**
