### PR TITLE
Moves seccomp to separate package

### PR DESCRIPTION
**Pull request by tomponline**
- Also fixes static analysis check for ucred package.

### CODE REVIEW

**Comment by stgraber** [comment]
```
lxd/container_lxc.go:37:2: build constraints exclude all Go files in /Users/travis/gopath/src/github.com/lxc/lxd/lxd/seccomp
```

**Comment by tomponline** [comment]
@stgraber where did you see that error? There is also a spelling error causing tests to fail "lxd/seccomp/seccomp.go:606:23: "recieves" is a misspelling of "receives""

**Comment by tomponline** [comment]
@stgraber I see it, its in the appveyor build on windows.

**Comment by tomponline** [comment]
@stgraber I've added an empty file to the `seccomp` package without any build tags so there is at least one candidate file that can "compile" on non-linux systems. This is passing the AppVeyor tests now, but I am confused & concerned how the build is succeeding given that functions that LXD relies on are missing in windows builds (this must've been the case before anyhow, I'd like to understand how that works).

**Comment by tomponline** [comment]
@stgraber it looks like appveyor is only testing builds for lxc and client packages, but looks like `go get ./...` was failing on getting files for seccomp?

**Pull request merged**
