### PR TITLE
lxd: Send metadata in CreateImage error response

### PR DESCRIPTION
**Pull request by joelhockey**
Include fingerprint and size metadata in CreateImage error
response when image already exists.  When creating an image
from a container snapshot, it is useful to know the fingerprint
of an existing image.  It can currently be parsed from the error
string, but this makes it more explicit.

Signed-off-by: Joel Hockey <joelhockey@chromium.org>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Hm, Jenkins is unhappy :)
```
+ lxc publish c1 --alias=protected
+ LXC_LOCAL=1 lxc_remote publish c1 --alias=protected
+ set +x
+ eval /lxc-ci/build/tmp.QzTEgIDf3r/go/bin/lxc "publish" "c1" "--alias=protected" --verbose
+ /lxc-ci/build/tmp.QzTEgIDf3r/go/bin/lxc publish c1 --alias=protected --verbose
INFO[01-23|22:57:37] Exporting container                      project=default name=c1 created=2019-01-23T22:57:35+0000 ephemeral=false used=2019-01-23T22:57:36+0000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xf2c21d]

goroutine 57959 [running]:
main.imagesPost.func2(0xc000182620, 0x0, 0x0)
	/lxc-ci/build/tmp.QzTEgIDf3r/go/src/github.com/lxc/lxd/lxd/images.go:723 +0x23d
main.(*operation).Run.func1(0xc000182620, 0xc0006f27e0)
	/lxc-ci/build/tmp.QzTEgIDf3r/go/src/github.com/lxc/lxd/lxd/operations.go:141 +0x4a
created by main.(*operation).Run
	/lxc-ci/build/tmp.QzTEgIDf3r/go/src/github.com/lxc/lxd/lxd/operations.go:140 +0x3b9
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```
https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5381/arch=amd64,backend=dir,compiler=golang-1.11,restrict=lxd-priv/console

**Comment by joelhockey** [comment]
I've made a fix for the error shown in jenkins and force pushed an update.  Should I be running any of these tests locally?  How would I do that?

**Comment by brauner** [comment]
So you can run the tests locally and there's a doc describing how to run them and various options https://github.com/lxc/lxd/tree/master/test like running them on a `tmpfs` etc.

Whether to report back success or error in this case becomes a matter of whether this breaks existing users expectations or not. For now I'd just go with reporting back an error but @stgraber might have an opinion as well.

**Pull request merged**
