### PR TITLE
Use the node ID from the nodes ID table, not the raft one

### PR DESCRIPTION
**Pull request by freeekanayaka**
Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>

### CODE REVIEW

**Comment by freeekanayaka** [comment]
This is a first pass: probably we're missing a new database update which tries to fix clusters with broken state (I believe it will be possible by looking a the raft_nodes table and comparing addresses). I'm not feeling great so I might finish it tomorrow.

**Comment by stgraber** [comment]
Thanks. I'll push a follow-up commit.

I think all we need to do is add a patch which wipes the table and re-populate it as we did when the role branch landed.

**Comment by stgraber** [comment]
@freeekanayaka ended up tweaking our existing patch to also remove bad roles and then added it back to the list to re-run.

**Comment by stgraber** [comment]
@freeekanayaka I'm happy with your change, if you're happy with mine, feel free to merge :)

**Comment by freeekanayaka** [comment]
@stgraber nice!

**Pull request merged**
