### PR TITLE
Redo logging and keep original logging API

### PR DESCRIPTION
**Pull request by jsimonetti**
This pullrequest changes logging in the shared library to use empty anonymous functions
The main package (lxd and lxc) have been reworked to use a new logging package which adds back the original functionality of the logging and also keeps the original API.

The effect of this is that the shared package no longer has the following dependencies:
github.com/mattn/go-colorable
gopkg.in/inconshreveable/log15.v2/term
gopkg.in/inconshreveable/log15.v2/stack
gopkg.in/inconshreveable/log15.v2

3rd try, if this doesn't work ... :)

Signed-off-by: Jeroen Simonetti jeroen@simonetti.nl

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

An organization member must perform one of the following:

 - To have this branch tested by Jenkins, use the "ok to test" command.
 - To have a one time test done, use the "test this please" command.

Those commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by stgraber** [comment]
jenkins: ok to test

**Comment by jsimonetti** [comment]
@stgraber could you shed some light on why this fails?
I'm totally unsure what happens in that piece of code (func logContextMap) and it appears to be the only place in the code that does custom error handling.

**Comment by stgraber** [comment]
I'll pull your branch here and try to fix that one bit, should be possible to make the event logging interface more flexible to allow both the standard Ctx (map[string]interface{}) or a string.

**Comment by stgraber** [comment]
old: [path /var/lib/lxd]
new: [[[map[path:/var/lib/lxd]]] <nil> LOG15_ERROR Normalized odd number of arguments by adding nil]

So something in your change is seriously mangling Ctx.

**Comment by stgraber** [comment]
I think the problem is in LxdLog

**Comment by stgraber** [comment]
Fixed it. Sending my own pull request, taking this one over.

**Pull request closed without merging**
