### PR TITLE
Clean up index page

### PR DESCRIPTION
**Pull request by ru-fu**
This change will not work until we move the docs to Sphinx.

The idea is to move the content that is required in the repo (README.md and contributing.md) to the root folder instead of symlinking it (because the symlinks don't work reliably), and then pull the required content into the documentation. This makes it easier to ensure that we don't include MyST commands in these files, which wouldn't show up correctly in the GitHub rendering.

### CODE REVIEW

**Review by tomponline — COMMENTED** [review]
@ru-fu based on our discussion here https://github.com/lxc/lxd/issues/9665, this link on `README.md` to `security.md` will still be broken after the move to sphinx when viewed from github. (for some reason github won't let me comment on the specific line sorry).

**Comment by ru-fu** [comment]
> @ru-fu based on our discussion here #9665, this link on `README.md` to `security.md` will still be broken after the move to sphinx when viewed from github. (for some reason github won't let me comment on the specific line sorry).

Yep, I noticed, will fix this.
I think I just ignored it originally since it's no regression. ;)

**Comment by stgraber** [comment]
So I think that as part of that, we should probably move some more stuff around. I'd expect our top level files to be:
 - CONTRIBUTING.md
 - CODE_OF_CONDUCT.md (moved from .github/)
 - README.md
 - SECURITY.md (moved from .github/)
 - SUPPORT.md (moved from .github/)

As none of those are really Github-specific and would benefit from the extra visibility. Also the all-caps spelling is what we've seen as the most common pattern elsewhere.

All of those must be pure Markdown and render properly on Github. Their content can then be included as needed in the Sphinx doc.

**Comment by ru-fu** [comment]
Should we just move them for now and handle including them in the docs as a separate task?
Looking at SECURITY.md now and the security information in the docs, it'll take some time to figure out which information should go in the root folder, which in the docs, and which in both.

**Comment by ru-fu** [comment]
Moved the files now.

**Pull request merged**
