### PR TITLE
Do not show version command by default

### PR DESCRIPTION
**Pull request by techtonik**
Used only once in a lifetime, and easily discoverable

Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by tych0** [comment]
On Fri, Jul 01, 2016 at 02:16:49AM -0700, anatoly techtonik wrote:
> Used only once in a lifetime, and easily discoverable

I'm not sure I agree; isn't `lxc version` exactly the sort of thing
used by a beginner when they're trying to debug something? They may
not realize that there are hidden commands initially.

**Comment by techtonik** [comment]
> They may not realize that there are hidden commands initially.

That's pretty obvious:
```
Options:
  --all              Print less common commands.
```

**Comment by techtonik** [comment]
There is no sense to expose internal commands, obvious command or commands that are rarely used. For example, `hg` doesn't expose it:
```
$ hg
...
 update        update working directory (or switch revisions)

(use "hg help" for the full list of commands or "hg -v" for details)
```

**Comment by stgraber** [comment]
I'm not against hiding it from the commands but then I'd want to have "--version" listed in the argument list below (it's supported but not currently listed).

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by techtonik** [comment]
@stgraber do you understand why jenkins fails? I don't get it.

**Comment by stgraber** [comment]
You're adding a translated string but didn't run "make i18n" to update the translation template.

**Comment by techtonik** [comment]
I am on Windows without make, so I guess the sequence of command is this:
```
go get -v -x github.com/snapcore/snapd/i18n/xgettext-go/
xgettext-go -o po/lxd.pot --add-comments-tag=TRANSLATORS: --sort-output --package-name=lxd --msgid-bugs-address=lxc-devel@lists.linuxcontainers.org --keyword=i18n.G --keyword-plural=i18n.NG *.go shared/*.go lxc/*.go lxd/*.go
```

**Comment by techtonik** [comment]
`xgettext-go` hangs with `panic:` message in console.

**Comment by techtonik** [comment]
How do you debug go code?

**Comment by stgraber** [comment]
Cherry-picked your commits into my bugfix branch and added a i18n run on top. Closing this pull request.

**Pull request closed without merging**
