### PR TITLE
Add internal metrics

### PR DESCRIPTION
**Pull request by monstermunchkin**

### CODE REVIEW

**Comment by tomponline** [comment]
Let me know if you would like this reviewed.

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
@ru-fu where do you think these new metrics should go in the docs?

I was thinking https://linuxcontainers.org/lxd/docs/master/metrics/#provided-metrics but that page's title is "Instance metrics" and these are not instance metrics.

Maybe the page should be split out to show the general server metrics and the per-instance metrics?

**Comment by ru-fu** [comment]
> @ru-fu where do you think these new metrics should go in the docs?
> 
> I was thinking https://linuxcontainers.org/lxd/docs/master/metrics/#provided-metrics but that page's title is "Instance metrics" and these are not instance metrics.
> 
> Maybe the page should be split out to show the general server metrics and the per-instance metrics?

That page needs a cleanup anyway, since it's currently under API but we don't really describe the API.
For now, we could just rename the page to "Metrics" and add another list with the server metrics.

**Comment by tomponline** [comment]
Thanks @ru-fu makes sense, ok to add @monstermunchkin ?

**Pull request merged**
