### PR TITLE
Move all our API structs to shared/api

### PR DESCRIPTION
**Pull request by stgraber**
The goal here is to make writing the new client much easier and also reduce the amount of code duplication we've had between the server and our shared code.

With this branch merged, we won't have any json structs outside of shared/api (with the exception of the custom protobuf thing for migration).

All of the new code is also using consistent naming and has comments that can be used to generate godoc documentation: https://godoc.org/github.com/stgraber/lxd/shared/api

### CODE REVIEW

**Comment by brauner** [comment]
This makes me really happy in terms of code organization, however, in terms of `git rebase` for the storage branch I'm about to jump out the window. :)
Two builders went offline. I couldn't find anything exiting so I'll merge. :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Yeah, I had a clean run before, then did a few tweaks for godoc and buildd06 died during that try.
buildd06 is back online so re-testing now.

Rebasing branches and pushing this to stable-2.0 will certainly be interesting :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Just pushed another update, this time to make go lint happy with the generated documentation.

**Comment by stgraber** [comment]
@brauner I'm done with this one, feel free to hit merge.

**Pull request merged**
