### PR TITLE
images: Tar and compress in a combined stream when packing an image

### PR DESCRIPTION
**Pull request by joelhockey**
By doing tar and compress in a combined stream, we require
1 less copy of the tarred image, and save time for IO for
writing and reading that file.

In my tests with an image of about 1.4GB when compressed this
saves 2.6GB of space used by the tar file, and reduces total
export time from approx 4m40s to 4m10s (30s quicker).

Signed-off-by: Joel Hockey <joelhockey@chromium.org>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by joelhockey** [comment]
Currently when exporting a container, I call CreateImage to create an image from a container, then I call GetImage to download it.  Ideally I would like to have a single call that streams the image without ever persisting it.  Does something like that already exist?  If I was to send a patch, do you have suggestions on the best way for me to do this?  Should I modify CreateImage or GetImage to take an arg to specify to stream the image rather than persisting?  A new API?  And I guess it would be good to have something similar for importing an image to create a container that doesn't persist the image, but just streams the image into a newly created container.

**Comment by brauner** [comment]
@joelhockey, can you file a new issue for the new API/patch you're suggesting? I'll tag accordingly then. :)

**Comment by brauner** [comment]
I'm a fan of that patch. Not sure if @stgraber had a reason for splitting it into two parts but he can always just revert. :)

**Comment by stgraber** [comment]
@joelhockey what you're suggesting sounds much closer to our current export/import of containers for backups than what we normally associate with an image, so I suspect having some way of getting a backup out without it hitting disk/database would be the preferred approach here.

**Pull request merged**
