### PR TITLE
Fix Defer

### PR DESCRIPTION
**Pull request by gsquire**
This patch fixes a call to defer inside of a loop and instead uses an anonymous function to ensure proper behavior.

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@gsquire I believe your PR doesn't compile because the anonymous function you've added now contains return statements that do not match the function signature and you have `continue` statements that are not inside a loop.

I would suggest you update the anonymous function to take arguments for tplPath and tpl (so they are local to the function in case they are used in a defer in the future) and update the functions signature to return an error, which you can then test for errors in the loop. Thanks

**Comment by gsquire** [comment]
@tomponline Sorry about that. I don't have a Linux machine handy and I've been messing around with Docker to try and build it in an image. I _think_ this solves the problem though.

**Comment by tomponline** [comment]
@gsquire this still doesn't compile I'm afraid. The anonymous function is missing a return at the end and the function argument data types are incorrect.

We could also do with the same fix applied to these functions:

https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_lxc.go#L5121-L5197
https://github.com/lxc/lxd/blob/master/lxd/instance/drivers/driver_qemu.go#L1536-L1593

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
