### PR TITLE
lvm: resolve mount options properly

### LINKED ISSUE #3284: LVM storage driver doesn't convert some mount options into flags for try.Mount
Currently, LVM storage driver passes all options from volume.block.mount_options as is: https://github.com/lxc/lxd/blob/master/lxd/storage_lvm.go#L813
But as I was able to find out in btrfs storage driver, some options have to be converted to mount flags in a such way: https://github.com/lxc/lxd/blob/master/lxd/storage_btrfs.go#L28

In the result, you can't add any flag (eg, noatime) from this list: https://github.com/lxc/lxd/blob/master/lxd/storage_utils.go#L17 to volume.block.mount_options -- a container won't start afterwards.
It could be fixed by adding the same logic into LVM storage driver or, that looks better to me, to tryMount function.

### PR DESCRIPTION
**Pull request by brauner**
Closes #3284.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber, fyi this branch will likely result in merge conflicts with #3285.

**Comment by brauner** [comment]
Uh, jenkins forkstart failures are back on the table.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
