### PR TITLE
Add support to enable custom storage volume refreshment

### LINKED ISSUE #7873: Support refreshing custom storage volume copies
This is the same idea as `lxc copy --refresh` which allows updating an existing copy, both locally and remotely.
But this time, we want to do it for storage volumes, so at the `lxc storage volume copy` level.

The infrastructure should be identical and so require little to no changes at the storage package layer.
As the same migration structs are used for both instances and storage, that layer should also already be able to handle it.

So this is primarily an API, CLI and tiny bit of plumbing to get it to work (+ some tests).

### PR DESCRIPTION
**Pull request by zakufish**
Add support to refresh existing custom storage volume copies for storage volume copy operations.

Resolves #7873

Signed-off-by: Ricky Yu lijierickyyu@gmail.com

### CODE REVIEW

**Comment by zakufish** [comment]
Pending tests, which I am going to work on later. 

Please let me know if I also need to add the support to refresh custom storage volume for migration.

**Comment by stgraber** [comment]
Just did a quick rebase and re-shuffle the commit messages. Need to do a bit of testing now :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Hmm, the code doesn't actually build :)

**Comment by zakufish** [comment]
Yeh, realised I had a last minute uncommitted change. Just pushed and it should be good.

**Comment by zakufish** [comment]
@stgraber I've added the test. Although I am not sure if this is what you expected.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
I did some more cleanups of the commits, moving some code around and adding a couple of small missing things.
Structure now looks good, though the actual logic during the refresh doesn't look correct.

I think I'd have expected a function in `lxd/storage/backend_lxd.go` similar to the `RefreshInstance` we already have.

Rather than just deleting the volume if it already exists and putting a new one in its place, it should call that new `RefreshCustomVolume` when in a local copy case.

Then we also need to support it in the migration case where Refresh similarly needs to be passed through to the storage layer.

I'd recommend getting the local copy case sorted out first, so implementing a `RefreshCustomVolume` in the storage package and changing your logic to call that. Once that's done, we can sort out the bits needed for this to work remotely too.

**Comment by zakufish** [comment]
Hi @stgraber I've made a new commit to this PR, which contains the change that incorporates the new RefreshCustomVolumes method.

The implementation is as follows:

- When the source volume and the destination volume both present in the same storage pool, a same-pool mode will be activated, and the method will simply call the RefreshVolume function.
- When the two volumes are in two distinct storage pools, the LXD will first migrate the source volume from its original pool to the pool that destination volume resides in. This migration operation will create a volume with a `-tmp` postfix.
- After the first migration operation is completed, the LXD will proceed to refresh the destination volume using the newly created `tmp` volume.
- Eventually, the tmp volume will be purged.

Please let me know your thoughts on this :)

**Comment by tomponline** [comment]
Looks like this needs a rebase, and then `make i18n` commit re-run and updated.

**Review by tomponline — CHANGES_REQUESTED** [review]
Looks like this needs a rebase, and then make i18n commit re-run and updated.

**Comment by stgraber** [comment]
I'll handle the rebase and will do a few edits, then review it.

**Comment by zakufish** [comment]
Thanks @stgraber @tomponline just let me know if there's anything else I need to do for this PR.

**Comment by stgraber** [comment]
There seems to be some issues still:

```
root@vm01:~# lxc storage create zfs zfs
Storage pool zfs created
root@vm01:~# lxc storage volume create zfs foo
Storage volume foo created
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume copy zfs/foo zfs/bar
Storage volume copied successfully!
root@vm01:~# lxc storage volume delete zfs bar
Storage volume bar deleted
root@vm01:~# lxc storage volume copy zfs/foo zfs/bar
Storage volume copied successfully!
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume delete zfs foo/snap2
Storage volume foo/snap2 deleted
root@vm01:~# lxc storage volume delete zfs foo/snap3
Storage volume foo/snap3 deleted
root@vm01:~# lxc storage volume copy zfs/foo zfs/bar --refresh
Error: Failed to run: zfs mount zfs/custom/default_snap0: cannot open 'zfs/custom/default_snap0': dataset does not exist
root@vm01:~# 
```

**Comment by stgraber** [comment]
This test creates a volume with a bunch of snapshots, copying to make sure normal copies work and then doing a refresh which should delete some snapshots and add a few new ones.

**Comment by zakufish** [comment]
I tried the functionality with no snapshot volumes - everything seems to be working.
`root@localhost:~# ~/go/bin/lxc storage volume copy btrfs/foo btrfs/foo2 --refresh
Storage volume copied successfully!`

The error is probably related to the snapshot operations. Let me check.

**Comment by zakufish** [comment]
```
root@localhost:~# ~/go/bin/lxc storage volume snapshot btrfs foo
root@localhost:~# ~/go/bin/lxc storage volume snapshot btrfs foo
root@localhost:~# ~/go/bin/lxc storage volume snapshot btrfs foo
root@localhost:~# ~/go/bin/lxc storage volume copy btrfs/foo btrfs/foo3 --refresh
Error: Failed to run: btrfs subvolume snapshot /var/lib/lxd/storage-pools/btrfs/custom/default_foo3 /var/lib/lxd/storage-pools/btrfs/custom-snapshots/default_foo3: ERROR: cannot snapshot '/var/lib/lxd/storage-pools/btrfs/custom/default_foo3': File exists
root@localhost:~# ~/go/bin/lxc storage volume copy btrfs/foo btrfs/foo3 --refresh --volume-only
Storage volume copied successfully!
```

Another example where everything seems to be working once I apply the `--volume-only` flag.

**Comment by zakufish** [comment]
Hi @stgraber I am not sure what is going on here. I've made some minor adjustment to the code but the problem still persists.
Is it possible that this could be caused by the issue regarding RefreshVolume?

**Comment by zakufish** [comment]
Hi @stgraber 

I received the following messages when trying to run `lxc storage volume copy btrfs/foobar4 btrfs/foobar5 --refresh`:
```DBUG[07-27|15:17:22] Creating snapshot                        driver=btrfs pool=btrfs volName=default_foobar5/
DBUG[07-27|15:17:22] Failure for task operation: 9eb8e61b-0b02-491a-9414-0f61ebdc28de: Failed to run: btrfs subvolume snapshot /var/lib/lxd/storage-pools/btrfs/custom/default_foobar5 /var/lib/lxd/storage-pools/btrfs/custom-snapshots/default_foobar5: ERROR: cannot snapshot '/var/lib/lxd/storage-pools/btrfs/custom/default_foobar5': File exists```

This means the the error is thrown from the reference of the method `RefreshVolume`.

The log line: ` Creating snapshot driver=btrfs pool=btrfs volName=default_foobar5/` is actually from the method `genericVFSCopyVolume()`. I am wondering if the error could come from there.

**Comment by zakufish** [comment]
@stgraber I had another look, and couldn't figure out what is going on. I don't think I am referencing `RefreshVolume` in an incorrect way.

Do you mind having a look at this and point me a direction for further investigation?

**Comment by zakufish** [comment]
@stefanv I think I've figured out what's wrong. Seems like I was referencing the wrong snapshoht volume name.

```
root@localhost:~# ~/go/bin/lxc storage volume create lvm source
Storage volume source created
root@localhost:~# ~/go/bin/lxc storage volume create lvm dest
Storage volume dest created
root@localhost:~# ~/go/bin/lxc storage volume snapshot lvm source
root@localhost:~# ~/go/bin/lxc storage volume snapshot lvm source
root@localhost:~# ~/go/bin/lxc storage volume copy lvm/source lvm/dest --refresh
Storage volume copied successfully!
root@localhost:~# ~/go/bin/lxc storage volume copy lvm/source lvm/dest --refresh
Error: LVM snapshot volume already exists "default_dest/snap0"
```

Looks like it's working now. Please check.

**Comment by zakufish** [comment]
What is funny is that the snapshot volume for `dest` doesn't appear in the list, but the system somehow knows it exists...

**Comment by stefanv** [comment]
You probably meant to ping @stgraber

**Comment by zakufish** [comment]
Yeh that was my bad, sorry about that xD

**Comment by stgraber** [comment]
Bit of a crazy week here, it's next on my list, hoping to play with it this afternoon.

**Comment by stgraber** [comment]
Didn't have a lot of time to play with it, but the snapshot comparison logic still seems wrong even on what should be a simpler operation:

```
root@vm01:~# lxc storage create zfs zfs
root@vm01:~# lxc storage volume create zfs foo
Storage volume foo created
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume copy zfs/foo zfs/bar --refresh
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume snapshot zfs foo
root@vm01:~# lxc storage volume copy zfs/foo zfs/bar --refresh
Error: Failed to run: zfs snapshot zfs/custom/default_bar@snapshot-snap0: cannot create snapshot 'zfs/custom/default_bar@snapshot-snap0': dataset already exists
```

When we do this against an instance, what happens is:
 - Source and destination snapshot list is pulled
 - Snapshot names and timestamps are compared
 - Snapshots which don't match in name and timestamp on target are deleted
 - Missing snapshots are copied
 - Main volume is updated using rsync

The error I'm getting here suggests that the snapshot diff part isn't functioning properly as `snap0` wasn't modified and so shouldn't be transferred again. In this example, only snap2 and snap3 should have been transferred, followed by rsync for the main volume.

This test would then be followed by a more complex one, first validating that deleting a snapshot on the source results in it being deleted on the target, and if that works then do the real complex test where a snapshot is deleted on the source, then taken again using the same name, followed by a refresh operation (to confirm that the timestamps are compared) which should lead to the snapshot getting deleted on the target and then transferred again.

**Comment by zakufish** [comment]
Hi @stgraber 

That would make sense. Because at the moment,  I am just:
1. Gather a list of snapshots from the source volume.
2. Put them in `RefreshVolume` so they will be transferred to the dest nation volume.

Just to confirm, I need to have a snapshot comparison logic added to my code, which does:
1. Gather the list of snapshots from the source volume.
2. Gather the list of snapshots from the destination volume.
3. Compare whether both lists.
4. Avoid transferring the volume snapshots that are already transferred.

That would make a lot of sense. I originally thought `RefreshVolume` would take care of that for me.

**Comment by stgraber** [comment]
Hmm, actually you may be right for the same-pool copy case as in the instance case, so long as your srcSnapVols are correct, the copy seems to be working fine. I'll do a couple more checks now, first to confirm we don't have the same issue with instances and then to sort out why you're hitting a different code path somehow.

**Comment by stgraber** [comment]
Confirmed that the instance equivalent works properly, so going to be adding some debugging to see exactly what's being passed to RefreshVolume and what may make it unhappy.

**Comment by stgraber** [comment]
Using your branch, I'm getting:
```
src={name:default_foo pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:custom contentType:filesystem config:map[] driver:0xc000033d10 mountCustomPath: mountFilesystemProbe:false} 

snapshots=[
  {name:default_foo/snap0 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:custom contentType:filesystem config:map[] driver:0xc000033d10 mountCustomPath: mountFilesystemProbe:false}
  {name:default_foo/snap1 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:custom contentType:filesystem config:map[] driver:0xc000033d10 mountCustomPath: mountFilesystemProbe:false}
  {name:default_foo/snap2 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:custom contentType:filesystem config:map[] driver:0xc000033d10 mountCustomPath: mountFilesystemProbe:false
  {name:default_foo/snap3 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:custom contentType:filesystem config:map[] driver:0xc000033d10 mountCustomPath: mountFilesystemProbe:false}
]
```

Doing the same with an instance, I'm getting:
```
src={name:a1 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:containers contentType:filesystem config:map[] driver:0xc00024ceb0 mountCustomPath: mountFilesystemProbe:false} 

snapshots=[
  {name:a1/snap2 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:containers contentType:filesystem config:map[] driver:0xc00024ceb0 mountCustomPath: mountFilesystemProbe:false}
  {name:a1/snap3 pool:zfs poolConfig:map[size:9GB source:/var/snap/lxd/common/lxd/disks/zfs.img zfs.pool_name:zfs] volType:containers contentType:filesystem config:map[] driver:0xc00024ceb0 mountCustomPath: mountFilesystemProbe:false}
]
```

So this does seem to confirm that when `RefreshInstance` is called in the instance case, its `srcSnapshots` list only includes those snapshots that need to be copied. And indeed, if you dig into `instance.go`, you can see a list being built up there.

https://github.com/lxc/lxd/blob/master/lxd/instance.go#L251

In this case, we're going to need the logic in `lxd/storage_volumes.go` to perform the same kind of comparison, then delete anything that shouldn't be on the target volume and lastly call `RefreshCustomVolume` with the list of snapshots that need to be transferred.

**Comment by zakufish** [comment]
@stgraber Thanks for your help.

I'll get on this once right away later today.

**Comment by stgraber** [comment]
Thanks! Sorry it took me so long to dig into this deeper :)

**Comment by zakufish** [comment]
@stgraber That is no problem at all! It is totally understandable that sometimes things get a bit crazy at work :)

However, at the moment I am getting the list of snapshots inside the `RefreshCustomVolume` function. Do you reckon whether I could add the logic there instead?

**Comment by stgraber** [comment]
I think I'd prefer it be aligned in behavior with RefreshInstance, makes it easier to make changes and improvements to both later on.

**Comment by zakufish** [comment]
Make sense. I am on it.

**Comment by stgraber** [comment]
Thanks!

**Comment by zakufish** [comment]
Hi @stgraber sorry about the delay in delivery. I was quite busy at work last week.

**Comment by zakufish** [comment]
The code doesn't actually build. Please ignore my previous message - it's pretty late here in Sydney. I'll see if I can fix these issues tomorrow.

**Comment by zakufish** [comment]
Hi @stgraber sorry about the delay in delivery. I had a super busy week and only got sometime to continue working on this task just now. 

I gave your approach a stab, and turned out it's not as trivial as I thought. As a result of doing the volume comparison logic outside of the actual refresh function, I now have to try to convert `drivers` to `lxdBackend` in `storage_volumes` ; I also had to add the `db` package to `storage_volumes`, which causes weirdness of `Daemon` (seems to be a conflicting naming issue).

The code is becoming quite messy, and I have achieved a successful attempt. With these being said, I think calling the `utils` function for comparing overlapping storage volume snapshots inside `RefreshCustomVolumes` will be a neater approach.

Please let me know your thoughts on this.

**Comment by zakufish** [comment]
Okay, turned out Daemon has been failing in the branch build before I introduced these changes.
```
./storage_volumes.go:164:31: undefined: Daemon
./storage_volumes.go:362:35: undefined: Daemon
./storage_volumes.go:464:36: undefined: Daemon
./storage_volumes.go:557:31: undefined: Daemon
./storage_volumes.go:659:30: undefined: Daemon
./storage_volumes.go:744:32: undefined: Daemon
./storage_volumes.go:817:27: undefined: Daemon
./storage_volumes.go:938:31: undefined: Daemon
./storage_volumes.go:1116:41: undefined: Daemon
./storage_volumes.go:1148:39: undefined: Daemon
./storage_volumes.go:1148:39: too many errors
```

**Comment by zakufish** [comment]
Hi @stgraber , any suggestion?

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Fixed some issues with uninitialized variables in syncSnapshotsVolumeGet and with DB record handling when creating from migration with refresh enabled.

I'm now able to get refresh to behave between storage pools when adding snapshots, though snapshot removal on the source is somehow ignored. I'm also running into issues when the target volume has a name different from the source.

I'll try to find some more time later to look into those. The differing volume name issue should be pretty easy to track down. For the snapshot removal not occurring, I'll need to add some debugging to the logic doing the snapshot list delta to see what's going on.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Fixed a few issues with the snapshot diff function, fixed missing DB logic in a few places and did extensive testing copying within and across local pools. This seems to be working fine here now.

It's almost 2am so I'll stop here for now. Next step will be to deploy it on two LXD servers and then see how this all behave when refreshing a remote volume.

And lastly I'll want to validate the behavior with some actual data. So far all my testing is with a bunch of empty snapshots and me checking the DB records, FS layout and ZFS layout to make sure all the records look correct. But we'll want to make sure the data itself is also correct :)

**Comment by zakufish** [comment]
@stgraber Thank you for your help on this! Is there anything else I could do to help you test these features?

**Comment by stgraber** [comment]
Ok, so the remote case doesn't seem to be handled at all. I'll add the needed code to the client and see what happens on the server side.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Got the remote case working here. Next up will be a bit of local testing:

- [ ] Confirm snapshot add/remove (same-pool refresh)
- [ ] Confirm snapshot add/remove (cross-pool refresh)
- [ ] Confirm snapshot add/remove (cross-host refresh)
- [ ] Validate that main volume is updated (same-pool refresh)
- [ ] Validate that main volume is updated (cross-pool refresh)
- [ ] Validate that main volume is updated (cross-host refresh)
- [ ] Validate new snapshot contains expected content (same-pool refresh)
- [ ] Validate new snapshot contains expected content (cross-pool refresh)
- [ ] Validate new snapshot contains expected content (cross-host refresh)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@zakufish thanks for your work on this!
Sorry it ended up quite a bit harder than it first sounded!

**Comment by zakufish** [comment]
@stgraber no worries at all! It is a good learning experience for me ;)

**Pull request merged**
