### PR TITLE
Device: Relax `bridged` NIC duplicate instance DNS name checks

### PR DESCRIPTION
**Pull request by tomponline**
- Don't check if parent network has `dns.mode=none` as there cannot be conflicting DNS names in that case.
- Check the conflicting NIC instance is connected to same bridge VLAN.

### CODE REVIEW

**Review by monstermunchkin — APPROVED** [review]

**Comment by stgraber** [comment]
@tomponline can you give this a quick rebase?
Looks like we both did the same i18n update :)

**Comment by tomponline** [comment]
@stgraber done

**Comment by StyXman** [comment]
Any way to know when is this going to be ported to LTS? Or did I misunderstood and this will not make it there?

**Comment by tomponline** [comment]
I believe this will be in LXD 5.0.2 cc @stgraber

**Pull request merged**
