### PR TITLE
Ouputs errors on server side error

### PR DESCRIPTION
**Pull request by jensg-st**
Signed-off-by: Jens Gerke <jens.gerke@sisa-tech.com>

### CODE REVIEW

**Comment by jensg-st** [comment]
Just found out that error messages are not shown, if there is an error on server and the "sub-method" does not do a ParseError. Adding it to ParseResponse should fix that. Last pull request for the weekend. Last pull request for the weekend.

**Comment by tych0** [comment]
I think we don't want to do this; in some cases we want to inspect the Error type response (e.g. to get the error code). We could add a helper that does both (and probably should) and call that where we want to do both, since it may be missing in a few places.

**Comment by jensg-st** [comment]
Ok. Just thought it would be nice to see the server errors on the CLI. At the moment most of the commands fail silently. Thanks for clarifying. Just ditch the pull request.

**Comment by tych0** [comment]
We definitely do want to see errors, I just don't think this is the right
place to expose them. Can you she'd some light on which commands fail
silently?

**Comment by jensg-st** [comment]
Basically all commands, which return with ParseResponse in client.go. I thought, that is what you mean. There should be a consistent way, what to do at the end of each command. If you have a look at the client.go, you will see, that each commands handles it differently. Some do a ParseError at the end, some don't. I just noticed it with image delete and I did something inconsistent as well (guilty as charged) when I did the image export. I do the ParseError now in the func. 

Need to go now, but I can write something up, when I'm back. Maybe it doesn't make sense to you what I have just said. :)

**Comment by jensg-st** [comment]
Had a look again. It seems that all other methods, at least in the 'image' part, are running their response through ParseError, if required. Except the 'delete' statements. Running a delete on an non-existing alias or image for example, returns no error at all. I think you can close this pull request, but I think the delete statements need to run ParseError as well.

**Comment by tych0** [comment]
On Mon, Mar 16, 2015 at 01:35:53AM -0700, Jens Gerke wrote:
> Had a look again. It seems that all other methods, at least in the 'image' part, are running their response through ParseError, if required. Except the 'delete' statements. Running a delete on an non-existing alias or image for example, returns no error at all. I think you can close this pull request, but I think the delete statements need to run ParseError as well.

Ok, thanks. I'll leave it open and try and push a fix today.

**Pull request closed without merging**
