### PR TITLE
lxd/db: Fix container/profile updates

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by freeekanayaka** [comment]
This PR fixes a bug but there's no issue linked to it. Please can you attach a description of the problem?

Also, it'd be good to have a test reproducing the issue and proving that the branch fixes it.

**Comment by stgraber** [comment]
Problem was when you have a container in another project which inherits profiles from the default project.

A change to the profile would trigger an update of all containers but that update code was assuming that all containers were in the same project as the profile being changed. This is obviously not true and so needed to return a map with a list of containers per affected project instead.

**Comment by stgraber** [comment]
The other one is about some cases where setting "" doesn't clear the key.

**Comment by freeekanayaka** [comment]
@stgraber : I see. It seems adding a test should be doable?

**Pull request merged**
