### PR TITLE
misc(rest-api.md): formatting

### PR DESCRIPTION
**Pull request by mkg20001**
Fixed formatting by adding spaces to lines starting with "*" (as that's more commonly used than without) and also fixed header for one `PUT` heading

### CODE REVIEW

**Comment by mkg20001** [comment]
If you're wondering why I'm so nitpicky about formatting: I've written a LXD client that uses this doc to generate an API https://github.com/mkg20001/lxdn

**Comment by stgraber** [comment]
@mkg20001 Hi, all commits going into LXD must be signed off with a `Signed-off-by: Firstname Lastname <email>` line in the commit message.

Can you please update your commit to match that (see CONTRIBUTING.md too)?

**Comment by mkg20001** [comment]
@stgraber Done

**Comment by stgraber** [comment]
Oops, looks like Jenkins is picky and expects:

`Signed-off-by: Maciej Krüger <mkg20001@gmail.com>`
and not
`Signed-Off-By: Maciej Krüger <mkg20001@gmail.com>`

Note that you can normally have `git` do that for you by using the `-s` argument to `git commit`.

**Comment by mkg20001** [comment]
Done

**Comment by stgraber** [comment]
Thanks!

**Comment by mkg20001** [comment]
Actually I already corrected that but forgot to add `-f` to the push and noticed only after I've written the comment :sweat_smile:

**Pull request merged**
