### PR TITLE
Add --target-project to lxc image copy

### LINKED ISSUE #10009: Add --target-project to lxc image copy
**LXD v. 4.23**
Lxc image copy takes a --project flag which overrides the source project, though actions only within a project. 
Copying an image across projects needs an additional flag  --target-project.

### PR DESCRIPTION
**Pull request by presztak**
Closes #10009

### CODE REVIEW

**Review by monstermunchkin — CHANGES_REQUESTED** [review]
Looks good overall. Could you please add some tests?

**Review by tomponline — APPROVED** [review]

**Comment by presztak** [comment]
I've added some tests.

**Comment by monstermunchkin** [comment]
jenkins: test this please

**Review by monstermunchkin — APPROVED** [review]

**Review by tomponline — APPROVED** [review]
LGTM, thanks!

But the translations need to be updated.

**Comment by presztak** [comment]
Translations updated.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Thanks!

**Pull request merged**
