### PR TITLE
lxd/storage/drivers/btrfs: Fix quota

### PR DESCRIPTION
**Pull request by monstermunchkin**
This adds the `--raw` flags to `btrfs qgroup show`. The flag is needed
as the sizes in the output are listed with suffixes (KiB, MiB, etc.).
Since `ParseInt` cannot deal with that, it fails and returns -1. Adding
the `--raw` flag removes all suffixes, and returns the correct usage.

Signed-off-by: Thomas Hipp <thomas.hipp@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@monstermunchkin thanks, how did this issue manifest itself? I'm wondering if we should add a test to check it doesn't regress in the future?

**Comment by monstermunchkin** [comment]
When manually testing #7071, I noticed that the usage didn't work for containers either which was odd. I'll look into adding tests.

**Comment by tomponline** [comment]
@monstermunchkin ah yes usage would make sense why it wasn't picked up before. Thanks

**Comment by monstermunchkin** [comment]
@tomponline I added the tests.

**Comment by tomponline** [comment]
Cheers @monstermunchkin, I wonder if you could add them to the existing quota related tests though, there's already some driver specific exceptions such as https://github.com/lxc/lxd/blob/master/test/suites/storage.sh#L787-L794 and https://github.com/lxc/lxd/blob/master/test/suites/storage.sh#L810-L816, it might be a good place to slip in the additional tests. As the other drivers (with the exception of ceph) don't have their own tests as such.

**Comment by monstermunchkin** [comment]
@tomponline done.

**Comment by tomponline** [comment]
@monstermunchkin great thanks, I'll let @stgraber cast his eye over this with regards to the test structure (in terms of whether this is where he wants it to go).

**Comment by stgraber** [comment]
@monstermunchkin tests failed on btrfs

**Pull request merged**
