### PR TITLE
VM: Only attempt to open NVRAM file on UEFI architectures

### LINKED ISSUE #10275: unable to launch VM with LXD 5.0.0-69602b2 on s390x
Hello,
with LXD 5.0.0-69602b2 I am no longer able to launch LXD VMs and get this error message:
$ sudo lxc launch ubuntu-daily:22.04 ubu-vm-11 --vm
Creating ubu-vm-11
Starting ubu-vm-11                        
Error: Failed opening NVRAM file: open /var/snap/lxd/common/lxd/virtual-machines/ubu-vm-11/qemu.nvram: no such file or directory
Try `lxc info --show-log local:ubu-vm-11` for more info
(might be related/same as https://github.com/lxc/lxd/pull/10262, but I was asked to open a new issue)

'lxc list' shows me a stopped machine:
 lxc list
+-----------+---------+------+------+-----------------+-----------+
|   NAME    |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+-----------+---------+------+------+-----------------+-----------+
| ubu-vm-11 | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+-----------+---------+------+------+-----------------+-----------+

There is indeed no qemu.nvram file:
$ sudo ls -l /var/snap/lxd/common/lxd/virtual-machines/ubu-vm-10/total 1321760
-rw-r--r-- 1 root root         700 Apr 19 10:34 agent-client.crt
-rw------- 1 root root         288 Apr 19 10:34 agent-client.key
-rw-r--r-- 1 root root         733 Apr 19 10:34 agent.crt
-rw------- 1 root root         288 Apr 19 10:34 agent.key
-r-------- 1 root root        1901 Apr 19 10:34 backup.yaml
dr-x------ 6 root root        4096 Apr 19 10:34 config
-rw-r--r-- 1 root root         293 Apr 14 02:27 metadata.yaml
-rw-r--r-- 1 root root 10737418240 Apr 19 10:34 root.img
drwxr-xr-x 2 root root        4096 Apr 14 02:27 templates

And there are also no further logs available:
$ lxc info --show-log local:ubu-vm-11
Name: ubu-vm-11
Status: STOPPED
Type: virtual-machine
Architecture: s390x
Created: 2022/04/19 10:39 UTC
Error: open /var/snap/lxd/common/lxd/logs/ubu-vm-11/qemu.log: no such file or directory

Btw the last version I tried was 5.0.0-c5bcb80 (just a few days ago, on April 5th or so) which worked fine, so looks like a regression?!

Please note that I experienced this on s390x, but looks like it's independent of the underlying architecture.
__________

Additional info:

Ubuntu Jammy (release candidate 2022 04 18.2) is used.

ubuntu@s1lp15:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
ubuntu@s1lp15:~$ uname -a
Linux s1lp15 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:59 UTC 2022 s390x s390x s390x GNU/Linux
ubuntu@s1lp15:~$ arch 
s390x
ubuntu@s1lp15:~$ snap list lxd
Name  Version        Rev    Tracking      Publisher   Notes
lxd   5.0.0-69602b2  22912  5.0/stable/…  canonical✓  -
ubuntu@s1lp15:~$ snap info lxd
name:      lxd
summary:   LXD - container and VM manager
publisher: Canonical✓
store-url: https://snapcraft.io/lxd
contact:   https://github.com/lxc/lxd/issues
license:   unset
description: |
  LXD is a system container and virtual machine manager.
  
  It offers a simple CLI and REST API to manage local or remote instances,
  uses an image based workflow and support for a variety of advanced
  features.
  
  Images are available for all Ubuntu releases and architectures as well
  as for a wide number of other Linux distributions. Existing
  integrations with many deployment and operation tools, makes it work
  just like a public cloud, except everything is under your control.
  
  LXD containers are lightweight, secure by default and a great
  alternative to virtual machines when running Linux on Linux.
  
  LXD virtual machines are modern and secure, using UEFI and secure-boot
  by default and a great choice when a different kernel or operating
  system is needed.
  
  With clustering, up to 50 LXD servers can be easily joined and managed
  together with the same tools and APIs and without needing any external
  dependencies.
  
  
  Supported configuration options for the snap (snap set lxd
  [<key>=<value>...]):
  
    - ceph.builtin: Use snap-specific Ceph configuration [default=false]
    - ceph.external: Use the system's ceph tools (ignores ceph.builtin)
    [default=false]
    - criu.enable: Enable experimental live-migration support [default=false]
    - daemon.debug: Increase logging to debug level [default=false]
    - daemon.group: Set group of users that have full control over LXD
    [default=lxd]
    - daemon.user.group: Set group of users that have restricted LXD access
    [default=lxd]
    - daemon.preseed: Pass a YAML configuration to `lxd init` on initial
    start
    - daemon.syslog: Send LXD log events to syslog [default=false]
    - lvm.external: Use the system's LVM tools [default=false]
    - lxcfs.pidfd: Start per-container process tracking [default=false]
    - lxcfs.loadavg: Start tracking per-container load average
    [default=false]
    - lxcfs.cfs: Consider CPU shares for CPU usage [default=false]
    - openvswitch.builtin: Run a snap-specific OVS daemon [default=false]
    - ovn.builtin: Use snap-specific OVN configuration [default=false]
    - shiftfs.enable: Enable shiftfs support [default=auto]
  
  For system-wide configuration of the CLI, place your configuration in
  /var/snap/lxd/common/global-conf/ (config.yml and servercerts)
commands:
  - lxd.benchmark
  - lxd.buginfo
  - lxd.check-kernel
  - lxd.lxc
  - lxd.lxc-to-lxd
  - lxd
  - lxd.migrate
services:
  lxd.activate:    oneshot, enabled, inactive
  lxd.daemon:      simple, enabled, active
  lxd.user-daemon: simple, enabled, inactive
snap-id:      J60k4JY0HppjwOjW8dZdYc8obXKxujRu
tracking:     5.0/stable/ubuntu-22.04
refresh-date: today at 10:30 UTC
channels:
  latest/stable:    5.0.0-69602b2 2022-04-19 (22912) 74MB -
  latest/candidate: 5.0.0-69602b2 2022-04-15 (22912) 74MB -
  latest/beta:      ↑                                     
  latest/edge:      git-74496dc   2022-04-16 (22917) 74MB -
  5.0/stable:       5.0.0-69602b2 2022-04-19 (22912) 74MB -
  5.0/candidate:    5.0.0-69602b2 2022-04-16 (22912) 74MB -
  5.0/beta:         ↑                                     
  5.0/edge:         ↑                                     
  4.24/stable:      4.24-c92c0b2  2022-04-01 (22756) 72MB -
  4.24/candidate:   4.24-c92c0b2  2022-04-01 (22756) 72MB -
  4.24/beta:        ↑                                     
  4.24/edge:        ↑                                     
  4.0/stable:       4.0.9-8e2046b 2022-03-26 (22755) 61MB -
  4.0/candidate:    4.0.9-8e2046b 2022-03-24 (22755) 61MB -
  4.0/beta:         ↑                                     
  4.0/edge:         git-407205d   2022-03-31 (22799) 63MB -
  3.0/stable:       3.0.4         2019-10-10 (11354) 52MB -
  3.0/candidate:    3.0.4         2019-10-10 (11354) 52MB -
  3.0/beta:         ↑                                     
  3.0/edge:         git-81b81b9   2019-10-10 (11366) 52MB -
installed:          5.0.0-69602b2            (22912) 74MB -
ubuntu@s1lp15:~$ 

# Steps to reproduce

Updated LXD to latest available version before I started to test:
$ sudo snap refresh lxd

LXD was initialized with:
$ sudo lxd init --auto --storage-backend dir

Then just tried to launch a VM:
$ sudo lxc launch ubuntu-daily:22.04 ubu-vm-11 --vm

# Information to attach

 - [ ] Any relevant kernel output (`dmesg`)
 https://pastebin.canonical.com/p/6wWBWwjSK9/
 - [ ] Container log (`lxc info NAME --show-log`)
$ lxc info ubu-vm-11 --show-log
Name: ubu-vm-11
Status: STOPPED
Type: virtual-machine
Architecture: s390x
Created: 2022/04/19 10:39 UTC
Error: open /var/snap/lxd/common/lxd/logs/ubu-vm-11/qemu.log: no such file or directory
 - [ ] Container configuration (`lxc config show NAME --expanded`)
$ lxc config show ubu-vm-11 --expanded
architecture: s390x
config:
  image.architecture: s390x
  image.description: ubuntu 22.04 LTS s390x (daily) (20220414)
  image.label: daily
  image.os: ubuntu
  image.release: jammy
  image.serial: "20220414"
  image.type: disk1.img
  image.version: "22.04"
  volatile.base_image: d30fb2c08b664365250e4019f19a08d9ade1e06dc6aca8ada9a968b3f6509fd8
  volatile.cloud-init.instance-id: b81e07f0-681e-4d14-8a4c-9a8cbd23babb
  volatile.eth0.hwaddr: 00:16:3e:b2:62:bf
  volatile.uuid: 42bbc2e0-35e8-43c2-bd0b-47757dbbbd6c
  volatile.vsock_id: "6"
devices:
  eth0:
    name: eth0
    network: lxdbr0
    type: nic
  root:
    path: /
    pool: default
    type: disk
ephemeral: false
profiles:
- default
stateful: false
description: ""
ubuntu@s1lp15:~$ 
 - [ ] Main daemon log (at /var/log/lxd/lxd.log or /var/snap/lxd/common/lxd/logs/lxd.log)
 https://pastebin.canonical.com/p/phrCJNh8F6/
 - [ ] Output of the client with --debug
 https://pastebin.canonical.com/p/yh98cSnYXw/
 - [ ] Output of the daemon with --debug (alternatively output of `lxc monitor` while reproducing the issue)

### PR DESCRIPTION
**Pull request by tomponline**
Fixes #10275

Fixes regression caused by https://github.com/lxc/lxd/pull/10262

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber do we still have access to the s390x system I can test this on?

**Comment by stgraber** [comment]
Try 10.245.238.3 over company VPN.

**Comment by stgraber** [comment]
The firmware section has an architecture filter in the template, we need to make sure this is kept in sync with any Go code.

**Comment by tomponline** [comment]
> The firmware section has an architecture filter in the template, we need to make sure this is kept in sync with any Go code.

I think we should actually just take that out of the template, and ensure LXD only activates that template when appropriate, what do you think?

I'm not a fan of the pattern of calling a function that does nothing in certain circumstances (like `setupNvram` as it makes it easy to miss dependencies like this).

**Comment by tomponline** [comment]
@stgraber have refactored it based on your comments.

**Comment by tomponline** [comment]
> 

Thanks, I'm in, will build LXD and test.

**Comment by tomponline** [comment]
@stgraber tested working on s390x.

**Pull request merged**
