### PR TITLE
Implement built-in pprof server

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
@brauner should be good to go

**Comment by stgraber** [comment]
Actually, there's a bug in this branch, looking at it now.

**Comment by stgraber** [comment]
Fixed

**Comment by brauner** [comment]
That's still a lot of failures. Triggering a new build.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner happier now

**Comment by stgraber** [comment]
@brauner should be green enough (considering I only fixed documentation)

**Pull request merged**
