### PR TITLE
shared: export limit parsing function

### PR DESCRIPTION
**Pull request by tych0**
For other golang clients who want to figure out the memory from a LXD limit
in string format from the config, this is useful.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Maybe do the same with the matching Bits function?

**Comment by stgraber** [comment]
We don't export anything in bits yet but that's mostly because I can't figure out instant network usage more than a design decision :)

**Comment by tych0** [comment]
Sure, I'll make the change.

**Comment by tych0** [comment]
Oh, but then my function name doesn't really make sense :). Will resolve.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
