### PR TITLE
Storage volumes snapshots table

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Just wondering, what's the design decision for having `storage_volumes_all` + triggers in place to have `id` unique between `storage_volumes` and `storage_volumes_snapshots` rather than having the functions accessing that data know to look in one or the other (as I believe is done for instances)?

**Comment by freeekanayaka** [comment]
> Just wondering, what's the design decision for having `storage_volumes_all` + triggers in place to have `id` unique between `storage_volumes` and `storage_volumes_snapshots` rather than having the functions accessing that data know to look in one or the other (as I believe is done for instances)?

As mentioned in the 1-1, this is not ideal and it was mainly done for getting the data correctly split in the SQL model and minimize the amount of code changes needed. I started without the ```storage_volumes_all`` view at first but was falling into a rabbit hole. I think we can change the code in a second step, probably after some of the storage-related changes you mentioned have landed.

**Comment by stgraber** [comment]
This is good to go but I want to see if #6898 is going to need a DB patch before we merge this.

**Pull request merged**
