### PR TITLE
“your first time using LXD” is confusing

### PR DESCRIPTION
**Pull request by m4sk1n**

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
This needs a "make i18n" and subsequent commit to update the translation templates. I can do it and then merge this.

**Comment by m4sk1n** [comment]
@stgraber can you do this, please?

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Branch updated, just waiting for Jenkins to confirm it's happy.

**Pull request merged**
