### PR TITLE
config: set it in daemonConfig before calling the setters

### PR DESCRIPTION
**Pull request by tych0**
some setters inspect this value, let's set it in daemonConfig so they don't
screw up.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
So two problems:
 - This is wrong as it no longer lets a setter override the value, as can be seen by the test failure due to now missing password hashing.
 - This introduces a race during which the new value is present in configuration but may be reverted due to failure to actually apply.

**Comment by tych0** [comment]
On Wed, Apr 27, 2016 at 10:10:32AM -0700, Stéphane Graber wrote:
> So two problems:
>  - This is wrong as it no longer lets a setter override the value, as can be seen by the test failure due to now missing password hashing.
>  - This introduces a race during which the new value is present in configuration but may be reverted due to failure to actually apply.

So then I guess we have to go through and fix all the individual uses
of daemonConfig? That seems... ugly :). Ideally we'd be able to not be
in an incorrect state ever, but I'm not really sure how to do that.

**Comment by stgraber** [comment]
The former should be easy enough to fix, though at the cost of locking and modifying daemonConfig twice.

The second issue is a bit trickier. I don't think it's a good thing to always alter daemonConfig prior to the setter function having been called but looks like it'd be pretty difficult to fix this for storage, so I'd probably recommend we do the temporary update of daemonConfig inside daemonConfigSetStorage rather than for all the keys.

**Comment by stgraber** [comment]
@tych0 https://github.com/stgraber/lxd/commit/92063e973fccce02cbced6a3d39591d87f14efd4

**Comment by tych0** [comment]
closing in favor of https://github.com/lxc/lxd/pull/1955

**Pull request closed without merging**
