### PR TITLE
specs: Add details about the default profile

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by BarthV** [comment]
So it means that we'll able too choose profile at spawn / launch time ?

**Comment by stgraber** [comment]
Currently the list of profiles is set at container creation time, so that's "POST /1.0/containers" using the API which in the client maps to "lxc launch" and "lxc init".

It's certainly possible that we'll allow a temporary override of the profiles list in start too so "PUT /1.0/containers/\<name\>/state" using the API which in the client maps to "lxc start".

**Comment by tych0** [comment]
On Mon, Mar 09, 2015 at 01:33:08PM -0700, St�phane Graber wrote:
> Currently the list of profiles is set at container creation time, so that's "POST /1.0/containers" using the API which in the client maps to "lxc launch" and "lxc init".

Right now I don't think it respects this (you can only set it via
PUT), but I'm making it respect the initial profiles piece on
container create because we need that for migration :)

**Comment by hallyn** [comment]
On Mon, Mar 09, 2015 at 01:33:09PM -0700, St�phane Graber wrote:
> Currently the list of profiles is set at container creation time, so that's "POST /1.0/containers" using the API which in the client maps to "lxc launch" and "lxc init".

Not true;  'lxc config profile apply container onenic,unconfined' works just fine

**Comment by stgraber** [comment]
Ah yeah, sure. I was treating the question by thinking of the one-off override case (override the profiles list at startup time, in a non-persistent way).

**Pull request merged**
