### PR TITLE
Fix total memory for per NUMA node

### PR DESCRIPTION
**Pull request by nicolasbock**
This change applies the same change as

375ce45456e9f0789a48541704014a1695896a0f

To the per NUMA node total memory calculation.

Signed-off-by: Nicolas Bock <nicolas.bock@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Had to perform a few minor changes to deal with `memoryXYZ` being a symlink rather than a directory and make the original code in this PR to actually build, seems to be behaving as expected here now.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by nicolasbock** [comment]
Thanks @stgraber !

**Comment by LaurentDumont** [comment]
Thank you for this, it seems it's leveraged by MaaS and it make the reported memory inconsistent with numas.

**Pull request merged**
