### PR TITLE
[TEST] Add hook for leadership changes

### PR DESCRIPTION
**Pull request by freeekanayaka**
Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Neat, thanks!

@tomponline want to send a branch which uses this new ability? We should define a handler and if we just became the leader, then log an Info entry and immediately trigger a round of heartbeat.

This will replace the logic we currently have in the heartbeat task to detect an initial round and so should similarly do the two passes and without being spread over time.

So effectively same logic we have right now but without risking the 10s delay.

**Comment by tomponline** [comment]
@stgraber will do.

@freeekanayaka is there a way to detect the dqlite library being used has this feature?

**Comment by freeekanayaka** [comment]
@tomponline if lxd builds at all, the underlying libdqlite has it :)

For now I think we don't need to feature detect this, as we'll bundle dqlite updates with our LXD releases.

**Comment by tomponline** [comment]
@freeekanayaka I see, we bundle them, got it, thanks.

**Comment by freeekanayaka** [comment]
From Jenkins:

```
INFO[07-15|08:39:40] Elected as leader 
```

So this seems to work as expected and @tomponline should be able to use it right away. Closing this PR for now.

**Pull request closed without merging**
