### PR TITLE
fsmonitor: fixes

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <brauner@kernel.org>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
Is it worth replacing other calks in lxd to syscall.CloseOnExec too (if any) is there any difference?

**Comment by stgraber** [comment]
Unlikely to be any difference though `syscall` is usually considered to be legacy with `unix` being preferred when it offer what we want.

**Comment by stgraber** [comment]
Doing a quick grep, only fsmonitor currently uses syscall.CloseOnExec (and this PR will fix that one), the other occurence is in util/http and already uses unix.CloseOnExec

**Comment by brauner** [comment]
What I'm still fuzzy about is `4` fds that each container that is started closes:
```
lxc imp1 20220110170207.475 ERROR    start - start.c:lxc_check_inherited:331 - Success - AAAA: anon_inode:[eventpoll]
lxc imp1 20220110170207.475 INFO     start - start.c:lxc_check_inherited:337 - Closed inherited fd 4
lxc imp1 20220110170207.475 ERROR    start - start.c:lxc_check_inherited:331 - Success - AAAA: pipe:[1512989]
lxc imp1 20220110170207.475 INFO     start - start.c:lxc_check_inherited:337 - Closed inherited fd 5
lxc imp1 20220110170207.475 ERROR    start - start.c:lxc_check_inherited:331 - Success - AAAA: pipe:[1512989]
lxc imp1 20220110170207.475 INFO     start - start.c:lxc_check_inherited:337 - Closed inherited fd 6
lxc imp1 20220110170207.475 ERROR    start - start.c:lxc_check_inherited:331 - Success - AAAA: socket:[1512267]
lxc imp1 20220110170207.475 INFO     start - start.c:lxc_check_inherited:337 - Closed inherited fd 14
```
I have no idea where that `eventpoll` fd for example is supposed to come from. Unless it is a leak from a dependency we link against.

**Comment by tomponline** [comment]
From what I can see in my tests they exist in even a minimal go program that just imports time and fmt packages.

**Pull request merged**
