### PR TITLE
Docs: Update build instructions

### PR DESCRIPTION
**Pull request by tomponline**

### CODE REVIEW

**Comment by stgraber** [comment]
The memory requirement feels like a good fit for doc/requirements.md

**Comment by tomponline** [comment]
> The memory requirement feels like a good fit for doc/requirements.md

Yep will add there too, are you happy to leave it here so that new users building this don't get caught out building it (the error itself doesn't immediately indicate a memory issue, but rather a Go linker problem).

**Comment by stgraber** [comment]
Yeah, I think it's fine to duplicate it

**Comment by tomponline** [comment]
@stgraber updated

**Pull request merged**
