### PR TITLE
Support zstd compression.

### PR DESCRIPTION
**Pull request by likema**

### CODE REVIEW

**Comment by stgraber** [comment]
Hi, all commits must be signed off before we can review them.

You can usually do this with: git commit -s --amend && git push --force

Or by manually editing your commit to include the `Signed-off-by: Firstname Lastname <email>` line.

**Comment by likema** [comment]
> Hi, all commits must be signed off before we can review them.
> 
> You can usually do this with: git commit -s --amend && git push --force
> 
> Or by manually editing your commit to include the `Signed-off-by: Firstname Lastname <email>` line.

Done

**Comment by stgraber** [comment]
Great, thank you, that looks good!

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by likema** [comment]
> Great, thank you, that looks good!

BTW, `zstd` has not been included in **lxd 4.8** , which is installed by snap.

**Comment by stgraber** [comment]
I just pushed a commit to add zstd to the snap. For now in an upcoming build of latest/edge and then will make it to candidate/stable when the LXD commit makes it there too.

**Comment by likema** [comment]
> I just pushed a commit to add zstd to the snap. For now in an upcoming build of latest/edge and then will make it to candidate/stable when the LXD commit makes it there too.

Thanks

**Comment by likema** [comment]
> I just pushed a commit to add zstd to the snap. For now in an upcoming build of latest/edge and then will make it to candidate/stable when the LXD commit makes it there too.

@stgraber The version of `zstd` that is added into `LXD 4.9` is ony `1.3.3`

```bash
/snap/lxd/18772/bin/zstd --version

*** zstd command line interface 64-bits v1.3.3, by Yann Collet ***
```

which compression speed and ratio are less than the latest stable release `1.4.5`

**Comment by stgraber** [comment]
That will improve once the snap is built from a core20 base instead of core18. So in a few months most likely.

**Pull request merged**
