### PR TITLE
Regex for image list filters

### PR DESCRIPTION
**Pull request by jseguillon**
Proposal : regex on lxc image filter. Example with images.linuxcontainers.org : 
- before : 
lxc image list images: description=Ubuntu => no results
- after : 
lxc image list images: description=Ubuntu 
OR
lxc image list images: description='Ubu.*'
==> all ubuntus images 

Used a regex test and falling back to old test to ensure it won't fail. 

Let me know if it sounds good for you. 

Signed-off-by: Joel Seguillon <joel.seguillon@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Seems reasonable, though you probably also want to do the same thing for "lxc list" then as the code is very similar for both.

**Comment by jseguillon** [comment]
Job done for lxc list. With this patch : lxc list user.blah=bl replies lxc container with defined config user.blah: blah

Let know if some more code should be added.

**Comment by stgraber** [comment]
hmm, seems like I'd expect "user.blah=bl" to only be interpreted as "^bl$" so not return "blah" and instead require "user.blah=bl.*" if you wanted to get blah in your result set.

**Comment by jseguillon** [comment]
Yep that sounds good to me. I think i could do this : 

Solution 1 :
-  test if ^ is not in filter => add it at beginning of regexp

- test if $ is not in filter => add it at end of filter 

Solution 2: 

- test if nor $ nor ^ is in regexp => add both

Solution 2 may lead to more flexible regexp. Do you have an opinion ?

**Comment by stgraber** [comment]
I'd be happy with solution 2

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks like your branch needs rebasing too

**Comment by jseguillon** [comment]
Job Done. Now  : 

- lxc list user.blah=bl  => does not respond, lxc list user.blah=blah => responds and lxc list user.blah=bl.* => responds

- lxc image list description=Ubuntu => does not respond, lxc image list description=Ubutun.* => responds

Rebased on master. Let me know if more improvement should be done.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Please run "go fmt ./..." and update your branch, thanks!

**Comment by jseguillon** [comment]
fmt done. may be good to add this in contrib guide so you don't loose your time asking for this.  I can open trivial issue to trace this if you're ok.

for the PR itself, i stay tuned for any comments

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
