### PR TITLE
Storage: BTRFS subvolume migration support

### PR DESCRIPTION
**Pull request by tomponline**
Adds support for migrating BTRFS containers that have subvolumes.

WIP.

### CODE REVIEW

**Comment by stgraber** [comment]
Wow, 3 full pass from Jenkins in a row? That's got to be some kind of record.

**Comment by tomponline** [comment]
@stgraber I know! Its quite the turn up.

I've gone with the approach of sending each individual subvolume using a separate iteration of `btrfs send` and `btrfs receive` for now as this allows me to receive, create and then move the subvolume on the target before receiving the next one. This way it avoids any conflicts with the received volume's name (as it takes the last part of the subvolume path as the volume name to receive to).

I thought about modifying `snapshotSubvolume()` to create random snapshots of sub-sub volumes in the root, however there are other uses of `snapshotSubvolume()` that depend on them being created in the right place in the snapshotted tree, and didn't want to duplicate the logic just for migration.

I also think it will allow us to be more flexible with specifying the `parent` option on the `btrfs send` side when sending differentials of sub-sub volumes as each iteration can then specify the correct parent, i.e the parent is the sub-sub volume snapshot not the snapshot of the root volume.

**Comment by stgraber** [comment]
Yeah, approach is fine

**Comment by tomponline** [comment]
@stgraber I've got this working now with snapshots (including subvolumes) and with differential based on those snapshotted subvolumes. It restores readonly status for subvolumes as well.

**Pull request merged**
