### PR TITLE
Net bridge documentation

### PR DESCRIPTION
**Pull request by danielrobbins**
Trying to flesh out the Network documentation a bit.

### CODE REVIEW

**Comment by stgraber** [comment]
You should rebase on master to get rid of those merge commits.

**Comment by danielrobbins** [comment]
Yes, those are annoying. The only way I've found to update my fork via the UI is to send myself a pull request with your most recent upstream changes. But this is kind of pointless since it creates the merge commits.

**Comment by danielrobbins** [comment]
Should be cleaned up now.

**Comment by stgraber** [comment]
thanks!

**Pull request merged**
