### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by adrian5**

### CODE REVIEW

**Comment by tomponline** [comment]
thanks @adrian5 please can you sign off your commit.

**Comment by adrian5** [comment]
Oh blimey, I wasn't aware of the contribution guidelines. I now recall running into this once in the past. Since my GitHub account isn't intended to represent me publicly, I'll close the pull request instead.

I found another issue in the same document while reading:

```markdown
LXD supports the following additional source types:
- Ceph-rbd: Mount from existing
```

The first line should be followed by a space (best) or linebreak to ensure that the list item gets interpreted as such – in the [rendered documentation](https://linuxcontainers.org/lxd/docs/master/instances#type-disk) it doesn't look to be.

**Comment by tomponline** [comment]
@adrian5 Yes the details are available herehttps://github.com/lxc/lxd/blob/master/doc/contributing.md#developer-certificate-of-origin

**Comment by stgraber** [comment]
Ah yeah, if you turn this into an issue then we can go fix it easily enough.

**Comment by adrian5** [comment]
Ok, will open an issue if I run into anything in the future :+1:

**Comment by tomponline** [comment]
Implemented here https://github.com/lxc/lxd/pull/6966

**Pull request closed without merging**
