### PR TITLE
VM: Add support for snap lxd-agent.debug in /var/snap/lxd/common/

### PR DESCRIPTION
**Pull request by tomponline**
Enables side loading debug builds of the lxd-agent binary when using the snap.

Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
I'd rather we do that in the snap packaging logic.

**Comment by stgraber** [comment]
@tomponline what I'd do is detect /var/snap/lxd/common/lxd-agent.debug and if found, symlink that into our in-memory (tmpfs) `bin` directory. This is prepended in the PATH so LXD will favor this one over the original.

**Comment by tomponline** [comment]
> @tomponline what I'd do is detect /var/snap/lxd/common/lxd-agent.debug and if found, symlink that into our in-memory (tmpfs) `bin` directory. This is prepended in the PATH so LXD will favor this one over the original.

Where should this be done in the snap packaging?

**Comment by stgraber** [comment]
`snapcraft/commands/daemon.start` look for `# Setup an additional bin directory`

**Comment by tomponline** [comment]
https://github.com/lxc/lxd-pkg-snap/pull/103

**Pull request closed without merging**
