### PR TITLE
copy: wait asynchronously

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
we seem to be getting much more failures somehow, hard to pinpoint where though

**Comment by brauner** [comment]
Loop device failures for storage tests, not migration.

**Comment by brauner** [comment]
There are all storage test failures and again related to `LVM`. I suspect that creating a `LVM` storage pool and immediately afterwards deleting it on a highly loaded system might cause the `LVM` cache to be confused or not ready. I tried to tweak the test-suite a little and also added `--mknodes` to the `vgscan` calls.

**Comment by brauner** [comment]
Note, that I've added a bunch more `LVM` storage pool creation tests with create-deletion directly after each other in the non-thinpool `LVM` pr.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Pull request merged**
