### PR TITLE
VM: lxd-agent systemd dependency conflicts

### PR DESCRIPTION
**Pull request by tomponline**
Was seeing errors like this on ubuntu 18.04 VMs:

```
[    3.304595] systemd[1]: cloud-init-local.service: Found ordering cycle on lxd-agent.service/start
[    3.305700] systemd[1]: cloud-init-local.service: Found dependency on sysinit.target/start
[    3.306768] systemd[1]: cloud-init-local.service: Found dependency on cloud-init.service/start
[    3.307790] systemd[1]: cloud-init-local.service: Found dependency on systemd-networkd-wait-online.service/start
[ SKIP ] Ordering cycle found, skipping LXD - agent
```

This seems to fix it.

### CODE REVIEW

**Comment by stgraber** [comment]
Hmm, you're making it run before / is mounted read write, this is going to break file templating or at least make it seriously racy.

**Comment by tomponline** [comment]
@stgraber is there a target we can use for that?

**Comment by tomponline** [comment]
@stgraber cloud init also has `systemd-remount-fs.service` which is why I used it.

**Comment by tomponline** [comment]
@stgraber I've tried it using `After=systemd-remount-fs.service` and that works too.

**Comment by tomponline** [comment]
@stgraber @monstermunchkin I'm may need to tweak this some more as seeing some errors on boot:

```
 Error: Failed to listen on vsock: listen vsock: open /dev/vsock: no such file or directory
```

The restart part of the systemd unit means that the agent does eventually start, but really I'd like it not to have to start/stop twice during boot.

**Comment by tomponline** [comment]
@stgraber that seems to have fixed it, I see lxd agent 9p start, followed by lxd-agent, then it doesn't get restarted later in the boot and no errors in syslog.

**Comment by tomponline** [comment]
Using `After=local-fs.target` fixed it.

**Comment by stgraber** [comment]
@tomponline are you going to send a distrobuilder PR to line things up there?

**Comment by tomponline** [comment]
@stgraber yep will do, I'm not sure how to use distrobuilder to test it, but will make the PR anyway without testing as should only be a small change.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
