### PR TITLE
shared/util.go: use string method with stdout and stderr

### PR DESCRIPTION
**Pull request by TimRots**
* use String() method with stdout and stderr
* simplified IsTrue function

Signed-off-by: Tim Rots <tim.rots@protonmail.ch>

### CODE REVIEW

**Comment by stgraber** [comment]
Hello, all LXD commits must have a `Signed-off-by: Firstname Lastname <email>` line.

This is usually done by passing `-s` to `git commit`.
You can do it on your branch with `git commit --amend -s` followed by `git push -f`

**Comment by TimRots** [comment]
> Hello, all LXD commits must have a `Signed-off-by: Firstname Lastname <email>` line.

Thank you for pointing this out. Will keep it in mind for future reference. 

> You can do it on your branch with git commit --amend -s followed by git push -f

Done

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Thanks!

**Pull request merged**
