### PR TITLE
Support stand-by cluster members

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@freeekanayaka just to make sure I didn't miss anything, this does:
 - Run dqlite on all nodes
 - Base roles on raft roles for database and standby
 - Set 2 standby nodes, so first idle is the 6th node

We'll then have a different piece of work which will allow for both the number of voting and non-voting (standby) nodes to be configurable.

Correct?

**Comment by freeekanayaka** [comment]
> @freeekanayaka just to make sure I didn't miss anything, this does:
> 
>     * Run dqlite on all nodes

Correct.

>     * Base roles on raft roles for database and standby
> 

Not sure what you mean here. You'll see a "YES" in the DATABASE column of ```lxc cluster list``` if and only if the underlying dqlite/raft node has the Voter role. If it has StandBy or Spare, it won't be listed as database node.

>     * Set 2 standby nodes, so first idle is the 6th node

Correct.
 
> We'll then have a different piece of work which will allow for both the number of voting and non-voting (standby) nodes to be configurable.
> 
> Correct?

Yeah, I guess so, if we wish. There's currently a separate card for that in Trello.

**Pull request merged**
