### PR TITLE
Storage: Updates internalImport to use new storage framework

### PR DESCRIPTION
**Pull request by tomponline**
Includes @stgraber's removal of some of the legacy storage drivers.

Tested for `dir` driver, need to test the rest of the drivers.

- [x] DIR
- [x] LVM
- [x] BTRFS
- [x] ZFS

### CODE REVIEW

**Comment by stgraber** [comment]
LVM looks potentially broken, will re-try jenkins and see what things look like then.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
@stgraber ok thanks, it passes locally, also I need to redo commit https://github.com/lxc/lxd/pull/6915/commits/768499bc8a0cdcc3bc022c7e7b488c2aa9df5ec7 as its lost its meaning during a rebase.

**Comment by tomponline** [comment]
@stgraber failed again on lvm, will take a look as passing locally.

**Comment by stgraber** [comment]
@tomponline yeah, same spot. Be sure to rebase on master, @freeekanayaka changed some of the db logic that may affect this.

**Comment by stgraber** [comment]
So if you haven't rebased your local copy, that would explain the difference in behavior vs jenkins.

**Comment by tomponline** [comment]
@stgraber update LVM snapshots list generation to use prefix matching output from `lvs` instead.

I checked which other storage driver uses the `genericVFSVolumeSnapshots` function, and its only `dir`, `btrfs` and `cephfs`. They all seems suitable to use `genericVFSVolumeSnapshots`, my only uncertainly was around `cephfs`?

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tomponline yeah, cephfs would be wrong, it should look for the content of the `.snap` directory in the volume mount path.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
