### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
As stated on IRC, we shouldn't merge this until we've tested the following:

 - [ ] --auto with --storage-pool
 - [ ] --auto with --storage-device
 - [ ] --auto with --storage-loop
 - [ ] interactive with existing ZFS pool
 - [ ] interactive with existing ZFS dataset (existing subset of existing pool)
 - [ ] interactive with new ZFS dataset (new subset of existing pool)
 - [ ] interactive with new ZFS loop
 - [ ] interactive with new ZFS device backed
 - [ ] interactive with dir backend
 - [ ] interactive without any storage config

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
@stgraber, tested all of these. I have this commit with your sign-off in my branch but we can merge this first and then my branch with additional fixes. Whatever you prefer.

**Comment by brauner** [comment]
This branch causes a temporary lxd init breakage on the `security.sh` tests. Will be fixed in my branch.

**Pull request merged**
