### PR TITLE
[DO NOT MERGE]: jenkins debugging

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
So the `not found` error stems from the websocket operation not being found. So on migration success you usually have:

```
DBUG[04-13|21:00:33] Success for websocket operation: c5a15249-897f-46bc-b307-004e08bc4696 
<snip>
DBUG[04-13|21:00:34] handling                                 ip=127.0.0.1:54780 method=GET url=/1.0/operations/c5a15249-897f-46bc-b307-004e08bc4696/wait
DBUG[04-13|21:00:34] 
	{
		"type": "sync",
		"status": "Success",
		"status_code": 200,
		"operation": "",
		"error_code": 0,
		"error": "",
		"metadata": {
			"id": "c5a15249-897f-46bc-b307-004e08bc4696",
			"class": "websocket",
			"created_at": "2017-04-13T21:00:27.125533742Z",
			"updated_at": "2017-04-13T21:00:27.125533742Z",
			"status": "Success",
			"status_code": 200,
			"resources": {
				"containers": [
					"/1.0/containers/nonlive"
				]
			},
			"metadata": {
				"control": "1e65329d8706cbdb5a47dfd12cb422153cbab789022f94af936ac6fdb7795fa1",
				"fs": "a695b2ff0ab6216dc0b6f8ecc17daed66835ccba4b25bf57ec0cc841bed40ef5"
			},
			"may_cancel": false,
			"err": ""
		}
	} 
DBUG[04-13|21:00:34] Raw response: {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"id":"c5a15249-897f-46bc-b307-004e08bc4696","class":"websocket","created_at":"2017-04-13T21:00:27.125533742Z","updated_at":"2017-04-13T21:00:27.125533742Z","status":"Success","status_code":200,"resources":{"containers":["/1.0/containers/nonlive"]},"metadata":{"control":"1e65329d8706cbdb5a47dfd12cb422153cbab789022f94af936ac6fdb7795fa1","fs":"a695b2ff0ab6216dc0b6f8ecc17daed66835ccba4b25bf57ec0cc841bed40ef5"},"may_cancel":false,"err":""}}
```

While on `not found` we have:

```
DBUG[04-13|21:16:02] Success for websocket operation: 5e07a5e0-8d1f-4170-8cf3-d90b19c3dc3f 
<snip>
DBUG[04-13|21:16:26] handling                                 ip=127.0.0.1:58434 method=GET url=/1.0/operations/5e07a5e0-8d1f-4170-8cf3-d90b19c3dc3f/wait
DBUG[04-13|21:16:26] 
	{
		"error": "not found",
		"error_code": 404,
		"type": "error"
	} 
DBUG[04-13|21:16:26] Raw response: {"error":"not found","error_code":404,"type":"error"}

 
error: not found
```

**Comment by stgraber** [comment]
Is that because we're being too slow to call /wait?
An operation will go away and return not found, 5s after it's completed.

**Comment by brauner** [comment]
Hm, so this in `copy.go` could be the problem:

```
	for _, addr := range addresses {
		var migration *api.Response

		sourceWSUrl := "https://" + addr + sourceWSResponse.Operation
		migration, err = dest.MigrateFrom(destName, sourceWSUrl, source.Certificate, secrets, status.Architecture, status.Config, status.Devices, status.Profiles, baseImage, ephemeral == 1, false, source, sourceWSResponse.Operation, containerOnly)
		if err != nil {
			continue
		}

		// If push mode is implemented then MigrateFrom will return a
		// non-waitable operation. So this needs to be conditionalized
		// on pull mode.
		if err = dest.WaitForSuccess(migration.Operation); err != nil {
			continue
		}

		if err = source.WaitForSuccess(sourceWSResponse.Operation); err != nil {
			return err
		}

		if destResource == "" {
			op, err := migration.MetadataAsOperation()
			if err != nil {
				return fmt.Errorf(i18n.G("didn't get any affected image, container or snapshot from server"))
			}

			containers, ok := op.Resources["containers"]
			if !ok || len(containers) == 0 {
				return fmt.Errorf(i18n.G("didn't get any affected image, container or snapshot from server"))
			}

			fields := strings.Split(containers[0], "/")
			fmt.Printf(i18n.G("Container name is: %s")+"\n", fields[len(fields)-1])
		}

		return nil
	}
```

The two waits should maybe be done asynchronously or is there are reason that they can't be?

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Yeah, it's pretty likely that this might be caused by the operation vanishing before we had a chance to wait on it. I've added a `logger.Errorf()` statement to the timeout function to catch this case.

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
As discussed on IRC this is likely caused by LVM mounts being slow or failing and this is taking too long and the operation has already vanished. I've sent a patch in #3174 which tries to mitigate this problem by waiting asynchronously.

**Pull request closed without merging**
