### PR TITLE
Provide daily Windows binaries for client with AppVeyor

### PR DESCRIPTION
**Pull request by techtonik**
* [x] now build artifacts can be downloaded - https://ci.appveyor.com/project/lxc/lxd/build/artifacts
* [x] open the gate for Windows users

### CODE REVIEW

**Comment by techtonik** [comment]
I planned to enable junit test reporting, but because there is no `tee` on Windows, it requires some non-obvious hacks to get both real-time screen output and nice counter on test tab (see https://github.com/golang/go/issues/17542 for details). Maybe later.

This is ready to be merged.

**Comment by stgraber** [comment]
Any chance you can squash all of this into one or two commits?

That makes cherry-picking into the stable branch quite a bit easier :)

**Comment by techtonik** [comment]
From one side it is nice to see elevation of pain for future researchers in devops usability. From the other, nobody is going discover this, so.. sure. =)

**Comment by techtonik** [comment]
Reduced to 5 logical chunks from 13. I suppose you want to merge only few features from the set for now.

**Pull request merged**
