### PR TITLE
Fixed minor typo in checkNetwork error message

### PR DESCRIPTION
**Pull request by vahe**

### CODE REVIEW

**Comment by stgraber** [comment]
Can you please sign-off your commit? (see CONTRIBUTING.md)

Since this changes a translatable string, you should also include the result of "make i18n" in your commit as the translation templates must be updated.

**Comment by vahe** [comment]
Thanks. Done

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
thanks!

**Pull request merged**
