### PR TITLE
fix dead lock bug

### PR DESCRIPTION
**Pull request by ichiro999**
dead lock found when watch an existing device

unixRunHandlers acquires lock unixMutex while, if the watch function being triggered, together with the acquiring d.mu.lock, dead lock will be found.

The fix moved device watch register from unixMutex lock scope

Signed-off-by:   ichiro999 <93505768@qq.com>

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Review by tomponline — CHANGES_REQUESTED** [review]
Thanks for this!

Please can you sign off your commit.

**Comment by ichiro999** [comment]
> Thanks for this!
> 
> Please can you sign off your commit.

done

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
The check is failing with:

"  Expected "ichiro999 <93505768@qq.com>", but got "Fan Hui <93505768@qq.com>"."

**Comment by ichiro999** [comment]
> The check is failing with:
> 
> " Expected "ichiro999 [93505768@qq.com](mailto:93505768@qq.com)", but got "Fan Hui [93505768@qq.com](mailto:93505768@qq.com)"."
> 
> > What should I do to fix it ?
> 
> All proposed commits should include a Signed-off-by: line in their commit message. This is most conveniently done by using --signoff (-s) when running git commit.

sorry, I fix it now

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Thanks!

**Pull request merged**
