### PR TITLE
Update TLS 1.2 ciphersuites

### PR DESCRIPTION
**Pull request by simondeziel**
When LXD uses an ECDSA key, here is the list of ciphersuites exposed (as reported by `testssl.sh`):

```
Hexcode  Cipher Suite Name (OpenSSL)       KeyExch.   Encryption  Bits     Cipher Suite Name (IANA/RFC)
-----------------------------------------------------------------------------------------------------------------------------
SSLv2
 - 
SSLv3
 - 
TLSv1
 - 
TLSv1.1
 - 
TLSv1.2 (server order)
 xc02b   ECDHE-ECDSA-AES128-GCM-SHA256     ECDH 521   AESGCM      128      TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256            
 xc02c   ECDHE-ECDSA-AES256-GCM-SHA384     ECDH 521   AESGCM      256      TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384            
 xc009   ECDHE-ECDSA-AES128-SHA            ECDH 521   AES         128      TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA               
 xc00a   ECDHE-ECDSA-AES256-SHA            ECDH 521   AES         256      TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA               
TLSv1.3 (server order)
 x1303   TLS_CHACHA20_POLY1305_SHA256      ECDH 253   ChaCha20    256      TLS_CHACHA20_POLY1305_SHA256                       
 x1301   TLS_AES_128_GCM_SHA256            ECDH 253   AESGCM      128      TLS_AES_128_GCM_SHA256                             
 x1302   TLS_AES_256_GCM_SHA384            ECDH 253   AESGCM      256      TLS_AES_256_GCM_SHA384
```

Both SHA1 and AES-CBC mode have known weaknesses so let's disable ciphersuites relying on them (so both for RSA and ECDSA keys).

While in there, ChaCha20-Poly1305 ciphersuites were enabled and the list was ordered to better align with what upstream `crypto/tls` automatically does with Go 1.17 and later.

### CODE REVIEW

**Comment by tomponline** [comment]
Is there an option to use a recommended set from Go defaults, rather than having to specify these ourselves?

**Comment by simondeziel** [comment]
If compatibility with middle box/enterprise proxies is a concern, AES-CBC + SHA1 could be reinstated at the end of the list so following the Go upstream ordering rules which seem sensible.

**Comment by simondeziel** [comment]
@tomp, the modern Go default looks good to me (non-cryptographer opinion warning) but for older Go versions this is the kind of thing we seem to have to deal with.

Fortunately, early on, LXD made sure to pick very decent defaults: ECDHE instead of DHE, GCM over CBC and TLS 1.2+ only.

**Comment by tomponline** [comment]
> @tomp, the modern Go default looks good to me (non-cryptographer opinion warning) but for older Go versions this is the kind of thing we seem to have to deal with.
> 
> Fortunately, early on, LXD made sure to pick very decent defaults: ECDHE instead of DHE, GCM over CBC and TLS 1.2+ only.

We are going to be targetting at least go 1.17 and up, so do we need to deal with it? Or at worst, take the defaults + some specific extras (with comments as to why they are there)?

**Comment by tomponline** [comment]
> non-cryptographer opinion warning

Yeah same, which is why I'm drawn to accepting the Go defaults they seem to be keeping them up to date.

**Comment by simondeziel** [comment]
Keeping the ciphersuites list still makes sense even with Go 1.17 as the minimum version because what's done for us is the ordering alone.

Since LXD has never supported weak stuff like 3DES/RC4, going with Go's default would increase the number of ciphersuites supported. Apparently in a safe way so maybe it's worth doing. I'm on the fence :)

**Comment by tomponline** [comment]
> Keeping the ciphersuites list still makes sense even with Go 1.17 as the minimum version because what's done for us is the ordering alone.
> 
> Since LXD has never supported weak stuff like 3DES/RC4, going with Go's default would increase the number of ciphersuites supported. Apparently in a safe way so maybe it's worth doing. I'm on the fence :)

Could we use https://pkg.go.dev/crypto/tls#CipherSuites as this excludes ones that are considered insecure:

currently this is:

https://cs.opensource.google/go/go/+/refs/tags/go1.18:src/crypto/tls/cipher_suites.go;l=52

**Comment by tomponline** [comment]
If this gets merged then we will only support 1.18+ https://github.com/lxc/lxd/pull/10125

**Comment by stgraber** [comment]
I prefer to be explicit about this stuff rather than implicit or worse dependent on an external package which could change overnight.

**Comment by tomponline** [comment]
@stgraber we should at least make sure progmatically that nothing on this list becomes considered insecure by the Go team. 
So we should call [CipherSuites](https://pkg.go.dev/crypto/tls#CipherSuites) and check our preferences all appear in that list and fail if not?

**Comment by tomponline** [comment]
Or do we specifically pin some that are considered insecure? If so we should mark those as exceptions with a comment as to why, and then the rest should only be used if they also appear in `CiperSuites()`.

**Comment by tomponline** [comment]
This will means we take the intersection of those we want and those that the Go team consider secure.

**Pull request merged**
