### PR TITLE
lxd: updated dnsmasq and forkdns to use new subprocess module

### PR DESCRIPTION
**Pull request by ribsthakkar**
Building on issue #5826 to use the new background proceess manager to refactor how dnsmasq and forkdns are processes are started or killed.

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
```
# github.com/lxc/lxd/lxd
lxd/networks.go:1955:13: undefined: subprocess
lxd/networks.go:2253:12: undefined: subprocess
lxd/networks_utils.go:5:2: imported and not used: "bytes"
lxd/networks_utils.go:22:2: imported and not used: "golang.org/x/sys/unix"
```

**Comment by stgraber** [comment]
Did the fixes for you, lets see what Jenkins thinks.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by ribsthakkar** [comment]
> ```
> # github.com/lxc/lxd/lxd
> lxd/networks.go:1955:13: undefined: subprocess
> lxd/networks.go:2253:12: undefined: subprocess
> lxd/networks_utils.go:5:2: imported and not used: "bytes"
> lxd/networks_utils.go:22:2: imported and not used: "golang.org/x/sys/unix"
> ```
@stgraber sorry for not responding sooner, and thank you for fixing that. It should have been just a few minutes to remove the unused imports but how would I have properly imported the subprocess module?

**Comment by ribsthakkar** [comment]
It seems that it is trying to reload dnsmasq but the process itself is not initlialized, which probably means its not running. The network.Setup() should have already been called and it did not seem to throw an error.

**Comment by ribsthakkar** [comment]
@stgraber I saw you self assigned this, but do you need me to do anything else? I'm trying to understand where I had gone wrong in my implementation

**Comment by stgraber** [comment]
I'm planning on sorting out what's going on by LXD 3.20, but if you have some time to figure it out, go ahead! :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Thanks!

**Comment by ribsthakkar** [comment]
Sorry @stgraber  I though I would get to this this semester, which I obviously did not. Thanks for letting us work on the project though! I learned a lot!

**Pull request merged**
