### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by facundobatista**

### CODE REVIEW

**Comment by brauner** [comment]
Hey, thanks for the patch. Can you please sign-off your commit with `git commit -s`?

**Comment by facundobatista** [comment]
Hi @brauner ! I did this through GH interface, it tells me that "This commit was created on GitHub.com and signed with a verified signature using GitHub’s key.".

If that's not enough, I'll see how can I get this branch and run the `git` command, as you suggested. Let me know if it's needed, are those two different ways of signing it?

Thanks!!

**Comment by stgraber** [comment]
@facundobatista yes, all commit messages against lxc, lxcfs, lxd, ... need to include a `Signed-off-by: Firstname Lastname <email>` line at the end of the commit message.

This is separate from GPG signing the commit. You can find out more about the DCO in the contributing.md document.

**Comment by stgraber** [comment]
In this case, you also need to run `make i18n` to update the translation templates, so I'll just send a separate PR which does those two things.

**Pull request closed without merging**
