### PR TITLE
Multi idmap

### PR DESCRIPTION
**Pull request by tych0**
This adds support for custom idmaps to LXD, and in particular adds a simple mechanism to isolate containers from each others' idmaps entirely.

### CODE REVIEW

**Comment by stgraber** [comment]
The Windows test looks unhappy.

**Comment by tych0** [comment]
Meh.

**Comment by stgraber** [comment]
I'll do a more in depth review of this tomorrow. It overall looks good to me and I'm quite happy to see all the tests to cover this rather tricky piece of work :)

One thing that should get updated as part of this is doc/userns-idmap.md. Having it mention the new options and explain what's allowed as part of raw.idmap.

**Comment by stgraber** [comment]
This pull request closes #164

**Comment by tych0** [comment]
Cool, I added a little doc on it. One question I had is whether or not to cover the volatile keys there. If it's a user facing doc it might not make sense, but I could go either way. Anyway, I'd be happy to add it if you think it's useful.

**Comment by tych0** [comment]
And now I even pushed the doc to the right remote :)

**Pull request merged**
