### PR TITLE
add filtering of lxc aliases

### LINKED ISSUE #1798: Feature request: 'lxc image alias list [remote:] [filter]'
Using lxc version 2.0.0.rc5 from on Trusty from the ppa.

It would be nice if you could pass a filter to "lxc image alias list". Especially now that you support Simplestreams remotes doing:
  lxc image alias list ubuntu:
is  3603 lines long. Which means I always have to dump it into a text editor to find what I want. Being able to do:
 lxc image alias list ubuntu:trusty*
or some variant of that "trusty.*" as a regex, trusty* as a glob, "ubuntu:" "trusty*" as 2 commandline parameters, or "--filter trusty" as a simple string match from a named parameter.

Just something that would let me see a subset so I can get a quick answer (is my local hash the same as the official source?)

### PR DESCRIPTION
**Pull request by akshaykarle**
* similar to lxc image filter
* resolves #1798

### CODE REVIEW

**Comment by akshaykarle** [comment]
This is a first attempt to resolve the issue, before signing off I wanted to know if there is something missing. I also couldn't find any comprehensive test suite around this. Is this how we expect to proceed with this?

**Comment by tych0** [comment]
There is a test suite in tests/ which you can run by doing `sudo -E ./main.sh`. Adding a test to it for this functionality would be much appreciated.

**Comment by stgraber** [comment]
I can't read the code until you sign off as otherwise I wouldn't be legally able to implement this feature should you decide not to sign off (as it would be considered at least partly copying copyrighted code without rights).

**Comment by akshaykarle** [comment]
Thanks for your inputs both of you. I will look into adding some tests for
the filtering and sign-off the commits so that you can review it.

On Wed, Mar 30, 2016 at 9:11 AM Stéphane Graber <notifications@github.com>
wrote:

> I can't read the code until you sign off as otherwise I wouldn't be
> legally able to implement this feature should you decide not to sign off
> (as it would be considered at least partly copying copyrighted code without
> rights).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lxc/lxd/pull/1823#issuecomment-203507149>
>
-- 
Akshay Karle
ThoughtWorks | Snap CI
https://snap-ci.com

**Comment by akshaykarle** [comment]
Done! Can someone review?

**Comment by stgraber** [comment]
You are changing translated strings, you need to run "make i18n" and commit the resulting changes.

**Comment by akshaykarle** [comment]
I didn't think about translations. I ran the make and checked in the changes.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
