### PR TITLE
Directly re-exec LXD when requesting to remove self from a cluster

### PR DESCRIPTION
**Pull request by masnax**
Addresses the `EOF` error in #9464

This is the full fix after investigation for #9468

When a node requests to remove itself from the database, the request is forwarded to the leader, which removes the node from dqlite and then sends another request to the to-be-removed node to disable clustering on itself and re-exec its daemon. This happens via the following in `lxd/api_cluster.go`
```go
put := api.ClusterPut{}
put.Enabled = false
_, err = client.UpdateCluster(put, "")
```

This made it so that flushing the response in `clusterPutDelete` was rendering to the leader node, even though we were initiating the request from the to-be-removed node. The daemon on the requesting node would restart before the response could be sent back.

Instead of asking the leader to request the to-be-removed node to disable clustering, this commit makes the original requesting node immediately disable clustering on itself and re-exec its daemon if the request goes through, and prevents the leader from sending the update request if the request came from the node to be removed.

### CODE REVIEW

**Comment by tomponline** [comment]
@masnax the test suite is red across the board I'm afraid. There's at least 2 different issues, one is code style in the tests and the other is an actual functionality issue.

**Comment by tomponline** [comment]
Taking a look at this.

**Comment by masnax** [comment]
> @masnax the test suite is red across the board I'm afraid. There's at least 2 different issues, one is code style in the tests and the other is an actual functionality issue.

That's what I get for a late-night PR :)

Pretty simple fixes here. Just some formatting on the tests, and I'm checking the wrong variable `r.Host`. It should be `r.RemoteAddr` and the port should be cut off.

**Comment by tomponline** [comment]
Thanks, in my tests as well as the EOF error which hopefully is fixed now, I also see that LXD hangs when restarting.

**Comment by tomponline** [comment]
I'll push this branch down fresh and try again.

**Comment by masnax** [comment]
Missed one line in the test. Static analysis never complains for me locally :(

**Comment by tomponline** [comment]
@stgraber @masnax added systemd socket activation detection and exits in that case rather than replacing the LXD process, as otherwise we were losing the socket FDs and environment variables and were incorrectly trying to connect to ourselves to check if running already, causing a hang.

**Review by tomponline — APPROVED** [review]

**Review by tomponline — APPROVED** [review]

**Comment by tomponline** [comment]
I'm going with a slightly different approach that doesn't depend on remote address comparison logic, as that has proven unreliable in tests, and we can do it a different way internally without having to rely on remote address logic.

**Pull request closed without merging**
