### PR TITLE
zfs: Always require existing datasets to be empty

### LINKED ISSUE #3657: Deletion of storage pools always deletes zfs source volume
# Required information

 * Distribution: Debian
 * Distribution version: Stretch
 * The output of "lxc info" or if that fails:
```
architectures:
  - x86_64
  - i686
driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.9.0-3-amd64
  server: lxd
  server_version: "2.16"
  storage: zfs
  storage_version: 0.6.5.9-5

```
# Issue description
LXC storage pools can be created for existing zfs volumes like tank/volume. Unfortunately those storage pools can't be removed from LXC without deleting the zfs volume as well. Also unsetting the source as a workaround doesn't work in this case. This leads to potential data loss in case the wrong volume has been added and can't be removed from lxc but kept as a volume afterwards.

# Steps to reproduce

 0. Set up a zfs pool `tank`
 1. create a zfs volume `zfs create tank/myvolume`
 2.1 check with `zfs list`
 2. add zfs volume as lxc storage pool `lxc storage create pool1 zfs source=tank/myvolume`
 3. try to delete the lxc storage while retaining the zfs volume `lxc storage delete pool1`
 3.1 check with `zfs list`

[edit] inserted two additional steps

### PR DESCRIPTION
**Pull request by stgraber**
Closes #3657

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
Well, at this point we can almost drop the requirement that the pool is viewed as being under full control by lxd. We're relaxing this restriction more and more. :)

**Comment by stgraber** [comment]
What do you mean? This pull request makes it stricter, not looser.

The problem was that we'd allow the user to use a used zfs dataset but then would recursively delete that dataset on removal, causing dataloss. This pull request makes sure that we do the pool check both when provided a full zpool AND when provided a dataset off an existing zpool.

**Comment by brauner** [comment]
We're explicitly stating in the docs that anything the user gives us as pool is considered to be fully under LXDs control and that it will be deleted and thus should be empty and exclusive to LXD. In that sense we're getting less strict. The or in general is fine. :)

**Comment by stgraber** [comment]
I'm really not sure what you mean. This pull request changes the code to actually do what we say we do in the doc.

Prior to it, LXD was perfectly happy using a pool which contained stuff, I fix it so that it doesn't do that anymore, making it behave as LXD used to before the storage pool work.

**Comment by brauner** [comment]
I'm referring to: "Note that LXD will assume it has full control over the ZFS pool or dataset. It is recommended to not maintain any non-LXD owned filesystem entities in a LXD zfs pool or dataset since LXD might delete them."

**Pull request merged**
