### PR TITLE
lxd/storage: Re-introduce cluster distribution of volume snapshots

### LINKED ISSUE #8680: Volume snapshots should only be done on one node
`cephfs` volume snapshots appear to be done by all of my servers causing in this case 3x as many snapshots as I should have...

### PR DESCRIPTION
**Pull request by stgraber**
Closes #8680

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber I think @monstermunchkin is already working on this here https://github.com/lxc/lxd/pull/8672

It was removed by another recent commit in 4.13, however we also noticed that as it is its also triggering a cluster heartbeat through the use of getting the node status which seemed inefficient if you didn't have any remote volumes so its being refactored to avoid it.

**Comment by tomponline** [comment]
I'd appreciate your thoughts on the other PR, as the way I read this restoration of the original code, it seems like it could lead to some local volumes being skipped on their local node and being erroneously done on an invalid remote node.

**Comment by stgraber** [comment]
I'll need to look into this closer but having things as broken as before would be a good step up compared to the current state of things where my cluster is snapshotting everything 3 time at the same time which on ceph means freezing filesystem access and causing massive load spikes across the cluster and taking down services.

This is the source of the recent issues with the image servers as it keeps freezing the volumes related to the image publishing.

**Comment by tomponline** [comment]
@stgraber OK I'll merge this one now then. I'm pretty happy with the @monstermunchkin one too, there were just a couple of minor suggestions about  logging errors.

**Pull request merged**
