### PR TITLE
seccomp: cause a default message to be sent

### PR DESCRIPTION
**Pull request by brauner**
If liblxc is sending us messages of an indeterminate size we have two
options:
1. trigger a default response and _close_ the connection
2. trigger a default connection and _keep_ the connection

Option 1. means that we keep hanging the container for 30s on each
request. If liblxc is sending us garbage or a message of unknown size.

Options 2. means we keep handling the requests and responding with a
dummy response without doing anything. This will cause liblxc to respond
with the defaule ENOSYS response to the kernel. The container will not
be stalled.

I think option 1. is better than option 2.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
1) with a suitable logger.Warning seems reasonable

**Comment by brauner** [comment]
> 1. with a suitable logger.Warning seems reasonable

What do you mean "suitable logger"?

**Comment by stgraber** [comment]
we should log a warning message to the LXD log when that happens, recording what container (project and name) sent the garbage request

**Comment by brauner** [comment]
> we should log a warning message to the LXD log when that happens, recording what container (project and name) sent the garbage request

That's not possible. We don't have the monitor's pid and we can't use the request pid since that would trigger a deadlock. The logging we have right now should help a little bit at least.

**Comment by stgraber** [comment]
Why do you have to run `cleanup` in a separate Go routine?

Also, for logging, I'd like to see `cleanup` log something saying that we got an invalid request and use `ucred.pid` to indicate who sent it to us. That's information we have and having those logged as warnings seems useful.

**Comment by brauner** [comment]
On July 9, 2019 11:52:35 PM GMT+02:00, "Stéphane Graber" <notifications@github.com> wrote:
>Why do you have to run `cleanup` in a separate Go routine?

Because it handles multiple requests via InvalidHandler() just like Handler() does for valid ones. Otherwise you serialize all requests.

>
>Also, for logging, I'd like to see `cleanup` log something saying that
>we got an invalid request and use `ucred.pid` to indicate who sent it
>to us. That's information we have and having those logged as warnings
>seems useful.

That's already logged in all paths where cleanup is called.
Every failure path also explains why it fails.

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stgraber** [comment]
Right but you have those as Debugf so there's no way any of our users will ever see this should they get garbage data coming from their liblxc.

**Comment by brauner** [comment]
Right but that's not what your original mail was asking for. ;)
I'll make them warns. I find error a bit hefty.

On July 10, 2019 12:51:43 AM GMT+02:00, "Stéphane Graber" <notifications@github.com> wrote:
>Right but you have those as Debugf so there's no way any of our users
>will ever see this should they get garbage data coming from their
>liblxc.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lxc/lxd/pull/5928#issuecomment-509839094

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by brauner** [comment]
Done.

**Pull request merged**
