### PR TITLE
Fix help to provide sample that actually works

### PR DESCRIPTION
**Pull request by elvsp1n**
Using 1 doesn't display privileged containers but if we use true it does.

### CODE REVIEW

**Comment by brauner** [comment]
Hi, you need to sign-off your commit. This should be as simple as `git commit -s ...` :)

**Comment by elvsp1n** [comment]
Ok, let me give it another try.

**Comment by stgraber** [comment]
@elvsp1n looks good, but since you're modifying a translated string, you should run "make i18n" and commit the changes it makes as a second commit (we usually call it "i18n: update templates").

If you're not on a system where you can run "make i18n", let me know and I'll do it for you.

**Comment by elvsp1n** [comment]
@stgraber I should be able to do it from osx or ubuntu, let me give it a try to keep learning this git process that you guys have.

**Comment by elvsp1n** [comment]
Ok gents, I was able to do it on a fresh ubuntu install with this:
Ubuntu:
sudo apt install make golang gettext
export PATH=$PATH:/usr/local/go/bin
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
mkdir -p ~/go/src
git clone https://github.com/elvsp1n/lxd
cd lxd/
git checkout patch-3
make i18n

Running git status I see this
	modified:   po/de.po
	modified:   po/el.po
	modified:   po/fr.po
	modified:   po/it.po
	modified:   po/ja.po
	modified:   po/lxd.pot
	modified:   po/nl.po
	modified:   po/ru.po
	modified:   po/sr.po
	modified:   po/sv.po
	modified:   po/tr.po

Now I added the file with
git add .
Then committed the changes (with the signoff)
git commit --signoff -m "i18n: update templates"
And finally
git push
Sorry for all the details, I use this for future reference for my own :). I will now start using make i18n on my own projects as this make things way easier to keep everything translated.

**Comment by stgraber** [comment]
Sounds good.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
