### PR TITLE
Replace `forkuserns` with Go's native uid/gid map

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline good to go

**Comment by brauner** [comment]
Apparently the required options in SysProcAttr have been around since go 1.4? If so we did miss this for a very long time.

**Comment by tomponline** [comment]
@stgraber just testing this now and something not quite right with it:

```
   65534   62034  0.0  0.0  79784  1676 ?        Ssl  15:52   0:00 /usr/lib/qemu/virtiofsd --fd=3 -o source=/var/lib/lxd/devices/restricted_v1/disk.d1.mnt
   65534   62059  0.0  0.0   5624  1604 ?        Ss   15:52   0:00 /usr/lib/qemu/virtfs-proxy-helper --nodaemon --fd 3 --path /var/lib/lxd/devices/restricted_v1/disk.d1.mnt
   65534   62082  0.0  0.0 1146176 2056 ?        Sl   15:52   0:00 /usr/lib/qemu/virtiofsd --fd=3 -o source=/var/lib/lxd/devices/restricted_v1/disk.d1.mnt
```

VM's raw.idmap is
```
  raw.idmap: both 1000 1000
```

So those processes should be running as 1000 on the host (and root in the user namespace).

Looks like we need to use proc.SetCreds() and extract the root host uid and gid from the idmap ranges.

**Comment by tomponline** [comment]
> 

Although it does seem to work OK, writing a file as root inside the VM does create it as owner by 1000 on the host.

**Comment by tomponline** [comment]
@stgraber you're correct, we run the process as 65534, so its working as designed.

**Pull request merged**
