### PR TITLE
zfs: Use tryMount when mounting filesystem

### PR DESCRIPTION
**Pull request by stgraber**
May help with some of the EBUSY.

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
Seems to be an alright addition. Let's merge.

**Pull request merged**
