### PR TITLE
doc/instances: Add section about raw.qemu.conf

### PR DESCRIPTION
**Pull request by tarruda**
ref: https://github.com/lxc/lxd/pull/10512#issuecomment-1152875317

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
Thanks! I would have struggled to use this feature without that, very useful.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by tomponline** [comment]
Jenkins Found some typos
doc/instances.md:1273:33: "overriden" is a misspelling of "overridden"

**Comment by tomponline** [comment]
I get caught out by this one often too 😀

**Comment by tarruda** [comment]
Fixed the misspelling and made a few extra changes

**Comment by tomponline** [comment]
jenkins: test this please

**Pull request merged**
