### PR TITLE
Resume dump on failed restore

### PR DESCRIPTION
**Pull request by tych0**

### CODE REVIEW

**Comment by stgraber** [comment]
So unless there's some kind of way for us to detect whether go-lxc supports the feature or not, we won't be able to include that second commit in the stable branch due to it depending on a newer go-lxc.

**Comment by stgraber** [comment]
I seem to remember us hitting this before for some other migration feature (was it the new Migrate API?).

Is there anything we can do with reflection or similar to detect this stuff?

**Comment by tych0** [comment]
It was with PreservesInodes, and I think you just didn't cherry pick it, right?

**Comment by stgraber** [comment]
Yeah, that's the one. Was just wondering if there was something better we could do about those.

**Comment by tych0** [comment]
I'm not aware of anything; I don't think golang has conditional compilation for go code proper, just C :\

**Comment by stgraber** [comment]
Couldn't use reflect with FieldByName to check whether the field exists in the struct from go-lxc?

**Comment by stgraber** [comment]
Same "should" work for PreservesInodes too

**Comment by stgraber** [comment]
http://paste.ubuntu.com/18828543/

**Comment by tych0** [comment]
You can, but I'd rather not :)

**Pull request merged**
