### PR TITLE
shared/osarch: Add gentoo armhf variant

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Failures are unrelated though we should wait until liblxc is fixed on the test runners before we merge this change.

**Comment by brauner** [comment]
liblxc fix is merged

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner good to go

**Pull request merged**
