### PR TITLE
lxd/instances_post: Fix copying profiles during instance copy

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by tomponline** [comment]
Thanks! I'll add a test for that as seems there is a gap.

**Comment by tomponline** [comment]
@stgraber what was the scenario you encountered this?

**Comment by gianfurrer** [comment]
@tomponline  I assume the scenario which gets addressed with this fix is the following (which I already encountered while using 5.10):

1. Creating any kind of container, e.g. (`lxc launch images:debian/11 my-container`)
2. Trying to copy the container via `pylxd` (I was not able to reproduce the issue with `lxc copy`):

```python
import pylxd
client = pylxd.Client()
config = {"name": "my-container-copy", "source": {"type": "copy", "source": "my-container"}}
client.containers.create(config, wait=True)
```

Results in the following error:
```
pylxd.exceptions.LXDAPIException: Failed creating instance record: Failed initialising instance: Failed getting root disk: No root device could be found
```

Which indicated to me that the default profile which contains the root device was not applied to the copied container.

It works with `5.9/latest` and `latest/candidate`, but not with `latest/stable`. Therefore I assume that this MR fixed the issue.

**Comment by tomponline** [comment]
Yes indeed it requires direct API usage, not using `lxc copy` which always populates the `Profiles` field in the request and so was not affected by the bug.

**Pull request merged**
