### PR TITLE
ceph: add "ceph.osd.force_reuse" property

### LINKED ISSUE #3716: creating a container in ceph storage
After updating into lxd 2.16 on my ubuntu 16.04 LTS, wanted to make a try with new lxd storage feature :  ceph storage as i 've a ceph cluster for a while.

Here what i did  : 

     root@inxovh-hy001 (node1):~# lxc storage create lxd-pool ceph
     Storage pool lxd-pool created

     root@inxovh-hy001 (node1):~# ceph osd lspools
     0 data,6 libvirt-pool,7 .rgw.root,9 lxd-pool,

     root@inxovh-hy001 (node1):~# lxc storage list
     +----------+-------------+--------+-----------+---------+
     |   NAME   | DESCRIPTION | DRIVER |  SOURCE   | USED BY |
     +----------+-------------+--------+-----------+---------+
     | default  |             | zfs    | zdata/lxd | 27      |
     +----------+-------------+--------+-----------+---------+
     | lxd-pool |             | ceph   | lxd-pool  | 0       |
     +----------+-------------+--------+-----------+---------+

     root@inxovh-hy001 (node1):~#  lxc launch ubuntu-xenial-infranix inxovh-nli5001 -s lxd-pool
     Creating inxovh-nli5001
     error: Failed to run: rbd --cluster ceph --pool lxd-pool map      image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write      failed
     In some cases useful info is found in syslog - try "dmesg | tail" or so.
     rbd: map failed: (110) Connection timed out

     root@inxovh-hy001 (node1):~# rbd -p lxd-pool ls
     lxd_lxd-pool

In /var/log/syslog,

     Aug 24 19:10:32 inxovh-hy001 kernel: [155075.557163] libceph: mon0 10.0.0.1:6789 feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000
     Aug 24 19:10:42 inxovh-hy001 kernel: [155085.572520] libceph: mon0 10.0.0.1:6789 missing required protocol features
     Aug 24 19:10:52 inxovh-hy001 lxd[10584]: lvl=eror msg="Failed to map RBD storage volume for image \"b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7\" on storage pool \"lxd-pool\": Failed to run: rbd --cluster ceph --pool lxd-pool map image_b1b87ba5fde28e52d0ba8dec4717da54a088a78e9a4f75f0f386ce6796a899a7: rbd: sysfs write failed\nIn some cases useful info is found in syslog - try \"dmesg | tail\" or so.\nrbd: map failed: (110) Connection timed out" t=2017-08-24T19:10:52+0200

any clue about "feature set mismatch, my 106b84a842a42 < server's 40106b84a842a42, missing 400000000000000" ??

Kernel info: 

    root@inxovh-hy001 (node1):~# uname -a
    Linux inxovh-hy001 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Ceph version : 10.2.9-1xenial 

Info 

root@inxovh-hy001 (node1):~# lxc info
config:
  core.https_address: '[::]:8443'
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
api_status: stable
api_version: "1.0"
auth: trusted
public: false
environment:
  addresses:
  - 192.168.10.1:8443
  - 192.168.20.1:8443
  - 192.168.30.1:8443
  - 192.168.40.1:8443
  - 192.168.5.1:8443
  - 192.168.6.1:8443
  - 192.168.25.1:8443
  - 10.0.0.1:8443
  - 151.80.26.210:8443
  - '[2001:41d0:1008:26d2::]:8443'
  - 10.0.1.1:8443
  - 192.168.2.1:8443
  - 192.168.122.1:8443
  - 192.168.1.1:8443
  architectures:
  - x86_64
  - i686
  driver: lxc
  driver_version: 2.0.8
  kernel: Linux
  kernel_architecture: x86_64
  kernel_version: 4.4.0-92-generic
  server: lxd
  server_pid: 10584
  server_version: "2.16"
  storage: zfs | ceph
  storage_version: '0.6.5.6-0ubuntu16 | '

### PR DESCRIPTION
**Pull request by brauner**
Closes #3716.

Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Missing API extension and documentation for that one. A short paragraph in storage.md about the fact that you can't share a Ceph OSD pool between multiple hosts would be good too.

**Comment by brauner** [comment]
@stgraber, I was actually not sure whether this is a proper api extension. I thought this was a bugfix.

**Comment by stgraber** [comment]
You're adding a config key, so that's an API extension.

**Comment by brauner** [comment]
@stgraber, I don't believe you. :) (jk)

**Comment by brauner** [comment]
@stgraber, about the paragraph: I've already added one when I implemented the ceph storage driver.

**Comment by brauner** [comment]
@stgraber, updated.

**Pull request merged**
