### PR TITLE
Moves containerLXC and instance interface to instance package

### PR DESCRIPTION
**Pull request by tomponline**
@stgraber this is quite a bit larger than I had anticipated, as I had to move more parts of the `main` package than expected to avoid circular dependencies.

I've tried to split the commits between the actual new functions and removal of old ones and the updating of the usage of those functions and types.

I dont expect the tests to pass as when running locally the lint check was asking me to add comments to every exported symbol in containerLXC (as it was a new file).

However if the general direction of this PR is approved then I will go through and clean it up further, but didn't want to spend any more time on it if its going in the wrong direction.

Thanks

### CODE REVIEW

**Comment by tomponline** [comment]
Rebased onto master.

**Comment by stgraber** [comment]
Overall direction is good, though we'll definitely want this turned into a lot of smaller PRs that can be easier reviewed. This PR does have the issue of not being in order, so going from commits to commits I can't actually tell what's the impact of a particular piece of code being moved to its own package.

Just a few notes from the commits I briefly went through:
 - We'll want all those new packages to be golint clean and be added to the test suite
 - On the Response side, I believe @monstermunchkin was also looking at moving all of those to a separate package, probably worth prioritizing
 - CPU rebalancing would make more sense in a cgroup package I think. We were going to eventually need that anyway to properly handle cgroupv2 next cycle
 - I think we'll want to figure out the best way to split API endpoint logic between what's purely API (marshal/unmarshal, etag, ...), what belongs in the package itself and what belongs in the DB package. Then reuse that pattern for anything we're splitting out of main. Operations is the first such instance I'm seeing and the way it's done looks reasonable to me. We may want to reconsider Render() eventually as it's hardcoding URL paths which feel like belong more in the API layer, but close enough.
 - Any reason for `instancetype` package rather than `instance/type` sub-package?
 - I would stay as far way from Storage as possible for now as we have a separate branch moving it to a package already
 - Seccomp and AppArmor deserve their own packages
 - We probably want to wait for Storage to be sorted before digging too much into Migration

**Comment by stgraber** [comment]
As for immediate next steps, I think we can attack:
 - `response` as its own package (check if @monstermunchkin doesn't have it ready to push already)
 - `instance/type` re-shuffle
 - `seccomp` and `apparmor` packages

If you have a bit of time tomorrow morning before we meet, take a look at #5717, sync with @monstermunchkin on the goal behind the storage API rework and we'll chat about it in our meeting.

I've been quite terrible at getting the storage side of things to move forward but I'm hoping that now that we have actual work blocked on it, we can move forward with it, updating some of it based on what we learned with the other package reshuffle we've done lately.

**Comment by tomponline** [comment]
@stgraber thanks, have synced with @monstermunchkin on the response package and he's got a PR for response and operations, which is great.

I'll put a PR up for the instance/type re-shuffle, the reason I didn't go with `instance/type` is to avoid the reserved worked `type` and forcing users of the package to have to import it and then alias it to potentially different names each time. But happy to call it that and then alias it as `instancetype` during import.

The originally tried to move seccomp and apparmor into their own packages and the issues I hit were:

- They both depend on the `container` type, which is defined in main so cannot be imported when moving to a different package. So it requires `container` (or as we are getting rid of `container` then changing it to accept `ContainerLXC` or `Intstance`) to be moved into their own package(s) first. And because `ContainerLXC` uses those functions, it cannot access them if they are defined in main (without manually linking each one, which is possible but time consuming and messy), so they effectively have to be moved together.

- Even after I had done that, I then hit the circular dependency issue because the `ContainerLXC` struct needs to import the `apparmor` and `seccomp` package, which also needs to import the package where `ContainerLXC` is defined. Now from what I can see in `apparmor` it would probably get away with accepting an `Instance` rather than a `ContainerLXC`, so if we were able to define those 2 in separate packages then this could work. For `seccomp` however it uses some of the container's IDMAP functions and so will require a `ContainerLXC` so will hit the circular dependency issue.

- As soon as `seccomp` is defined in `Instance` package then this prevents `ContainerLXC` being defined in its own package as you get a circular dependency on `instance` package.

**Comment by tomponline** [comment]
@stgraber update on `instancetype` vs `type`, I had instinctively avoided calling it `type`, but trying it now Go prevents me from defining a package called `type` anyway, so will stick with instancetype.

**Comment by tomponline** [comment]
@stgraber I've been thinking about the package splitting issue and I think that defining some smaller interfaces inside the split packages (such as `seccomp` and `appamor`) would allow them to be kept separate without relying on importing the large `Instance` interface or directly needing `ContainerLXC`. I'll give it a go.

**Comment by tomponline** [comment]
@stgraber I got almost there with moving seccomp to its own package using a specialised non-exported instance interface. But I was foiled at the last minute by seccomp's use of `findContainerForPid()` which is defined in `main` and returns a `container`. Which stops me from linking the function from main into the `seccomp` package too due to the return signature.

I should be able to move that function to its own package though which can then import the `instance` package as `seccomp` wont need to import `instance` to use it. However that blocks me completing this until at least the `instance` interface has been moved to its own package.

**Comment by stgraber** [comment]
Going to close this one for now in favor of the smaller branches we've been sending through to get this in cleanly.

Don't delete the branch though, we certainly still want to pull commits from it!

**Pull request closed without merging**
