### PR TITLE
lxd/vm: Add udev rule fallback

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by tomponline** [comment]
What does this fix?

**Comment by stgraber** [comment]
Fixes potential races where the path we check for doesn't exist at the time systemd considers the unit.

**Comment by tomponline** [comment]
@stgraber looks like there is a formatting issue

**Comment by stgraber** [comment]
Yup, fixed now

**Pull request merged**
