### PR TITLE
Fix bad tests hiding return values

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Retracting while I figure out what's going on with CEPH.

**Comment by stgraber** [comment]
found another CEPH issue, will dig into it now

**Comment by stgraber** [comment]
All green, jenkins test results at: https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/5430/

**Comment by stgraber** [comment]
@brauner ready to go

**Comment by freeekanayaka** [comment]
Yeah, this was long due indeed, thanks.

**Pull request merged**
