### PR TITLE
Make the client utility compatible with darwin, move around util.go.

### PR DESCRIPTION
**Pull request by pcdummy**
This patch moves stuff in util.go around so shared is compatible with Darwin (Mac OS-X).
Not shure about GetFileStat (shared/util.go:26), lxc seems to work on darwin tough.

### CODE REVIEW

**Comment by stgraber** [comment]
So I'd just move IsBridge to lxd/networks.go since it's not actually shared with anything else.

**Comment by stgraber** [comment]
You also seem to be missing the removal of the stuff you moved to util_unix from util.go itself.

**Comment by pcdummy** [comment]
You need `IsBridge` to generate an ssl certificate, which is required on the client also. Right?

**Comment by stgraber** [comment]
Actually, there's no good reason for the IsBridge() in there. If I have an IP on a bridge, I want it in the certificate...

So I'd recommend you drop the IsBridge check from certs.go, then move IsBridge to lxd/networks.go and drop the darwin specific version of shared/networks.go

**Comment by stgraber** [comment]
I'd also recommend calling things _linux when they are using Linux-specific interfaces. /sys is a linux-ism so it won't be available on any other unix OS.

**Comment by pcdummy** [comment]
Refs issue #815

**Pull request merged**
