### PR TITLE
fix busybox image

### PR DESCRIPTION
**Pull request by tych0**
don't merge yet, I'll add a real discussion of the issue when I write up a
patch to the busybox ML. for now, hopefully this will test that it actually
works in jenkins.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like we hit a bug in go tip, lets retry.

Jenkins: please test this

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by tych0** [comment]
is there something equivalent to travis' allowed_failures that we can use so go tip doesn't block us?

**Comment by stgraber** [comment]
There's probably a plugin for that :)

**Comment by tych0** [comment]
Ok, I couldn't decide what the right fix was, so I just mailed their list to ask them about it instead. Anyway, I've updated the comment here and this should be ok to merge now. Hopefully between this and the other fix the test suite reliability goes up somewhat.

**Pull request merged**
