### PR TITLE
More lints suggested by golint.

### PR DESCRIPTION
**Pull request by pcdummy**

### CODE REVIEW

**Comment by stgraber** [comment]
Changes to the yaml field names (yaml:"blah") breaks the REST API and causes the travis failure.

**Comment by pcdummy** [comment]
I don't know what to do with these:

    api10.go:51:3: don't use underscores in Go names; var backing_fs should be backingFs
    container_delete.go:16:2: don't use underscores in Go names; var backing_fs should be backingFs
    containers.go:37:2: struct field rootUid should be rootUID
    containers.go:290:2: don't use underscores in Go names; var backing_fs should be backingFs
    containers_post.go:181:2: don't use underscores in Go names; var backing_fs should be backingFs
    db.go:18:2: error var DbErrAlreadyDefined should have name of the form ErrFoo
    db.go:20:2: comment on exported var NoSuchObjectError should be of the form "NoSuchObjectError ..."
    db.go:27:2: error var NoSuchObjectError should have name of the form ErrFoo
    db.go:39:7: don't use ALL_CAPS in Go names; use CamelCase
    db.go:39:7: exported const DB_CURRENT_VERSION should have comment or be unexported
    db.go:42:7: don't use ALL_CAPS in Go names; use CamelCase
    db_test.go:11:7: don't use ALL_CAPS in Go names; use CamelCase
    devices.go:12:1: exported function DeviceToLxc should have comment or be unexported
    devices.go:75:1: exported function ValidDeviceType should have comment or be unexported
    devices.go:92:1: exported function ValidDeviceConfig should have comment or be unexported
    devices.go:167:1: exported function AddDevices should have comment or be unexported
    devlxd_gc.go:29:6: exported type DevLxdResponse should have comment or be unexported
    devlxd_gc.go:34:1: exported function OkResponse should have comment or be unexported
    devlxd_gc.go:38:6: exported type DevLxdHandler should have comment or be unexported
    devlxd_gc.go:201:6: exported type ConnPidMapper should have comment or be unexported
    devlxd_gc.go:205:1: exported method ConnPidMapper.ConnStateHandler should have comment or be unexported
    devlxd_gc.go:279:5: error var pidNotInContainerErr should have name of the form errFoo
    images.go:25:2: don't use ALL_CAPS in Go names; use CamelCase
    images.go:25:2: exported const COMPRESSION_TAR should have comment (or a comment on this block) or be unexported
    images.go:26:2: don't use ALL_CAPS in Go names; use CamelCase
    images.go:27:2: don't use ALL_CAPS in Go names; use CamelCase
    images.go:28:2: don't use ALL_CAPS in Go names; use CamelCase
    images.go:29:2: don't use ALL_CAPS in Go names; use CamelCase
    operations.go:17:16: should omit type map[string]*shared.Operation from declaration of var operations; it will be inferred from the right-hand side
    operations.go:19:1: exported function CreateOperation should have comment or be unexported
    operations.go:59:1: exported function StartOperation should have comment or be unexported
    response.go:25:6: exported type Response should have comment or be unexported
    response.go:46:1: exported function FileResponse should have comment or be unexported
    response.go:78:1: exported function WriteJSON should have comment or be unexported
    response.go:107:1: comment on exported function SyncResponse should be of the form "SyncResponse ..."
    response.go:116:5: exported var EmptySyncResponse should have comment or be unexported
    response.go:172:1: exported function AsyncResponse should have comment or be unexported
    response.go:176:1: exported function AsyncResponseWithWs should have comment or be unexported
    response.go:180:6: exported type ErrorResponse should have comment or be unexported
    response.go:185:1: exported method ErrorResponse.Render should have comment or be unexported
    response.go:211:5: exported var NotFound should have comment or be unexported
    response.go:212:5: exported var Forbidden should have comment or be unexported
    response.go:213:5: exported var Conflict should have comment or be unexported
    response.go:215:1: exported function BadRequest should have comment or be unexported
    response.go:219:1: exported function InternalError should have comment or be unexported
    response.go:223:1: comment on exported function SmartError should be of the form "SmartError ..."
    serverconfig.go:16:2: don't use ALL_CAPS in Go names; use CamelCase
    serverconfig.go:16:2: exported const PW_SALT_BYTES should have comment (or a comment on this block) or be unexported
    serverconfig.go:17:2: don't use ALL_CAPS in Go names; use CamelCase
    serverconfig.go:47:1: exported function ValidServerConfigKey should have comment or be unexported
    template.go:16:6: exported type TemplateEntry should have comment or be unexported

**Comment by pcdummy** [comment]
I don't know why the tests still fails.

**Comment by pcdummy** [comment]
The problem here is:

    $ curl -s -k --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key https://127.0.0.1:8443/1.0/images
    {"type":"sync","status":"Success","status_code":200,"metadata":null

**Comment by pcdummy** [comment]
YEAH :)

**Pull request merged**
