### PR TITLE
Fix LXD forkmount with liblxc 3.1

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by brauner** [comment]
Somehow jenkins still looks unhappy. ;(

**Comment by stgraber** [comment]
@brauner yeah because liblxc is busted when inserting a mount for a file instead of a dir...

I provided details on IRC, short version is: https://paste.ubuntu.com/p/SpsZmMkzBb/

**Comment by stgraber** [comment]
So we'll need this to get fixed in liblxc and likely have the fix introduce an API extension so we can check for that rather than the original one and detect whether liblxc will actually do what we want, otherwise fallback to the old code.

**Comment by stgraber** [comment]
As unfortunately the 3.1 release is broken, so we'll need to skip this code when running on an unpatched version of it.

**Comment by stgraber** [comment]
@brauner preference on the name? mount_injection1? mount_injection_file?

Once we pick a name, I can update my branch to look for that, which will fix LXD, then we can fix liblxc and have LXD use that codepath again.

**Comment by brauner** [comment]
All that should be needed on LXC is remove instead of unlink.

**Comment by stgraber** [comment]
@brauner hmm, the unlink isn't what's failing, the mknod call is

**Comment by stgraber** [comment]
@brauner anyway, this branch should be good to go, then the readme one can go since it's not touching code and my third branch needs a retry but should then be fine

**Pull request merged**
