### PR TITLE
Optional firewall

### LINKED ISSUE #2647: Disabling iptables rules injected by lxd networks.
* Distribution: Ubuntu
 * Distribution version: 16.04
 * The output of "lxc info" or if that fails:
   * Kernel version: 4.4.0-47-generic
   * LXC version: 2.0.5
   * LXD version: 2.5
   * Storage backend in use: btrfs

Can a feature be added to disable the iptables roles injected by LXD networking.
Now I you setup a (ufw) firewall, it will be canceld out by lxd and for example if forwards all IPv6 traffic.

### PR DESCRIPTION
**Pull request by simondeziel**
Makes firewall filter rule insertion optional. Add ip6tables filter rules while at it.

Closes #2647

### CODE REVIEW

**Comment by stgraber** [comment]
I guess we'll want to also drop TCP dhcp in lxd/networks.go (master branch) then. /etc/services lists both ports as reserved but that indeed doesn't appear to ever be used.

To make things consistent with current LXD, the variable should probably also toggle the INPUT rules, so every rule in the filter table, only leaving mangle and nat unchanged.

**Comment by simondeziel** [comment]
Indeed the TCP/67 rules should also be removed from the current LXD. I can propose a branch if you'd like.

As for the INPUT rules, I don't think they should be toggled the same as the FORWARD ones. The INPUT rules are to let dnsmasq do it's job (DNS/DHCP) so it always have to be authorized. If a user doesn't want dnsmasq to begin with, they will simply not use lxd-bridge.

**Comment by stgraber** [comment]
@simondeziel ok but then it's consistent with what was done in recent LXD. So maybe we should change current LXD to match that too...

**Comment by stgraber** [comment]
Sent https://github.com/lxc/lxd/pull/2655

**Pull request merged**
