### PR TITLE
removed the `-p 1053` param from the `dig` call

### PR DESCRIPTION
**Pull request by dn**
by default the DNS listens on 53.

### CODE REVIEW

**Comment by stgraber** [comment]
I think I'd go the other way around and have the doc recommend setting `core.dns_address :1053` as while the default DNS port is indeed 53, the likelihood of that conflicting with a local DNS cache/resolver is quite high.

**Review by tomponline — COMMENTED** [review]
My opinion on this is that we should better show that the port used here should relate to the port specified in the `core.dns_address` server setting (https://linuxcontainers.org/lxd/docs/master/server/#core-configuration) as this tutorial currently lacks an explanation as to where that port number comes from.

**Comment by tomponline** [comment]
Snap!

**Comment by dn** [comment]
Does it make sense to add `-p <DNS_server_PORT> ` to the `dig` call? That alone would have helped me.

**Comment by tomponline** [comment]
> Does it make sense to add `-p <DNS_server_PORT> ` to the `dig` call? That alone would have helped me.

I think so. And add a section that shows how that has been set in LXD.

**Comment by stgraber** [comment]
Cool, looks like this branch needs a rebase so we just have the one commit and the commit should be signed off (Signed-off-by) line.

**Pull request merged**
