### PR TITLE
lxd/storage/drivers: Add a reverter stage for failed VM snapshot with LVM backend

### PR DESCRIPTION
**Pull request by gabrielmougard**
closes: #11431

### CODE REVIEW

**Comment by tomponline** [comment]
Great thanks! How did u come across it?

**Comment by tomponline** [comment]
I'm a bit confused, did you experience a problem that caused you to look into this?

**Comment by tomponline** [comment]
OK makes sense thanks. Although looking at the original error:

> Error: Error deleting storage volume: Error removing LVM logical volume: Failed to run: lvremove -f /dev/vmpool127383/virtual-machines_<vm_name>.block: exit status 5 (Logical volume vmpool127383/virtual-machines_<vm_name>.block in use.)

I don't see how removing the mount path is going to help with that. Thats not to say its not useful still, but I don't think it will fix the issue (or worse mask it).

**Comment by gabrielmougard** [comment]
@stgraber do you have any ideas on how to approachh this one ? Before calling `lvcreate` here `lxd/storage/drivers/driver_lvm_utils.go:line 418`, where do we check that we have enough storage resources before creation the volume ?

**Comment by tomponline** [comment]
@gabrielmougard the fix here isnt to check for sufficient capacity (lvm will do that for you by failing). The fix needed is to properly clean up on error.

**Comment by gabrielmougard** [comment]
@tomponline right. I see that there is a `removeLogicalVolume` in the reverter but it's being added after the `lvcreate` command so it should not be executed by `revert.Fail()`. Could it be part of the problem ?

**Comment by tomponline** [comment]
So looking at that function in more detail, the call to:

```go
_, err = d.createLogicalVolumeSnapshot(d.config["lvm.vg_name"], parentFSVol, fsVol, true, d.usesThinpool())
```

Is the last call in that function, so there's no need to add a revert for it (it either succeeds and the function is done or it fails and would never need the revert).

I don't think we are yet clear on the actual problem, and thus we don't know how to go forward with the fix.

Please can you reproduce the error and then show me the output of `sudo lvs` and `mount` on your system when the snapshot fails and when you cannot delete the instance. Thanks

**Comment by gabrielmougard** [comment]
@tomponline it's strange... I can't reproduce the bug. The described scenario works just fine now (I'm on LXD 5.11) : 

```bash
lxc storage create pool1 lvm size=12GiB lvm.use_thinpool=false
# Storage pool pool1 created

lxc init images:ubuntu/jammy v1 --vm -s pool1
# Creating v1 (OK)

lxc config device set v1 root size.state=1GiB
# OK

lxc snapshot v1 snap0
# Error: Create instance snapshot: Error creating LVM logical volume snapshot: Failed to run: lvcreate -n virtual-machines_v1-snap0 -s /dev/pool1/virtual-machines_v1 --setactivationskip y -l 100%ORIGIN -pr: exit status 5 (Insufficient suitable allocatable extents found for logical volume virtual-machines_v1-snap0.)

lxc delete v1
# OK => this time it works...

##########################
# Here is the output of `sudo lvs`

sudo lvs
#  LV                        VG    Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
#  virtual-machines_v1       pool1 -wi-ao---k 100.00m                                                    
#  virtual-machines_v1.block pool1 -wi-ao---k  10.00g

########################
# Here is the output of `mount`

mount

# sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
# proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
# udev on /dev type devtmpfs (rw,nosuid,noexec,relatime,size=15974468k,nr_inodes=3993617,mode=755,inode64)
# devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
# tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3203468k,mode=755,inode64)
# /dev/nvme0n1p2 on / type ext4 (rw,relatime,errors=remount-ro)
# securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
# tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
# tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
# tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755,inode64)
# cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime)
# cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
# pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
# efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
# bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
# cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
# cgroup on /sys/fs/cgroup/misc type cgroup (rw,nosuid,nodev,noexec,relatime,misc)
# cgroup on /sys/fs/cgroup/rdma type cgroup (rw,nosuid,nodev,noexec,relatime,rdma)
# cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,clone_children)
# cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
# cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
# cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
# cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
# cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
# cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
# cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
# cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
# systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=28,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=15057)
# mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
# hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
# debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
# tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
# fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
# configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
# /var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/core20_1822.snap on /snap/core20/1822 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/canonical-livepatch_164.snap on /snap/canonical-livepatch/164 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/spotify_60.snap on /snap/spotify/60 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/gnome-3-38-2004_115.snap on /snap/gnome-3-38-2004/115 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/snapd_18357.snap on /snap/snapd/18357 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/gnome-3-28-1804_161.snap on /snap/gnome-3-28-1804/161 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/core_14784.snap on /snap/core/14784 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/core20_1828.snap on /snap/core20/1828 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/snap-store_638.snap on /snap/snap-store/638 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/lxd_24483.snap on /snap/lxd/24483 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/gnome-3-38-2004_119.snap on /snap/gnome-3-38-2004/119 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
# /var/lib/snapd/snaps/snap-store_558.snap on /snap/snap-store/558 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
# lxcfs on /var/lib/lxcfs type fuse.lxcfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
# tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=3203468k,mode=755,inode64)
# tmpfs on /run/user/125 type tmpfs (rw,nosuid,nodev,relatime,size=3203464k,mode=700,uid=125,gid=130,inode64)
# gvfsd-fuse on /run/user/125/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=125,group_id=130)
# nsfs on /run/snapd/ns/canonical-livepatch.mnt type nsfs (rw)
# nsfs on /run/snapd/ns/lxd.mnt type nsfs (rw)
# tmpfs on /var/snap/lxd/common/ns type tmpfs (rw,relatime,size=1024k,mode=700,inode64)
# nsfs on /var/snap/lxd/common/ns/shmounts type nsfs (rw)
# nsfs on /var/snap/lxd/common/ns/mntns type nsfs (rw)
# tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=3203464k,mode=700,uid=1000,gid=1000,inode64)
# gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
# /dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
# nsfs on /run/snapd/ns/snap-store.mnt type nsfs (rw)
# nsfs on /run/snapd/ns/spotify.mnt type nsfs (rw)
# /var/lib/snapd/snaps/core18_2708.snap on /snap/core18/2708 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
# /var/lib/snapd/snaps/core18_2714.snap on /snap/core18/2714 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
```

Should we close this issue then because of the lack of a minimum bug reproducer ?

**Comment by tomponline** [comment]
@gabrielmougard did you mean to close this?

**Comment by gabrielmougard** [comment]
@tomponline I closed the issue yesterday yes.. I really could not reproduce the scenario I experienced with LXD 5.11. Can I close this PR then ?

**Pull request closed without merging**
