### PR TITLE
Storage: Removes usage of old storage pool loader

### PR DESCRIPTION
**Pull request by tomponline**
Includes https://github.com/lxc/lxd/pull/6915

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like there's some work to do on the go test front :)

**Comment by tomponline** [comment]
@stgraber yes indeed, the functional tests pass, but the unit tests dont. Do the unit tests actually create volumes on a storage device or is it faked somehow?

**Comment by stgraber** [comment]
@tomponline I think that may be the use case for the mock driver.

**Comment by tomponline** [comment]
@stgraber ah indeed, have found in the tests where the old storage layer loaded a 'mock' driver type, so now will set `storagePools.MockBackend = true` and then will need to implement as much of the mock backend as needed.

**Comment by stgraber** [comment]
Yeah, the old one was pretty much all empty, so hopefully, not much needs implementing.

**Comment by tomponline** [comment]
@stgraber have added mock driver, tests are looking better now.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
