### PR TITLE
Fix `lxc image` help

### PR DESCRIPTION
**Pull request by techtonik**
It is now
	help       - Presents details on how to use lxd.
	image      - lxc image import <tarball> [target] [--created-at=ISO-8601] [--expires-at=ISO-8601] [--fingerprint=HASH] [prop=value]
	info       - List information on containers.

### CODE REVIEW

**Comment by stgraber** [comment]
Hi,

Thanks for the fix, it looks good.

Your branch does need a few changes though:
 - Your commit message must contain "Signed-off-by: Firstname Lastname \<email\>"
 - You're changing a translated string without updating the translation template. Run "make i18n" and commit the resulting change to po/lxd.pot
 - Your Go formatting doesn't match that of "go fmt" (that's the current Travis failure), so you'll want to update your code to match.

**Comment by techtonik** [comment]
Well, I used GitHub to edit the file. The LXC thing still doesn't work for my workflow. The container is running, but I can't login and share folder inside.

**Comment by techtonik** [comment]
I better leave this to professionals. =)

**Comment by techtonik** [comment]
But frankly, I really find it awkward to write email down into commit message. It is too easy to forge, so it can not realistically serve any purpose. Commit has the author field already, and the repository is reviewed. If Mallory can inject commits into reviewed queue, she will add a signature as well. Not trusting people who submit stuff through GitHub doesn't make it more secure from attacks. It is just makes the contribution barrier higher.

**Comment by stgraber** [comment]
It's not that we don't trust people submitting through github, in fact we do get the e-mail address of any github contributor anyway.

The Signed-off-by line is a legal requirement of the Developer Certificate of Ownership which states that you are the author of the code that you're sending (didn't copy/paste it from somewhere else) and that you have the authority to submit this under the license of the project (as in, you don't have a contract with an employer which would prevent you from doing this).

**Comment by techtonik** [comment]
So, I don't understand how it works or why it here. People who are owned by employers through their contract (or somebody posing as them) can submit anything and sign it. So, what is the consequence with and without this DCO? I don't get it.

**Comment by stgraber** [comment]
With the DCO you can't say you didn't know and so it's clear that you are the one at fault and the one who should be sued should you have contributed stolen code (from your employer or someone else).

The name and e-mail isn't terribly important, it's just a standard convention that has been used by the Linux kernel community and that a lot of projects (us included) picked-up. The Signed-off-by part is important as it means "me the contributor of this patch, read the DCO and confirm that I am allowed to contribute this". If you do so even though you stole the code from someone (under an incompatible license) then you won't be able to deny that you knew that.

**Comment by stgraber** [comment]
Anyway, I'm done arguing about it. All LXC projects use the DCO, just like a ton of other open source projects, that's just how it is.

**Comment by techtonik** [comment]
Software developers are like lemmings. =) No offence. I just disagree with the position to follow the practice that you don't understand. But you probably being paid for that, so that's ok. Anyway, thanks for the help with containers. I finally got it started after 3+ years of different tries with no result. Yay!

**Comment by techtonik** [comment]
(if I didn't promise to deliver something working on LXC three years ago and didn't fail, I could had a job in that area too)

**Comment by techtonik** [comment]
I don't get why do not trust people by default. You can just say in guidelines to this repository "please don't commit stolen code, we don't accept it" and you'll be safe, but instead all these dances the meaningless DSO.

I think it is job of Canonical, who with Red Hat has the resources to protect default freedom for people to participate in open source projects in their free time. Getting paper permission from your owner looks like a promotion of slavery to me. I don't like the Python uses CLA, and I think that Canonical is wrong too to look at these guys.

Node.js got this right https://www.joyent.com/blog/broadening-node-js-contributions all others are just following trend afraid to speak to deal with that creeping nonsense.

**Pull request closed without merging**
