### PR TITLE
Handle VMs in instancesOnDisk

### LINKED ISSUE #9265: Update the instancesOnDisk function to handle VMs
The `instancesOnDisk` is called by the `instancesShutdown` function during LXD daemon shutdown when the cluster database isn't available (perhaps the cluster has lost quorum). It attempts to scan the local storage to find instances to shutdown.

However currently it only supports detecting containers, and it should be updated to detect VMs too.

### PR DESCRIPTION
**Pull request by monstermunchkin**
This fixes #9265.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
I do wonder why we don't use `instancesOnDisk` only and always for this shutdown process, rather than trying `instance.LoadNodeAll` first and then falling back to `instancesOnDisk`.

If the former has some benefit over the latter, then it would be good to add a comment there explaining the logic behind that.

**Comment by monstermunchkin** [comment]
Looking at the code, we need to know whether the database is online in order to call `ResetInstancesPowerState`.

**Comment by tomponline** [comment]
Yes indeed, although later on in that function it then goes onto to try and run multiple queries to set each instance's power state via the `c.VolatileSet` call. Could you add a check that skips those calls if `!dbAvailable`.

Also, just a small nit but the `c` var should be called `inst` now it refers to more than just containers.

**Review by tomponline — APPROVED** [review]

**Comment by stgraber** [comment]
@tomponline some of the things I can think of:
 - I'm not sure that InstanceOnDisk can give us the shutdown priority or timeout or any of those configs
 - On device shutdown, we don't get to save volatile key changes

**Comment by tomponline** [comment]
> @tomponline some of the things I can think of:
> 
>     * I'm not sure that InstanceOnDisk can give us the shutdown priority or timeout or any of those configs
> 
>     * On device shutdown, we don't get to save volatile key changes

Yep that makes sense thanks.

**Pull request merged**
