### PR TITLE
lxd/device/disk: Include network-config in cidata

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
@stgraber is there a reason we don't need to populate an empty config if not specified (like the others)?

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tomponline yeah, it's clearly an optional file since it's been working so far :)

**Comment by tomponline** [comment]
@stgraber ah ok, wasn't sure. Inconsistencies like this worry ne. I thought perhaps we have to override defaults in the other files by providing an empty file. Seems a bit odd that cloud init requires empty configs for the other ones now that this one can be missing.  But nothing we can do about that. 🙂

**Comment by stgraber** [comment]
@tomponline that's because network-config was introduced much after the others :)

**Comment by stgraber** [comment]
@tomponline @brauner good to go

**Comment by OddBloke** [comment]
Thanks for this!

**Pull request merged**
