### PR TITLE
Change 'containers' to 'instances' in used_by fields for projects and profiles

### PR DESCRIPTION
**Pull request by freeekanayaka**
First pass at #6491. I'm planning to change the user-visible bits in a separate branch.

### CODE REVIEW

**Comment by freeekanayaka** [comment]
I'm not sure anymore we want/need to do this, see the comment in the issue.

**Comment by stgraber** [comment]
@freeekanayaka looks like something is busted in UsedBy for networks?

**Comment by freeekanayaka** [comment]
@stgraber ah true, the used_by field for networks is not rendered using those db views (which are indeed unrelated), but still I had changed the networks integration tests to look for "/1.0/instances" instead of "/containers", regressing them. I assume we want "/1.0/instances" also for networks, so I fixed the code as well.

**Comment by stgraber** [comment]
@freeekanayaka yep, perfect, thanks

**Pull request merged**
