### PR TITLE
lxc: Switches to use Instance functions of client package

### PR DESCRIPTION
**Pull request by tomponline**
- Switches `lxc` CLI tool to use the `client` Instance functions.
- Adds `--instance-only` command line param and updates `--container-only` help to indicate it is deprecated (both still work).

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber apart from the .pot file issue. I've commented that out locally and run the tests and this passes.

**Comment by stgraber** [comment]
@tomponline the way you solve those is with:
 - make i18n
 - git add po/
 - git commit -s -m "i18n: Update translation templates" po/

**Comment by tomponline** [comment]
@stgraber thanks, I'd tried committing them, just without that specific message.

**Comment by tomponline** [comment]
@stgraber ready for review when you get a chance.

**Comment by stgraber** [comment]
Looks good to me

**Pull request merged**
