### PR TITLE
refuse to delete containers when running

### PR DESCRIPTION
**Pull request by tych0**
I have no idea if this works because the network is so bad here I can't run the test suite. But if it doesn't work, I'll fix it tomorrow :)

### CODE REVIEW

**Comment by tych0** [comment]
jenkins, test this please

**Comment by tych0** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@tych0 Jenkins triggers automatically on code changes so you only need to request it if it's a jenkins issue that needs re-trying.

**Comment by stgraber** [comment]
@tych0 your code still has the wait_for, so looks like you didn't push the fix :)

**Comment by tych0** [comment]
On Wed, Oct 07, 2015 at 03:43:20AM -0700, Stéphane Graber wrote:
> @tych0 your code still has the wait_for, so looks like you didn't push the fix :)

Ah, ok. I wondered why it hadn't started building...

**Comment by jsimonetti** [comment]
Shouldn't there be a lxc stop deletewhilerunning in the test?
Or add a --force flag?

```
+  my_curl -X DELETE https://${LXD_ADDR}/1.0/containers/deletewhilerunning | grep "container is running"
+  lxc stop deletewhilerunning
+  lxc delete deletewhilerunning
```

**Comment by stgraber** [comment]
nope, delete does the stop for you

**Comment by tych0** [comment]
jenkins: test this please

**Pull request merged**
