### PR TITLE
Console color support for Windows (fixes #1290)

### LINKED ISSUE #1290: Color support for Windows client
Working with #1236 - so far so good. But ANSI sequences are not rendered, because Windows console has an orthogonal API for color manipulation. This can be fixed by piping remote output through https://github.com/shiena/ansicolor

Where is the piping of from remote host occurs?

### PR DESCRIPTION
**Pull request by techtonik**
Signed-off-by: anatoly techtonik <techtonik@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

To have this branch tested by Jenkins, use the "ok to test" command.
To have a one time test done, use the "test this please" command.

Commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by techtonik** [comment]
jenkins: ok to test

**Comment by stgraber** [comment]
jenkins: ok to test

**Comment by stgraber** [comment]
@tych0 can you take a look at this? I remember you working on those Exec args recently because of JuJu.

**Comment by techtonik** [comment]
Oops. Wrong button pressed.

**Comment by stgraber** [comment]
This pull request didn't trigger Jenkins as its author isn't in the whitelist.

To have this branch tested by Jenkins, use the "ok to test" command.
To have a one time test done, use the "test this please" command.

Commands are simple Github comments of the format: "jenkins: COMMAND"

**Comment by tych0** [comment]
So I think this is ok, but I'm surprised that we don't close the socket on WebsocketRecv since that's what the API advertises. It's conceivable that we want to close it (in fact, I think we probably do).

Can you write a little wrapper for the ansi wrapper that turns it into a WriteCloser and keep the same API? After we merge this, I can send a patch to close things on WebsocketRecv.

**Comment by techtonik** [comment]
@tych0 WriteCloser is the interface for os.Stdout, not for socket. Are you sure you want to close os.Stdout and not the socket?

Actually, I tried to write the wrapper, but right now my knowledge about Go is too limited to understand how its "subclassing" model works. And also I don't understand what Close method on the console object should do. For me, it is the role of the code that provides Writer object to close it. Like `with` context manager in Python.

**Comment by tych0** [comment]
On Tue, Nov 10, 2015 at 01:13:59AM -0800, anatoly techtonik wrote:
> @tych0 WriteCloser is the interface for os.Stdout, not for socket. Are you sure you want to close os.Stdout and not the socket?

Yes, I think so. Mostly because this area of the code has always been
quite sticky, and in my experience it is better to close everything
you can.

> Actually, I tried to write the wrapper, but right now my knowledge about Go is too limited to understand how its "subclassing" model works. And also I don't understand what Close method on the console object should do. For me, it is the role of the code that provides Writer object to close it. Like `with` context manager in Python.

I don't think there is a good way besides something like:

type CloseWrapper struct {
  closer      io.Closer
  fancyWriter io.Writer
}

/* implement the Writer interface */
func (cw *CloseWrapper) Write(...) {
  return cw.FancyWriter(...)
}

func (cw *CloseWrapper) Close() error {
  return cw.closer.Close()
}

func getStdout() io.WriteCloser {
  return CloseWrapper{os.Stdout, ansicolor.NewAnsiColorWriter(os.Stdout)}
}

**Comment by techtonik** [comment]
Reading https://www.golang-book.com/books/intro/9 ... The question I have why it is not possible to create https://golang.org/pkg/io/#WriteCloser by something like:

func getStdout() io.WriteCloser {
  return io.WriteCloser{os.Stdout, ansicolor.NewAnsiColorWriter(os.Stdout)}
}

**Comment by tych0** [comment]
On Tue, Nov 17, 2015 at 07:23:46AM -0800, anatoly techtonik wrote:
> Reading https://www.golang-book.com/books/intro/9 ... The question I have why it is not possible to create https://golang.org/pkg/io/#WriteCloser by something like:
> 
> func getStdout() io.WriteCloser {
>   return io.WriteCloser{os.Stdout, ansicolor.NewAnsiColorWriter(os.Stdout)}
> }

Oh, that seems much better than what I suggested. Definitely go with
that :)

**Comment by techtonik** [comment]
=) Trying to test if that works just right now. Give me a couple of minutes.

**Comment by techtonik** [comment]
Looks like this doesn't work.

```
# github.com/lxc/lxd/lxc
lxc\exec_windows.go:19: invalid type for composite literal: io.WriteCloser
```

```diff
--- a/lxc/exec_windows.go
+++ b/lxc/exec_windows.go
@@ -13,8 +13,10 @@ import (
        "github.com/lxc/lxd/shared"
 )

-func getStdout() io.Writer {
-       return ansicolor.NewAnsiColorWriter(os.Stdout)
+func getStdout() io.WriteCloser {
+       // Windows doesn't process ANSI sequences natively, so we wrap
+       // os.Stdout for improved user experience for Windows client
+       return io.WriteCloser{io.Stdout, ansicolor.NewAnsiColorWriter(os.Stdout)}
 }

 func controlSocketHandler(c *lxd.Client, control *websocket.Conn) {
```

**Comment by techtonik** [comment]
There was a mistake in the code above and it still doesn't work.

```
github.com/lxc/lxd/lxc
# github.com/lxc/lxd/lxc
lxc\exec_windows.go:19: invalid type for composite literal: io.WriteCloser
```

```diff
--- a/lxc/exec_windows.go
+++ b/lxc/exec_windows.go
@@ -13,8 +13,10 @@ import (
        "github.com/lxc/lxd/shared"
 )

-func getStdout() io.Writer {
-       return ansicolor.NewAnsiColorWriter(os.Stdout)
+func getStdout() io.WriteCloser {
+       // Windows doesn't process ANSI sequences natively, so we wrap
+       // os.Stdout for improved user experience for Windows client
+       return io.WriteCloser{ansicolor.NewAnsiColorWriter(os.Stdout), os.Stdout}
 }

 func controlSocketHandler(c *lxd.Client, control *websocket.Conn) {
```

**Comment by techtonik** [comment]
Still fighting with it.

**Comment by techtonik** [comment]
I still don't understand those type/interface stuff.
```
github.com/lxc/lxd/lxc
# github.com/lxc/lxd/lxc
lxc\exec_windows.go:29: cannot use WrappedWriteCloser literal (type WrappedWriteCloser) as type io.WriteCloser in return argument:
        WrappedWriteCloser does not implement io.WriteCloser (Write method has pointer receiver)
```

```diff
--- a/lxc/exec_windows.go
+++ b/lxc/exec_windows.go
@@ -13,8 +13,20 @@ import (
        "github.com/lxc/lxd/shared"
 )

-func getStdout() io.Writer {
-       return ansicolor.NewAnsiColorWriter(os.Stdout)
+
+type WrappedWriteCloser struct {
+       io.Closer
+       wrapper io.Writer
+}
+
+func (wwc *WrappedWriteCloser) Write(p []byte) (int, error) {
+       return wwc.wrapper.Write(p)
+}
+
+func getStdout() io.WriteCloser {
+       // Windows doesn't process ANSI sequences natively, so we wrap
+       // os.Stdout for improved user experience for Windows client
+       return WrappedWriteCloser{os.Stdout, ansicolor.NewAnsiColorWriter(os.Stdout)}
 }
```

**Comment by techtonik** [comment]
Missed &.. Still don't get why I need & to return interface. Anyway, this now works. Rebased for the master.

**Comment by tych0** [comment]
jenkins: ok to test

**Comment by tych0** [comment]
Thanks!

**Pull request merged**
