### PR TITLE
lxd/resources: Handle unreadable VPD

### LINKED ISSUE #10412: Failed to retrieve PCI information: Failed to read \"/sys/bus/pci/devices/0000:03:00.0/vpd\": read /sys/bus/pci/devices/0000:03:00.0/vpd: input/output error
```
snap list lxd
Name  Version      Rev    Tracking     Publisher   Notes
lxd   git-b670447  23056  latest/edge  canonical✓  -
```
Is there away to work around this / safe to jump back to rolling releases?

### PR DESCRIPTION
**Pull request by stgraber**
Closes #10412

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline should be ready to merge once it builds properly (can't be tested by jenkins or even our lab).

**Comment by tomponline** [comment]
Looks like jenkins is unhappy

**Comment by stgraber** [comment]
Just Github being crap...

**Comment by stgraber** [comment]
@tomponline should be good to go, the few builds that survived the Github API built LXD properly.

**Pull request merged**
