### PR TITLE
Add /1.0/events to the /dev/lxd API (and some cleanup and fixes)

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
I'm still working on adding a couple of tests for it.

**Comment by brauner** [comment]
On Thu, Dec 21, 2017 at 10:52:20PM +0000, Stéphane Graber wrote:
> I'm still working on adding a couple of tests for it.

I'll just wait for you to ping me. ;)

**Comment by stgraber** [comment]
Now includes tests, documentation and API extension.

If Jenkins is happy, this should be ready to merge.

**Comment by stgraber** [comment]
@brauner ready

**Pull request merged**
