### PR TITLE
Implement "lxc operation"

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by brauner** [comment]
Some reasons for this would be good. :)

**Comment by stgraber** [comment]
It's useful for developers and users to see what's going on in the background and to have a chance to cancel things that are stuck.

We've always had this in our API, we just never bothered to expose it.

**Comment by brauner** [comment]
I guess an API extension is not really needed since this has always been there.

**Comment by stgraber** [comment]
Correct, nothing changed at the API level, this branch even works if run against a LXD 2.0.0 server.

**Pull request merged**
