### PR TITLE
Re-import images in pools if volume.block.filesystem has changed

### LINKED ISSUE #3811: Changing volume.block.filesystem causes container creation failures
When changing volume.block.filesystem on a pool with existing images, then creating a container from one of those existing image, you'll get the wrong filesystem and will most likely hit an error as LXD tries to run fs-specific code for the wrong filesystem.

Instead we should add code to the LVM and Ceph backends so that when doing CreateFromImage, we check whether the existing volume's filesystem (block.filesystem) matches the one of the new one, if they don't, then the existing volume should be deleted and a new image import be done.

### PR DESCRIPTION
**Pull request by albertodonato**
Fixes #3811

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks like a bug in the ceph storage driver which doesn't allow changing the filesystem for new volumes.
@brauner

**Comment by brauner** [comment]
@stgraber, @albertodonato, this is not a bug this was an intentional decision when first implementing the ceph storage driver. If you want this to be enabled you need to adapt `StoragePoolUpdate()`.

**Comment by stgraber** [comment]
@brauner was there a specific reason not to allow it? Seems to me like ceph and lvm should be behaving the same in this regard.

**Comment by brauner** [comment]
@stgraber, since the ceph driver was relatively new to us the original idea was to implement the minimal working set of features and then expand the functionality as needed. So as a first pass I didn't enable changing any properties since I wasn't sure how robust ceph would be in the face of all the map-unmap routines that it requires. Especially, since we've been bitten by the LVM driver quite often when the whole storage api first landed.

**Comment by albertodonato** [comment]
@brauner @stgraber if allow property change is something we'll do in the future, I'd leave the code as it is and just comment out the test (so we remember that the code for the feature is there) for the ceph case

**Comment by brauner** [comment]
@albertodonato, my point wasn't that we shouldn't enable it now but that I didn't want to enable it right when I implemented the driver. We've seen good results with ceph and it's fine to enable this property now in `StoragePoolUpdate()`. :)

**Comment by stgraber** [comment]
So just to record some of the IRC discussions. This is currently blocked on ceph behaving more like LVM and allowing for a number of configuration keys to be updated after pool creation.

As part of fixing that particular thing, we should also cleanup the way key handling is done in StoragePoolUpdate so that we no longer have the very very long hardcoded list of all the storage config keys in every storage driver. The suggested approach is to have each storage driver implement ConfigOptions() and UpdatableConfigOptions() functions which each return a list of strings representing the config keys that are supported by the backend and that can be updated after the fact.

It will then be pretty straightforward to do a first pass check on all storage configs and then individually handling the keys that got changed.

**Comment by stgraber** [comment]
Ok, so lets not keep this blocked on Ceph for now. @brauner will send a branch which fixes the storage pool update handling and allows for ceph storage pools options to be updated at which point the ceph testing part of this branch can be added.

For now, just drop that part of the branch so we can merge it.

**Comment by albertodonato** [comment]
@stgraber what the approach I suggested above? Keep the change and just comment out the test?
I'm afraid we'll forget to re-add it once the ceph rework is done, otherwise

**Comment by brauner** [comment]
@albertodonato, drop the test, please. I've got an issue open that references the ceph storage driver property changing so we won't forget.

**Comment by brauner** [comment]
I cherry-picked your commits onto my branch which reworks the storage pool update logic so I won't be blocked on you making the change here. Your Signed-off-by line is of course retained! See https://github.com/lxc/lxd/issues/3834 .

**Pull request closed without merging**
