### PR TITLE
Short Id for Images

### PR DESCRIPTION
**Pull request by jensg-st**

### CODE REVIEW

**Comment by jensg-st** [comment]
Btw, the help seems to be quite inconsistent, e.g. between config and image. The config has a knid of explanation for each command where config just has the command without any explanation. I prefer the config one.

**Comment by tych0** [comment]
Is there any reason to hard code 12 characters here? Is it possible to use an arbitrary-length prefix?

**Comment by jensg-st** [comment]
You mean turning it into a like statement? Or defining a constant?

**Comment by tych0** [comment]
I'm not sure what the best way to implement it would be, but ideally I wouldn't need to provide exactly 12 characters of hash, anything not ambiguous from say 6 to 64 characters would work.

**Comment by jensg-st** [comment]
I can do it, but don't see the real benefit to be honest. Ids are getting used by other servers, so I'm assuming this communication would run on the full id anyway. The short id is for users only and they would use what they see. In this case 12 characters. That is what is getting displayed on the screen.

I would use a minimum of 12 anyway, because the likelihood of returning two images from the database is basically zero. If you go down to 6, there is a good chance of running into trouble and you have to handle the event of getting two images from the database. 

I chose 12 because it was the cleanest way in SQL terms and for me it is logical. Use long or short id. I can do it, but with my SQL knowledge you would end up with something like:

select  * from images where  fingerprint like '?' and length(?) > minlength, e.g. 8

where '?' is the id you pass in plus %.

On the other hand, Git does the following:


> Git is smart enough to figure out what commit you meant to type if you provide the first few characters, as long as your partial SHA-1 is at least four characters long and unambiguous — that is, only one object in the current repository begins with that partial SHA-1.

> Generally, eight to ten characters are more than enough to be unique within a project. One of the largest Git projects, the Linux kernel, is beginning to need 12 characters out of the possible 40 to stay unique.

Do you want to copy that behavior, so basically you can send in one character as long as lxd returns one image and return an error, if the result set has more than one entry? That would be a simple like statement plus error handling. 

I wouldn't mind if I can just use 12 chars of the full id. Less error-prone, but it is your call.

**Comment by jensg-st** [comment]
I will play around with QueryRow and normal error handling for multiple rows and see what's best.

**Comment by tych0** [comment]
Yep, I use the git behavior quite frequently, so I imagine `lxc` having the same thing. That would be great!

**Comment by jensg-st** [comment]
Next try. I have moved all image requests based on fingerprint in db.go. The return value is now a struct (which could potentially be merged with the existing image struct). This makes it easier to implement the short id approach. Data overhead should be minimal, because it is requesting just one image.

I added a consistent 404, if the image could not be found. 

The dereferenceAlias has been changed as well. With this approach it would not be necessary anymore to fetch the list of images first, because shortened ids will be sorted on the server side.

I have tested all the functions and ran the test, but the change is quite complex.

**Comment by stgraber** [comment]
Can you get rid of all that commented code if it's no longer useful?

**Comment by jensg-st** [comment]
Cleaned up

**Comment by stgraber** [comment]
Looks like your branch needs rebasing.

**Comment by jensg-st** [comment]
Too many conflicts now. No time to merge/rebase. Ditching it for now. I will do it another time.

**Comment by stgraber** [comment]
I've submitted #386 with the result of a rebase.

**Comment by stgraber** [comment]
Closing this one since the rebased one was merged.

**Pull request closed without merging**
