### PR TITLE
lxd/storage/ceph: Fix ext4 shrinking

### PR DESCRIPTION
**Pull request by stgraber**
Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Without this the `UnmountTask` wrapper used during ext4 shrinking will cause an RBD unmap before trying to interact with the block device, failing.

This is a bit of a unique CEPH thing at this point where we really have those separate things, mapping and mounting. Because the two are combined in our API (with reason as CEPH is a weird case), we're adding an extra flag to the volume struct to control the unmount behavior in such cases.

**Comment by tomponline** [comment]
@stgraber I was thinking more about this change, and perhaps this could be moved into the generic `shrinkFilesSystem` function, as it could be applied in the future to the LVM storage driver, as we could deactivate the volumes when they are not in use so that the device doesn't appear either.

That way, the `shrinkFileSystem` function would always set the `keepDevice` to `true` and it would be up to the drivers to respect it if needed.

I was also thinking, we could just add this as an argument to the `UnmountTask` function and `UnmountVolume()` functions respectively, rather than pass it around as a property of the `Volume`, that way it would be clearer that this is only used during specific unmount scenarios.

I'm happy to make the PR if you agree with the approach?

**Comment by tomponline** [comment]
@stgraber alternatively we could rename this variable to something like `unmountMode` and give it its own numeric type, e.g. `type UnmountMode int`, then have constants for `UnmountFull` - which would be the zero value default, and `UnmountOnly` which would be set only for `shrinkFileSystem`.

By avoiding the term "device" in the variable name, it means that for drivers that don't unmap devices, both options still make sense (i.e if "full" is only unmounting, then both "unmount full" and "unmount only" are the same), but for drivers that do unmap devices during a "full" unmount, the "unmount only" option then indicates that only the directory is unmounted.

**Comment by stgraber** [comment]
Ah yeah, if we want to start deactivating LVs, then that makes sense.

**Pull request merged**
