### PR TITLE
Initial documentation for production use of LXD

### PR DESCRIPTION
**Pull request by naisanza**
A collection of server changes in order for LXD to function correctly when many file operations are requried

Signed-off-by: Eric Jaw <naisanza@gmail.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Looks like you forgot to sign-off your commit. Please make sure every one of your commits include the "Signed-off-by:" line. See CONTRIBUTING.md for details

**Comment by stgraber** [comment]
@naisanza ping

We can't merge this unless it's signed-off.

**Comment by naisanza** [comment]
I thought I edited the initial commit comment above

**Comment by stgraber** [comment]
Oh, sorry, I didn't see that.

Yes you did indeed, however what we care about is what's in the git branch, not the github comments.
You can edit your commit message with "git commit --amend" and then push it over to github with "git push --force".

If you don't have the time to do so, I can do it for you in my branch, since your comment above clearly shows your intent to have this work signed-off.

**Comment by naisanza** [comment]
@stgraber perfect! Yes please!

**Pull request closed without merging**
