### PR TITLE
Fix status code

### PR DESCRIPTION
**Pull request by tych0**

### CODE REVIEW

**Comment by stgraber** [comment]
Does that also close #691 then?

**Comment by tych0** [comment]
Not exactly, the values are still hardcoded here: https://github.com/lxc/lxd/pull/1075/files#diff-222bdbc19dc142063660fe9d95d71ca0R55

**Comment by stgraber** [comment]
Fair enough. I'm not sure what we can really do about #691 then. We can't exactly go parse the LXC code short of having a wrapper around our code to do that (similar to protobuf).

At the same time, it'd be an API break in LXC to change any of those, so it's probably fine to hardcode them.

**Comment by tych0** [comment]
Yeah, that's why I haven't done much with it yet :)

**Comment by stgraber** [comment]
Not sure how I feel about reporting the status as Running instead of RUNNING. If it feels too weird when I see it, I'll send a branch to capitalize the string in the client.

**Pull request merged**
