### PR TITLE
Add recursion support to /1.0/networks #474

### PR DESCRIPTION
**Pull request by sl1pm4t**
Signed-off-by: Matt Morrison <matt@mojo.net.nz>

### CODE REVIEW

**Comment by sl1pm4t** [comment]
Example Output:

```
$ curl -k -s --cert ~/.config/lxc/client.crt --key ~/.config/lxc/client.key  https://localhost:8443/1.0/networks?recursion=1 | jq .
{
  "type": "sync",
  "status": "Success",
  "status_code": 200,
  "metadata": [
    {
      "name": "lo",
      "type": "loopback",
      "members": []
    },
    {
      "name": "eth0",
      "type": "unknown",
      "members": []
    },
    {
      "name": "lxcbr0",
      "type": "bridge",
      "members": [
        "ubuntu"
      ]
    },
    {
      "name": "veth6MLIXE",
      "type": "unknown",
      "members": []
    }
  ]
}
```

**Comment by stgraber** [comment]
Looks like your branch isn't "go fmt" clean. Run "go fmt ./..." and commit the result.

Thanks

**Comment by stgraber** [comment]
Besides that, code seems fine, thanks!

**Comment by sl1pm4t** [comment]
Thanks for that @stgraber . I'm a golang newbie and didn't know about gofmt.

**Pull request merged**
