### PR TITLE
Added a heading in the client/operations.go file that was missing

### PR DESCRIPTION
**Pull request by ibilalkayy**
Hey there,

There was documentation missing in one [function](https://github.com/lxc/lxd/blob/71fd927db5672c33fa2c8a7b04ccb555834dba53/client/operations.go#L147) in the **client/operations.go** file. I added 2 lines of text there to make them understandable.

Thank you!

### CODE REVIEW

**Comment by tomponline** [comment]
Hi @ibilalkayy thanks for this. It looks like the documentation and dco checks are failing.

**Comment by ibilalkayy** [comment]
@tomponline  It's my first time sending the PRs here and I don't know how to pass these checks. What is lacking?

**Comment by tomponline** [comment]
> @tomponline It's my first time sending the PRs here and I don't know how to pass these checks. What is lacking?

The DCO one says here;

https://github.com/lxc/lxd/actions/runs/5441251213/jobs/9895028225?pr=11914

> What should I do to fix it ?
> All proposed commits should include a Signed-off-by: <your-name> <your-email-address> line in their commit message.
> This is most conveniently done by using --signoff (-s) when running git commit.

**Comment by ibilalkayy** [comment]
@tomponline Although I visited the contribution guide and I was not able to understand where to sign off these details.

Can you guide me? Thank you!

**Comment by tomponline** [comment]
please can you rebase to fix the documentation failure.

**Comment by ibilalkayy** [comment]
@markylaing and @tomponline I added the signed-off details in the commit message and pushed it

**Review by tomponline — APPROVED** [review]
Thanks!

**Pull request merged**
