### PR TITLE
shared: Switch to using unix.BTRFS_SUPER_MAGIC constant in IsMountPoint

### PR DESCRIPTION
**Pull request by tomponline**
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber I wondered if this was going to be acceptable, as I am looking at using the x/sys package for detecting the other filesystem types for mount custom volumes. I wasn't sure why we have different constants for 32bit vs 64bit archs, when x/sys package doesn't have them. Also are we supporting 32 bit any more anyway?

**Comment by stgraber** [comment]
@tomponline we currently still build on both i386 and armhf for 32bit and armhf will remain even after i386 is dropped.

**Comment by tomponline** [comment]
> @tomponline we currently still build on both i386 and armhf for 32bit and armhf will remain even after i386 is dropped.

And does this prevent that build from functioning?

**Comment by stgraber** [comment]
@tomponline 
```
stgraber@castiana:~$ cat main.go 
package main

import (
	"fmt"

	"golang.org/x/sys/unix"
)


func main() {
	fs := unix.Statfs_t{}
	err := unix.Statfs("/mnt/", &fs)
	if err == nil {
		if fs.Type == unix.BTRFS_SUPER_MAGIC {
			fmt.Printf("is btrfs\n")
		} else {
			fmt.Printf("is not btrfs\n")
		}
	} else {
		fmt.Printf("failed: %v\n", err)
	}
}
stgraber@castiana:~$ CGO_ENABLED=0 GOARCH=arm go build ./main.go 
# command-line-arguments
./main.go:14:14: constant 2435016766 overflows int32
```

**Comment by tomponline** [comment]
Thanks. That is pretty poor of the x/sys library to not offer 32 bit variant constants.

So I'll need to try some other approach to finding the filesystem name.

Can you remind me why we don't routinely test on 32 bit arm any more?

Thanks

**Comment by stgraber** [comment]
@tomponline we stopped doing build tests on i386 because the architecture is gone in Ubuntu 20.04. We can't test on armhf because it's not an architecture you can really virtualize. You can run it in containers on arm64 but that won't get your the right kernel.

The snap does build on armhf and is tested on armhf daily still, so if something like this was to get accidentally merged, we'd know within 24h.

**Comment by tomponline** [comment]
@stgraber out of interest, would something like this work?

```
package main

import (
        "fmt"

        "golang.org/x/sys/unix"
)


func main() {
        fs := unix.Statfs_t{}
        err := unix.Statfs("/mnt/", &fs)
        if err == nil {
                var i int64 = unix.EXT4_SUPER_MAGIC
                i32 := int32(i)
                t32 := int32(fs.Type)

                fmt.Println(i32)
                fmt.Println(t32)
                if t32  == i32 {
                        fmt.Printf("is btrfs\n")
                } else {
                        fmt.Printf("is not btrfs\n")
                }
        } else {
                fmt.Printf("failed: %v\n", err)
        }
}
```

It works on amd64 and compiles for arm64.

**Comment by stgraber** [comment]
```
root@rpi-basement:~# mount -o loop -t btrfs /home/stgraber/test.img /mnt/
root@rpi-basement:~# /home/stgraber/main 
-1859950530
-1859950530
is btrfs
root@rpi-basement:~# umount /mnt
root@rpi-basement:~# /home/stgraber/main 
-1859950530
16914836
is not btrfs
root@rpi-basement:~# 
```

Looks like it works, yes.

**Comment by tomponline** [comment]
@stgraber excellent, I'll re-open the PR using that, and then I can use the other constants from x/sys/unix for filesystem detection of an existed mounted volume.

**Pull request closed without merging**
