### PR TITLE
Fix regression in volume snapshot sequence

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
@markylaing FYI, that's a regression that came from your recent change. I had completely forgotten about the weird behavior of that particular table. Basically we have a legacy view which requires that `id` be unique across storage_volumes and storage_volumes_snapshots which is why we have this weird trigger in place.

Re-loading the table content didn't hit the trigger properly and caused the sequence to be incorrect...

Hopefully we can spend some time in the future to untangle this mess in the storage tables and make that snapshot table behave normally with its own sequence so we don't hit such issues in the future.

**Comment by stgraber** [comment]
@tomponline if you end up looking at your phone at some point overnight, we're going to want this one fast tracked as we need to push it as a quick snap update to everyone who got 4.22.

**Comment by stgraber** [comment]
@tomponline good to go

**Comment by tomponline** [comment]
@markylaing @stgraber can we add a test to catch a regression of this in the future. It feels like this is the sort of thing that can be easily missed as its unusual.

**Comment by markylaing** [comment]
> @markylaing @stgraber can we add a test to catch a regression of this in the future. It feels like this is the sort of thing that can be easily missed as its unusual.

@tomponline I'll create an issue for this. I just want to make sure I understand it fully beforehand:

> Re-loading the table content didn't hit the trigger properly and caused the sequence to be incorrect...

@stgraber it makes sense that reloading the table data for [volumes](https://github.com/lxc/lxd/pull/9684/files#diff-a15876f82899798b44f27be9568d0261586296cb95d2a0de0fdd583e598ea05eR666) and [snapshots](https://github.com/lxc/lxd/pull/9684/files#diff-a15876f82899798b44f27be9568d0261586296cb95d2a0de0fdd583e598ea05eR707) wouldn't hit the [triggers](https://github.com/lxc/lxd/pull/9684/files#diff-a15876f82899798b44f27be9568d0261586296cb95d2a0de0fdd583e598ea05eR854) because the triggers haven't been applied to the new tables yet, but I don't understand why it matters as data is copied directly from the original table (for which the trigger still existed during data insert, so the ids can't be invalid).

I can see how dropping the `storage_volumes` and `storage_volumes_snapshots` tables will have deleted their rows in the `sqlite_sequence` table and why this would break autoincrement behaviour though. So I'm guessing the newly inserted row in `storage_volumes_snapshots` has an erroneous, low value as an id (e.g. `1`), and because the id is duplicated in `storage_volumes_snapshots` and not in `storage_volumes` the trigger thinks it's valid and it hits the uniqueness constraint afterwards.

On that basis, don't we need to update the `sqlite_sequence` table for both `storage_volumes` and `storage_volumes_snapshots`? Currently (after this PR) inserting into `storage_volumes` will be fine because the autoincrement is fixed for that table. For `storage_volumes_snapshots` though, `sqlite_sequence` hasn't been updated and so we'd hit the same scenario as in the paragraph above (if I've understood it correctly).

**Comment by stgraber** [comment]
There is no sequence or auto increment on storage_volumes_snapshots. The id column is just a unique int and what makes it increment is the trigger which also causes the volumes sequence to increment with it.

**Comment by stgraber** [comment]
For this one, our best bet is to include a couple of snapshot creations to our daily Jenkins migration test.

**Comment by markylaing** [comment]
> There is no sequence or auto increment on storage_volumes_snapshots. The id column is just a unique int and what makes it increment is the trigger which also causes the volumes sequence to increment with it.

Ah I missed that. Think I understand it now. 

> For this one, our best bet is to include a couple of snapshot creations to our daily Jenkins migration test.

Ok cool, there are already some snapshot creations in that test but I assume you mean create more snapshots after the migration is ran ([line 121](https://github.com/lxc/lxc-ci/blob/master/bin/test-lxd-migration#L121)?

**Comment by stgraber** [comment]
Indeed. I'd do the connectivity check and then after that try to create 2-3 snapshots of the same container. That will cover this issue.

**Pull request merged**
