### PR TITLE
Storage: VM migration fixes

### PR DESCRIPTION
**Pull request by tomponline**
- Fixes migration from ZFS storage pools.
- Improves error reporting back to user and avoids hangs when an error occurs.

### CODE REVIEW

**Comment by brauner** [comment]
Jenkins not happy. :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
```
==> TEST BEGIN: static analysis
# github.com/lxc/lxd/lxd/storage/memorypipe
lxd/storage/memorypipe/memory_pipe.go:76:2: unreachable code
# github.com/lxc/lxd/lxd/storage
lxd/storage/backend_lxd.go:683:3: the cancel function is not used on all paths (possible context leak)
lxd/storage/backend_lxd.go:693:4: this return statement may be reached without using the cancel var defined on line 683
lxd/storage/backend_lxd.go:828:3: the cancel function is not used on all paths (possible context leak)
lxd/storage/backend_lxd.go:838:4: this return statement may be reached without using the cancel var defined on line 828
lxd/storage/backend_lxd.go:2273:2: the cancel function is not used on all paths (possible context leak)
lxd/storage/backend_lxd.go:2283:3: this return statement may be reached without using the cancel var defined on line 2273
```

**Comment by tomponline** [comment]
@stgraber @brauner thanks, I've fixed those errors now, once the `cancel` function leak was fixed, I also found that there was a race when cancelling the context when the send/recv functions had finished cleanly (due to Go's random polling of channels when using select, it would sometimes read from the context's Done() channel first before reading the last message to be sent). So I've changed it now so that the context isn't cancelled unless one of the sides actually fails or if both sides finish cleanly.

**Pull request merged**
