### PR TITLE
add LXD_UNPRIVILEGED_ONLY to disallow privileged containers.

### PR DESCRIPTION
**Pull request by Catramen**
Signed-off-by: Jingkui Wang <jkwang@google.com>

### CODE REVIEW

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner looks good, but I don't get why you're making that huge change to the testsuite.
Wouldn't it be simpler to just have the test set the env variable before calling spawn_lxd and then unset it immediately afterwards?

**Comment by brauner** [comment]
On Fri, Apr 20, 2018, 00:53 Stéphane Graber <notifications@github.com>
wrote:

> @brauner <https://github.com/brauner> looks good, but I don't get why
> you're making that huge change to the testsuite.
> Wouldn't it be simpler to just have the test set the env variable before
> calling spawn_lxd and then unset it immediately afterwards?
>
That's what I did first but it didn't work as LXD didn't pick it up on
start. Note that we do the same for LXD_DIR. If you are convinced that it
works the other way you could do a reset on the branch and just add that
piece. But I didn't get it to work. But that might just be oversight on my
part. :)

**Comment by stgraber** [comment]
@brauner yeah, doing that now, the big diff in tests/ bothers me :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner please review my changes and merge if you're happy with them, I'm fine with yours :)

**Comment by stgraber** [comment]
@brauner good to go

**Pull request merged**
