### PR TITLE
Add basic REST API usage example to README.md

### PR DESCRIPTION
**Pull request by monokal**
Signed-off-by: Daniel Middleton <d@monokal.io>

### CODE REVIEW

**Comment by monokal** [comment]
Sorry about that palaver @stgraber ;) Signed-off and good to go.

**Comment by stgraber** [comment]
Maybe replace ${LXD_API_KEY} and ${LXD_API_CERT} by ~/.config/lxc/client.key and ~/.config/lxc/client.crty as those are more likely to be valid than the env variables to exist.

**Comment by stgraber** [comment]
I would also argue that "architecture" probably shouldn't be set so that the example works on all architectures and maybe not set the profiles key either as it's set to the default value in the example.

**Comment by monokal** [comment]
Agreed @stgraber. I've amended as suggested!

**Comment by stgraber** [comment]
Oh, actually it'd be shorter and more reliable to use the unix socket. That way the user won't have to figure out how to have LXD bind to the network and how to setup a trust relationship.

With that you can remove the --key and --cert and just use something like:

    curl -L \
    --unix-socket /var/lib/lxd/unix.socket \
    -H "Content-Type: application/json" \
    -X POST \
    -d @hello-ubuntu.json \
    "unix/1.0/containers"

**Comment by stgraber** [comment]
Wouldn't hurt showing both though but I'd argue the unix socket should be first as it's far easier and also safer if only dealing with a local LXD.

**Comment by monokal** [comment]
Agreed, but I think most people looking at using the REST API are probably interested in the remote management aspect via TCP (...or perhaps I'm just speaking for myself). Anyways, tests have passed so I'd appreciate the merge as I intend on expanding the documentation further shortly (and I'll add the Unix socket example too). Thanks!

**Pull request merged**
