### PR TITLE
Device MAC improvements

### PR DESCRIPTION
**Pull request by tomponline**
- Adds support for short MAC variant (8 bytes) that will only be applied to last 8 bytes of the 20 byte infiniband MAC address to avoid issues changing the first 12 bytes that indicate queue and subnet of the device and cannot be changed by the `ip` tool.
- Adds infiniband MAC tests using new short variant.
- Adds NIC validation of ethernet MAC addresses too (6 bytes of colon separate lower case hex chars).
- Removes a global regex.

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber ready for review.

**Comment by stgraber** [comment]
@tomponline 
```/lxc-ci/build/tmp.8vVWnp0hoq/go/src/github.com/lxc/lxd/lxd/device/device_utils_infiniband.go:125:20: ineffectual assignment to err```

**Comment by tomponline** [comment]
> @tomponline
> `/lxc-ci/build/tmp.8vVWnp0hoq/go/src/github.com/lxc/lxd/lxd/device/device_utils_infiniband.go:125:20: ineffectual assignment to err`

Thats fixed now.

**Comment by tomponline** [comment]
@stgraber are you happy to have `hwaddr` enforced to be lowercase for `nic` and `infiniband` devices?

**Comment by stgraber** [comment]
Yeah, that should be fine. If we have users that have it in uppercase, they can fix it thanks to the other fix we did recently.

**Pull request merged**
