### PR TITLE
lxd/bgp: a TCP port is 16bit

### PR DESCRIPTION
**Pull request by simondeziel**

### CODE REVIEW

**Comment by simondeziel** [comment]
I noticed this when setting an invalid port (```lxc config set core.bgp_address '[::]:179000'```) and never got an error.
In retrospect, it seems to be because the listener is not created unless you set `core.bgp_routerid` (but the doc says it has a default value). Anyway, when setting the router ID, it properly errors out:

```
# lxc config set core.bgp_address '[::]:179000'
# lxc config set core.bgp_routerid 10.98.30.46
Error: listen tcp6: address 179000: invalid port
```

**Comment by simondeziel** [comment]
This is probably the wrong way to fix the problem, I'll report an issue instead and let real coder fix it ;)

**Comment by tomponline** [comment]
We have `IsNetworkPort` which should help validate this.

https://github.com/lxc/lxd/blob/f2350b0e6e620e84921742e56c356678f9585e0c/shared/validate/validate.go#L525-L536

**Comment by simondeziel** [comment]
Right. This function should call `strconv.ParseUint(value, 10, 16)` because TCP/UDP ports are 16bit numbers. Probably not relevant due to the range checking that follows. Checking `port <0` shouldn't be needed for a Uint though.

**Comment by tomponline** [comment]
Yeah I suppose though that allowing larger numbers (arguably increasing it to 64bit) would mean more cases where the friendlier error message about ranges are shown, rather than a more generic conversion error that isn't as helpful.

**Pull request closed without merging**
