### PR TITLE
Generator: Add interfaces

### PR DESCRIPTION
**Pull request by masnax**
This was an interesting one, dealing with the go source code parser :)

The main change is to generate interface files for every generated file, to provide a summary view of the generated methods.

I ran into a bit of a snag with the go source code parser expecting every method signature to either be a proper implementation, or have its own interface declaration. To get around this, after the first interface is written to the file, future writes are checked for go validity, and then the interface struct is stripped away, and only the signature is appended to the file.

I also moved creation of method signatures out of the individual functions, into a helper function called `signature`, which just switches over the supported method types.

### CODE REVIEW

**Review by tomponline — APPROVED** [review]
Enjoying this! thanks.

It really makes it easier to reason about what 'interface' is being exposed to LXD developers.
And it helps to highlight that the `DeleteOne` functions stand out ATM as being 'odd' because they don't have their required fields as dedicated arguments (unlike the equivalent `Update` functions). BTW why do we call it "DeleteOne" and not just "Delete", whereas "Update" isn't "UpdateOne"?

**Comment by masnax** [comment]
Alas, I just noticed it doesn't build, so give me a sec :)

**Comment by tomponline** [comment]
> Alas, I just noticed it doesn't build, so give me a sec :)

Oh right ok, I'd assumed it would build ;)

**Comment by masnax** [comment]
Was missing build comments and some other static analysis related things. Should be good to go now!

**Pull request merged**
