### PR TITLE
WIP: Change ConnectInfo to take a RemoteConfig.

### PR DESCRIPTION
**Pull request by jameinel**
We need the other attributes of RemoteConfig in order to connect
to the simplestreams and other 'static' hosts.

Signed-off-by: John Arbash Meinel <john@arbash-meinel.com>

I'm not 100% sure this is enough for us, I want to update the Juju client to match, so that Juju can use the known remotes to copy images for LXD provider instead of "lxd-images import". But I wanted to check that this is an ok step in that direction.

### CODE REVIEW

**Comment by tych0** [comment]
+1 on this, I have a PR that changes the way juju imports images, so I'll try and update it to use this (and whatever else we need) as well. I talked with @jameinel about it, so we're on the same page (although I need to find some time to update my juju pr :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Please run "go fmt ./..."

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks good, keeping it blocked until we finish doing some jenkins optimizations though.

**Pull request merged**
