### PR TITLE
Use flake8 instead of separate pyflakes and pep8

### PR DESCRIPTION
**Pull request by albertodonato**
Use flake8 instead of separate pep8/pyflakes for python linting

### CODE REVIEW

**Comment by stgraber** [comment]
flake8 doesn't exist in trusty

**Comment by stgraber** [comment]
It's not critical that we run pyflakes and pep8 on trusty, but we need to make sure that things won't fail if flake8 is missing then.

**Comment by stgraber** [comment]
I'd say we should drop shellcheck and flake8 from hard required dependencies and have them skipped if missing as we do with a bunch of others.

**Comment by albertodonato** [comment]
@stgraber I disabled the checks if the executables are not found

**Comment by stgraber** [comment]
Added flake8 to builder profile, should be deployed within an hour or so.

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
