### PR TITLE
GET of a nonexistent file 404s

### LINKED ISSUE #2059: GET on non-existent container files should 404
# Required information

 * Distribution: ubuntu
 * Distribution version: xenial
 * The output of "lxc info" or if that fails:
   * Kernel version: N/A
   * LXC version: N/A
   * LXD version: 2.0.1
   * Storage backend in use: N/A

# Issue description

Getting a non-existent file from a container results in a 500 HTTP status. It should result in a 404 rather than a 500.

# Steps to reproduce

 1. GET /1.0/containers/<container>/files
 2. See the response code is 500

### PR DESCRIPTION
**Pull request by tych0**
Closes #2059

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This is going to fail on systems using a non-english locale.

We really should be returning the errno as part of the error message and then check the errno instead.

**Comment by tych0** [comment]
On Tue, May 31, 2016 at 09:48:57AM -0700, Stéphane Graber wrote:
> This is going to fail on systems using a non-english locale.
> 
> We really should be returning the errno as part of the error message and then check the errno instead.

Ah, so it will. I'll update, thanks.

**Comment by stgraber** [comment]
Did you locally run "go fmt", "go vet" and run the testsuite?

I'm asking because jenkins is currently broken so we can't trust its result until the github plugin is fixed...

**Comment by tych0** [comment]
I hadn't, but I just did and they passed.

**Pull request merged**
