### PR TITLE
DB: Fix getImagesByFingerprintPrefix to handle NULL datetime values

### PR DESCRIPTION
**Pull request by tomponline**
Since https://github.com/canonical/go-dqlite/issues/123 this function hasn't worked correctly.

### CODE REVIEW

**Comment by stgraber** [comment]
@tomponline shouldn't this branch include a gomod change to switch back to the new dqlite?

**Comment by tomponline** [comment]
> @tomponline shouldn't this branch include a gomod change to switch back to the new dqlite?

Not until @masnax puts up a fix for the DB generator for the parts of the code base that are also failing due to the go-dqlite change.

**Comment by masnax** [comment]
> > @tomponline shouldn't this branch include a gomod change to switch back to the new dqlite?
> 
> Not until @masnax puts up a fix for the DB generator for the parts of the code base that are also failing due to the go-dqlite change.

I've modified the db package structs to use `*time.Time` for all the complaining datetimes, so this change to `getImagesByFingerprintPrefix` should be unnecessary now.

**Comment by tomponline** [comment]
I've superseded this PR with https://github.com/lxc/lxd/pull/9485

**Pull request closed without merging**
