### PR TITLE
VM: Migration

### PR DESCRIPTION
**Pull request by tomponline**
Adds support for VM migration (and cross-pool local copy/move that uses migration layer):

- [x] Dir
- [x] LVM
- [x] BTRFS
- [x] ZFS
- [x] Ceph

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber I've got all drivers working now except ceph. 

The generic transport method sends the config volume first, then the block volume for each LXD volume (i.e snap0 config, snap0 block, snap1 config, snap1 block, main config, main block etc). Whereas with ZFS, I was able to make the code simpler by sending all the config volumes first and then the block volumes (i.e snap0 config, snap1 config, main config, snap0 block, snap1 block, main block). This doesn't seem to be an issue, just thought I'd highlight it.

Please can you remind me again where I should test/develop for the ceph driver? Thanks

**Comment by stgraber** [comment]
@tomponline easiest for ceph is to use a branch that doesn't have an open PR (so it doesn't trigger jenkins when you push), then directly run the tests you want on the branch using the `build-lxd` script on one of the x86_64 test runners (I usually use root@buildd01.dev.mtl for that).

**Comment by stgraber** [comment]
```
ssh ubuntu@canonical-lxd.stgraber.org -t ssh root@buildd01.dev.mtl
  cd /lxc-ci
  time bin/build-lxd golang-tip https://github.com/stgraber/lxd master ceph security
```

In this case that would run the `security` test on the `master` branch of my personal repo, for the `ceph` storage driver using `tip` Go.

**Comment by tomponline** [comment]
@stgraber tested ceph migration, both block_and_rsync and rbd by doing a same-host by cross-pool migrations between different types of pool (including another ceph pool to test rbd).

**Pull request merged**
