### PR TITLE
db/cluster: Bump the value of sqlite_sequence for storage_volumes

### LINKED ISSUE #7024: error creating snapshot
```
$ lxc snapshot nextcloud "18.02"
Error: Create instance: Insert volume snapshot: UNIQUE constraint failed: storage_volumes_snapshots.id
$ lxd sql global "SELECT * FROM storage_volumes_snapshots;"
+----+-------------------+------------------+-------------+
| id | storage_volume_id |       name       | description |
+----+-------------------+------------------+-------------+
| 74 | 73                | upgrade_to_19.10 |             |
| 76 | 75                | upgrade_to_19.10 |             |
| 92 | 91                | upgade_to_19.10  |             |
| 94 | 93                | upgrade_to_19.10 |             |
+----+-------------------+------------------+-------------+
```

### PR DESCRIPTION
**Pull request by freeekanayaka**
Fixes #7024

Signed-off-by: Free Ekanayaka <free.ekanayaka@canonical.com>

### CODE REVIEW

**Comment by tomponline** [comment]
@freeekanayaka do you know why the patch is needed, and the increment didn't happen normally? Could there be somewhere in the code that isn't incrementing it as needed?

Also, for my own information, do we use the `sqlite_sequence` table rather than an auto increment field because of the cluster replication?

**Comment by freeekanayaka** [comment]
> @freeekanayaka do you know why the patch is needed, and the increment didn't happen normally?

I believe it's because during the last db upgrade we dropped and recreated the `storage_volumes` table and hence the `sqlite_sequence` table was reset to the maximum ID of the new `storage_volumes` table, which had less rows since we migrated snapshot rows to a separate table.

> Could there be somewhere in the code that isn't incrementing it as needed?

Not afaics.
 
> Also, for my own information, do we use the `sqlite_sequence` table rather than an auto increment field because of the cluster replication?

It's a compromise: ideally we'd use autoincrement (which basically mean a "private" table-specific counter in the `sqlite_sequence` table), but our internal code was very coupled with the fact that we had a single table for both volumes and snapshot, so as I first step I decided to share IDs. As we move forward we might be able to fix this and switch to autoincrement, the work that @monstermunchkin is doing seems to go into that direction.

**Comment by tomponline** [comment]
thanks @freeekanayaka

**Comment by YosuCadilla** [comment]
Having similar issues as those mentioned in #7024 on a node with lots of snapshot usage. 
Do you have a release date for 3.23?
Should I switch from stable to beta or just be patient?

**Pull request merged**
