### PR TITLE
lxd/storage: Expand local config

### LINKED ISSUE #8119: Loop-backed ZFS storage pool creation fails with error about minimum size (64M)
# Issue description

Hi,
This looks like a small bug, but I am not 100% sure and might have overlooked something. 

Using LXD 4.7 on Ubuntu 20.10, I am trying to create a new loop-based ZFS storage pool, but I am getting error about "the minimum size (64M)" of ZFS pool, which I guess should not happen...Seems like the default minimum for the ZFS pool size in LXD is set too low. Have not verified it, but could also be LXD cluster specific...

# Steps to reproduce

1. created LXD cluster (say: 3 nodes: lxd-host-01, lxd-host-02, lxd-host-03, with IPs: 192.168.100.131, .132 and .133 resp.)
2. the storage pool from lxd init on /dev/sdb works fine: 

> lxc storage list
> +-------+-------------+--------+---------+---------+
> | NAME  | DESCRIPTION | DRIVER |  STATE  | USED BY |
> +-------+-------------+--------+---------+---------+
> | local |             | zfs    | CREATED | 15      |
> +-------+-------------+--------+---------+---------+

3. 
> lxc storage create myzfspool zfs --target lxd-host-01
> Storage pool myzfspool pending on member lxd-host-01

4. 
> lxc storage create myzfspool zfs --target lxd-host-02
> Storage pool myzfspool pending on member lxd-host-02

5. 
> lxc storage create myzfspool zfs --target lxd-host-03
> Storage pool myzfspool pending on member lxd-host-03
 

6.
> lxc storage create myzfspool zfs
> Error: Failed to run: zpool create -f -m none -O compression=on myzfspool /var/snap/lxd/common/lxd/disks/myzfspool.img: 
> cannot create 'myzfspool': one or more devices is less than the minimum size (64M)

However, manually creating the loop-backed ZFS pool first and sourcing it to LXD, works fine:
1. same cluster as above
2. doing the following **on each of the 3 nodes**:
> sudo truncate -s 2G /tmp/myloopfile.img
> 
> sudo zpool create myzfslooppool /tmp/myloopfile.img
> 
> zpool list
> NAME            SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
> local           254G  6.84G   247G        -         -     0%     2%  1.00x    ONLINE  -
> myzfslooppool  1.88G   117K  1.87G        -         -     0%     0%  1.00x    ONLINE  -
> 
3. 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-01
> Storage pool myzfslooppool pending on member lxd-host-01
> 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-02
> Storage pool myzfslooppool pending on member lxd-host-02
> 
> lxc storage create myzfslooppool zfs source=myzfslooppool  --target lxd-host-03
> Storage pool myzfslooppool pending on member lxd-host-03
> 
4. 
> lxc storage create myzfslooppool zfs
> Storage pool myzfslooppool created
> 
5. 

> lxc storage ls
> +---------------+-------------+--------+---------+---------+
> |     NAME      | DESCRIPTION | DRIVER |  STATE  | USED BY |
> +---------------+-------------+--------+---------+---------+
> | local         |             | zfs    | CREATED | 15      |
> +---------------+-------------+--------+---------+---------+
> | myzfslooppool |             | zfs    | CREATED | 0       |
> +---------------+-------------+--------+---------+---------+
> | myzfspool     |             | zfs    | PENDING | 0       |
> +---------------+-------------+--------+---------+---------+
> 

# Required information
$ lxc info
config:
  cluster.https_address: 192.168.100.131:8443
  core.https_address: 192.168.100.131:8443
  core.trust_password: true
api_extensions:
- storage_zfs_remove_snapshots
- container_host_shutdown_timeout
- container_stop_priority
- container_syscall_filtering
- auth_pki
- container_last_used_at
- etag
- patch
- usb_devices
- https_allowed_credentials
- image_compression_algorithm
- directory_manipulation
- container_cpu_time
- storage_zfs_use_refquota
- storage_lvm_mount_options
- network
- profile_usedby
- container_push
- container_exec_recording
- certificate_update
- container_exec_signal_handling
- gpu_devices
- container_image_properties
- migration_progress
- id_map
- network_firewall_filtering
- network_routes
- storage
- file_delete
- file_append
- network_dhcp_expiry
- storage_lvm_vg_rename
- storage_lvm_thinpool_rename
- network_vlan
- image_create_aliases
- container_stateless_copy
- container_only_migration
- storage_zfs_clone_copy
- unix_device_rename
- storage_lvm_use_thinpool
- storage_rsync_bwlimit
- network_vxlan_interface
- storage_btrfs_mount_options
- entity_description
- image_force_refresh
- storage_lvm_lv_resizing
- id_map_base
- file_symlinks
- container_push_target
- network_vlan_physical
- storage_images_delete
- container_edit_metadata
- container_snapshot_stateful_migration
- storage_driver_ceph
- storage_ceph_user_name
- resource_limits
- storage_volatile_initial_source
- storage_ceph_force_osd_reuse
- storage_block_filesystem_btrfs
- resources
- kernel_limits
- storage_api_volume_rename
- macaroon_authentication
- network_sriov
- console
- restrict_devlxd
- migration_pre_copy
- infiniband
- maas_network
- devlxd_events
- proxy
- network_dhcp_gateway
- file_get_symlink
- network_leases
- unix_device_hotplug
- storage_api_local_volume_handling
- operation_description
- clustering
- event_lifecycle
- storage_api_remote_volume_handling
- nvidia_runtime
- container_mount_propagation
- container_backup
- devlxd_images
- container_local_cross_pool_handling
- proxy_unix
- proxy_udp
- clustering_join
- proxy_tcp_udp_multi_port_handling
- network_state
- proxy_unix_dac_properties
- container_protection_delete
- unix_priv_drop
- pprof_http
- proxy_haproxy_protocol
- network_hwaddr
- proxy_nat
- network_nat_order
- container_full
- candid_authentication
- backup_compression
- candid_config
- nvidia_runtime_config
- storage_api_volume_snapshots
- storage_unmapped
- projects
- candid_config_key
- network_vxlan_ttl
- container_incremental_copy
- usb_optional_vendorid
- snapshot_scheduling
- container_copy_project
- clustering_server_address
- clustering_image_replication
- container_protection_shift
- snapshot_expiry
- container_backup_override_pool
- snapshot_expiry_creation
- network_leases_location
- resources_cpu_socket
- resources_gpu
- resources_numa
- kernel_features
- id_map_current
- event_location
- storage_api_remote_volume_snapshots
- network_nat_address
- container_nic_routes
- rbac
- cluster_internal_copy
- seccomp_notify
- lxc_features
- container_nic_ipvlan
- network_vlan_sriov
- storage_cephfs
- container_nic_ipfilter
- resources_v2
- container_exec_user_group_cwd
- container_syscall_intercept
- container_disk_shift
- storage_shifted
- resources_infiniband
- daemon_storage
- instances
- image_types
- resources_disk_sata
- clustering_roles
- images_expiry
- resources_network_firmware
- backup_compression_algorithm
- ceph_data_pool_name
- container_syscall_intercept_mount
- compression_squashfs
- container_raw_mount
- container_nic_routed
- container_syscall_intercept_mount_fuse
- container_disk_ceph
- virtual-machines
- image_profiles
- clustering_architecture
- resources_disk_id
- storage_lvm_stripes
- vm_boot_priority
- unix_hotplug_devices
- api_filtering
- instance_nic_network
- clustering_sizing
- firewall_driver
- projects_limits
- container_syscall_intercept_hugetlbfs
- limits_hugepages
- container_nic_routed_gateway
- projects_restrictions
- custom_volume_snapshot_expiry
- volume_snapshot_scheduling
- trust_ca_certificates
- snapshot_disk_usage
- clustering_edit_roles
- container_nic_routed_host_address
- container_nic_ipvlan_gateway
- resources_usb_pci
- resources_cpu_threads_numa
- resources_cpu_core_die
- api_os
- container_nic_routed_host_table
- container_nic_ipvlan_host_table
- container_nic_ipvlan_mode
- resources_system
- images_push_relay
- network_dns_search
- container_nic_routed_limits
- instance_nic_bridged_vlan
- network_state_bond_bridge
- usedby_consistency
- custom_block_volumes
- clustering_failure_domains
- resources_gpu_mdev
- console_vga_type
- projects_limits_disk
- network_type_macvlan
- network_type_sriov
- container_syscall_intercept_bpf_devices
- network_type_ovn
- projects_networks
- projects_networks_restricted_uplinks
- custom_volume_backup
- backup_override_name
- storage_rsync_compression
- network_type_physical
- network_ovn_external_subnets
- network_ovn_nat
- network_ovn_external_routes_remove
api_status: stable
api_version: "1.0"
auth: trusted
public: false
auth_methods:
- tls
environment:
  addresses:
  - 192.168.100.131:8443
  architectures:
  - x86_64
  - i686
  certificate: |
    -----BEGIN CERTIFICATE-----
    MIICFDCCAZmgAwIBAgIRAI5AM5uTzznAZfWivq1V2bkwCgYIKoZIzj0EAwMwOTEc
    MBoGA1UEChMTbGludXhjb250YWluZXJzLm9yZzEZMBcGA1UEAwwQcm9vdEBseGQt
    aG9zdC0wMTAeFw0yMDExMDIxNzIzNDBaFw0zMDEwMzExNzIzNDBaMDkxHDAaBgNV
    BAoTE2xpbnV4Y29udGFpbmVycy5vcmcxGTAXBgNVBAMMEHJvb3RAbHhkLWhvc3Qt
    MDEwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAS8jTKvsufhaZLPrl28dPoeBcmRiSp+
    jHPdZ/E+pjOSTkj19t/nuoqEWbMDHC4cQm3+6YoV40fTPPkWYPV0wXHfWBQwXv5s
    kTNVr9mxIPFvdpY1Z8fk5iR7An+TzBPBjL6jZTBjMA4GA1UdDwEB/wQEAwIFoDAT
    BgNVHSUEDDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMC4GA1UdEQQnMCWCC2x4
    ZC1ob3N0LTAxhwR/AAABhxAAAAAAAAAAAAAAAAAAAAABMAoGCCqGSM49BAMDA2kA
    MGYCMQCbqScv5GPQbYsmLNVoapN9q1iCSQ+Y+L7ULr9PHzK16NYMp3i6YKVrZeoJ
    FffK1c0CMQDZmWpswqIo4r9W0NvrJDMZ+daSWeHInGnMCNcQYcfStcBpDaSue+pP
    AyaDlagSrdg=
    -----END CERTIFICATE-----
  certificate_fingerprint: b164bab6343eb9f253b9585072ee10a1c4f35f48ff2a4e1c21821e4d27bf4234
  driver: lxc
  driver_version: 4.0.5
  firewall: nftables
  kernel: Linux
  kernel_architecture: x86_64
  kernel_features:
    netnsid_getifaddrs: "false"
    seccomp_listener: "true"
    seccomp_listener_continue: "true"
    shiftfs: "true"
    uevent_injection: "true"
    unpriv_fscaps: "true"
  kernel_version: 5.8.0-26-generic
  lxc_features:
    cgroup2: "true"
    devpts_fd: "true"
    mount_injection_file: "true"
    network_gateway_device_route: "true"
    network_ipvlan: "true"
    network_l2proxy: "true"
    network_phys_macvlan_mtu: "true"
    network_veth_router: "true"
    pidfd: "true"
    seccomp_allow_deny_syntax: "true"
    seccomp_notify: "true"
    seccomp_proxy_send_notify_fd: "true"
  os_name: Ubuntu
  os_version: "20.10"
  project: default
  server: lxd
  server_clustered: true
  server_name: lxd-host-01
  server_pid: 138963
  server_version: "4.7"
  storage: zfs
  storage_version: 0.8.4-1ubuntu11

### PR DESCRIPTION
**Pull request by stgraber**
Closes #8119

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
@brauner @tomponline ready to go

**Review by tomponline — COMMENTED** [review]
I'm not sure about why this change is required, shouldn't the request that creates the original DB entry have run the user supplied config through `storagePoolFillDefault` rather than relying on the  this function who's comment says it only does "non-db" work (I admit that modifying a map locally isn't DB work, however from what I can see it does run the risk of potentially diverging from what is in the DB - presumably the record has already been created somewhere by this time).

Also, the `storagePoolCreateLocal` is called from multiple places, including `storagePoolCreateGlobal` which first calls `storagePoolDBCreate` which in turn calls `storagePoolFillDefault` so in that situation the `storagePoolCreateLocal` doesn't need to call `storagePoolFillDefault`.

From my time going through the storage layer, I have sometimes found it quite hard to reason about where something, such as a config change like this, should be performed as it can be selectively performed in various places.

If there are places where  `storagePoolFillDefault` should be called before calling `storagePoolCreateLocal` then I would find it easier to follow if we update those places first, as then we can see how the logical flow is different from other places that call `storagePoolCreateLocal`, and we can always reason that one would expect the defaults to be populated before then.

**Comment by stgraber** [comment]
@tomponline This branch makes it so that the node-specific config is also filled in and recorded.
Without it, we do fill in the config when creating the pool but we then strip all node-specific keys.

This change does cause things to be recorded in the DB properly as we already support the storage drivers themselves making pool config changes that are node specific and recording those during the node storage creation part.

**Pull request merged**
