### PR TITLE
[DO NOT MERGE] lvm: log loop device used

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
Should be something more visible than Debugf for debugging since Jenkins won't show you those.

**Comment by stgraber** [comment]
Did that help you find the problem with loop re-use?

I don't actually want this constantly logged at that level, so won't be merging this branch. We can just keep throwing it at Jenkins until it hits the problem again, then use that to debug the actual problem.

**Comment by brauner** [comment]
Not, since the problem occurred even before we could call `lxc storage create bla lvm` which would use our internal `storage_cgo.go` functions. I might just force a rerun and see if I can trigger the problem while our own functions are called.

**Comment by brauner** [comment]
Jenkins: test this please.

**Comment by brauner** [comment]
```
+ losetup --show -f /lxd/build/tmp.9GwL7PEWsP/go/src/github.com/lxc/lxd/test/tmp.eYz/j2nQ.lvm
+ pvloopdev=/dev/loop17
+ [ ! -e /dev/loop17 ]
+ echo /dev/loop17
+ pvcreate /dev/loop17
  WARNING: Volume Group lxdtest-uoNeHelg7-pool6 is not consistent.
  Physical volume "/dev/loop17" successfully created
```

I think that this is pretty telling. If I were hard-pressed right now to give an explanation I would say that
a) there is some locking failure in lvm going on that causes the metadata to go corrupt
b) that missing pvscan calls on pvcreate might cause problems

So I'm going to send a pr that runs `pvscan` and `vgscan` on pool creation (In the script and our storage functions) and see if this resolves the problems.

**Comment by brauner** [comment]
Also, forkstart errors on buildd03:

```
[ 1202.728486] Call Trace:
[ 1202.728488]  [<ffffffff81838545>] schedule+0x35/0x80
[ 1202.728490]  [<ffffffff818387ee>] schedule_preempt_disabled+0xe/0x10
[ 1202.728492]  [<ffffffff8183a429>] __mutex_lock_slowpath+0xb9/0x130
[ 1202.728494]  [<ffffffff8183a4bf>] mutex_lock+0x1f/0x30
[ 1202.728498]  [<ffffffff813a2f4b>] aa_create_ns+0x3b/0x100
[ 1202.728502]  [<ffffffff81380e6e>] ns_mkdir_op+0x1be/0x330
[ 1202.728504]  [<ffffffff812196c8>] ? __inode_permission+0x48/0xc0
[ 1202.728507]  [<ffffffff8121bcfc>] vfs_mkdir+0x10c/0x1b0
[ 1202.728509]  [<ffffffff812200ff>] SyS_mkdirat+0xcf/0x100
[ 1202.728511]  [<ffffffff8183c672>] entry_SYSCALL_64_fastpath+0x16/0x71
```

**Pull request closed without merging**
