### PR TITLE
lvm: only pass -kn to lvcreate for lvm > 2.02.99

### LINKED ISSUE #1470: LVM Backend is broken on 0.26
Sorry everyone,

Didn't mean to double post but thought the issue need to be separated.

I just tested 0.26 and no such luck. LVM is still broken when creating images with lxd

lxc init centos7-amd64 webtest1-chi -p default
error: Error mounting snapshot LV: no such file or directory

```
lxc init --debug --verbose centos7-amd64 webtest2-chi -p default
Creating webtest2-chi DBUG[01-06|02:41:55] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"api_compat":1,"auth":"trusted","config":{"storage.lvm_thinpool_name":"LXDPool","storage.lvm_vg_name":"lxc"},"environment":{"addresses":[],"architectures":[2,1],"driver":"lxc","driver_version":"1.1.5","kernel":"Linux","kernel_architecture":"x86_64","kernel_version":"4.2.0-23-generic","server":"lxd","server_pid":1508,"server_version":"0.26","storage":"lvm","storage_version":"2.02.122(2) (2015-06-20) / 1.02.99 (2015-06-20) / 4.33.0"}},"operation":""}
 
DBUG[01-06|02:41:55] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"target":"1582f9bc9f9558f826cad94dc8968004c8c014c4bfcffcadfbd1e4e96145404e","description":"centos7-amd64"},"operation":""}
 
DBUG[01-06|02:41:55] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"aliases":[{"target":"centos7-amd64","description":"centos7-amd64"}],"architecture":2,"fingerprint":"1582f9bc9f9558f826cad94dc8968004c8c014c4bfcffcadfbd1e4e96145404e","filename":"centos-7-amd64-default-20160105_02:16.tar.xz","properties":{"description":"Centos 7 (amd64)"},"public":0,"size":61906508,"created_at":1451964217,"expires_at":0,"uploaded_at":1452047788},"operation":""}
 
DBUG[01-06|02:41:55] Posting {"name":"webtest2-chi","profiles":["default"],"source":{"fingerprint":"1582f9bc9f9558f826cad94dc8968004c8c014c4bfcffcadfbd1e4e96145404e","type":"image"}}
 to http://unix.socket/1.0/containers 
DBUG[01-06|02:41:55] Raw response: {"type":"async","status":"OK","status_code":100,"metadata":{"id":"37cd6b43-67b4-4ef6-8a1f-49c61ec9b2db","class":"task","created_at":"2016-01-06T02:41:55.866914316Z","updated_at":"2016-01-06T02:41:55.866914316Z","status":"Running","status_code":103,"resources":{"containers":["/1.0/containers/webtest2-chi"]},"metadata":null,"may_cancel":false,"err":""},"operation":"/1.0/operations/37cd6b43-67b4-4ef6-8a1f-49c61ec9b2db"}
 
DBUG[01-06|02:41:55] 1.0/operations/37cd6b43-67b4-4ef6-8a1f-49c61ec9b2db/wait 
DBUG[01-06|02:42:06] Raw response: {"type":"sync","status":"Success","status_code":200,"metadata":{"id":"37cd6b43-67b4-4ef6-8a1f-49c61ec9b2db","class":"task","created_at":"2016-01-06T02:41:55.866914316Z","updated_at":"2016-01-06T02:41:55.866914316Z","status":"Failure","status_code":400,"resources":{"containers":["/1.0/containers/webtest2-chi"]},"metadata":null,"may_cancel":false,"err":"Error mounting snapshot LV: no such file or directory"},"operation":""}
```
```
lxc config show
config:
  storage.lvm_thinpool_name: LXDPool
  storage.lvm_vg_name: lxc
```
```
lxc profile show default
name: default
config:
  raw.lxc: |
    lxc.start.auto = 1
    lxc.arch = amd64
    lxc.cgroup.cpu.shares = 1
  security.privileged: "true"
devices:
  eth0:
    nictype: bridged
    parent: br0
    type: nic
```

### PR DESCRIPTION
**Pull request by mikemccracken**
-kn, aka '--setactivationskip n', is required after LVM version 2.02.99, which sets
the activationskip flag to true by default for thin LVs.

However, it is not supported prior to that version so we need to send it
conditionally.

Fixes #1470 

Signed-off-by: Michael McCracken <mike.mccracken@canonical.com>

### CODE REVIEW

**Comment by tych0** [comment]
The commit log and the patch notes say 1.02.99, but the actual patch says 2.02.99

**Comment by stgraber** [comment]
Also, "go fmt ./..." :)

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by alitvak69** [comment]
I pulled new master for lxd, lxc, and lxcfs.  The issue still persists.

```
t=2016-01-09T04:02:31+0000 lvl=info msg=handling ip=@ method=POST url=/1.0/containers
t=2016-01-09T04:02:31+0000 lvl=dbug msg="\n\t{\n\t\t\"name\": \"webtest22\",\n\t\t\"profiles\": [\n\t\t\t\"default\"\n\t\t],\n\t\t\"source\": {\n\t\t\t\"fingerprint\": \"e62ce217535634bb8a78238f928f4b57e70b4f4639f049b599d350a278ba136e\",\n\t\t\t\"type\": \"image\"\n\t\t}\n\t}"
t=2016-01-09T04:02:31+0000 lvl=dbug msg="Responding to container create"
t=2016-01-09T04:02:31+0000 lvl=dbug msg="New task operation: 57b411c7-1d08-4fde-9f13-ae40347d3e1b"
t=2016-01-09T04:02:31+0000 lvl=dbug msg="Started task operation: 57b411c7-1d08-4fde-9f13-ae40347d3e1b"
t=2016-01-09T04:02:31+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"async\",\n\t\t\"status\": \"OK\",\n\t\t\"status_code\": 100,\n\t\t\"metadata\": {\n\t\t\t\"id\": \"57b411c7-1d08-4fde-9f13-ae40347d3e1b\",\n\t\t\t\"class\": \"task\",\n\t\t\t\"created_at\": \"2016-01-09T04:02:31.23735626Z\",\n\t\t\t\"updated_at\": \"2016-01-09T04:02:31.23735626Z\",\n\t\t\t\"status\": \"Running\",\n\t\t\t\"status_code\": 103,\n\t\t\t\"resources\": {\n\t\t\t\t\"containers\": [\n\t\t\t\t\t\"/1.0/containers/webtest22\"\n\t\t\t\t]\n\t\t\t},\n\t\t\t\"metadata\": null,\n\t\t\t\"may_cancel\": false,\n\t\t\t\"err\": \"\"\n\t\t},\n\t\t\"operation\": \"/1.0/operations/57b411c7-1d08-4fde-9f13-ae40347d3e1b\"\n\t}"
t=2016-01-09T04:02:31+0000 lvl=info msg=handling method=GET url=/1.0/operations/57b411c7-1d08-4fde-9f13-ae40347d3e1b/wait ip=@
t=2016-01-09T04:02:31+0000 lvl=dbug msg=ContainerCreateFromImage driver=storage/lvm imageFingerprint=e62ce217535634bb8a78238f928f4b57e70b4f4639f049b599d350a278ba136e name=webtest22 isPrivileged=true
t=2016-01-09T04:02:36+0000 lvl=dbug msg=containerDeleteSnapshots container=webtest22
t=2016-01-09T04:02:36+0000 lvl=dbug msg=ContainerDelete driver=storage/lvm container=webtest22
t=2016-01-09T04:02:41+0000 lvl=dbug msg="Could not remove LV" driver=storage/lvm output="  Failed to find logical volume \"lxc/webtest22\"\n" lvname=webtest22
t=2016-01-09T04:02:41+0000 lvl=dbug msg="Failure for task operation: 57b411c7-1d08-4fde-9f13-ae40347d3e1b: Error mounting snapshot LV: no such file or directory"
t=2016-01-09T04:02:41+0000 lvl=dbug msg="\n\t{\n\t\t\"type\": \"sync\",\n\t\t\"status\": \"Success\",\n\t\t\"status_code\": 200,\n\t\t\"metadata\": {\n\t\t\t\"id\": \"57b411c7-1d08-4fde-9f13-ae40347d3e1b\",\n\t\t\t\"class\": \"task\",\n\t\t\t\"created_at\": \"2016-01-09T04:02:31.23735626Z\",\n\t\t\t\"updated_at\": \"2016-01-09T04:02:31.23735626Z\",\n\t\t\t\"status\": \"Failure\",\n\t\t\t\"status_code\": 400,\n\t\t\t\"resources\": {\n\t\t\t\t\"containers\": [\n\t\t\t\t\t\"/1.0/containers/webtest22\"\n\t\t\t\t]\n\t\t\t},\n\t\t\t\"metadata\": null,\n\t\t\t\"may_cancel\": false,\n\t\t\t\"err\": \"Error mounting snapshot LV: no such file or directory\"\n\t\t},\n\t\t\"operation\": \"\"\n\t}"
```

**Comment by tych0** [comment]
On Fri, Jan 08, 2016 at 08:09:59PM -0800, alitvak69 wrote:
> I pulled new master for lxd, lxc, and lxcfs.  The issue still persists.

What's the output of "lvm version"?

**Pull request merged**
