### PR TITLE
lxd/lxd: Record requestor as part of lifecycle events

### LINKED ISSUE #8011: Record requestor as part of `lifecycle` events
`lifecycle` events would be quite useful for auditing if they would also record who asked for a given action.

To do this, I suspect we'll want to:
 - Refactor the current SendLifecycle calls to be done through a common function on instance driver
 - Have that function take care of adding context like instance name, instance project, resources, ...
 - Add some way to store the requestor onto the struct too and seed that from the `user` field on requests (when available)
 - Then add that context to the lifecycle events.

### PR DESCRIPTION
**Pull request by my5t3ry**
maybe partly resolves #8011 

Signed-off-by: Sascha Bast <sash@mischkonsum.org>

### CODE REVIEW

**Comment by stgraber** [comment]
I think a simpler approach would be:
 - Define a new Requestor struct in the `lxd/operations/` package.
 - Allow storing and retrieving this on an operation
   - op.SetRequestor(ctx)
   - op.Requestor()
 - Update `lifecycle()` in driver_common to use `d.op.Requestor` to get the information and add it to the event

This should require a lot less plumbing overall as you won't have to pass around the context everywhere.

**Comment by my5t3ry** [comment]
Thanks for the hint. I already thought that this looks so very bulky and can't be right. I'm still stumbling through the code, holding on to breakpoints, as I lack a sense of orientation. But it's fun :) 

I have an off-topic question:
Is there the possibility to make suggestions for new features, and if so what is the best way to do that?

**Comment by stgraber** [comment]
Yeah, new features are usually handled through Github issues that we then tag with the Feature tag and possibly others depending on what's involved.

**Comment by my5t3ry** [comment]
Ok, thanks. I don't know if there is another mechanism to achieve what I would consider a useful feature. I was thinking about adding a "snapshots.mirror" configuration key to configure a remote lxd instance, where snapshots of instances and storage volumes are pushed to, to create offsite backups. 
I plan to spend some time tomorrow resolving this pull request, and aso can create an output with the requirements for it. Unless there is already another/better way to accomplish this, or you think the idea is generally bad.

: )

**Comment by stgraber** [comment]
This type of feature would be more suited for a 3rd party tool outside of LXD.

The reason for that is that LXD doesn't actually hold any credentials nor does it know about remotes (it's a client concept), so having LXD itself initiate migrations would require very large changes which could be quite tricky from a security point of view.

But you could have a pretty small binary which does the equivalent of a `lxc copy --refresh` for all instances with a particular `user.XYZ` key set quite easily as that client could read your remotes and use your credentials to access both source and target servers.

**Comment by my5t3ry** [comment]
@stgraber sry for the late reply. i had a week off from computers. I understood that lxd/lxc is the client for lxd daemons, but I didn't realize that lxd doesn't know about other lxds. I wrote a native graalvm image application some time ago that includes sping boot and does exactly what you suggested, and I still use it in production. I also took some time in my computer-free week to work on a private project, implementing a java lxd socket client to create/manage vms. 
I have a much better understanding of operations and the socket api in general. 
lxc/lxd, lxc is really something, has completely changed the way i work, instance dust everywhere. great : )

**Pull request closed without merging**
