### PR TITLE
Mips cast

### PR DESCRIPTION
**Pull request by jwh**
Hi guys,

This PR fixes the remaining issues preventing LXD building on mips - build and run tested on amd64 also.

Relevant: https://github.com/docker/docker-ce/commit/25d244c1db47dec23879b0928c366e34d5756a89

Although it builds, there are still some issues when remapping containers, so as-is this does not quite work

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
I'd have expectes sign extension might be a problem in a few other places as well then. But good that it builds with this.

**Comment by brauner** [comment]
You need to sign off all of your commits though. :)

**Comment by jwh** [comment]
> 
> 
> I'd have expectes sign extension might be a problem in a few other places as well then. But good that it builds with this.

I also expect so, at least now it runs I can identify other issues

**Comment by jwh** [comment]
> 
> 
> You need to sign off all of your commits though. :)

They should all be signed

**Pull request merged**
