### PR TITLE
Attach already provisioned ceph rbd/fs to containers

### PR DESCRIPTION
**Pull request by ribsthakkar**
Addresses #6174 
You can attach rbd with a command like `lxc config device add c1 ceph-rbd1 disk source=ceph:my-pool/my-volume ceph.user_name=admin ceph.cluster_name=ceph path=/ceph`

You can attach a fs with a command like:
` lxc config device add c1 ceph-fs1 disk source=cephfs:my-fs/some-path ceph.user_name=admin ceph.cluster_name=ceph path=/cephfs`

### CODE REVIEW

**Comment by stgraber** [comment]
Some of your commits appear to be missing the needed `Signed-off-by` line (or lines when multiple author).

The branch also needs rebasing as it's conflicting on a number of files.
You also likely want to squash a number of those commits together to end up with the structure described in the issue.

**Comment by ribsthakkar** [comment]
Do we need to put the signed-off-by line for merge commits?

**Comment by ribsthakkar** [comment]
I am having trouble figuring out which commits to rebase and add the signed-off-by. Quite frankly, I think I've been going in circles rebasing over and over

**Comment by ribsthakkar** [comment]
We have tried to sign off on this one commit `527f191e` which I don't even think should be there anymore, but the Jenkins continues to fail due to missing the sign off. I don't think the commit should even be there since I had squashed the commits and signed them when I first did the rebase.

**Comment by stgraber** [comment]
Yeah, your branch needs rebasing on master, that will drop all those duplicate commits you have in here.

Normally you'd do that by running:
 - git remote update
 - git rebase origin/master
 - git push --force

**Comment by ribsthakkar** [comment]
I think we're going to start fresh with a new branch and a new set of commits since our changes were easy enough to find and reapply. Will close this PR for now

**Pull request closed without merging**
