### PR TITLE
Don't require vendorid for USB devices

### PR DESCRIPTION
**Pull request by Catramen**
Sometimes I just want a stupid way to pass in everything.

Signed-off-by: Jingkui Wang <jkwang@google.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This indeed sounds pretty useful as a way to just pass all USB devices, though I think we should do it the same way we do for GPUs.

That is, making `vendorid` optional and simply passing everything if both vendorid and productid are empty.

@Catramen can you update your branch to do that instead?

Thanks!

**Comment by brauner** [comment]
@Catramen, unless it is company policy, could you please sign-off your commits with the same mail address for consistency. :)

**Comment by Catramen** [comment]
Done, I squashed the changes.

**Comment by brauner** [comment]
@Catramen, lovely! Thank you! :)

**Comment by brauner** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
I'll be adding an API extension for this so clients can detect whether the LXD server has had this change in behavior. This won't prevent backporting to 3.0 though as it's not really a new feature.

**Pull request merged**
