### PR TITLE
Moves swagger response definitions to response package.

### PR DESCRIPTION
**Pull request by markylaing**
In order to include swagger response models in the LXD Cloud admin API, we need to include them in doc generation without including all models from LXD. Additionally, we need to avoid including the swagger metadata. This change moves the swagger response definitions into the response package (where they are mostly defined) so that we can include this package only.

### CODE REVIEW

**Comment by stgraber** [comment]
@markylaing just checking, you ran `make update-api` and confirmed that we get the same YAML and no errors?

**Comment by markylaing** [comment]
> @markylaing just checking, you ran `make update-api` and confirmed that we get the same YAML and no errors?

Yeah I'm running it and getting the same YAML. That's with go-swagger version v.0.29.0.

**Review by tomponline — CHANGES_REQUESTED** [review]
@markylaing static analyses failures:

```
deadcode: lxd/response/swagger.go:10:1: swaggerOperation is unused
deadcode: lxd/response/swagger.go:33:1: swaggerEmptySyncResponse is unused
deadcode: lxd/response/swagger.go:51:1: swaggerBadRequest is unused
deadcode: lxd/response/swagger.go:69:1: swaggerForbidden is unused
deadcode: lxd/response/swagger.go:87:1: swaggerPreconditionFailed is unused
deadcode: lxd/response/swagger.go:105:1: swaggerInternalServerError is unused
deadcode: lxd/response/swagger.go:123:1: swaggerNotFound is unused
```

**Comment by markylaing** [comment]
> @markylaing static analysis failures:
> 
> ```
> deadcode: lxd/response/swagger.go:10:1: swaggerOperation is unused
> deadcode: lxd/response/swagger.go:33:1: swaggerEmptySyncResponse is unused
> deadcode: lxd/response/swagger.go:51:1: swaggerBadRequest is unused
> deadcode: lxd/response/swagger.go:69:1: swaggerForbidden is unused
> deadcode: lxd/response/swagger.go:87:1: swaggerPreconditionFailed is unused
> deadcode: lxd/response/swagger.go:105:1: swaggerInternalServerError is unused
> deadcode: lxd/response/swagger.go:123:1: swaggerNotFound is unused
> ```

@tomponline Looks like a specific exception was made for `lxd/swagger.go` in the static analysis suite for deadcode. I've updated it to the new path.

**Review by tomponline — APPROVED** [review]

**Pull request merged**
