### PR TITLE
Storage: Improve failed snapshot create revert cleanup

### PR DESCRIPTION
**Pull request by tomponline**
Addresses failed snapshot creation leaving database records as discussed in https://discuss.linuxcontainers.org/t/not-able-create-snapshot-through-zfs-snapshot-storage-name-containers-containers-name-snapshot-snapshot-name-due-to-invalid-argument-in-its-name/7243

### CODE REVIEW

**Comment by tomponline** [comment]
@stgraber this change is failing tests with ceph saying that the volume already exists. I suspect that the ceph `HasVolume()` function is having problems, and its introduction as a prerequisite before deleting a volume is causing the failures. Have spun up edfu to experiment.

**Comment by tomponline** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Not sure if related https://jenkins.linuxcontainers.org/job/lxd-github-pull-test/813/arch=amd64,backend=zfs,compiler=golang-1.13/

**Comment by stgraber** [comment]
Hmm, probably not

**Pull request merged**
