### PR TITLE
lvm improvements

### PR DESCRIPTION
**Pull request by brauner**

### CODE REVIEW

**Comment by stgraber** [comment]
If that works, you'll probably want to silence the pvscan/vgscan in the testsuite otherwise we'll end up with quite a bit of not so useful output.

**Comment by brauner** [comment]
Yeah, I want to see it through a couple of runs though. :)

**Comment by brauner** [comment]
Seems to be exactly what I said: locking issues + missing pvscan for loop devices.

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by brauner** [comment]
I also need to check if the pvcreate calls in `configure_lvm_loop_device` are necessary. I'm pretty sure we can do without and rely on our internal pvcreate calls. That should provide more reliability.

**Comment by brauner** [comment]
Jenkins: test this please.

**Pull request merged**
