### PR TITLE
lxd/instance/qemu: Drop bootIndex from PCI

### LINKED ISSUE #10531: Physical PCI Devices - qemu.conf always assigns `bootIndex` arg
# Issue Description
When adding a physical PCI device to an instance, the corresponding block in qemu.conf will contain a `bootIndex` argument, but not all drivers will support this.

# Steps to reproduce

`lxc init images:ubuntu/22.04/cloud vm --vm`
`lxc config device add vm dev pci address=...`
`lxc start vm         # This fails.`

Output of `lxc info --show-log vm`:
`qemu-system-x86_64:/var/log/lxd/vm/qemu.conf:266: Property 'vfio-pci.bootIndex' not found`

# Information to attach
This seems to be connected to a3cf5ec0d, particularly [here](https://github.com/lxc/lxd/commit/a3cf5ec0d1968ae70574a4d66cb667c20ba36cc1#diff-451c9f8fe94f3f932d8bb04a03d9dd963155f1b00f138137e7886595ae39dcb4R666-R683), with the following snippet: 
```go
type qemuPCIPhysicalOpts struct {
	dev         qemuDevOpts
	devName     string
	pciSlotName string
	bootIndex   int
}

func qemuPCIPhysicalSections(opts *qemuPCIPhysicalOpts) []cfgSection {
	deviceOpts := qemuDevEntriesOpts{
		dev:     opts.dev,
		pciName: "vfio-pci",
		ccwName: "vfio-ccw",
	}

	entries := append(qemuDeviceEntries(&deviceOpts), []cfgEntry{
		{key: "host", value: opts.pciSlotName},
		{key: "bootIndex", value: fmt.Sprintf("%d", opts.bootIndex)},
	}...)
```

### PR DESCRIPTION
**Pull request by stgraber**
Closes #10531

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by stgraber** [comment]
This was reported by @masnax. The bootIndex isn't relevant for vfio-pci and looking at our previous code (prior to @tarruda's change), we weren't setting the property (and still aren't).

The new logic now sets it to 0 which causes issues/crashes.

**Review by tomponline — APPROVED** [review]
I expect the tests will need updating too.

**Comment by stgraber** [comment]
> I expect the tests will need updating too.

indeed. fixed.

**Comment by masnax** [comment]
Ah nice looks like you beat me to it :)

**Comment by tomponline** [comment]
Tests still sad

**Comment by tarruda** [comment]
> Tests still sad

Applying this diff should fix it:

```diff
diff --git a/lxd/instance/drivers/driver_qemu_config_test.go b/lxd/instance/drivers/driver_qemu_config_test.go
index c942df6fb..196d0306f 100644
--- a/lxd/instance/drivers/driver_qemu_config_test.go
+++ b/lxd/instance/drivers/driver_qemu_config_test.go
@@ -926,7 +926,7 @@ func TestQemuConfigTemplates(t *testing.T) {
                        driver = "vfio-pci"
                        bus = "qemu_pcie1"
                        addr = "00.0"
-                       host = "host-slot"
+                       host = "host-slot"`,
                }, {
                        qemuPCIPhysicalOpts{
                                dev:         qemuDevOpts{"ccw", "qemu_pcie2", "00.2", true},
@@ -937,7 +937,7 @@ func TestQemuConfigTemplates(t *testing.T) {
                        [device "dev-lxd_physical-ccw-name"]
                        driver = "vfio-ccw"
                        multifunction = "on"
-                       host = "host-slot-ccw"
+                       host = "host-slot-ccw"`,
                }}
                for _, tc := range testCases {
                        runTest(tc.expected, qemuPCIPhysical(&tc.opts))

```

**Comment by stgraber** [comment]
Yep, just came up with the same ;)

**Comment by stgraber** [comment]
@tomponline good to go

**Pull request merged**
