### PR TITLE
Adapt to new dqlite api

### PR DESCRIPTION
**Pull request by freeekanayaka**

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Pull request merged**
