### PR TITLE
Testsuite re-org & code style

### PR DESCRIPTION
**Pull request by stgraber**
This re-organizes the test/ directory in prevision for adding support
for the different backing stores.

This is solely about moving files around and updating the code style to
be consistent across all files, no change to the actual code is included
in this commit.

Signed-off-by: Stéphane Graber <stgraber@ubuntu.com>

### CODE REVIEW

**Comment by mikemccracken** [comment]
I'm +1 on this, works for me, but I can't run the migration tests... @tych0 ?

**Comment by stgraber** [comment]
the migration test fails here in the same way as it did before :)

**Comment by tych0** [comment]
To be honest, I'm not sure those have worked for a while. I'll take a look, but let's not block merging this on that.

**Comment by tych0** [comment]
Or, are they failing even when you don't have criu installed?

**Comment by stgraber** [comment]
nah, without criu they pass fine, it's just the criu part which fails as it always did for me.

**Comment by stgraber** [comment]
would be nice if we could get criu 1.7 in the archive and have the tests pass

**Pull request merged**
