### PR TITLE
lxc {copy,move}: improve error handling

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
This branch will fail but this is expected for now. Because we've changed handling `/dev/ptmx` in liblxc we need to fix a few things. I'll take care of that asap.

**Comment by brauner** [comment]
Or rather should fail.

**Comment by stgraber** [comment]
@brauner what's the link with this and /dev/ptmx?

I'm wondering because we'll be pushing the /dev/ptmx thing as a stable update to the 2.0 branch so if it's regressing something that's gonna be a problem.

**Comment by brauner** [comment]
@stgraber, the `/dev/ptmx` thing was unrelated. It accidently kept an fd to the underlying mount point file open which confused criu. I'm trying to test migration locally but the criu binary keeps hanging for me.

**Pull request merged**
