### PR TITLE
Apparmor simplification

### PR DESCRIPTION
**Pull request by simondeziel**
This was tested by comparing the profile of an unprivileged container with a simplified version where the mount options alternations were removed:

```
# get a generated profile
lxc launch images:ubuntu/20.04 u1
cp /var/snap/lxd/common/lxd/security/apparmor/profiles/lxd-u1 lxd-u1.orig

cp lxd-u1.orig lxd-u1.simplified
vim lxd-u1.simplified # remove mount options alternations from this branch (essentially apply this diff: https://termbin.com/v1vd)

# DFA comparison
apparmor_parser -Q --dump=dfa-states -K lxd-u1.orig 2> lxd-u1.orig.dfa
apparmor_parser -Q --dump=dfa-states -K lxd-u1.simplified 2> lxd-u1.simplified.dfa
cmp lxd-u1.orig.dfa lxd-u1.simplified.dfa

# full compilation comparison
apparmor_parser -K lxd-u1.orig -o lxd-u1.orig.compiled
apparmor_parser -K lxd-u1.simplified -o lxd-u1.simplified.compiled
cmp lxd-u1.orig.compiled lxd-u1.simplified.compiled
```

Those tests were done once in each of:

* 20.04 VM with Apparmor 2.13.3-7ubuntu5.1
```
root@v1:~# ll lxd-u1.orig.dfa lxd-u1.simplified.dfa
-rw-r--r-- 1 root root 168556 Oct  5 03:29 lxd-u1.orig.dfa
-rw-r--r-- 1 root root 168556 Oct  5 03:29 lxd-u1.simplified.dfa
root@v1:~# ll lxd-u1.orig.compiled lxd-u1.simplified.compiled
-rw-r--r-- 1 root root 41793 Oct  5 03:29 lxd-u1.orig.compiled
-rw-r--r-- 1 root root 41793 Oct  5 03:30 lxd-u1.simplified.compiled
```
* 18.04 VM with Apparmor 2.12-4ubuntu5.1
```
root@v2:~# ll lxd-u1.orig.dfa lxd-u1.simplified.dfa
-rw-r--r-- 1 root root 168556 Oct  5 03:29 lxd-u1.orig.dfa
-rw-r--r-- 1 root root 168556 Oct  5 03:29 lxd-u1.simplified.dfa
root@v2:~# ll lxd-u1.orig.compiled lxd-u1.simplified.compiled
-rw-r--r-- 1 root root 41785 Oct  5 03:30 lxd-u1.orig.compiled
-rw-r--r-- 1 root root 41785 Oct  5 03:30 lxd-u1.simplified.compiled
```

P.S.: Special thanks to sarnold for the help with Apparmor.

### CODE REVIEW

**Comment by tomponline** [comment]
jenkins: test this please

**Review by tomponline — APPROVED** [review]
So are you effectively removing some specific rules that are already covered by more general rules?

**Comment by tomponline** [comment]
@simondeziel I like the use of the apparmor tools to compare the actual compiled policy.

@stgraber I wonder if we should add something to the test suite to ensure that the apparmor policy for a test container is being applied as expected based on a static policy in the test suite, that would capture any regressions in the basic apparmor policy.

**Comment by stgraber** [comment]
Not sure how easy that would be. It couldn't be a compiled policy as that would change based on compiler version.

So it would have to be an expanded text version of the policy that we would then need to mangle to match the conditional bits of the Go code (paths mostly).

It feels to me like one of those tests that effectively just checks if another file changed as I don't see what could alter our generated profiles other than a change to lxd/apparmor and we already know to pay very close attention to any PR which touches that package.

**Comment by simondeziel** [comment]
> So are you effectively removing some specific rules that are already covered by more general rules?

It's basically removing rules with alternated order of mount options on the basis that those 2 rules are identical in meaning:

```
mount options(ro,noatime) ...
mount options(noatime,ro) ...
```

**Comment by stgraber** [comment]
jenkins: test this please

**Pull request merged**
