### PR TITLE
Cluster performance improvements

### PR DESCRIPTION
**Pull request by stgraber**

### CODE REVIEW

**Comment by stgraber** [comment]
Please don't re-run this branch until the dqlite issue it's hitting is tracked down.
Snippet from the issue:
```
INFO[08-07|23:34:05] Creating container                       ephemeral=false name=cNonConflictingProfiles
panic: unknown data type

goroutine 5855 [running]:
github.com/CanonicalLtd/go-dqlite/internal/client.(*Rows).Next(0xc420598e80, 0xc4201f4480, 0x3, 0x3, 0xc420052a70, 0xc4204cc5d8)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/CanonicalLtd/go-dqlite/internal/client/message.go:547 +0x914
github.com/CanonicalLtd/go-dqlite.(*Rows).Next(0xc420598e80, 0xc4201f4480, 0x3, 0x3, 0xe6ef00, 0xc4202346f8)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/CanonicalLtd/go-dqlite/driver.go:515 +0x4b
database/sql.(*Rows).nextLocked(0xc4201fe600, 0xc4201f0000)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/golang/src/database/sql/sql.go:2622 +0xc4
database/sql.(*Rows).Next.func1()
	/lxc-ci/build/tmp.6JMgWkBKpm/go/golang/src/database/sql/sql.go:2600 +0x3c
database/sql.withLock(0x1122a00, 0xc4201fe630, 0xc4204cc690)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/golang/src/database/sql/sql.go:3032 +0x63
database/sql.(*Rows).Next(0xc4201fe600, 0xc4201f4ed0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/golang/src/database/sql/sql.go:2599 +0x7a
github.com/lxc/lxd/lxd/db/query.SelectObjects(0xc4201fe580, 0xc4204366b0, 0xc420372000, 0xaa, 0xc4202ea560, 0x1, 0x1, 0x0, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/query/objects.go:18 +0xda
github.com/lxc/lxd/lxd/db.(*ClusterTx).containerArgsList(0xc4204365b0, 0x1129401, 0xc420038128, 0x0, 0x17f6601, 0xc4201fe580, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/containers.go:439 +0x572
github.com/lxc/lxd/lxd/db.(*ClusterTx).ContainerArgsNodeList(0xc4204365b0, 0x0, 0x0, 0xc4204ccab0, 0x77187c, 0xc42043e460)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/containers.go:347 +0x30
main.containerLoadNodeAll.func1(0xc4204365b0, 0x0, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/container.go:1199 +0x38
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1.1(0xc4201fe580, 0xc4201fe580, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/db.go:309 +0x42
github.com/lxc/lxd/lxd/db/query.Transaction(0xc42043e460, 0xc4204ccb38, 0xe93d00, 0x8)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/query/transaction.go:17 +0x5a
github.com/lxc/lxd/lxd/db.(*Cluster).transaction.func1(0x7f4b19a03000, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/db.go:307 +0x55
github.com/lxc/lxd/lxd/db/query.Retry(0xc4204ccbe8, 0xc4204365b0, 0x434e69)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/query/retry.go:20 +0xae
github.com/lxc/lxd/lxd/db.(*Cluster).transaction(0xc420232000, 0xc4204ccc98, 0xc420232010, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/db.go:306 +0x6d
github.com/lxc/lxd/lxd/db.(*Cluster).Transaction(0xc420232000, 0xc4204ccc98, 0x0, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/db/db.go:270 +0x80
main.containerLoadNodeAll(0xc4202cde20, 0x17f6658, 0x0, 0x0, 0x0, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/container.go:1197 +0x67
main.networkUpdateStatic(0xc4202cde20, 0x0, 0x0, 0x0, 0x0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/networks_utils.go:774 +0xed
main.containerLXCCreate(0xc4202cde20, 0x6, 0x0, 0x0, 0x0, 0xc42003a440, 0x40, 0x0, 0xed2fc236d, 0x17d0400, ...)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/container_lxc.go:461 +0xc61
main.containerCreateInternal(0xc4202cde20, 0x6, 0x0, 0x0, 0x0, 0xc42003a440, 0x40, 0x0, 0xed2fc236d, 0x17d0400, ...)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/container.go:1100 +0x8e2
main.containerCreateFromImage(0xc4202b3e10, 0x0, 0x0, 0x0, 0x0, 0xc42003a440, 0x40, 0x0, 0x0, 0x0, ...)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/container.go:787 +0x35f
main.createFromImage.func1(0xc4200a8f70, 0xc4204fed08, 0x4470ac)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/containers_post.go:129 +0x2e5
main.(*operation).Run.func1(0xc4200a8f70, 0xc4204494a0)
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/operations.go:140 +0x4a
created by main.(*operation).Run
	/lxc-ci/build/tmp.6JMgWkBKpm/go/src/github.com/lxc/lxd/lxd/operations.go:139 +0x397
Error: websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by freeekanayaka** [comment]
jenkins: test this please

**Comment by freeekanayaka** [comment]
The dqlite issue has been fixed, it was a corner case which was not handled correctly by the wire protocol parser in go-dqlite. Branch is failing because of static analysis now.

**Comment by stgraber** [comment]
Should be ready for review, Jenkins is all green except for our current favorite issue "no transition is active" but that's unrelated to this branch.

**Pull request merged**
