### PR TITLE
Snapshot restore - first drop - closes #621

### LINKED ISSUE #621: No `lxc restore`
Looks like `lxc restore` is not implemented yet. Using `lxc copy` for now.

https://github.com/lxc/lxd/blob/master/specs/command-line-user-experience.md#restore

### PR DESCRIPTION
**Pull request by sl1pm4t**
Fixed up my branches and re-committed.
This commit adds tests too.

Signed-off-by: Matt Morrison <matt@mojo.net.nz>

### CODE REVIEW

**Comment by stgraber** [comment]
Hi,

Travis can't start containers (as it's running inside OpenVZ), so you need to put a check for Travis at the point in your testsuite where starting container is actually required.

Look at our other tests for that.

Typically I make sure to test absolutely everything that's possible without a container startup first, then add the Travis check and then do a simpler test including a container startup.

**Comment by sl1pm4t** [comment]
Well I'm having a bad time with the tests.

**Comment by stgraber** [comment]
Looks like this branch needs rebasing.

**Comment by sl1pm4t** [comment]
rebased

**Comment by stgraber** [comment]
Hi,

Very sorry about this but a branch we just landed just changed i18n again, so your branch requires yet another rebase :)

**Comment by sl1pm4t** [comment]
Moving foward, is there not a better way lxd.pot can be handled? It's the #1 cause of conflicts it seems, and the file can be auto generated so why not remove it from the developer workflow, add it to .gitignore and just auto generate whenever tests are run or a build is generated?

**Comment by stgraber** [comment]
lxd.pot must always be up to date so that translators (arguably, not many of them so far) can translate the strings into po/LANGCODE.po and contribute that back to us.

**Comment by sl1pm4t** [comment]
messed this one up

**Pull request closed without merging**
