### PR TITLE
Backport the test functions refactoring

### PR DESCRIPTION
**Pull request by albertodonato**

### CODE REVIEW

**Comment by stgraber** [comment]
Did you notice that this is completely failing on Jenkins?

**Comment by stgraber** [comment]
Did some poking and this branch is very wrong. It refers to the storage and network code in a lot of places despite none of that existing in LXD 2.0.

**Comment by albertodonato** [comment]
I'm looking into the changes, but the jenkins failure is about "Target branch stable-2.0 isn't the master branch."

**Comment by albertodonato** [comment]
jenkins: test this please

**Pull request merged**
