### PR TITLE
don't require a client cert for untrusted reqs

### PR DESCRIPTION
**Pull request by tych0**
Since we have the concept of "trusted" and "untrusted" requests, and we
don't verify the client cert for untrusted requests, we may as well not
require one.

Signed-off-by: Tycho Andersen <tycho.andersen@canonical.com>

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

Looks like we need a retry.

**Comment by stgraber** [comment]
And now run into the busybox issue...

Jenkins: test this please

**Comment by tych0** [comment]
Yeah, I'm looking at the busybox thing now since I can reproduce it reliably. At first I thought it was that liblxc was passing /dev/zero as stdin, but we don't, we pass /dev/null. So busybox re-opens it, and then spins on reading it forever... bah.

**Comment by stgraber** [comment]
Damn, really unlucky today...

Jenkins: test this please

**Comment by stgraber** [comment]
Fine, got stuck again but calling it good enough :)

**Pull request merged**
