### PR TITLE
lxd/storage: Add rsync.compression to storagePoolConfigKeys

### LINKED ISSUE #7936: Add config option to disable rsync compression during migration
Rsync compression can cause up to 11x lxc copy degration over fast localprivate networks. 

Lxc copy which may use rsync which enables compression=2 causes two local servers (amd 3900x with nvme/raid0) with 10g nics to communicate at only 300Mbps with 100% cpu usage on a single cpu core. Disabling compression in source enabled lxc copy to reach 3500Mbps at 80% cpu usage on the same cpu core.

https://discuss.linuxcontainers.org/t/how-to-disable-rsync-compression-for-lxc-copy-100-cpu-and-slow-for-local-network-transfer/9028

### PR DESCRIPTION
**Pull request by drs-11**
Fixes #7936 

Signed-off-by: D R Siddhartha <siddharthadr11@gmail.com>

I had issues while trying to run the testsuites locally on my machine which I think are probably due to the poorly set up local development environment. I am not sure if the test cases will pass.

Also I couldn't start `make check` without changing the line for `go get -v -x github.com/golang/lint/golint` to `go get -v -x golang.org/x/lint/golint`. [This](https://github.com/golang/lint/issues/415) golint issue resolved it.

### CODE REVIEW

**Comment by stgraber** [comment]
jenkins: test this please

**Comment by stgraber** [comment]
Looks good to me. The commits will have to be re-arranged a bit, effectively:
 - Rebase on master
 - Split changes to shared/version/api.go and doc/api-extensions.md into a separate `api: storage_rsync_compression` commit
 - Split change to doc/storage.md to a separate `doc: Add rsync.compression` commit
 - Split changes to `tests/` to a separate `tests: Valid rsync.compression` commit

Resulting in a set of 4 commits which we can easily deal with should we ever need this backported to a stable branch.

**Comment by stgraber** [comment]
```
lxd/storage/drivers/driver_btrfs.go:378:53: "assoicated" is a misspelling of "associated"
lxd/storage/drivers/driver_ceph.go:345:53: "assoicated" is a misspelling of "associated"
lxd/storage/drivers/driver_cephfs.go:317:53: "assoicated" is a misspelling of "associated"
lxd/storage/drivers/driver_common.go:137:53: "assoicated" is a misspelling of "associated"
lxd/storage/drivers/driver_zfs.go:457:53: "assoicated" is a misspelling of "associated"
```

**Comment by stgraber** [comment]
```
+ /lxc-ci/build/tmp.7CwhfJMmXs/go/bin/lxc storage set l1:lxdtest-x3o rsync.compression false --verbose
Error: Invalid option for pool "lxdtest-x3o" option "rsync.compression"
```

**Comment by stgraber** [comment]
Looks like you need to add it to `validatePoolCommonRules` in `lxd/storage/utils.go` too as `validate.Optional(validate.IsBool)`

**Comment by drs-11** [comment]
Ok I think I messed up the commits. Sorry!

**Comment by drs-11** [comment]
I should probably close this PR and start afresh.

**Comment by stgraber** [comment]
Ok :)

It takes some getting used to to drive `git rebase` and be able to really control exactly what commits are in your branch after the master branch has diverged.

**Comment by gaia** [comment]
Feedback: Wouldn't it make sense to default rsync.compression to false when copying within local storage? I'd go further and set it false by default and only turn on on demand (which is only when copying to a remote via WAN, and the contents of the container is worth compressing, which is not the case on our CTs, but ok), but that's just me.

Question: Do I set it to false on the outgoing or the incoming storage? I actually set them all to false, but curious as to how to properly use this setting.

**Comment by stgraber** [comment]
If it's purely local (same system), then LXD won't use compression as it won't use the network part of rsync.
For migrations, LXD doesn't know what kind of bandwidth limits may be affecting the different machines and trading CPU for speed is usually reasonable for that.

As to what side to turn off, it doesn't matter. Compression is a negotiated property, so if one of the side doesn't support it, it won't be used during migration.

**Comment by gaia** [comment]
> If it's purely local (same system), then LXD won't use compression as it won't use the network part of rsync. For migrations, LXD doesn't know what kind of bandwidth limits may be affecting the different machines and trading CPU for speed is usually reasonable for that.

Weird, I had the default setting, and copying from one storage pool to another on the same machine (2 NVME disks) was hovering just under 40MB/s. I interrupted the transfer (killed the processes) then set it to false: transfer never dropped below 320MB/s.

**Pull request closed without merging**
